/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter
open scoped BigOperators ENNReal

noncomputable section

/-! ## Uniform active-coordinate strict range -/

/-- The uniform strict model constant transports to every active coordinate.
Unlike the earlier pointwise formulation, its constant is chosen before the
translation, coefficient, and input tuple; this is the form consumed by the
complexification and lattice-mode stages. -/
theorem scratch_exists_uniform_activeModelFullForm_bound_weight100
    (α : Anisotropy) (i : Fin 3) (q : Fin 4 → ℝ)
    (hq : ∀ j : Fin 4, 0 < q j)
    (hsum : ∑ j : Fin 4, (q j)⁻¹ = 1)
    (hqs : ∀ j : Fin 4, activeSourceStoppingExponent i j < q j) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (u : E3) (c : ℝ → ℝ)
      (F : ModelSchwartzInput),
      Measurable c → (∀ t : ℝ, |c t| ≤ 1) →
      |activeModelFullForm α i u c F| ≤ C * sourceWeight u ^ 100 *
        ∏ j : Fin 4, lpNorm (F j : E3 → ℝ) (ENNReal.ofReal (q j)) volume := by
  rcases exists_coordinatePermutation_to_active i with ⟨σ, hσ⟩
  let q' : Fin 4 → ℝ := permutedModelExponent σ q
  have hq' : ∀ j : Fin 4, 0 < q' j := by
    simpa only [q'] using permutedModelExponent_pos σ q hq
  have hsum' : ∑ j : Fin 4, (q' j)⁻¹ = 1 := by
    calc
      (∑ j : Fin 4, (q' j)⁻¹) = ∑ j : Fin 4, (q j)⁻¹ := by
        simpa only [q'] using sum_inv_permutedModelExponent σ q
      _ = 1 := hsum
  have hqs' : ∀ j : Fin 4, sourceStoppingExponent j < q' j := by
    simpa only [q'] using
      permutedModelExponent_stoppingThreshold σ i q hσ hqs
  rcases exists_uniform_initialModelFullForm_bound_weight100
    (permutedAnisotropy α σ) q' hq' hsum' hqs' with ⟨C, hC, hbound⟩
  refine ⟨C, hC, ?_⟩
  intro u c F hcmeas hc
  rw [activeModelFullForm_permute_to_third α σ i u c F hσ]
  have hbound' := hbound (coordinatePermutation σ u) c
    (permutedModelInput σ F) hcmeas hc
  rw [sourceWeight_coordinatePermutation σ u,
    prod_lpNorm_permutedModelInput σ F q] at hbound'
  simpa only [q'] using hbound'

#print axioms scratch_exists_uniform_activeModelFullForm_bound_weight100

end
end Twisted
end Auto
