/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted
import LeanSpherical.Auto.MikhlinHormander
import LeanSpherical.Auto.SteinInterpolation
import LeanSpherical.Auto.CalderonVaillancourt

/-!
# Library bridge audit for Task 3

This scratch file only checks the exact existing linear multiplier and
interpolation interfaces considered for the final anisotropic twisted
paraproduct.  It intentionally introduces no new mathematical declarations.
-/

namespace Auto.Twisted

open MeasureTheory FourierTransform
open scoped ENNReal FourierTransform

noncomputable section

#check Auto.MikhlinHormander.MikhlinCondition
#check Auto.MikhlinHormander.CoordinateMikhlinCondition
#check Auto.MikhlinHormander.coordinateMikhlinCondition_to_mikhlinCondition
#check Auto.MikhlinHormander.mikhlin
#check Auto.MikhlinHormander.mikhlin_two
#check Auto.MikhlinHormander.mikhlin_two_of_coordinateMikhlinCondition
#check Auto.MikhlinHormander.compactAnnularSchwartzMultiplier_strong_type
#check Auto.MikhlinHormander.exists_uniform_strongLp_mikhlinMultiplier_withCutoffs
#check Auto.SteinInterpolation.riesz_thorin_core
#check Auto.SteinInterpolation.stein_interpolation_constant_bounds
#check Auto.Spherical.Auxiliary.marcinkiewicz_weak_one_two
#check Auto.Spherical.Auxiliary.marcinkiewicz_weak_q_top_on_additive_split
#check Auto.CalderonVaillancourt.eLpNorm_kernelApply_le

end Auto.Twisted
