/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## Joint integrability in frequency and scale

Source: the absolute-convergence paragraph of `thm:cone`, which justifies
Fubini between frequencies and scales.  Sliced in the scale the integrand is
integrable for every frequency, and the resulting scale mass is bounded by the
multiplier constant against the Calderón constant, so the frequency integral of
that mass is controlled by the Schwartz factor alone.
-/

/-- The joint integrand is measurable. -/
theorem measurable_coneFrequencySymbol_prod
    (α : Anisotropy) (M : ℝ) (m : E3 → ℂ)
    (hm : Anisotropy.IsAnisotropicMultiplier α M m) (i : Fin 3) (Q : Schwartz3) :
    Measurable (fun p : E3 × ℝ ↦
      (coneFrequencySymbol α m i p.2 p.1 / (p.2 : ℂ)) * Q p.1) := by
  have hswap : Measurable (fun p : E3 × ℝ ↦ (p.2, p.1)) :=
    measurable_snd.prodMk measurable_fst
  have hsym : Measurable (fun p : E3 × ℝ ↦ coneFrequencySymbol α m i p.2 p.1) :=
    (measurable_coneFrequencySymbol_uncurry α M m hm i).comp hswap
  have hden : Measurable (fun p : E3 × ℝ ↦ ((p.2 : ℝ) : ℂ)) :=
    Complex.measurable_ofReal.comp measurable_snd
  have hQ : Measurable (fun p : E3 × ℝ ↦ Q p.1) :=
    Q.continuous.measurable.comp measurable_fst
  exact (hsym.div hden).mul hQ

/-- **Joint integrability of the cone integrand** in frequency and scale. -/
theorem integrable_coneFrequencySymbol_prod
    (α : Anisotropy) (M : ℝ) (m : E3 → ℂ)
    (hm : Anisotropy.IsAnisotropicMultiplier α M m) (i : Fin 3) (Q : Schwartz3) :
    Integrable (fun p : E3 × ℝ ↦
        (coneFrequencySymbol α m i p.2 p.1 / (p.2 : ℂ)) * Q p.1)
      ((volume : Measure E3).prod ((volume : Measure ℝ).restrict (Ioi (0 : ℝ)))) := by
  have hw : (0 : ℝ) < (α.weight i : ℝ) := by exact_mod_cast α.weight_pos i
  set f : E3 × ℝ → ℂ := fun p ↦
    (coneFrequencySymbol α m i p.2 p.1 / (p.2 : ℂ)) * Q p.1 with hf
  have hmeas : AEStronglyMeasurable f
      ((volume : Measure E3).prod ((volume : Measure ℝ).restrict (Ioi (0 : ℝ)))) :=
    (measurable_coneFrequencySymbol_prod α M m hm i Q).aestronglyMeasurable
  refine (integrable_prod_iff hmeas).mpr ⟨?_, ?_⟩
  · refine Filter.Eventually.of_forall fun ξ ↦ ?_
    exact (integrableOn_coneFrequencySymbol_div α m i ξ).mul_const (Q ξ)
  · -- the scale mass is bounded by the multiplier constant times the Schwartz factor
    have hslice : ∀ ξ : E3,
        (∫ t in Ioi (0 : ℝ), ‖f (ξ, t)‖)
          = (∫ t in Ioi (0 : ℝ), ‖coneFrequencySymbol α m i t ξ‖ / t) * ‖Q ξ‖ := by
      intro ξ
      rw [← integral_mul_const]
      refine setIntegral_congr_fun measurableSet_Ioi fun t ht ↦ ?_
      have ht0 : (0 : ℝ) < t := ht
      rw [hf]
      simp only [norm_mul, norm_div, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos ht0]
    have hbound : ∀ ξ : E3,
        ‖∫ t in Ioi (0 : ℝ), ‖f (ξ, t)‖‖ ≤
          (M * cPsi ^ 3 / (α.weight i : ℝ)) * ‖Q ξ‖ := by
      intro ξ
      have hnn : 0 ≤ ∫ t in Ioi (0 : ℝ), ‖f (ξ, t)‖ :=
        setIntegral_nonneg measurableSet_Ioi fun t _ ↦ norm_nonneg _
      rw [Real.norm_eq_abs, abs_of_nonneg hnn, hslice ξ]
      exact mul_le_mul_of_nonneg_right
        (integral_norm_coneFrequencySymbol_div_le α M m hm i ξ) (norm_nonneg _)
    refine Integrable.mono' (Q.integrable.norm.const_mul (M * cPsi ^ 3 / (α.weight i : ℝ)))
      (hmeas.norm.integral_prod_right') (Filter.Eventually.of_forall hbound)

end
end Twisted
end Auto
