/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## The cone coefficients are measurable contractions

Source: `thm:cone`, "the coefficients `c_{i,nu}` are measurable with modulus at
most one".  Choosing the envelope constant above the decay budget at all three
cones at once makes every contracted coefficient a contraction, and each is
measurable in the scale because the Fourier coefficient is.
-/

/-- **A single envelope constant serves all three cones.** -/
theorem exists_envelope_norm_coneModeCoefficient_le_one
    (α : Anisotropy) (M : ℝ) (m : E3 → ℂ)
    (hm : Anisotropy.IsAnisotropicMultiplier α M m) :
    ∃ A0 : ℝ, 0 < A0 ∧ ∀ (i : Fin 3) (t : ℝ), 0 < t → ∀ ν : Fin 3 → ℤ,
      ‖coneModeCoefficient A0 ν
        (UnitAddTorus.mFourierCoeff
          (unitTorusLocalizedSymbol (conePermutedAnisotropy α i)
            (conePermutedMultiplier m i) 2 t) ν)‖ ≤ 1 := by
  classical
  have hM0 : 0 ≤ M := hm.nonneg
  have hEx : ∀ i : Fin 3, ∃ A : ℝ, 0 ≤ A ∧ ∀ t : ℝ, 0 < t → ∀ ν : Fin 3 → ℤ,
      ‖UnitAddTorus.mFourierCoeff
          (unitTorusLocalizedSymbol (conePermutedAnisotropy α i)
            (conePermutedMultiplier m i) 2 t) ν‖ ≤
        (A * M) *
          (sourceWeight ((standardModeOfInt ν : standardModeLattice) : E3))⁻¹ ^
            (110 : ℕ) := fun i ↦
    scratch_exists_uniform_mFourierCoeff_unitTorusLocalizedSymbol_sourceWeight_110_decay
      (conePermutedAnisotropy α i) M (conePermutedMultiplier m i)
      (isAnisotropicMultiplier_conePermuted hm i) 2
  choose Af hAf0 hAfb using hEx
  refine ⟨1 + ∑ j : Fin 3, Af j * M, ?_, ?_⟩
  · have : (0 : ℝ) ≤ ∑ j : Fin 3, Af j * M :=
      Finset.sum_nonneg fun j _ ↦ mul_nonneg (hAf0 j) hM0
    linarith
  · intro i t ht ν
    have hA0 : (0 : ℝ) < 1 + ∑ j : Fin 3, Af j * M := by
      have : (0 : ℝ) ≤ ∑ j : Fin 3, Af j * M :=
        Finset.sum_nonneg fun j _ ↦ mul_nonneg (hAf0 j) hM0
      linarith
    have hle : Af i * M ≤ 1 + ∑ j : Fin 3, Af j * M := by
      have hmem := Finset.single_le_sum
        (f := fun j : Fin 3 ↦ Af j * M)
        (fun j _ ↦ mul_nonneg (hAf0 j) hM0) (Finset.mem_univ i)
      linarith
    exact norm_coneModeCoefficient_le_one hA0 hle ν (hAfb i t ht ν)

/-- The cone coefficients are measurable in the scale. -/
theorem measurable_coneModeCoefficient
    (α : Anisotropy) (M : ℝ) (m : E3 → ℂ)
    (hm : Anisotropy.IsAnisotropicMultiplier α M m) (i : Fin 3) (A0 : ℝ)
    (ν : Fin 3 → ℤ) :
    Measurable (fun t : ℝ ↦ coneModeCoefficient A0 ν
      (UnitAddTorus.mFourierCoeff
        (unitTorusLocalizedSymbol (conePermutedAnisotropy α i)
          (conePermutedMultiplier m i) 2 t) ν)) := by
  have hbase : Measurable (fun t : ℝ ↦
      UnitAddTorus.mFourierCoeff
        (unitTorusLocalizedSymbol (conePermutedAnisotropy α i)
          (conePermutedMultiplier m i) 2 t) ν) :=
    measurable_mFourierCoeff_unitTorusLocalizedSymbol
      (conePermutedAnisotropy α i) M (conePermutedMultiplier m i)
      (isAnisotropicMultiplier_conePermuted hm i) 2 ν
  exact hbase.neg.div_const _

end
end Twisted
end Auto
