/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## One cone's weighted mode sum is bounded

Source: the closing paragraph of the proof of `thm:main`.  The weight carries
the order-110 decay and the model estimate contributes order-100 growth, so
each term carries order ten, which the lattice sums.
-/

/-- **A cone's weighted mode sum obeys the order-ten majorant.** -/
theorem norm_coneModeTermSum_le
    (α : Anisotropy) (i : Fin 3) {A0 Cm P : ℝ} (hA0 : 0 < A0) (hCm : 0 ≤ Cm)
    (hP : 0 ≤ P) (Y : (Fin 3 → ℤ) → ℂ)
    (hY : ∀ ν : Fin 3 → ℤ, ‖Y ν‖ ≤ Cm *
      (sourceWeight ((standardModeOfInt ν : standardModeLattice) : E3)) ^ (100 : ℕ) * P) :
    ‖∑' ν : Fin 3 → ℤ, ((coneModeWeight α i A0 ν : ℝ) : ℂ) * Y ν‖
      ≤ ((cPsi ^ 3)⁻¹ * (α.weight i : ℝ) * A0 * Cm * P) *
          ∑' ν : Fin 3 → ℤ,
            (sourceWeight ((standardModeOfInt ν : standardModeLattice) : E3))⁻¹ ^
              (10 : ℕ) := by
  classical
  set K : ℝ := (cPsi ^ 3)⁻¹ * (α.weight i : ℝ) * A0 * Cm * P with hK
  have hcPsi3 : (0 : ℝ) < cPsi ^ 3 := by have := cPsi_pos; positivity
  have hK0 : 0 ≤ K := by
    rw [hK]
    have : (0 : ℝ) ≤ (cPsi ^ 3)⁻¹ := by positivity
    have hw : (0 : ℝ) ≤ (α.weight i : ℝ) := Nat.cast_nonneg _
    positivity
  set g : (Fin 3 → ℤ) → ℝ := fun ν ↦ K *
    (sourceWeight ((standardModeOfInt ν : standardModeLattice) : E3))⁻¹ ^ (10 : ℕ)
    with hg
  have hgsum : Summable g := summable_intMode_sourceWeight_inv.mul_left K
  have hterm : ∀ ν : Fin 3 → ℤ,
      ‖((coneModeWeight α i A0 ν : ℝ) : ℂ) * Y ν‖ ≤ g ν := by
    intro ν
    set W : ℝ := sourceWeight ((standardModeOfInt ν : standardModeLattice) : E3) with hW
    have hW0 : 0 < W := sourceWeight_pos _
    have hWne : W ≠ 0 := hW0.ne'
    have hwt0 : 0 ≤ coneModeWeight α i A0 ν := nonneg_coneModeWeight α i hA0 ν
    rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hwt0]
    have hpow : W⁻¹ ^ (110 : ℕ) * W ^ (100 : ℕ) = W⁻¹ ^ (10 : ℕ) := by
      field_simp
    refine (mul_le_mul_of_nonneg_left (hY ν) hwt0).trans (le_of_eq ?_)
    rw [coneModeWeight, modeEnvelope, hg, hK, ← hW]
    linear_combination ((cPsi ^ 3)⁻¹ * (α.weight i : ℝ) * A0 * Cm * P) * hpow
  have hsum : Summable (fun ν : Fin 3 → ℤ ↦
      ‖((coneModeWeight α i A0 ν : ℝ) : ℂ) * Y ν‖) :=
    Summable.of_nonneg_of_le (fun ν ↦ norm_nonneg _) hterm hgsum
  calc ‖∑' ν : Fin 3 → ℤ, ((coneModeWeight α i A0 ν : ℝ) : ℂ) * Y ν‖
      ≤ ∑' ν : Fin 3 → ℤ, ‖((coneModeWeight α i A0 ν : ℝ) : ℂ) * Y ν‖ :=
        norm_tsum_le_tsum_norm hsum
    _ ≤ ∑' ν : Fin 3 → ℤ, g ν := hsum.tsum_le_tsum hterm hgsum
    _ = K * ∑' ν : Fin 3 → ℤ,
          (sourceWeight ((standardModeOfInt ν : standardModeLattice) : E3))⁻¹ ^
            (10 : ℕ) := by
        rw [hg]
        exact summable_intMode_sourceWeight_inv.tsum_mul_left K

end
end Twisted
end Auto
