/- Copyright (c) 2026 Joris Roos. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter
open scoped BigOperators ENNReal NNReal

noncomputable section

/-! ## Full-scale three-cone Calderón identity

This scratch closes the finite-interval identity into the source's integral
over positive scales by exhibiting a compact positive support interval for the
literal three-cone density at each nonzero frequency. -/

/-- The literal three-cone density vanishes when every scaled coordinate is
in the low-frequency plateau. -/
theorem scratch_coneProductCalderonIntegrand_eq_zero_of_small
    (α : Anisotropy) (ξ : E3) (t : ℝ)
    (h : ∀ i : Fin 3, |t ^ (α.weight i) * ξ i| ≤ 1) :
    coneProductCalderonIntegrand α ξ t = 0 := by
  have h0 := conePsi_eq_zero_of_abs_le_one (h 0)
  have h1 := conePsi_eq_zero_of_abs_le_one (h 1)
  have h2 := conePsi_eq_zero_of_abs_le_one (h 2)
  unfold coneProductCalderonIntegrand
  rw [h0, h1, h2]
  ring

/-- The literal three-cone density vanishes when one scaled coordinate leaves
the high-frequency support. -/
theorem scratch_coneProductCalderonIntegrand_eq_zero_of_large
    (α : Anisotropy) (ξ : E3) (t : ℝ)
    (h : ∃ i : Fin 3, 2 ≤ |t ^ (α.weight i) * ξ i|) :
    coneProductCalderonIntegrand α ξ t = 0 := by
  rcases h with ⟨i, hi⟩
  fin_cases i
  · have hi' : 2 ≤ |t ^ (α.weight 0) * ξ 0| := by simpa using hi
    have hpsi := conePsi_eq_zero_of_two_le_abs hi'
    have hphi := conePhi_eq_zero_of_two_le_abs hi'
    unfold coneProductCalderonIntegrand
    rw [hpsi, hphi]
    ring
  · have hi' : 2 ≤ |t ^ (α.weight 1) * ξ 1| := by simpa using hi
    have hpsi := conePsi_eq_zero_of_two_le_abs hi'
    have hphi := conePhi_eq_zero_of_two_le_abs hi'
    unfold coneProductCalderonIntegrand
    rw [hpsi, hphi]
    ring
  · have hi' : 2 ≤ |t ^ (α.weight 2) * ξ 2| := by simpa using hi
    have hpsi := conePsi_eq_zero_of_two_le_abs hi'
    have hphi := conePhi_eq_zero_of_two_le_abs hi'
    unfold coneProductCalderonIntegrand
    rw [hpsi, hphi]
    ring

/-- A nonzero frequency has a positive finite scale interval outside of which
the literal three-cone density vanishes, with endpoint data retained in the
strong form needed for the full `Ioi` integral. -/
theorem scratch_exists_coneProductCalderon_support_endpoints
    (α : Anisotropy) (ξ : E3) (hξ : ξ ≠ 0) :
    ∃ a b : ℝ, 0 < a ∧ a ≤ b ∧
      (∀ j : Fin 3, |a ^ (α.weight j) * ξ j| ≤ 1) ∧
      (∃ i : Fin 3, 2 ≤ |b ^ (α.weight i) * ξ i|) := by
  obtain ⟨i, hξi⟩ : ∃ i : Fin 3, ξ i ≠ 0 := by
    by_contra h
    apply hξ
    ext j
    apply not_ne_iff.mp
    intro hj
    exact h ⟨j, hj⟩
  let R : ℝ := max |ξ 0| (max |ξ 1| |ξ 2|)
  have hRnonneg : 0 ≤ R := by
    dsimp [R]
    positivity
  have hR (j : Fin 3) : |ξ j| ≤ R := by
    fin_cases j
    · exact le_max_left _ _
    · exact (le_max_left _ _).trans (le_max_right _ _)
    · exact (le_max_right _ _).trans (le_max_right _ _)
  let a : ℝ := 1 / (1 + R)
  have hden : 0 < 1 + R := by linarith
  have ha : 0 < a := by
    dsimp [a]
    exact div_pos zero_lt_one hden
  have haone : a ≤ 1 := by
    dsimp [a]
    apply (div_le_iff₀ hden).mpr
    linarith
  have haR : a * R ≤ 1 := by
    calc
      a * R = R / (1 + R) := by
        dsimp [a]
        ring
      _ ≤ 1 := (div_le_iff₀ hden).mpr (by linarith)
  have hsmall : ∀ j : Fin 3, |a ^ (α.weight j) * ξ j| ≤ 1 := by
    intro j
    have hpow : a ^ (α.weight j) ≤ a :=
      pow_le_of_le_one ha.le haone (Nat.ne_zero_of_lt (α.weight_pos j))
    rw [abs_mul, abs_of_nonneg (pow_nonneg ha.le _)]
    calc
      a ^ (α.weight j) * |ξ j| ≤ a * |ξ j| :=
        mul_le_mul_of_nonneg_right hpow (abs_nonneg _)
      _ ≤ a * R := mul_le_mul_of_nonneg_left (hR j) ha.le
      _ ≤ 1 := haR
  let b : ℝ := max 1 (2 / |ξ i|)
  have hb_one : 1 ≤ b := le_max_left _ _
  have hb : 0 < b := lt_of_lt_of_le zero_lt_one hb_one
  have hab : a ≤ b := haone.trans hb_one
  have habs : 0 < |ξ i| := abs_pos.mpr hξi
  have hpowb : b ≤ b ^ (α.weight i) := by
    simpa only [pow_one] using
      (pow_le_pow_right₀ hb_one
        (Nat.one_le_iff_ne_zero.mpr (Nat.ne_zero_of_lt (α.weight_pos i))))
  have hlargei : 2 ≤ |b ^ (α.weight i) * ξ i| := by
    rw [abs_mul, abs_of_nonneg (pow_nonneg hb.le _)]
    calc
      2 ≤ b * |ξ i| :=
        (div_le_iff₀ habs).mp (le_max_right _ _)
      _ ≤ b ^ (α.weight i) * |ξ i| :=
        mul_le_mul_of_nonneg_right hpowb (abs_nonneg _)
  exact ⟨a, b, ha, hab, hsmall, ⟨i, hlargei⟩⟩

/-- The low-scale endpoint data forces vanishing on the entire positive
initial scale segment. -/
theorem scratch_coneProductCalderonIntegrand_eq_zero_of_pos_le_small
    (α : Anisotropy) (ξ : E3) (a t : ℝ) (ha : 0 < a)
    (hsmall : ∀ j : Fin 3, |a ^ (α.weight j) * ξ j| ≤ 1)
    (ht : 0 < t) (hta : t ≤ a) :
    coneProductCalderonIntegrand α ξ t = 0 := by
  apply scratch_coneProductCalderonIntegrand_eq_zero_of_small
  intro j
  rw [abs_mul, abs_of_nonneg (pow_nonneg ht.le _)]
  calc
    t ^ (α.weight j) * |ξ j| ≤ a ^ (α.weight j) * |ξ j| :=
      mul_le_mul_of_nonneg_right
        (pow_le_pow_left₀ ht.le hta (α.weight j)) (abs_nonneg _)
    _ = |a ^ (α.weight j) * ξ j| := by
      rw [abs_mul, abs_of_nonneg (pow_nonneg ha.le _)]
    _ ≤ 1 := hsmall j

/-- The high-scale endpoint data forces vanishing on the full terminal scale
ray. -/
theorem scratch_coneProductCalderonIntegrand_eq_zero_of_large_le
    (α : Anisotropy) (ξ : E3) (b t : ℝ) (hb : 0 ≤ b)
    (hlarge : ∃ i : Fin 3, 2 ≤ |b ^ (α.weight i) * ξ i|)
    (hbt : b ≤ t) :
    coneProductCalderonIntegrand α ξ t = 0 := by
  apply scratch_coneProductCalderonIntegrand_eq_zero_of_large
  rcases hlarge with ⟨i, hi⟩
  refine ⟨i, ?_⟩
  rw [abs_mul, abs_of_nonneg (pow_nonneg (hb.trans hbt) _)]
  calc
    2 ≤ |b ^ (α.weight i) * ξ i| := hi
    _ = b ^ (α.weight i) * |ξ i| := by
      rw [abs_mul, abs_of_nonneg (pow_nonneg hb _)]
    _ ≤ t ^ (α.weight i) * |ξ i| :=
      mul_le_mul_of_nonneg_right
        (pow_le_pow_left₀ hb hbt (α.weight i)) (abs_nonneg _)

/-- At nonzero frequency the literal three-cone density has a compact
positive-scale truncation.  The endpoints are constructed from the coordinate
frequencies, rather than obtained nonconstructively from the finite-interval
Calderón theorem. -/
theorem scratch_exists_coneProductCalderonIntegrand_Ioi_truncation
    (α : Anisotropy) (ξ : E3) (hξ : ξ ≠ 0) :
    ∃ a b : ℝ, 0 < a ∧ a ≤ b ∧
      ∀ t ∈ Set.Ioi (0 : ℝ) \ Set.Ioc a b,
        coneProductCalderonIntegrand α ξ t = 0 := by
  obtain ⟨a, b, ha, hab, hsmall, hlarge⟩ :=
    scratch_exists_coneProductCalderon_support_endpoints α ξ hξ
  refine ⟨a, b, ha, hab, ?_⟩
  intro t ht
  by_cases hta : t ≤ a
  · exact scratch_coneProductCalderonIntegrand_eq_zero_of_pos_le_small
      α ξ a t ha hsmall ht.1 hta
  · have hat : a < t := lt_of_not_ge hta
    have htb : b < t := by
      by_contra hnot
      exact ht.2 ⟨hat, le_of_not_gt hnot⟩
    exact scratch_coneProductCalderonIntegrand_eq_zero_of_large_le
      α ξ b t (le_trans ha.le hab) hlarge (le_of_lt htb)

/-- The finite three-cone Calderón identity is the actual integral over all
positive scales at a nonzero frequency: the density has been shown to vanish
off its explicit positive finite support interval. -/
theorem scratch_integral_coneProductCalderonIntegrand_Ioi
    (α : Anisotropy) (ξ : E3) (hξ : ξ ≠ 0) :
    ∫ t in Set.Ioi (0 : ℝ), coneProductCalderonIntegrand α ξ t = cPsi ^ 3 := by
  obtain ⟨a, b, ha, hab, hsmall, hlarge⟩ :=
    scratch_exists_coneProductCalderon_support_endpoints α ξ hξ
  have hsubset : Set.Ioc a b ⊆ Set.Ioi (0 : ℝ) := by
    intro t ht
    exact lt_trans ha ht.1
  have hzero : ∀ t ∈ Set.Ioi (0 : ℝ) \ Set.Ioc a b,
      coneProductCalderonIntegrand α ξ t = 0 := by
    intro t ht
    by_cases hta : t ≤ a
    · exact scratch_coneProductCalderonIntegrand_eq_zero_of_pos_le_small
        α ξ a t ha hsmall ht.1 hta
    · have hat : a < t := lt_of_not_ge hta
      have htb : b < t := by
        by_contra hnot
        exact ht.2 ⟨hat, le_of_not_gt hnot⟩
      exact scratch_coneProductCalderonIntegrand_eq_zero_of_large_le
        α ξ b t (le_trans ha.le hab) hlarge (le_of_lt htb)
  have hset :
      (∫ t in Set.Ioi (0 : ℝ), coneProductCalderonIntegrand α ξ t) =
        ∫ t in Set.Ioc a b, coneProductCalderonIntegrand α ξ t := by
    exact MeasureTheory.setIntegral_eq_of_subset_of_forall_sdiff_eq_zero
      measurableSet_Ioi hsubset hzero
  have hsmallprod : coneProduct α ξ a = cPsi ^ 3 :=
    coneProduct_eq_cPsi_pow_of_small α ξ a hsmall
  have hlargeprod : coneProduct α ξ b = 0 :=
    coneProduct_eq_zero_of_large α ξ b hlarge
  calc
    ∫ t in Set.Ioi (0 : ℝ), coneProductCalderonIntegrand α ξ t =
        ∫ t in Set.Ioc a b, coneProductCalderonIntegrand α ξ t := hset
    _ = ∫ t in a..b, coneProductCalderonIntegrand α ξ t :=
      (intervalIntegral.integral_of_le hab).symm
    _ = cPsi ^ 3 :=
      integral_coneProductCalderonIntegrand α ξ a b ha hab hsmallprod hlargeprod

/-- The full positive-scale multiplier-valued Calderón identity at a nonzero
frequency.  This is the source cone formula before inserting the Fourier
series of the localized symbol. -/
theorem scratch_multiplier_coneProduct_Ioi
    (α : Anisotropy) (m : E3 → ℂ) (ξ : E3) (hξ : ξ ≠ 0) :
    m ξ = ((cPsi : ℂ) ^ 3)⁻¹ *
      ∫ t in Set.Ioi (0 : ℝ), m ξ *
        (coneProductCalderonIntegrand α ξ t : ℂ) := by
  have hscalar := scratch_integral_coneProductCalderonIntegrand_Ioi α ξ hξ
  have hscalarC :
      (∫ t in Set.Ioi (0 : ℝ), (coneProductCalderonIntegrand α ξ t : ℂ)) =
        (cPsi : ℂ) ^ 3 := by
    rw [integral_complex_ofReal]
    norm_cast
  have hfactor :
      (∫ t in Set.Ioi (0 : ℝ), m ξ *
        (coneProductCalderonIntegrand α ξ t : ℂ)) =
        m ξ * ∫ t in Set.Ioi (0 : ℝ),
          (coneProductCalderonIntegrand α ξ t : ℂ) := by
    rw [MeasureTheory.integral_const_mul]
  rw [hfactor, hscalarC]
  have hc : (cPsi : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr cPsi_pos.ne'
  field_simp [hc]

/-- Away from scale zero, the literal three-cone density is continuous. -/
theorem scratch_continuousOn_coneProductCalderonIntegrand
    (α : Anisotropy) (ξ : E3) (a b : ℝ) (ha : 0 < a) :
    ContinuousOn (coneProductCalderonIntegrand α ξ) (Set.Icc a b) := by
  unfold coneProductCalderonIntegrand
  have harg (j : Fin 3) : Continuous (fun t : ℝ ↦
      t ^ (α.weight j) * ξ j) :=
    (continuous_pow (α.weight j)).mul continuous_const
  have hpsi (j : Fin 3) : Continuous (fun t : ℝ ↦
      conePsi (t ^ (α.weight j) * ξ j)) :=
    conePsi_contDiff.continuous.comp (harg j)
  have hphi (j : Fin 3) : Continuous (fun t : ℝ ↦
      conePhi (t ^ (α.weight j) * ξ j)) :=
    conePhi_contDiff.continuous.comp (harg j)
  have hderiv (j : Fin 3) : Continuous (fun t : ℝ ↦
      gaussianDeriv (t ^ (α.weight j) * ξ j)) :=
    continuous_gaussianDeriv.comp (harg j)
  have hterm0 : Continuous (fun t : ℝ ↦
      (α.weight 0 : ℝ) * conePsi (t ^ (α.weight 0) * ξ 0) *
          gaussianDeriv (t ^ (α.weight 0) * ξ 0) ^ 2 *
        conePhi (t ^ (α.weight 1) * ξ 1) *
          conePhi (t ^ (α.weight 2) * ξ 2)) :=
    ((((continuous_const.mul (hpsi 0)).mul ((hderiv 0).pow 2)).mul
      (hphi 1)).mul (hphi 2))
  have hterm1 : Continuous (fun t : ℝ ↦
      conePhi (t ^ (α.weight 0) * ξ 0) *
        ((α.weight 1 : ℝ) * conePsi (t ^ (α.weight 1) * ξ 1) *
          gaussianDeriv (t ^ (α.weight 1) * ξ 1) ^ 2) *
          conePhi (t ^ (α.weight 2) * ξ 2)) :=
    ((hphi 0).mul ((continuous_const.mul (hpsi 1)).mul
      ((hderiv 1).pow 2))).mul (hphi 2)
  have hterm2 : Continuous (fun t : ℝ ↦
      conePhi (t ^ (α.weight 0) * ξ 0) *
        conePhi (t ^ (α.weight 1) * ξ 1) *
          ((α.weight 2 : ℝ) * conePsi (t ^ (α.weight 2) * ξ 2) *
            gaussianDeriv (t ^ (α.weight 2) * ξ 2) ^ 2)) :=
    ((hphi 0).mul (hphi 1)).mul
      ((continuous_const.mul (hpsi 2)).mul ((hderiv 2).pow 2))
  exact ((hterm0.add hterm1).add hterm2).continuousOn.div continuousOn_id
    (fun t ht ↦ ne_of_gt (lt_of_lt_of_le ha ht.1))

/-- The three-cone Calderón density is integrable on all positive scales at a
nonzero frequency.  This records the compact-support step needed to treat the
source integral as an honest Bochner integral. -/
theorem scratch_integrableOn_coneProductCalderonIntegrand_Ioi
    (α : Anisotropy) (ξ : E3) (hξ : ξ ≠ 0) :
    IntegrableOn (coneProductCalderonIntegrand α ξ) (Set.Ioi (0 : ℝ)) volume := by
  obtain ⟨a, b, ha, hab, hzero⟩ :=
    scratch_exists_coneProductCalderonIntegrand_Ioi_truncation α ξ hξ
  have hcompact : IntegrableOn (coneProductCalderonIntegrand α ξ)
      (Set.Icc a b) volume :=
    ContinuousOn.integrableOn_compact isCompact_Icc
      (scratch_continuousOn_coneProductCalderonIntegrand α ξ a b ha)
  have hIoc : IntegrableOn (coneProductCalderonIntegrand α ξ)
      (Set.Ioc a b) volume :=
    hcompact.mono_set Set.Ioc_subset_Icc_self
  exact hIoc.of_forall_sdiff_eq_zero measurableSet_Ioi hzero

/-- The multiplier-weighted complex cone integrand is likewise integrable on
all positive scales. -/
theorem scratch_integrableOn_multiplier_coneProduct_Ioi
    (α : Anisotropy) (m : E3 → ℂ) (ξ : E3) (hξ : ξ ≠ 0) :
    IntegrableOn (fun t : ℝ ↦ m ξ *
      (coneProductCalderonIntegrand α ξ t : ℂ)) (Set.Ioi (0 : ℝ)) volume := by
  change Integrable (fun t : ℝ ↦ m ξ *
      (coneProductCalderonIntegrand α ξ t : ℂ))
        (volume.restrict (Set.Ioi (0 : ℝ)))
  have hreal : Integrable (coneProductCalderonIntegrand α ξ)
      (volume.restrict (Set.Ioi (0 : ℝ))) :=
    scratch_integrableOn_coneProductCalderonIntegrand_Ioi α ξ hξ
  have hcomplex : Integrable (fun t : ℝ ↦
      (coneProductCalderonIntegrand α ξ t : ℂ))
        (volume.restrict (Set.Ioi (0 : ℝ))) :=
    hreal.ofReal
  exact hcomplex.const_mul (m ξ)

end
end Twisted
end Auto
