/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## The scale-uniform multiplier certificate for the cone symbol

Source: `thm:cone`, whose conversion of the reconstructed cone from its
frequency representation to `multiplierForm` was stated conditionally on a
uniform anisotropic multiplier certificate for the scale-dependent cone
symbol.  All four components are now available.
-/

/-- The cone symbol is smooth to order 110. -/
theorem contDiff_thirdConeFrequencySymbol
    (α : Anisotropy) (M : ℝ) (m : E3 → ℂ)
    (hm : Anisotropy.IsAnisotropicMultiplier α M m) {t : ℝ} (ht : 0 < t) :
    ContDiff ℝ 110 (thirdConeFrequencySymbol α m t) := by
  have hLcont : Continuous (α.dilateLinear t) :=
    LinearMap.continuous_of_finiteDimensional (α.dilateLinear t)
  let L : E3 →L[ℝ] E3 := { α.dilateLinear t with cont := hLcont }
  have hLapply : ∀ z : E3, L z = α.dilate t z := fun z ↦ α.dilateLinear_apply t z
  have hfun : thirdConeFrequencySymbol α m t = coneScaleProfile α m t ∘ L := by
    funext z
    rw [Function.comp_apply, hLapply z]
    exact thirdConeFrequencySymbol_eq_coneScaleProfile_dilate α m ht.ne' z
  rw [hfun]
  exact (coneScaleProfile_contDiff α M m hm ht).comp L.contDiff

/-- **The scale-uniform certificate for the cone symbol.** -/
theorem exists_isAnisotropicMultiplier_thirdConeFrequencySymbol
    (α : Anisotropy) (M : ℝ) (m : E3 → ℂ)
    (hm : Anisotropy.IsAnisotropicMultiplier α M m) {t : ℝ} (ht : 0 < t) :
    ∃ M' : ℝ, Anisotropy.IsAnisotropicMultiplier α M'
      (thirdConeFrequencySymbol α m t) := by
  classical
  have hall : ∀ n : ℕ, ∃ C : ℝ, 0 ≤ C ∧ ∀ η : E3, n ≤ 110 →
      ‖iteratedFDeriv ℝ n (coneScaleProfile α m t) η‖ ≤ C := by
    intro n
    by_cases hn : n ≤ 110
    · obtain ⟨C, hC0, hC⟩ :=
        exists_bound_iteratedFDeriv_coneScaleProfile α M m hm ht n hn
      exact ⟨C, hC0, fun η _ ↦ hC η⟩
    · exact ⟨0, le_rfl, fun η hcon ↦ absurd hcon hn⟩
  choose Ck hCk0 hCk using hall
  set W : ℕ := α.weight 0 + α.weight 1 + α.weight 2 with hW
  set Csum : ℝ := ∑ k ∈ Finset.range 111, Ck k with hCsum
  have hCsum0 : 0 ≤ Csum := Finset.sum_nonneg fun k _ ↦ hCk0 k
  have hsmooth := contDiff_thirdConeFrequencySymbol α M m hm ht
  refine ⟨Csum * 6 ^ (110 * W), by positivity,
    hsmooth.continuous.measurable,
    thirdConeFrequencySymbol_zero α m t, hsmooth.contDiffOn, ?_⟩
  intro k hk ξ hξ σ
  have hbound := norm_iteratedFDeriv_thirdConeFrequencySymbol_coordinate_le
    α M m hm ht hξ k hk σ (hCk0 k) (fun η ↦ hCk k η hk)
  refine le_trans hbound ?_
  have hrad : 0 < α.radius ξ := radius_pos_of_ne_zero α hξ
  have hrpownn : 0 ≤ (α.radius ξ) ^ (-((α.derivativeWeight σ : ℕ) : ℝ)) :=
    Real.rpow_nonneg hrad.le _
  refine mul_le_mul_of_nonneg_right ?_ hrpownn
  have hCkle : Ck k ≤ Csum := by
    refine Finset.single_le_sum (f := Ck) (fun i _ ↦ hCk0 i) ?_
    exact Finset.mem_range.mpr (by omega)
  have hdle : α.derivativeWeight σ ≤ 110 * W := by
    refine le_trans (derivativeWeight_le α σ) ?_
    exact Nat.mul_le_mul_right _ hk
  have hpowle : (6 : ℝ) ^ α.derivativeWeight σ ≤ 6 ^ (110 * W) :=
    pow_le_pow_right₀ (by norm_num) hdle
  exact mul_le_mul hCkle hpowle (by positivity) hCsum0

/-- **The cone bridge with no remaining hypothesis.**  The reconstructed cone's
frequency form equals its multiplier form outright. -/
theorem thirdConeFrequencyFullForm_eq_multiplierFullForm_of_multiplier
    (α : Anisotropy) (M : ℝ) (m : E3 → ℂ)
    (hm : Anisotropy.IsAnisotropicMultiplier α M m)
    (F : ModelComplexSchwartzInput) :
    thirdConeFrequencyFullForm α m F = thirdConeMultiplierFullForm α m F := by
  classical
  choose M' hM' using fun t : {s : ℝ // 0 < s} ↦
    exists_isAnisotropicMultiplier_thirdConeFrequencySymbol α M m hm t.2
  unfold thirdConeFrequencyFullForm thirdConeMultiplierFullForm
  apply setIntegral_congr_fun measurableSet_Ioi
  intro t ht
  exact (multiplierForm_eq_frequencyForm α (M' ⟨t, ht⟩)
    (thirdConeFrequencySymbol α m t) (hM' ⟨t, ht⟩)
    (F 0) (F 1) (F 2) (F 3)).symm


end
end Twisted
end Auto
