/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter
open scoped BigOperators ENNReal

noncomputable section

/-! ## Finite selected bad fields exhaust the countable one

Source: `lem:one_fiber`, blueprint lines 2530--2540, "for any enumeration
`𝒟_1 = {I_1, I_2, …}` the sums `∑_{l≤N} b_{I_l}` converge pointwise almost
everywhere and in `L^p` to `b`: at most one term is nonzero at each point".
-/

/-- **At most one selected atom is nonzero at each point.**  A finite family
containing every index supporting the point already reproduces the countable
bad field there. -/
theorem fiberCZBadField_eq_countableBadField_of_mem
    {Z : Type*} [MeasurableSpace Z] (F : ℝ × Z → ℝ) (Zf : Set Z)
    (A : FiberDyadicInterval → Z → ℝ) (H : ℝ)
    (T : Finset FiberDyadicInterval) (yz : ℝ × Z)
    (hT : ∀ I : FiberDyadicInterval,
      yz ∈ fiberDyadicInterval I ×ˢ fiberDyadicSelectionSet Zf A H I →
      I ∈ T) :
    fiberCZBadField F T (fiberDyadicSelectionSet Zf A H) yz =
      fiberDyadicCountableBadField F Zf A H yz := by
  by_cases hex : ∃ I : FiberDyadicInterval,
      yz ∈ fiberDyadicInterval I ×ˢ fiberDyadicSelectionSet Zf A H I
  · obtain ⟨I₀, hI₀⟩ := hex
    have hcount : fiberDyadicCountableBadField F Zf A H yz =
        fiberCZBadAtom F (fiberDyadicSelectionSet Zf A H) I₀ yz :=
      fiberDyadicCountableBadField_eq_atom_of_mem F Zf A H I₀ yz hI₀
    have hvanish : ∀ I : FiberDyadicInterval, I ≠ I₀ →
        fiberCZBadAtom F (fiberDyadicSelectionSet Zf A H) I yz = 0 := by
      intro I hI
      have hdisj := pairwiseDisjoint_fiberDyadicSelectedRectangles Zf A H
        (Set.mem_univ I₀) (Set.mem_univ I) (Ne.symm hI)
      have hnot : yz ∉ fiberDyadicInterval I ×ˢ
          fiberDyadicSelectionSet Zf A H I := by
        intro hmem
        exact (Set.disjoint_left.mp hdisj) hI₀ hmem
      unfold fiberCZBadAtom
      exact Set.indicator_of_notMem hnot _
    rw [hcount]
    show (∑ I ∈ T, fiberCZBadAtom F (fiberDyadicSelectionSet Zf A H) I yz) = _
    refine Finset.sum_eq_single I₀ (fun I _ hI ↦ hvanish I hI) (fun hnot ↦ ?_)
    exact absurd (hT I₀ hI₀) hnot
  · push_neg at hex
    have hnotex : yz ∉ fiberDyadicExceptionalSet Zf A H := by
      intro hmem
      rcases Set.mem_iUnion.mp hmem with ⟨I, hI⟩
      exact hex I hI
    rw [fiberDyadicCountableBadField_eq_zero_outside_exceptional
      F Zf A H yz hnotex]
    show (∑ I ∈ T, fiberCZBadAtom F (fiberDyadicSelectionSet Zf A H) I yz) = 0
    apply Finset.sum_eq_zero
    intro I _
    unfold fiberCZBadAtom
    exact Set.indicator_of_notMem (hex I) _

/-- **Pointwise exhaustion.**  Along any exhausting sequence of finite
families the finite selected bad fields converge to the countable one; the
sequence is in fact eventually constant at each point. -/
theorem tendsto_fiberCZBadField_countableBadField
    {Z : Type*} [MeasurableSpace Z] (F : ℝ × Z → ℝ) (Zf : Set Z)
    (A : FiberDyadicInterval → Z → ℝ) (H : ℝ)
    (Tn : ℕ → Finset FiberDyadicInterval) (hmono : Monotone Tn)
    (hexh : ∀ I : FiberDyadicInterval, ∃ n, I ∈ Tn n) (yz : ℝ × Z) :
    Filter.Tendsto
      (fun n ↦ fiberCZBadField F (Tn n) (fiberDyadicSelectionSet Zf A H) yz)
      Filter.atTop (nhds (fiberDyadicCountableBadField F Zf A H yz)) := by
  have heventually :
      (fun n ↦ fiberCZBadField F (Tn n) (fiberDyadicSelectionSet Zf A H) yz)
        =ᶠ[Filter.atTop]
        (fun _ : ℕ ↦ fiberDyadicCountableBadField F Zf A H yz) := by
    by_cases hex : ∃ I : FiberDyadicInterval,
        yz ∈ fiberDyadicInterval I ×ˢ fiberDyadicSelectionSet Zf A H I
    · obtain ⟨I₀, hI₀⟩ := hex
      obtain ⟨n₀, hn₀⟩ := hexh I₀
      filter_upwards [Filter.eventually_ge_atTop n₀] with n hn
      refine fiberCZBadField_eq_countableBadField_of_mem F Zf A H (Tn n) yz ?_
      intro I hI
      have hIeq : I = I₀ := by
        by_contra hne
        have hdisj := pairwiseDisjoint_fiberDyadicSelectedRectangles Zf A H
          (Set.mem_univ I₀) (Set.mem_univ I) (Ne.symm hne)
        exact (Set.disjoint_left.mp hdisj) hI₀ hI
      subst hIeq
      exact hmono hn hn₀
    · push_neg at hex
      filter_upwards with n
      exact fiberCZBadField_eq_countableBadField_of_mem F Zf A H (Tn n) yz
        (fun I hI ↦ absurd hI (hex I))
  exact Filter.Tendsto.congr' heventually.symm tendsto_const_nhds

end
end Twisted
end Auto
