/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.FiberDyadicMaximalScratch

namespace Auto
namespace Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators ENNReal RealInnerProductSpace Topology

noncomputable section

#check zpow_add₀
#check zpow_sub₀
#check zpow_mul
#check zpow_natCast
#check zpow_neg
#check Real.sq_sqrt
#check sq_lt_sq₀
#check sq_le_sq₀
#check mul_self_le_mul_self
#check pow_le_pow_left₀
#check Finset.prod_pow
#check Integrable.fintype_prod
#check MeasureTheory.memLp_one_iff_integrable
#check MemLp.meas_ge_lt_top
#check Real.toNNReal_le_iff_le_coe
#check ENNReal.toReal_le_toReal
#check ENNReal.toReal_mono
#check ENNReal.toReal_mono
#check ENNReal.toReal_le_toReal
#check ENNReal.coe_toNNReal
#check Real.toNNReal_pos
#check one_ne_zero
#check ENNReal.one_ne_top

#print axioms fiberDyadicBallMaximal_memLp
#check fiberDyadicBallMaximal_memLp
set_option pp.explicit true in
#check fiberDyadicBallMaximal_memLp
#check MeasureTheory.MeasurePreserving.memLp_comp_iff
#check MeasureTheory.memLp_map_measure_iff

example (m : ℤ) : (16 : ℝ) ^ m = (2 : ℝ) ^ (4 * m) := by
  norm_num [← zpow_mul]

example (m : ℤ) : (2 : ℝ) ^ ((m - 1) * 4) =
    ((2 : ℝ) ^ (m - 1)) ^ 4 := by
  rw [← zpow_natCast]
  rw [zpow_mul]

example (d : ℝ) (m : ℤ) :
    (d ^ 4 / 16) * (16 : ℝ) ^ m =
      (d * (2 : ℝ) ^ (m - 1)) ^ 4 := by
  calc
    (d ^ 4 / 16) * (16 : ℝ) ^ m =
        d ^ 4 * (2 ^ (4 * m) / 2 ^ 4) := by
          rw [show (16 : ℝ) = (2 : ℝ) ^ 4 by norm_num]
          rw [show (16 : ℝ) ^ m = (2 : ℝ) ^ (4 * m) by
            norm_num [← zpow_mul]]
          ring
    _ = d ^ 4 * 2 ^ (4 * m - 4) := by
          rw [zpow_sub₀ (by norm_num : (2 : ℝ) ≠ 0)]
    _ = d ^ 4 * 2 ^ ((m - 1) * 4) := by
          congr 2
          ring
    _ = d ^ 4 * (2 ^ (m - 1)) ^ 4 := by
          rw [← zpow_natCast]
          rw [zpow_mul]
    _ = (d * 2 ^ (m - 1)) ^ 4 := by ring

end
end Twisted
end Auto
