/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal

noncomputable section

/-! ## `thm:extended_model` from the interpolated operator bound

Source: `thm:extended_model`, final display.  Once
`eq:extended_operator_bound` is available at the output exponent `R` with
`R^{-1} + p_0^{-1} = 1`, Hölder against the zeroth input closes the theorem.
The common factor `U(u)^{100}` passes through untouched, exactly as the source
notes it does through the weighted geometric mean.
-/

/-- **The extended-range form bound.**  Given the interpolated operator
estimate at the conjugate exponent, the finite-interval form obeys the bound of
`thm:extended_model` with the same constant and the same `U(u)^{100}`. -/
theorem abs_ModelScaleIntervalTruncation_le_of_extended_operator_bound
    (α : Anisotropy) (u : E3) (c : ℝ → ℝ) (F : ModelSchwartzInput) (a b : ℝ)
    (hjoint : Integrable (fun xt : E3 × ℝ ↦
      modelTruncatedOperatorPairingIntegrand α u c F xt.2 xt.1)
      ((volume : Measure E3).prod
        (((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
          (Set.Ioc a b))))
    (p : Fin 4 → ℝ) {R Cst : ℝ}
    (hconj : Real.HolderConjugate (p 0) R)
    (hf : MemLp (fun x : E3 ↦ F 0 x) (ENNReal.ofReal (p 0)) volume)
    (hU : MemLp (ModelTruncatedOperator α u c (modelOperatorInput F) a b)
      (ENNReal.ofReal R) volume)
    (hop : lpNorm (ModelTruncatedOperator α u c (modelOperatorInput F) a b)
        (ENNReal.ofReal R) volume
      ≤ Cst * sourceWeight u ^ 100 *
          ∏ j : Fin 3, lpNorm (fun x : E3 ↦ F j.succ x)
            (ENNReal.ofReal (p j.succ)) volume) :
    |ModelScaleIntervalTruncation α u c F a b|
      ≤ Cst * sourceWeight u ^ 100 *
          ∏ j : Fin 4, lpNorm (fun x : E3 ↦ F j x)
            (ENNReal.ofReal (p j)) volume := by
  have hstep := abs_ModelScaleIntervalTruncation_le_of_operator_lpNorm
    α u c F a b hjoint hconj hf hU
  have hnn : 0 ≤ lpNorm (fun x : E3 ↦ F 0 x) (ENNReal.ofReal (p 0)) volume :=
    lpNorm_nonneg
  have hmul : lpNorm (fun x : E3 ↦ F 0 x) (ENNReal.ofReal (p 0)) volume *
      lpNorm (ModelTruncatedOperator α u c (modelOperatorInput F) a b)
        (ENNReal.ofReal R) volume
      ≤ lpNorm (fun x : E3 ↦ F 0 x) (ENNReal.ofReal (p 0)) volume *
          (Cst * sourceWeight u ^ 100 *
            ∏ j : Fin 3, lpNorm (fun x : E3 ↦ F j.succ x)
              (ENNReal.ofReal (p j.succ)) volume) :=
    mul_le_mul_of_nonneg_left hop hnn
  have hprod : ∏ j : Fin 4, lpNorm (fun x : E3 ↦ F j x)
        (ENNReal.ofReal (p j)) volume
      = lpNorm (fun x : E3 ↦ F 0 x) (ENNReal.ofReal (p 0)) volume *
          ∏ j : Fin 3, lpNorm (fun x : E3 ↦ F j.succ x)
            (ENNReal.ofReal (p j.succ)) volume :=
    Fin.prod_univ_succ _
  refine le_trans (le_trans hstep hmul) (le_of_eq ?_)
  rw [hprod]
  ring

end
end Twisted
end Auto
