/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/

import Auto.Twisted.FiberCZCountableBadFieldCandidate

namespace Auto
namespace Twisted

open MeasureTheory Filter

noncomputable section

/-! ## Actual countable selected good--bad operator splitting -/

/-- A bounded measurable input tuple admits an exact actual operator split
along the literal countable source stopping family in any coordinate slot.
Global selected-rectangle disjointness supplies the `3 B` and `2 B` bounds
that discharge all finite positive-scale integrability obligations. -/
theorem ModelTruncatedOperator_coordinateFiberDyadicCountableGoodBad_split_of_bounded_measurable
    (α : Anisotropy) (u : E3) (c : ℝ → ℝ) (f : ModelOperatorRealInput)
    (m : Fin 3) (Zf : Set (TransverseSpace m))
    (A : FiberDyadicInterval → TransverseSpace m → ℝ) (H : ℝ)
    (a b C : ℝ) (B : Fin 3 → ℝ) (x : E3)
    (ha : 0 < a) (hC : 0 ≤ C) (hc : Measurable c)
    (hcB : ∀ t : ℝ, |c t| ≤ C)
    (hf : ∀ j, Measurable (f j)) (hZf : MeasurableSet Zf)
    (hA : ∀ I, Measurable (A I))
    (hB : ∀ j, 0 ≤ B j) (hfB : ∀ j, ∀ y : E3, |f j y| ≤ B j) :
    ModelTruncatedOperator α u c f a b x =
      ModelTruncatedOperator α u c
        (modelOperatorReplace f m
          (coordinateFiberDyadicCountableGoodField m (f m) Zf A H)) a b x +
        ModelTruncatedOperator α u c
          (modelOperatorReplace f m
            (coordinateFiberDyadicCountableBadField m (f m) Zf A H)) a b x := by
  let G : E3 → ℝ :=
    coordinateFiberDyadicCountableGoodField m (f m) Zf A H
  let D : E3 → ℝ :=
    coordinateFiberDyadicCountableBadField m (f m) Zf A H
  let BG : ℝ := 3 * B m
  let BD : ℝ := 2 * B m
  let fG : ModelOperatorRealInput := modelOperatorReplace f m G
  let fD : ModelOperatorRealInput := modelOperatorReplace f m D
  let CG : Fin 3 → ℝ := fun j ↦ if j = m then BG else B j
  let CD : Fin 3 → ℝ := fun j ↦ if j = m then BD else B j
  have hGmeas : Measurable G := by
    dsimp only [G]
    exact measurable_coordinateFiberDyadicCountableGoodField
      m (f m) Zf A H (hf m) hZf hA
  have hDmeas : Measurable D := by
    dsimp only [D]
    exact measurable_coordinateFiberDyadicCountableBadField
      m (f m) Zf A H (hf m) hZf hA
  have hGbound : ∀ y : E3, |G y| ≤ BG := by
    intro y
    dsimp only [G, BG]
    exact abs_coordinateFiberDyadicCountableGoodField_le_of_bound
      m (f m) Zf A H (B m) (hB m) (hfB m) y
  have hDbound : ∀ y : E3, |D y| ≤ BD := by
    intro y
    dsimp only [D, BD]
    exact abs_coordinateFiberDyadicCountableBadField_le_of_bound
      m (f m) Zf A H (B m) (hB m) (hfB m) y
  have hBG : 0 ≤ BG := by
    dsimp only [BG]
    exact mul_nonneg (by norm_num) (hB m)
  have hBD : 0 ≤ BD := by
    dsimp only [BD]
    exact mul_nonneg (by norm_num) (hB m)
  have hfG : ∀ j, Measurable (fG j) := by
    intro j
    by_cases hj : j = m
    · subst j
      simpa only [fG, modelOperatorReplace_same] using hGmeas
    · simpa only [fG, modelOperatorReplace_ne f m j G hj] using hf j
  have hfD : ∀ j, Measurable (fD j) := by
    intro j
    by_cases hj : j = m
    · subst j
      simpa only [fD, modelOperatorReplace_same] using hDmeas
    · simpa only [fD, modelOperatorReplace_ne f m j D hj] using hf j
  have hCG : ∀ j, 0 ≤ CG j := by
    intro j
    by_cases hj : j = m
    · simp only [CG, if_pos hj]
      exact hBG
    · simp only [CG, if_neg hj]
      exact hB j
  have hCD : ∀ j, 0 ≤ CD j := by
    intro j
    by_cases hj : j = m
    · simp only [CD, if_pos hj]
      exact hBD
    · simp only [CD, if_neg hj]
      exact hB j
  have hfBG : ∀ j, ∀ y : E3, |fG j y| ≤ CG j := by
    intro j y
    by_cases hj : j = m
    · subst j
      simpa only [fG, CG, modelOperatorReplace_same, if_pos] using hGbound y
    · simpa only [fG, CG, modelOperatorReplace_ne f m j G hj, if_neg hj] using hfB j y
  have hfBD : ∀ j, ∀ y : E3, |fD j y| ≤ CD j := by
    intro j y
    by_cases hj : j = m
    · subst j
      simpa only [fD, CD, modelOperatorReplace_same, if_pos] using hDbound y
    · simpa only [fD, CD, modelOperatorReplace_ne f m j D hj, if_neg hj] using hfB j y
  have hlineG : ∀ t ∈ Set.Ioc a b, Integrable (fun r : ℝ ↦
      G (x - r • Anisotropy.coordinateDirection m) *
        kernelDilate (activeModelKernel 2 m u) (t ^ α.weight m) r) := by
    intro t ht
    exact integrable_modelCoordinateConvolutionIntegrand_of_bounded_measurable
      m G (activeModelKernel 2 m u) (t ^ α.weight m) x hGmeas BG hGbound
      (integrable_activeModelKernel 2 m u) (pow_pos (lt_trans ha ht.1) _)
  have hlineD : ∀ t ∈ Set.Ioc a b, Integrable (fun r : ℝ ↦
      D (x - r • Anisotropy.coordinateDirection m) *
        kernelDilate (activeModelKernel 2 m u) (t ^ α.weight m) r) := by
    intro t ht
    exact integrable_modelCoordinateConvolutionIntegrand_of_bounded_measurable
      m D (activeModelKernel 2 m u) (t ^ α.weight m) x hDmeas BD hDbound
      (integrable_activeModelKernel 2 m u) (pow_pos (lt_trans ha ht.1) _)
  have hscaleG : IntegrableOn (fun t : ℝ ↦
      modelTruncatedOperatorIntegrand α u c fG t x) (Set.Ioc a b)
      ((volume : Measure ℝ).withDensity cubeScaleDensity) := by
    exact integrableOn_modelTruncatedOperatorIntegrand_of_bounded_measurable
      α u c fG a b C CG x ha hC hc hcB hfG hCG hfBG
  have hscaleD : IntegrableOn (fun t : ℝ ↦
      modelTruncatedOperatorIntegrand α u c fD t x) (Set.Ioc a b)
      ((volume : Measure ℝ).withDensity cubeScaleDensity) := by
    exact integrableOn_modelTruncatedOperatorIntegrand_of_bounded_measurable
      α u c fD a b C CD x ha hC hc hcB hfD hCD hfBD
  have hadd := ModelTruncatedOperator_replace_add_on_scaleInterval
    α u c f m G D a b x hlineG hlineD hscaleG hscaleD
  have hreplace : modelOperatorReplace f m (G + D) = f := by
    dsimp only [G, D]
    exact modelOperatorReplace_coordinateFiberDyadicCountableGoodBad_eq
      f m Zf A H
  rw [hreplace] at hadd
  simpa only [fG, fD, G, D] using hadd

end
end Twisted
end Auto
