/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted
import LeanSpherical.Auto.Spherical.Auxiliary

namespace Auto
namespace Twisted

open MeasureTheory Filter TopologicalSpace
open scoped ENNReal BigOperators RealInnerProductSpace
open Auto.HardyLittlewoodMaximal
open Auto.Spherical.Auxiliary

noncomputable section


/-- A bounded measurable fiber has finite mass on every dyadic line ball,
and that mass is controlled by the literal fiberwise dyadic maximum. -/
theorem fiberDyadicBall_integral_le_dyadic_average_sup
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (q : FiberDyadicBase × FiberDyadicLine) (m : ℤ) :
    (∫ y in Metric.ball q.2 ((2 : ℝ) ^ m), ‖G (q.1, y)‖) ≤
      fiberDyadicBallMaximal G q *
        (volume (Metric.ball q.2 ((2 : ℝ) ^ m))).toReal := by
  let S : ENNReal := ⨆ n : ℤ,
    ((volume (Metric.ball q.2 ((2 : ℝ) ^ n)))⁻¹ *
      ∫⁻ y in Metric.ball q.2 ((2 : ℝ) ^ n), ENNReal.ofReal ‖G (q.1, y)‖)
  have hSle : S ≤ ENNReal.ofReal a := by
    dsimp only [S]
    exact fiberDyadicBallMaximalRaw_le_of_norm_le G q a ha hGa
  have hSfin : S ≠ ⊤ :=
    ne_top_of_le_ne_top ENNReal.ofReal_ne_top hSle
  let r : ℝ := (2 : ℝ) ^ m
  have hr : 0 < r := by
    dsimp only [r]
    positivity
  have hvolpos : 0 < volume (Metric.ball q.2 r) :=
    Metric.measure_ball_pos volume q.2 hr
  have hvoltop : volume (Metric.ball q.2 r) ≠ (⊤ : ENNReal) :=
    measure_ball_lt_top.ne
  have havg :
      (volume (Metric.ball q.2 r))⁻¹ *
        (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖) ≤ S := by
    dsimp only [S]
    exact le_iSup (fun n : ℤ =>
      (volume (Metric.ball q.2 ((2 : ℝ) ^ n)))⁻¹ *
        ∫⁻ y in Metric.ball q.2 ((2 : ℝ) ^ n), ENNReal.ofReal ‖G (q.1, y)‖) m
  have hlin :
      (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖) ≤
        S * volume (Metric.ball q.2 r) := by
    calc
      (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖) =
          ((volume (Metric.ball q.2 r))⁻¹ *
            (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖)) *
              volume (Metric.ball q.2 r) := by
            calc
              (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖) =
                  1 * (∫⁻ y in Metric.ball q.2 r,
                    ENNReal.ofReal ‖G (q.1, y)‖) := by rw [one_mul]
              _ = ((volume (Metric.ball q.2 r))⁻¹ * volume (Metric.ball q.2 r)) *
                    (∫⁻ y in Metric.ball q.2 r,
                      ENNReal.ofReal ‖G (q.1, y)‖) := by
                    rw [ENNReal.inv_mul_cancel hvolpos.ne' hvoltop]
              _ = ((volume (Metric.ball q.2 r))⁻¹ *
                    (∫⁻ y in Metric.ball q.2 r,
                      ENNReal.ofReal ‖G (q.1, y)‖)) *
                    volume (Metric.ball q.2 r) := by ac_rfl
      _ ≤ S * volume (Metric.ball q.2 r) := by
        calc
          ((volume (Metric.ball q.2 r))⁻¹ *
              (∫⁻ y in Metric.ball q.2 r,
                ENNReal.ofReal ‖G (q.1, y)‖)) * volume (Metric.ball q.2 r) =
              volume (Metric.ball q.2 r) *
                ((volume (Metric.ball q.2 r))⁻¹ *
                  (∫⁻ y in Metric.ball q.2 r,
                    ENNReal.ofReal ‖G (q.1, y)‖)) := by ac_rfl
          _ ≤ volume (Metric.ball q.2 r) * S := mul_le_mul_right havg _
          _ = S * volume (Metric.ball q.2 r) := by ac_rfl
  have hline_meas : Measurable (fun y : FiberDyadicLine => ‖G (q.1, y)‖) :=
    (hG.comp (measurable_const.prodMk measurable_id)).norm
  have hline_int : IntegrableOn (fun y : FiberDyadicLine => ‖G (q.1, y)‖)
      (Metric.ball q.2 r) volume := by
    refine IntegrableOn.of_bound measure_ball_lt_top hline_meas.aestronglyMeasurable a ?_
    filter_upwards [] with y
    rw [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg _)]
    exact hGa (q.1, y)
  have hlinfin :
      (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖) ≠ ⊤ :=
    hline_int.lintegral_lt_top.ne
  have hreal :
      (∫ y in Metric.ball q.2 r, ‖G (q.1, y)‖) =
        (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖).toReal := by
    have hnonneg : 0 ≤ ∫ y in Metric.ball q.2 r, ‖G (q.1, y)‖ :=
      integral_nonneg fun y => norm_nonneg _
    rw [← ENNReal.toReal_ofReal hnonneg,
      MeasureTheory.ofReal_integral_eq_lintegral_ofReal hline_int
        (Filter.Eventually.of_forall fun _ => norm_nonneg _)]
  change (∫ y in Metric.ball q.2 r, ‖G (q.1, y)‖) ≤
    S.toReal * (volume (Metric.ball q.2 r)).toReal
  calc
    (∫ y in Metric.ball q.2 r, ‖G (q.1, y)‖) =
        (∫⁻ y in Metric.ball q.2 r, ENNReal.ofReal ‖G (q.1, y)‖).toReal := hreal
    _ ≤ (S * volume (Metric.ball q.2 r)).toReal :=
      (ENNReal.toReal_le_toReal hlinfin
        (ENNReal.mul_ne_top hSfin hvoltop)).2 hlin
    _ = S.toReal * (volume (Metric.ball q.2 r)).toReal := ENNReal.toReal_mul

/-- The literal fiber maximum controls balls of arbitrary positive radius.
The factor `2` is the sole loss from rounding the radius up to a dyadic one. -/
theorem fiberDyadicBall_integral_le_dyadic_average_sup_any_radius
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (q : FiberDyadicBase × FiberDyadicLine) {R : ℝ} (hR : 0 < R) :
    (∫ y in Metric.ball q.2 R, ‖G (q.1, y)‖) ≤
      fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal * (2 * R) := by
  obtain ⟨m, hm⟩ := exists_mem_Ico_zpow hR (by norm_num : (1 : ℝ) < 2)
  have hsubset : Metric.ball q.2 R ⊆ Metric.ball q.2 ((2 : ℝ) ^ (m + 1)) :=
    Metric.ball_subset_ball hm.2.le
  have hline_meas : Measurable (fun y : FiberDyadicLine => ‖G (q.1, y)‖) :=
    (hG.comp (measurable_const.prodMk measurable_id)).norm
  have htarget_int : IntegrableOn (fun y : FiberDyadicLine => ‖G (q.1, y)‖)
      (Metric.ball q.2 ((2 : ℝ) ^ (m + 1))) volume := by
    refine IntegrableOn.of_bound measure_ball_lt_top hline_meas.aestronglyMeasurable a ?_
    filter_upwards [] with y
    rw [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg _)]
    exact hGa (q.1, y)
  have hmono :
      (∫ y in Metric.ball q.2 R, ‖G (q.1, y)‖) ≤
        ∫ y in Metric.ball q.2 ((2 : ℝ) ^ (m + 1)), ‖G (q.1, y)‖ := by
    apply MeasureTheory.setIntegral_mono_set htarget_int
    · exact Filter.Eventually.of_forall fun y => norm_nonneg _
    · exact Filter.Eventually.of_forall hsubset
  have hrad : (2 : ℝ) ^ (m + 1) ≤ 2 * R := by
    calc
      (2 : ℝ) ^ (m + 1) = (2 : ℝ) ^ m * (2 : ℝ) ^ (1 : ℤ) :=
        zpow_add₀ (by norm_num) m 1
      _ = 2 * (2 : ℝ) ^ m := by norm_num; ring
      _ ≤ 2 * R := mul_le_mul_of_nonneg_left hm.1 (by norm_num)
  have hradpos : 0 < (2 : ℝ) ^ (m + 1) := by positivity
  have hvol : volume (Metric.ball q.2 ((2 : ℝ) ^ (m + 1))) =
      ENNReal.ofReal ((2 : ℝ) ^ (m + 1)) *
        volume (Metric.ball (0 : FiberDyadicLine) 1) := by
    rw [Measure.addHaar_ball_of_pos volume q.2 hradpos]
    simp only [finrank_euclideanSpace_fin]
    norm_num
  have hdyadic := fiberDyadicBall_integral_le_dyadic_average_sup
    G hG a ha hGa q (m + 1)
  have hfactor_nonneg : 0 ≤
      fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal := by
    exact mul_nonneg ENNReal.toReal_nonneg ENNReal.toReal_nonneg
  calc
    (∫ y in Metric.ball q.2 R, ‖G (q.1, y)‖) ≤
        ∫ y in Metric.ball q.2 ((2 : ℝ) ^ (m + 1)), ‖G (q.1, y)‖ := hmono
    _ ≤ fiberDyadicBallMaximal G q *
        (volume (Metric.ball q.2 ((2 : ℝ) ^ (m + 1)))).toReal := hdyadic
    _ = fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal *
          ((2 : ℝ) ^ (m + 1)) := by
      rw [hvol, ENNReal.toReal_mul,
        ENNReal.toReal_ofReal hradpos.le]
      ring
    _ ≤ fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal * (2 * R) :=
      mul_le_mul_of_nonneg_left hrad hfactor_nonneg

/-- The radial version of the source bracket kernel on the one-dimensional
fiber Euclidean space.  This formulation is invariant under later coordinate
reorderings. -/
noncomputable def fiberRadialBracket (z : FiberDyadicLine) : ℝ :=
  (1 + ‖z‖) ^ (-10 : ℝ)

theorem fiberRadialBracket_nonneg (z : FiberDyadicLine) :
    0 ≤ fiberRadialBracket z := by
  unfold fiberRadialBracket
  positivity

theorem fiberRadialBracket_le_one (z : FiberDyadicLine) :
    fiberRadialBracket z ≤ 1 := by
  unfold fiberRadialBracket
  exact Real.rpow_le_one_of_one_le_of_nonpos
    (le_add_of_nonneg_right (norm_nonneg _)) (by norm_num)

theorem integrable_fiberRadialBracket : Integrable fiberRadialBracket := by
  unfold fiberRadialBracket
  exact integrable_one_add_norm (E := FiberDyadicLine) (μ := volume)
    (r := (10 : ℝ)) (by norm_num)

/-- The scale cancellation in the one-dimensional shell decomposition. -/
private theorem fiber_shell_tail_coefficient
    (A r : ℝ) (n : ℕ) (hr : 0 < r) :
    (A * r⁻¹ * (((2 : ℝ)⁻¹) ^ (1 + 3)) ^ n) *
        (2 * ((2 : ℝ) ^ (n + 2) * r)) =
      A * (2 : ℝ) ^ 3 * (1 / 8 : ℝ) ^ n := by
  have hr0 : r ≠ 0 := hr.ne'
  rw [show 2 * ((2 : ℝ) ^ (n + 2) * r) =
      (2 : ℝ) ^ (n + 3) * r by
        rw [show n + 3 = (n + 2) + 1 by omega, pow_succ]
        ring]
  rw [show (((2 : ℝ)⁻¹) ^ (1 + 3)) ^ n =
      ((2 : ℝ)⁻¹) ^ ((1 + 3) * n) by rw [pow_mul]]
  rw [show ((2 : ℝ)⁻¹) ^ ((1 + 3) * n) =
      ((2 : ℝ) ^ ((1 + 3) * n))⁻¹ by rw [inv_pow]]
  rw [show (1 / 8 : ℝ) = ((2 : ℝ)⁻¹) ^ 3 by norm_num]
  rw [← pow_mul, inv_pow]
  norm_num
  field_simp
  ring

private theorem fiber_exists_dyadic_annulus {t : ℝ} (ht : 2 ≤ t) :
    ∃ n : ℕ, (2 : ℝ) ^ n ≤ t ∧ t < (2 : ℝ) ^ (n + 1) := by
  have hpow : Filter.Tendsto (fun n : ℕ => (2 : ℝ) ^ n) Filter.atTop Filter.atTop :=
    tendsto_pow_atTop_atTop_of_one_lt (by norm_num)
  obtain ⟨m, hm⟩ := Filter.eventually_atTop.1 (hpow.eventually_gt_atTop t)
  have hexists : ∃ n : ℕ, t < (2 : ℝ) ^ (n + 1) := by
    refine ⟨m, ?_⟩
    apply (hm m le_rfl).trans_le
    rw [show m + 1 = Nat.succ m by omega, pow_succ]
    have hnonneg : 0 ≤ (2 : ℝ) ^ m := pow_nonneg (by norm_num) _
    nlinarith
  let n : ℕ := Nat.find hexists
  have hnupper : t < (2 : ℝ) ^ (n + 1) := Nat.find_spec hexists
  have hnpos : 0 < n := by
    by_contra h
    have hnzero : n = 0 := Nat.eq_zero_of_not_pos h
    have hsmall : t < 2 := by
      simpa [hnzero] using hnupper
    linarith
  have hnlower : (2 : ℝ) ^ n ≤ t := by
    by_contra h
    have hlt : t < (2 : ℝ) ^ n := lt_of_not_ge h
    have hpred : n - 1 + 1 = n := Nat.sub_add_cancel (Nat.succ_le_iff.2 hnpos)
    have : t < (2 : ℝ) ^ ((n - 1) + 1) := by simpa [hpred] using hlt
    exact (not_lt_of_ge (Nat.find_min' hexists this))
      (Nat.sub_lt hnpos (by omega))
  exact ⟨n, hnlower, hnupper⟩

/-- A bounded measurable one-dimensional fiber is controlled by its literal
dyadic-ball maximal function against every nonnegative summable shell kernel.
The separate integrability hypothesis is discharged below for the bracket
kernel, and is what makes this version reusable after one maximal iteration. -/
theorem fiber_shell_weighted_integral_le_dyadic_average_sup
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (W : FiberDyadicLine → ℝ)
    {C L r : ℝ} (hC : 0 ≤ C) (hL : 1 ≤ L) (hr : 0 < r)
    (hW_nonneg : ∀ z, 0 ≤ W z)
    (hW_near : ∀ z, W z ≤ C * L)
    (hW_tail : ∀ (z : FiberDyadicLine) (m : ℕ),
      (2 : ℝ) ^ m / L ≤ |‖z‖ - 1| →
        W z ≤ C * L * (((2 : ℝ)⁻¹) ^ (1 + 3)) ^ m)
    (q : FiberDyadicBase × FiberDyadicLine) :
    (∫ y : FiberDyadicLine,
      ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2)))) ≤
      2 * ((C * L) *
        (fiberDyadicBallMaximal G q *
          (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) *
        (2 : ℝ) ^ 3) := by
  let ρ : ℝ := ((2 : ℝ)⁻¹) ^ (1 + 3)
  let A : ℝ := C * L
  let M : ℝ := fiberDyadicBallMaximal G q *
    (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal
  have hL_nonneg : 0 ≤ L := le_trans zero_le_one hL
  have hA : 0 ≤ A := mul_nonneg hC hL_nonneg
  have hM : 0 ≤ M := by
    dsimp [M]
    exact mul_nonneg ENNReal.toReal_nonneg ENNReal.toReal_nonneg
  have hrinv_nonneg : 0 ≤ r⁻¹ := inv_nonneg.mpr hr.le
  have hρ_nonneg : 0 ≤ ρ := by
    dsimp [ρ]
    positivity
  have hρ_lt_one : ρ < 1 := by
    dsimp [ρ]
    norm_num
  have hρ_norm_lt_one : ‖ρ‖ < 1 := by
    rw [Real.norm_eq_abs, abs_of_nonneg hρ_nonneg]
    exact hρ_lt_one
  have hgeom : Summable fun n : ℕ => ρ ^ n :=
    summable_geometric_of_norm_lt_one hρ_norm_lt_one
  have hline_meas : Measurable (fun y : FiberDyadicLine => ‖G (q.1, y)‖) :=
    (hG.comp (measurable_const.prodMk measurable_id)).norm
  let F : ℕ → FiberDyadicLine → ℝ := fun n y =>
    (A * r⁻¹ * ρ ^ n) *
      (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)).indicator
        (fun z => ‖G (q.1, z)‖) y
  have hF_nonneg (n : ℕ) (y : FiberDyadicLine) : 0 ≤ F n y := by
    dsimp [F]
    apply mul_nonneg
    · exact mul_nonneg (mul_nonneg hA hrinv_nonneg) (pow_nonneg hρ_nonneg _)
    · apply Set.indicator_nonneg
      intro z _
      exact norm_nonneg _
  have hF_le_major (n : ℕ) (y : FiberDyadicLine) :
      F n y ≤ (A * r⁻¹ * a) * ρ ^ n := by
    dsimp [F]
    have hind :
        (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)).indicator
          (fun z => ‖G (q.1, z)‖) y ≤ a := by
      by_cases hy : y ∈ Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)
      · simpa [hy] using hGa (q.1, y)
      · simp [hy, ha]
    calc
      (A * r⁻¹ * ρ ^ n) *
          (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)).indicator
            (fun z => ‖G (q.1, z)‖) y ≤
          (A * r⁻¹ * ρ ^ n) * a :=
        mul_le_mul_of_nonneg_left hind
          (mul_nonneg (mul_nonneg hA hrinv_nonneg) (pow_nonneg hρ_nonneg _))
      _ = (A * r⁻¹ * a) * ρ ^ n := by ring
  have hF_pointwise_summable (y : FiberDyadicLine) :
      Summable fun n : ℕ => F n y := by
    refine Summable.of_nonneg_of_le
      (f := fun n : ℕ => (A * r⁻¹ * a) * ρ ^ n)
      (g := fun n : ℕ => F n y) ?_ ?_ ?_
    · intro n
      exact hF_nonneg n y
    · intro n
      exact hF_le_major n y
    · simpa [mul_assoc] using hgeom.mul_left (A * r⁻¹ * a)
  have hball_of_scaled_norm_lt (n : ℕ) (y : FiberDyadicLine)
      (hy : ‖r⁻¹ • (y - q.2)‖ < (2 : ℝ) ^ (n + 2)) :
      y ∈ Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r) := by
    rw [Metric.mem_ball, dist_eq_norm_sub]
    have hnorm : ‖y - q.2‖ = r * ‖r⁻¹ • (y - q.2)‖ := by
      rw [norm_smul_of_nonneg hrinv_nonneg]
      field_simp [hr.ne']
    calc
      ‖y - q.2‖ = r * ‖r⁻¹ • (y - q.2)‖ := hnorm
      _ < r * (2 : ℝ) ^ (n + 2) := mul_lt_mul_of_pos_left hy hr
      _ = (2 : ℝ) ^ (n + 2) * r := by ring
  have hpointwise (y : FiberDyadicLine) :
      ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2))) ≤ ∑' n : ℕ, F n y := by
    have hsum := hF_pointwise_summable y
    by_cases hy : ‖r⁻¹ • (y - q.2)‖ < 2
    · have hyball : y ∈ Metric.ball q.2 ((2 : ℝ) ^ (0 + 2) * r) := by
        apply hball_of_scaled_norm_lt 0 y
        calc
          ‖r⁻¹ • (y - q.2)‖ < 2 := hy
          _ < (2 : ℝ) ^ (0 + 2) := by norm_num
      have hterm :
          ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2))) ≤ F 0 y := by
        have hW := hW_near (r⁻¹ • (y - q.2))
        calc
          ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2))) ≤
              ‖G (q.1, y)‖ * (r⁻¹ * A) := by
            apply mul_le_mul_of_nonneg_left
            · exact mul_le_mul_of_nonneg_left hW hrinv_nonneg
            · exact norm_nonneg _
          _ = F 0 y := by
            dsimp [F, ρ]
            rw [Set.indicator_of_mem hyball]
            norm_num
            ring
      exact hterm.trans (hsum.le_tsum 0 fun j _ => hF_nonneg j y)
    · have htwo : 2 ≤ ‖r⁻¹ • (y - q.2)‖ := le_of_not_gt hy
      obtain ⟨k, hklow, hkupper⟩ := fiber_exists_dyadic_annulus htwo
      have hkpos : 0 < k := by
        by_contra hk
        have hkzero : k = 0 := Nat.eq_zero_of_not_pos hk
        have hsmall : ‖r⁻¹ • (y - q.2)‖ < 2 := by
          simpa [hkzero] using hkupper
        exact (not_lt_of_ge htwo) hsmall
      let n : ℕ := k - 1
      have hnadd : n + 1 = k := by
        dsimp [n]
        omega
      have hnadd' : n + 2 = k + 1 := by omega
      have hlow : (2 : ℝ) ^ (n + 1) ≤ ‖r⁻¹ • (y - q.2)‖ := by
        simpa [hnadd] using hklow
      have hupp : ‖r⁻¹ • (y - q.2)‖ < (2 : ℝ) ^ (n + 2) := by
        simpa [hnadd'] using hkupper
      have hnorm_one : 1 ≤ ‖r⁻¹ • (y - q.2)‖ := by
        calc
          1 ≤ (2 : ℝ) ^ (n + 1) := one_le_pow₀ (by norm_num)
          _ ≤ ‖r⁻¹ • (y - q.2)‖ := hlow
      have hsub : (2 : ℝ) ^ n ≤ ‖r⁻¹ • (y - q.2)‖ - 1 := by
        have hpow_one : 1 ≤ (2 : ℝ) ^ n := one_le_pow₀ (by norm_num)
        rw [show (2 : ℝ) ^ (n + 1) = 2 * (2 : ℝ) ^ n by
          rw [pow_succ]
          ring] at hlow
        nlinarith
      have habs : (2 : ℝ) ^ n ≤ |‖r⁻¹ • (y - q.2)‖ - 1| := by
        rw [abs_of_nonneg (sub_nonneg.mpr hnorm_one)]
        exact hsub
      have hdiv : (2 : ℝ) ^ n / L ≤ |‖r⁻¹ • (y - q.2)‖ - 1| := by
        calc
          (2 : ℝ) ^ n / L ≤ (2 : ℝ) ^ n := by
            apply (div_le_iff₀ (lt_of_lt_of_le zero_lt_one hL)).2
            calc
              (2 : ℝ) ^ n = (2 : ℝ) ^ n * 1 := by ring
              _ ≤ (2 : ℝ) ^ n * L :=
                mul_le_mul_of_nonneg_left hL (pow_nonneg (by norm_num) _)
          _ ≤ _ := habs
      have hyball : y ∈ Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r) :=
        hball_of_scaled_norm_lt n y hupp
      have hterm :
          ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2))) ≤ F n y := by
        have hW := hW_tail (r⁻¹ • (y - q.2)) n hdiv
        calc
          ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2))) ≤
              ‖G (q.1, y)‖ * (r⁻¹ * (A * ρ ^ n)) := by
            apply mul_le_mul_of_nonneg_left
            · exact mul_le_mul_of_nonneg_left (by simpa [A, ρ] using hW) hrinv_nonneg
            · exact norm_nonneg _
          _ = F n y := by
            dsimp [F]
            rw [Set.indicator_of_mem hyball]
            ring
      exact hterm.trans (hsum.le_tsum n fun j _ => hF_nonneg j y)
  have hF_integrable (n : ℕ) : Integrable (F n) volume := by
    dsimp [F]
    have hline_int : IntegrableOn (fun y : FiberDyadicLine => ‖G (q.1, y)‖)
        (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)) volume := by
      refine IntegrableOn.of_bound measure_ball_lt_top hline_meas.aestronglyMeasurable a ?_
      filter_upwards [] with y
      rw [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg _)]
      exact hGa (q.1, y)
    exact (hline_int.integrable_indicator measurableSet_ball).const_mul
      (A * r⁻¹ * ρ ^ n)
  have hF_integral (n : ℕ) :
      (∫ y : FiberDyadicLine, F n y) =
        (A * r⁻¹ * ρ ^ n) *
          (∫ y in Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r), ‖G (q.1, y)‖) := by
    dsimp [F]
    rw [integral_const_mul, integral_indicator measurableSet_ball]
  have hF_integral_bound (n : ℕ) :
      (∫ y : FiberDyadicLine, F n y) ≤
        (A * M * (2 : ℝ) ^ 3) * (1 / 8 : ℝ) ^ n := by
    have hradius : 0 < (2 : ℝ) ^ (n + 2) * r :=
      mul_pos (pow_pos (by norm_num) _) hr
    rw [hF_integral]
    calc
      (A * r⁻¹ * ρ ^ n) *
          (∫ y in Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r), ‖G (q.1, y)‖) ≤
          (A * r⁻¹ * ρ ^ n) *
            (M * (2 * ((2 : ℝ) ^ (n + 2) * r))) :=
        mul_le_mul_of_nonneg_left
          (by
            simpa [M, mul_assoc] using
              (fiberDyadicBall_integral_le_dyadic_average_sup_any_radius
                G hG a ha hGa q hradius))
          (mul_nonneg (mul_nonneg hA hrinv_nonneg) (pow_nonneg hρ_nonneg _))
      _ = (A * M * (2 : ℝ) ^ 3) * (1 / 8 : ℝ) ^ n := by
        dsimp [ρ]
        convert fiber_shell_tail_coefficient (A * M) r n hr using 1
        ring
  have hG_summable : Summable fun n : ℕ =>
      (A * M * (2 : ℝ) ^ 3) * (1 / 8 : ℝ) ^ n := by
    have heighth : ‖(1 / 8 : ℝ)‖ < 1 := by norm_num
    have hbase := (summable_geometric_of_norm_lt_one heighth).mul_left
      (A * M * (2 : ℝ) ^ 3)
    exact hbase
  have hF_summable_integral_norm : Summable fun n : ℕ =>
      ∫ y : FiberDyadicLine, ‖F n y‖ := by
    refine Summable.of_nonneg_of_le
      (f := fun n : ℕ => (A * M * (2 : ℝ) ^ 3) * (1 / 8 : ℝ) ^ n)
      (g := fun n : ℕ => ∫ y : FiberDyadicLine, ‖F n y‖) ?_ ?_ hG_summable
    · intro n
      exact integral_nonneg fun y => norm_nonneg _
    · intro n
      have hnorm : (∫ y : FiberDyadicLine, ‖F n y‖) = ∫ y : FiberDyadicLine, F n y := by
        apply integral_congr_ae
        filter_upwards with y
        rw [Real.norm_of_nonneg (hF_nonneg n y)]
      rw [hnorm]
      exact hF_integral_bound n
  have hF_enorm_sum_lt_top :
      (∑' n : ℕ, ∫⁻ y : FiberDyadicLine, ‖F n y‖ₑ) < ⊤ := by
    calc
      (∑' n : ℕ, ∫⁻ y : FiberDyadicLine, ‖F n y‖ₑ) =
          ∑' n : ℕ, ENNReal.ofReal (∫ y : FiberDyadicLine, ‖F n y‖) := by
        apply tsum_congr
        intro n
        exact (ofReal_integral_norm_eq_lintegral_enorm (hF_integrable n)).symm
      _ < ⊤ := hF_summable_integral_norm.tsum_ofReal_lt_top
  have htsum_measurable : AEStronglyMeasurable
      (fun y : FiberDyadicLine => ∑' n : ℕ, F n y) volume :=
    AEStronglyMeasurable.tsum fun n => (hF_integrable n).aestronglyMeasurable
  have htsum_integrable : Integrable (fun y : FiberDyadicLine => ∑' n : ℕ, F n y) volume := by
    refine ⟨htsum_measurable, ?_⟩
    rw [hasFiniteIntegral_iff_enorm]
    calc
      ∫⁻ y : FiberDyadicLine, ‖∑' n : ℕ, F n y‖ₑ ≤
          ∫⁻ y : FiberDyadicLine, ∑' n : ℕ, ‖F n y‖ₑ :=
        lintegral_mono fun y => enorm_tsum_le_tsum_enorm
      _ = ∑' n : ℕ, ∫⁻ y : FiberDyadicLine, ‖F n y‖ₑ :=
        lintegral_tsum fun n => (hF_integrable n).aestronglyMeasurable.enorm
      _ < ⊤ := hF_enorm_sum_lt_top
  have htsum_integral :
      (∫ y : FiberDyadicLine, ∑' n : ℕ, F n y) =
        ∑' n : ℕ, ∫ y : FiberDyadicLine, F n y := by
    exact (MeasureTheory.integral_tsum_of_summable_integral_norm
      hF_integrable hF_summable_integral_norm).symm
  have hF_summable_integral : Summable fun n : ℕ =>
      ∫ y : FiberDyadicLine, F n y := by
    refine Summable.of_nonneg_of_le
      (f := fun n : ℕ => (A * M * (2 : ℝ) ^ 3) * (1 / 8 : ℝ) ^ n)
      (g := fun n : ℕ => ∫ y : FiberDyadicLine, F n y) ?_ ?_ hG_summable
    · intro n
      exact integral_nonneg fun y => hF_nonneg n y
    · intro n
      exact hF_integral_bound n
  have hD_nonneg : 0 ≤ A * M * (2 : ℝ) ^ 3 := by positivity
  have heighth : ‖(1 / 8 : ℝ)‖ < 1 := by norm_num
  have hsum_eighth : ∑' n : ℕ, (1 / 8 : ℝ) ^ n = 8 / 7 := by
    rw [(hasSum_geometric_of_norm_lt_one heighth).tsum_eq]
    norm_num
  have hsum_integrals_bound :
      (∑' n : ℕ, ∫ y : FiberDyadicLine, F n y) ≤
        2 * (A * M * (2 : ℝ) ^ 3) := by
    calc
      (∑' n : ℕ, ∫ y : FiberDyadicLine, F n y) ≤
          ∑' n : ℕ, (A * M * (2 : ℝ) ^ 3) * (1 / 8 : ℝ) ^ n :=
        Summable.tsum_le_tsum (fun n => hF_integral_bound n)
          hF_summable_integral hG_summable
      _ = (A * M * (2 : ℝ) ^ 3) * ∑' n : ℕ, (1 / 8 : ℝ) ^ n := by
        rw [tsum_mul_left]
      _ = (A * M * (2 : ℝ) ^ 3) * (8 / 7) := by rw [hsum_eighth]
      _ ≤ (A * M * (2 : ℝ) ^ 3) * 2 :=
        mul_le_mul_of_nonneg_left (by norm_num) hD_nonneg
      _ = 2 * (A * M * (2 : ℝ) ^ 3) := by ring
  have hleft_nonneg (y : FiberDyadicLine) :
      0 ≤ ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2))) := by
    exact mul_nonneg (norm_nonneg _)
      (mul_nonneg hrinv_nonneg (hW_nonneg _))
  calc
    (∫ y : FiberDyadicLine,
        ‖G (q.1, y)‖ * (r⁻¹ * W (r⁻¹ • (y - q.2)))) ≤
        ∫ y : FiberDyadicLine, ∑' n : ℕ, F n y :=
      integral_mono_of_nonneg
        (Filter.Eventually.of_forall hleft_nonneg) htsum_integrable
        (Filter.Eventually.of_forall hpointwise)
    _ = ∑' n : ℕ, ∫ y : FiberDyadicLine, F n y := htsum_integral
    _ ≤ 2 * (A * M * (2 : ℝ) ^ 3) := hsum_integrals_bound
    _ = _ := by
      dsimp [A, M]

theorem fiberRadialBracket_tail (z : FiberDyadicLine) (m : ℕ)
    (h : (2 : ℝ) ^ m ≤ |‖z‖ - 1|) :
    fiberRadialBracket z ≤ (((2 : ℝ)⁻¹) ^ (1 + 3)) ^ m := by
  rcases Nat.eq_zero_or_pos m with rfl | hm
  · simpa using fiberRadialBracket_le_one z
  have hpow_two : 2 ≤ (2 : ℝ) ^ m := by
    calc
      2 = (2 : ℝ) ^ 1 := by norm_num
      _ ≤ (2 : ℝ) ^ m := pow_le_pow_right₀ (by norm_num) (by omega)
  have hsub_nonneg : 0 ≤ ‖z‖ - 1 := by
    by_contra hneg
    have hsubneg : ‖z‖ - 1 < 0 := lt_of_not_ge hneg
    have habs_eq : |‖z‖ - 1| = 1 - ‖z‖ := by
      rw [abs_of_neg hsubneg]
      ring
    have habs_le : |‖z‖ - 1| ≤ 1 := by
      rw [habs_eq]
      linarith [norm_nonneg z]
    nlinarith
  have hbase : (2 : ℝ) ^ m ≤ 1 + ‖z‖ := by
    rw [abs_of_nonneg hsub_nonneg] at h
    linarith
  have hdenom : (2 : ℝ) ^ (4 * m) ≤ (1 + ‖z‖) ^ 10 := by
    calc
      (2 : ℝ) ^ (4 * m) ≤ (2 : ℝ) ^ (10 * m) :=
        pow_le_pow_right₀ (by norm_num) (by omega)
      _ = ((2 : ℝ) ^ m) ^ 10 := by
        calc
          (2 : ℝ) ^ (10 * m) = (2 : ℝ) ^ (m * 10) := by
            congr 1
            omega
          _ = ((2 : ℝ) ^ m) ^ 10 := pow_mul (2 : ℝ) m 10
      _ ≤ (1 + ‖z‖) ^ 10 :=
        pow_le_pow_left₀ (pow_nonneg (by norm_num) _) hbase 10
  have hdenom_pos : 0 < (2 : ℝ) ^ (4 * m) := pow_pos (by norm_num) _
  have htop_pos : 0 < (1 + ‖z‖) ^ 10 := pow_pos (by positivity) _
  have hinv : ((1 + ‖z‖) ^ 10)⁻¹ ≤ ((2 : ℝ) ^ (4 * m))⁻¹ :=
    (inv_le_inv₀ htop_pos hdenom_pos).2 hdenom
  have hbracket_eq : fiberRadialBracket z = ((1 + ‖z‖) ^ 10)⁻¹ := by
    unfold fiberRadialBracket
    rw [Real.rpow_neg (by positivity)]
    exact congrArg Inv.inv (Real.rpow_natCast (1 + ‖z‖) 10)
  have htail_eq : (((2 : ℝ)⁻¹) ^ (1 + 3)) ^ m =
      ((2 : ℝ) ^ (4 * m))⁻¹ := by
    norm_num
    rw [show (1 / 16 : ℝ) = (16 : ℝ)⁻¹ by norm_num, inv_pow]
    congr 1
    calc
      (16 : ℝ) ^ m = ((2 : ℝ) ^ 4) ^ m := by norm_num
      _ = (2 : ℝ) ^ (4 * m) := (pow_mul (2 : ℝ) 4 m).symm
  calc
    fiberRadialBracket z = ((1 + ‖z‖) ^ 10)⁻¹ := hbracket_eq
    _ ≤ ((2 : ℝ) ^ (4 * m))⁻¹ := hinv
    _ = (((2 : ℝ)⁻¹) ^ (1 + 3)) ^ m := htail_eq.symm

/-- The bounded-measurable one-dimensional bracket convolution is pointwise
controlled by the literal fiber dyadic-ball maximal function, uniformly over
all positive continuous scales. -/
theorem fiberRadialBracket_integral_le_dyadic_average_sup
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (q : FiberDyadicBase × FiberDyadicLine) {r : ℝ} (hr : 0 < r) :
    (∫ y : FiberDyadicLine,
      ‖G (q.1, y)‖ * (r⁻¹ * fiberRadialBracket (r⁻¹ • (y - q.2)))) ≤
      16 * (fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  have hmain := fiber_shell_weighted_integral_le_dyadic_average_sup
    G hG a ha hGa fiberRadialBracket
    (C := 1) (L := 1) (r := r) (by norm_num) (by norm_num) hr
    fiberRadialBracket_nonneg
    (fun z => by simpa using fiberRadialBracket_le_one z)
    (fun z m hz => by
      simpa using fiberRadialBracket_tail z m (by simpa using hz))
    q
  convert hmain using 1
  norm_num
  ring

end
end Twisted
end Auto
