/- Copyright (c) 2026 Joris Roos. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

/-! ### Measurable dyadic fibre stopping data

Scratch development for Section 8, `lem:fiber_cz`.  The source indexes the
one-dimensional fibres by the countable dyadic intervals and defines its
stopping sets using their fibrewise averages.  We retain the transverse-first
coordinate order used by `FiberDyadicBase × ℝ` in the main formalization.
-/

namespace Auto.Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal

noncomputable section

/-- The countable dyadic intervals from Section 8, indexed by their scale and
integer translation.  Its literal cell is defined below as a half-open real
interval. -/
structure FiberDyadicInterval where
  scale : ℤ
  translation : ℤ
  deriving DecidableEq

instance : Countable FiberDyadicInterval := by
  exact (show Function.Injective
      (fun I : FiberDyadicInterval => (I.scale, I.translation)) by
    intro I J h
    cases I
    cases J
    cases h
    rfl).countable

/-- The positive length of a literal dyadic interval. -/
noncomputable def fiberDyadicIntervalLength (I : FiberDyadicInterval) : ℝ :=
  (2 : ℝ) ^ I.scale

/-- The literal half-open dyadic interval
`[translation * 2^scale, (translation + 1) * 2^scale)`. -/
noncomputable def fiberDyadicIntervalSet (I : FiberDyadicInterval) : Set ℝ :=
  Ico ((I.translation : ℝ) * fiberDyadicIntervalLength I)
    (((I.translation + 1 : ℤ) : ℝ) * fiberDyadicIntervalLength I)

theorem fiberDyadicIntervalLength_pos (I : FiberDyadicInterval) :
    0 < fiberDyadicIntervalLength I := by
  unfold fiberDyadicIntervalLength
  positivity

theorem measurableSet_fiberDyadicIntervalSet (I : FiberDyadicInterval) :
    MeasurableSet (fiberDyadicIntervalSet I) := by
  unfold fiberDyadicIntervalSet
  exact measurableSet_Ico

/-- The immediate containing dyadic interval.  Strict ancestors are its
positive iterates. -/
def FiberDyadicInterval.parent (I : FiberDyadicInterval) : FiberDyadicInterval :=
  ⟨I.scale + 1, I.translation / 2⟩

/-- The `n + 1`-st strict dyadic ancestor of `I`. -/
def fiberDyadicStrictAncestor (I : FiberDyadicInterval) : ℕ →
    FiberDyadicInterval
  | 0 => I.parent
  | n + 1 => (fiberDyadicStrictAncestor I n).parent

/-- The unnormalized fibre mass of a nonnegative field over a literal dyadic
interval.  The input is written transverse-coordinate first, as in the
canonical `FiberDyadicBase × FiberDyadicLine` model. -/
noncomputable def fiberDyadicFiberMass
    (Φ : FiberDyadicBase × ℝ → ℝ≥0∞) (I : FiberDyadicInterval)
    (z : FiberDyadicBase) : ℝ≥0∞ := by
  classical
  exact ∫⁻ y : ℝ, if y ∈ fiberDyadicIntervalSet I then Φ (z, y) else 0

/-- The source's fibre average, represented in `ℝ≥0∞` to make its
measurability valid without premature fibre-integrability hypotheses. -/
noncomputable def fiberDyadicAverage
    (Φ : FiberDyadicBase × ℝ → ℝ≥0∞) (I : FiberDyadicInterval)
    (z : FiberDyadicBase) : ℝ≥0∞ :=
  (ENNReal.ofReal (fiberDyadicIntervalLength I))⁻¹ *
    fiberDyadicFiberMass Φ I z

/-- The measurable `p`-power field associated to a complex fibre function.
This is the literal `|f|^p` source integrand, in extended nonnegative form. -/
noncomputable def fiberDyadicNormPower
    (p : ℝ) (f : FiberDyadicBase × ℝ → ℂ) :
    FiberDyadicBase × ℝ → ℝ≥0∞ :=
  fun q => (ENNReal.ofReal ‖f q‖) ^ p

theorem measurable_fiberDyadicNormPower
    (p : ℝ) (f : FiberDyadicBase × ℝ → ℂ) (hf : Measurable f) :
    Measurable (fiberDyadicNormPower p f) := by
  unfold fiberDyadicNormPower
  exact ENNReal.continuous_rpow_const.measurable.comp
    (hf.norm.ennreal_ofReal)

theorem measurable_fiberDyadicFiberMass
    (Φ : FiberDyadicBase × ℝ → ℝ≥0∞) (hΦ : Measurable Φ)
    (I : FiberDyadicInterval) :
    Measurable (fiberDyadicFiberMass Φ I) := by
  classical
  let Ψ : FiberDyadicBase × ℝ → ℝ≥0∞ := fun q =>
    if q.2 ∈ fiberDyadicIntervalSet I then Φ q else 0
  have hset : MeasurableSet {q : FiberDyadicBase × ℝ |
      q.2 ∈ fiberDyadicIntervalSet I} := by
    exact measurableSet_preimage measurable_snd
      (measurableSet_fiberDyadicIntervalSet I)
  have hΨ : Measurable Ψ := by
    exact Measurable.ite hset hΦ measurable_const
  have hmass : Measurable (fun z : FiberDyadicBase =>
      ∫⁻ y : ℝ, Ψ (z, y)) := hΨ.lintegral_prod_right'
  change Measurable (fun z : FiberDyadicBase =>
    ∫⁻ y : ℝ, if y ∈ fiberDyadicIntervalSet I then Φ (z, y) else 0)
  exact hmass

theorem measurable_fiberDyadicAverage
    (Φ : FiberDyadicBase × ℝ → ℝ≥0∞) (hΦ : Measurable Φ)
    (I : FiberDyadicInterval) :
    Measurable (fiberDyadicAverage Φ I) := by
  unfold fiberDyadicAverage
  exact measurable_const.mul (measurable_fiberDyadicFiberMass Φ hΦ I)

/-- The measurable source stopping set `S_I`: the fibre lies in `Z`, its
average on `I` exceeds `H`, and every strict dyadic ancestor average is at
most `H`. -/
noncomputable def fiberDyadicSelectedSet
    (Z : Set FiberDyadicBase) (Φ : FiberDyadicBase × ℝ → ℝ≥0∞)
    (H : ℝ≥0∞) (I : FiberDyadicInterval) : Set FiberDyadicBase :=
  Z ∩ {z | H < fiberDyadicAverage Φ I z} ∩
    ⋂ n : ℕ, {z | fiberDyadicAverage Φ (fiberDyadicStrictAncestor I n) z ≤ H}

theorem measurableSet_fiberDyadicSelectedSet
    (Z : Set FiberDyadicBase) (hZ : MeasurableSet Z)
    (Φ : FiberDyadicBase × ℝ → ℝ≥0∞) (hΦ : Measurable Φ)
    (H : ℝ≥0∞) (I : FiberDyadicInterval) :
    MeasurableSet (fiberDyadicSelectedSet Z Φ H I) := by
  unfold fiberDyadicSelectedSet
  refine (hZ.inter (measurableSet_lt measurable_const
    (measurable_fiberDyadicAverage Φ hΦ I))).inter ?_
  apply MeasurableSet.iInter
  intro n
  exact measurableSet_le
    (measurable_fiberDyadicAverage Φ hΦ (fiberDyadicStrictAncestor I n))
    measurable_const

/-- The source exceptional set, in the transverse-first coordinate order:
the countable union of `S_I × I`. -/
noncomputable def fiberDyadicExceptionalSet
    (Z : Set FiberDyadicBase) (Φ : FiberDyadicBase × ℝ → ℝ≥0∞)
    (H : ℝ≥0∞) : Set (FiberDyadicBase × ℝ) :=
  ⋃ I : FiberDyadicInterval,
    fiberDyadicSelectedSet Z Φ H I ×ˢ fiberDyadicIntervalSet I

theorem measurableSet_fiberDyadicExceptionalSet
    (Z : Set FiberDyadicBase) (hZ : MeasurableSet Z)
    (Φ : FiberDyadicBase × ℝ → ℝ≥0∞) (hΦ : Measurable Φ)
    (H : ℝ≥0∞) :
    MeasurableSet (fiberDyadicExceptionalSet Z Φ H) := by
  unfold fiberDyadicExceptionalSet
  apply MeasurableSet.iUnion
  intro I
  exact (measurableSet_fiberDyadicSelectedSet Z hZ Φ hΦ H I).prod
    (measurableSet_fiberDyadicIntervalSet I)

end

end Auto.Twisted
