/- Copyright (c) 2026 Joris Roos. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory
open scoped ENNReal

noncomputable section

/-! ## Transport of the one-dimensional bracket majorant to `E3` -/

/-- The positive one-dimensional radial-bracket average in literal ambient
coordinate `i`, written through the measure-preserving coordinate split used
by the fiber dyadic maximal operator. -/
noncomputable def coordinateFiberRadialBracketAverage
    (i : Fin 3) (f : E3 → ℂ) (r : ℝ) (p : E3) : ℝ :=
  let e := e3ToFiberDyadicCoordinates i
  ∫ y : FiberDyadicLine,
    ‖f (e.symm ((e p).1, y))‖ *
      (r⁻¹ * fiberRadialBracket (r⁻¹ • (y - (e p).2)))

/-- The all-positive-scales radial-bracket maximum in one transported
ambient coordinate. -/
noncomputable def coordinateFiberRadialBracketMaximal
    (i : Fin 3) (f : E3 → ℂ) (p : E3) : ℝ :=
  sSup {a : ℝ | ∃ r : ℝ, 0 < r ∧
    a = coordinateFiberRadialBracketAverage i f r p}

/-- The product-fiber shell bound transports exactly to a literal coordinate
of `E3`.  Its right side is independent of the continuous scale `r`. -/
theorem scratch_coordinateFiberRadialBracketAverage_le_dyadic
    (i : Fin 3) (f : E3 → ℂ) (hf : Measurable f)
    (A : ℝ) (hA : 0 ≤ A) (hbound : ∀ x, ‖f x‖ ≤ A)
    (r : ℝ) (hr : 0 < r) (p : E3) :
    coordinateFiberRadialBracketAverage i f r p ≤
      16 * (coordinateDyadicBallMaximal i f p *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  let e := e3ToFiberDyadicCoordinates i
  let G : FiberDyadicBase × FiberDyadicLine → ℂ := f ∘ e.symm
  let q : FiberDyadicBase × FiberDyadicLine := e p
  have hG : Measurable G := hf.comp e.symm.measurable
  have hGbound : ∀ z, ‖G z‖ ≤ A := by
    intro z
    exact hbound (e.symm z)
  have h := fiberRadialBracket_integral_le_dyadic_average_sup
    G hG A hA hGbound q hr
  change (∫ y : FiberDyadicLine,
    ‖f (e.symm ((e p).1, y))‖ *
      (r⁻¹ * fiberRadialBracket (r⁻¹ • (y - (e p).2)))) ≤ _
  change (∫ y : FiberDyadicLine,
    ‖G (q.1, y)‖ *
      (r⁻¹ * fiberRadialBracket (r⁻¹ • (y - q.2))) ) ≤ _
  simpa only [coordinateDyadicBallMaximal, G, q, e, Function.comp_def] using h

/-- Taking the literal real supremum over all positive continuous scales
does not cost more than the same one-dimensional dyadic maximal function. -/
theorem scratch_coordinateFiberRadialBracketMaximal_le_dyadic
    (i : Fin 3) (f : E3 → ℂ) (hf : Measurable f)
    (A : ℝ) (hA : 0 ≤ A) (hbound : ∀ x, ‖f x‖ ≤ A)
    (p : E3) :
    coordinateFiberRadialBracketMaximal i f p ≤
      16 * (coordinateDyadicBallMaximal i f p *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  unfold coordinateFiberRadialBracketMaximal
  apply csSup_le
  · exact ⟨coordinateFiberRadialBracketAverage i f 1 p,
      ⟨1, by norm_num, rfl⟩⟩
  · rintro b ⟨r, hr, rfl⟩
    exact scratch_coordinateFiberRadialBracketAverage_le_dyadic
      i f hf A hA hbound r hr p

end

end Twisted
end Auto
