import Auto.Twisted.FiberCZCountableSelectedGoodBadOperatorScratch

namespace Auto.Twisted

#print axioms scratch_measurable_fiberDyadicCountableBadField
#print axioms scratch_fiberDyadicCountableBadField_eq_atom_of_mem
#print axioms scratch_abs_fiberDyadicCountableBadField_le_of_bound
#print axioms scratch_coordinateFiberDyadicCountableGoodBad_decomposition
#print axioms scratch_ModelTruncatedOperator_coordinateFiberDyadicCountableGoodBad_split_of_bounded_measurable

end Auto.Twisted
