/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Metric Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## Source stopping existence for the fiber decomposition

Source: `lem:fiber_cz`, blueprint lines 2258--2357, the step "On `Z_f`, if
`J` runs through growing dyadic ancestors then `A_J(z) → 0`; thus every
interval with average above `H` lies in a maximal one".
-/

/-- A literal fiber dyadic interval is determined by its scale together with
any of its points. -/
theorem fiberDyadicIndexAt_eq_of_mem
    (J : FiberDyadicInterval) (y : ℝ) (hy : y ∈ fiberDyadicInterval J) :
    J = fiberDyadicIndexAt J.1 y := by
  have hc : (0 : ℝ) < (2 : ℝ) ^ J.1 := zpow_pos (by norm_num) J.1
  obtain ⟨hle, hlt⟩ := hy
  have hfloor : ⌊y / (2 : ℝ) ^ J.1⌋ = J.2 := by
    rw [Int.floor_eq_iff]
    refine ⟨(le_div_iff₀ hc).2 hle, ?_⟩
    rw [div_lt_iff₀ hc]
    push_cast at hlt ⊢
    linarith
  exact Prod.ext rfl hfloor.symm

/-- A strict dyadic ancestor has a strictly larger scale. -/
theorem fiberDyadicProperAncestor_scale_lt
    (I J : FiberDyadicInterval) (h : fiberDyadicProperAncestor I J) :
    I.1 < J.1 := by
  rcases h with ⟨hsub, hne⟩
  have hmeas : volume (fiberDyadicInterval I) ≤ volume (fiberDyadicInterval J) :=
    measure_mono hsub
  rw [measure_fiberDyadicInterval, measure_fiberDyadicInterval] at hmeas
  have hlen : fiberDyadicIntervalLength I ≤ fiberDyadicIntervalLength J := by
    have := (ENNReal.ofReal_le_ofReal_iff (fiberDyadicIntervalLength_pos J).le).1 hmeas
    exact this
  have hscale : I.1 ≤ J.1 := by
    by_contra hcon
    push_neg at hcon
    have : fiberDyadicIntervalLength J < fiberDyadicIntervalLength I := by
      simpa [fiberDyadicIntervalLength] using
        (zpow_lt_zpow_right₀ (by norm_num : (1:ℝ) < 2) hcon)
    linarith
  rcases lt_or_eq_of_le hscale with h | h
  · exact h
  · exfalso
    -- same scale and overlapping forces equality
    have hpt : ((I.2 : ℝ) * (2 : ℝ) ^ I.1) ∈ fiberDyadicInterval I := by
      refine ⟨le_rfl, ?_⟩
      have hc : (0 : ℝ) < (2 : ℝ) ^ I.1 := zpow_pos (by norm_num) I.1
      push_cast
      nlinarith
    have hptJ : ((I.2 : ℝ) * (2 : ℝ) ^ I.1) ∈ fiberDyadicInterval J := hsub hpt
    have hI := fiberDyadicIndexAt_eq_of_mem I _ hpt
    have hJ := fiberDyadicIndexAt_eq_of_mem J _ hptJ
    rw [← h] at hJ
    exact hne (by rw [hI, hJ])

/-- A nonnegative fiber's dyadic average is controlled by its total mass. -/
theorem fiberDyadicIntervalAverage_le_inv_length_mul_integral
    {Z : Type*} [MeasurableSpace Z] (F : ℝ × Z → ℝ) (I : FiberDyadicInterval)
    (z : Z) (hF : Integrable (fun u : ℝ ↦ F (u, z)))
    (hFnonneg : ∀ u : ℝ, 0 ≤ F (u, z)) :
    fiberDyadicIntervalAverage F I z ≤
      (fiberDyadicIntervalLength I)⁻¹ * ∫ u : ℝ, F (u, z) := by
  rw [fiberDyadicIntervalAverage_eq_setIntegral]
  apply mul_le_mul_of_nonneg_left _
    (inv_nonneg.2 (fiberDyadicIntervalLength_pos I).le)
  exact setIntegral_le_integral hF (Filter.Eventually.of_forall hFnonneg)

/-- **Stopping existence.**  On a fiber of finite mass, a point covered by no
selected interval has every dyadic average at most `H`. -/
theorem fiberDyadicAverage_le_of_forall_not_mem_selected
    {Z : Type*} [MeasurableSpace Z] (F : ℝ × Z → ℝ) (Zf : Set Z) (H : ℝ)
    (hH : 0 < H) (y : ℝ) (z : Z) (hz : z ∈ Zf)
    (hF : Integrable (fun u : ℝ ↦ F (u, z)))
    (hFnonneg : ∀ u : ℝ, 0 ≤ F (u, z))
    (hy : ∀ I : FiberDyadicInterval,
      z ∈ fiberDyadicSelectionSet Zf (fiberDyadicIntervalAverage F) H I →
      y ∉ fiberDyadicInterval I)
    (k : ℤ) :
    fiberDyadicIntervalAverage F (fiberDyadicIndexAt k y) z ≤ H := by
  by_contra hcon
  push_neg at hcon
  set A : FiberDyadicInterval → Z → ℝ := fiberDyadicIntervalAverage F with hA
  set m : ℤ → ℝ := fun j ↦ A (fiberDyadicIndexAt j y) z with hm
  -- large scales have small averages
  have hmass : 0 ≤ ∫ u : ℝ, F (u, z) :=
    integral_nonneg hFnonneg
  obtain ⟨N, hN⟩ : ∃ N : ℕ, (∫ u : ℝ, F (u, z)) / H < (2 : ℝ) ^ (k + (N : ℤ)) := by
    obtain ⟨N, hN⟩ := pow_unbounded_of_one_lt
      (max 0 ((∫ u : ℝ, F (u, z)) / H) * (2 : ℝ) ^ (-k)) (by norm_num : (1:ℝ) < 2)
    refine ⟨N, ?_⟩
    have h2k : (0 : ℝ) < (2 : ℝ) ^ (-k) := zpow_pos (by norm_num) _
    have : max 0 ((∫ u : ℝ, F (u, z)) / H) * (2 : ℝ) ^ (-k) < (2 : ℝ) ^ (N : ℕ) := hN
    have hzk : (2 : ℝ) ^ (k + (N : ℤ)) = (2 : ℝ) ^ k * (2 : ℝ) ^ (N : ℕ) := by
      rw [zpow_add₀ (by norm_num : (2:ℝ) ≠ 0), zpow_natCast]
    rw [hzk]
    have hk : (0 : ℝ) < (2 : ℝ) ^ k := zpow_pos (by norm_num) k
    have hinv : (2 : ℝ) ^ (-k) = ((2 : ℝ) ^ k)⁻¹ := by rw [zpow_neg]
    rw [hinv] at this
    have := (div_lt_iff₀ hk).1 (by
      simpa [div_eq_mul_inv] using this)
    calc (∫ u : ℝ, F (u, z)) / H
        ≤ max 0 ((∫ u : ℝ, F (u, z)) / H) := le_max_right _ _
      _ < (2 : ℝ) ^ (N : ℕ) * (2 : ℝ) ^ k := this
      _ = (2 : ℝ) ^ k * (2 : ℝ) ^ (N : ℕ) := by ring
  have hsmall : ∀ j : ℕ, N ≤ j → m (k + (j : ℤ)) ≤ H := by
    intro j hj
    have hlen : fiberDyadicIntervalLength (fiberDyadicIndexAt (k + (j : ℤ)) y)
        = (2 : ℝ) ^ (k + (j : ℤ)) := rfl
    have hbig : (2 : ℝ) ^ (k + (N : ℤ)) ≤ (2 : ℝ) ^ (k + (j : ℤ)) := by
      apply zpow_le_zpow_right₀ (by norm_num : (1:ℝ) ≤ 2)
      omega
    have hpos : (0 : ℝ) < (2 : ℝ) ^ (k + (j : ℤ)) := zpow_pos (by norm_num) _
    have hle := fiberDyadicIntervalAverage_le_inv_length_mul_integral
      F (fiberDyadicIndexAt (k + (j : ℤ)) y) z hF hFnonneg
    rw [hlen] at hle
    refine hle.trans ?_
    rw [inv_mul_le_iff₀ hpos]
    have : (∫ u : ℝ, F (u, z)) / H < (2 : ℝ) ^ (k + (j : ℤ)) := lt_of_lt_of_le hN hbig
    rw [div_lt_iff₀ hH] at this
    nlinarith
  -- the finite nonempty set of exceeding offsets
  set S : Finset ℕ := (Finset.range (N + 1)).filter (fun j ↦ H < m (k + (j : ℤ)))
    with hS
  have h0S : (0 : ℕ) ∈ S := by
    rw [hS, Finset.mem_filter]
    refine ⟨Finset.mem_range.2 (by omega), ?_⟩
    simpa [hm, hA] using hcon
  have hSne : S.Nonempty := ⟨0, h0S⟩
  set M : ℕ := S.max' hSne with hM
  have hMS : M ∈ S := S.max'_mem hSne
  have hMlt : H < m (k + (M : ℤ)) := (Finset.mem_filter.1 hMS).2
  have habove : ∀ j : ℕ, M < j → m (k + (j : ℤ)) ≤ H := by
    intro j hj
    by_cases hjN : j ≤ N
    · by_contra hcon2
      push_neg at hcon2
      have : j ∈ S := by
        rw [hS, Finset.mem_filter]
        exact ⟨Finset.mem_range.2 (by omega), hcon2⟩
      exact absurd (S.le_max' j this) (by omega)
    · exact hsmall j (by omega)
  -- the maximal interval is selected
  set I : FiberDyadicInterval := fiberDyadicIndexAt (k + (M : ℤ)) y with hI
  have hIsel : z ∈ fiberDyadicSelectionSet Zf A H I := by
    refine ⟨⟨hz, hMlt⟩, ?_⟩
    refine Set.mem_iInter.2 fun J ↦ Set.mem_iInter.2 fun hJ ↦ ?_
    have hscale : I.1 < J.1 := fiberDyadicProperAncestor_scale_lt I J hJ
    have hIfst : I.1 = k + (M : ℤ) := rfl
    have hyJ : y ∈ fiberDyadicInterval J :=
      hJ.1 (mem_fiberDyadicInterval_fiberDyadicIndexAt (k + (M : ℤ)) y)
    have hJeq : J = fiberDyadicIndexAt J.1 y := fiberDyadicIndexAt_eq_of_mem J y hyJ
    obtain ⟨j, hj⟩ : ∃ j : ℕ, J.1 = k + (j : ℤ) ∧ M < j := by
      refine ⟨(J.1 - k).toNat, ?_, ?_⟩
      · have : 0 ≤ J.1 - k := by omega
        omega
      · omega
    show A J z ≤ H
    rw [hJeq, hj.1]
    exact habove _ hj.2
  exact hy I hIsel (mem_fiberDyadicInterval_fiberDyadicIndexAt (k + (M : ℤ)) y)

/-! ### Jensen's inequality for the fiber dyadic average -/

/-- Jensen/Hölder on one dyadic cell: the modulus of the fiber average is at
most the `p`-th root of the average of the `p`-th power.  This is the source
step `|f_I(z)|^p ≤ A_I(z)` of `lem:fiber_cz`. -/
theorem abs_fiberDyadicIntervalAverage_le_rpow
    {Z : Type*} [MeasurableSpace Z] (F : ℝ × Z → ℝ)
    (I : FiberDyadicInterval) (z : Z) {p : ℝ} (hp : 1 ≤ p)
    (hmeas : AEStronglyMeasurable (fun u : ℝ ↦ F (u, z))
      (volume.restrict (fiberDyadicInterval I)))
    (hFp : IntegrableOn (fun u : ℝ ↦ |F (u, z)| ^ p)
      (fiberDyadicInterval I) volume) :
    |fiberDyadicIntervalAverage F I z| ≤
      (fiberDyadicIntervalAverage (fun yz ↦ |F yz| ^ p) I z) ^ (1 / p) := by
  have hlen : (0 : ℝ) < fiberDyadicIntervalLength I :=
    fiberDyadicIntervalLength_pos I
  have hp0 : (0 : ℝ) < p := lt_of_lt_of_le zero_lt_one hp
  set L : ℝ := fiberDyadicIntervalLength I with hL
  have hmeasure : volume (fiberDyadicInterval I) = ENNReal.ofReal L :=
    measure_fiberDyadicInterval I
  have habs : |fiberDyadicIntervalAverage F I z| ≤
      L⁻¹ * ∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| := by
    rw [fiberDyadicIntervalAverage_eq_setIntegral, abs_mul,
      abs_of_nonneg (inv_nonneg.2 hlen.le)]
    apply mul_le_mul_of_nonneg_left _ (inv_nonneg.2 hlen.le)
    simpa only [Real.norm_eq_abs] using
      norm_integral_le_integral_norm (μ := volume.restrict (fiberDyadicInterval I))
        (fun u : ℝ ↦ F (u, z))
  have hRHS : (fiberDyadicIntervalAverage (fun yz ↦ |F yz| ^ p) I z) =
      L⁻¹ * ∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| ^ p := by
    rw [fiberDyadicIntervalAverage_eq_setIntegral]
  have hintp_nonneg : (0 : ℝ) ≤ ∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| ^ p :=
    integral_nonneg fun u ↦ Real.rpow_nonneg (abs_nonneg _) p
  rcases eq_or_lt_of_le hp with hp1 | hp1
  · rw [hRHS, ← hp1]
    simp only [Real.rpow_one, div_one]
    exact habs
  · set q : ℝ := p.conjExponent with hq
    have hpq : p.HolderConjugate q := Real.HolderConjugate.conjExponent hp1
    have hq0 : (0 : ℝ) < q := hpq.symm.pos
    have hmeasAbs : AEStronglyMeasurable (fun u : ℝ ↦ |F (u, z)|)
        (volume.restrict (fiberDyadicInterval I)) :=
      continuous_abs.comp_aestronglyMeasurable hmeas
    have hmemp : MemLp (fun u : ℝ ↦ |F (u, z)|) (ENNReal.ofReal p)
        (volume.restrict (fiberDyadicInterval I)) := by
      rw [← integrable_norm_rpow_iff hmeasAbs
        (ENNReal.ofReal_pos.2 hp0).ne' ENNReal.ofReal_ne_top,
        ENNReal.toReal_ofReal hp0.le]
      have hFp' : Integrable (fun x : ℝ ↦ |F (x, z)| ^ p)
        (volume.restrict (fiberDyadicInterval I)) := hFp
      simpa only [Real.norm_eq_abs, abs_abs] using hFp'
    haveI : IsFiniteMeasure (volume.restrict (fiberDyadicInterval I)) := by
      constructor
      rw [Measure.restrict_apply_univ, hmeasure]
      exact ENNReal.ofReal_lt_top
    have hmemq : MemLp (fun _ : ℝ ↦ (1 : ℝ)) (ENNReal.ofReal q)
        (volume.restrict (fiberDyadicInterval I)) := memLp_const 1
    have hholder := integral_mul_le_Lp_mul_Lq_of_nonneg
      (μ := volume.restrict (fiberDyadicInterval I)) hpq
      (f := fun u : ℝ ↦ |F (u, z)|) (g := fun _ : ℝ ↦ (1 : ℝ))
      (Filter.Eventually.of_forall fun u ↦ abs_nonneg _)
      (Filter.Eventually.of_forall fun _ ↦ zero_le_one) hmemp hmemq
    simp only [mul_one, Real.one_rpow, integral_const, smul_eq_mul,
      MeasureTheory.measureReal_def, Measure.restrict_apply_univ, hmeasure,
      ENNReal.toReal_ofReal hlen.le] at hholder
    have hinv : 1 / p + 1 / q = 1 := by
      simpa only [one_div] using hpq.inv_add_inv_eq_one
    have hneg : L ^ (-1 : ℝ) = L⁻¹ := by
      rw [Real.rpow_neg hlen.le, Real.rpow_one]
    have hLpow : L⁻¹ * L ^ (1 / q) = (L ^ (1 / p))⁻¹ := by
      rw [← hneg, ← Real.rpow_add hlen, ← Real.rpow_neg hlen.le]
      congr 1
      linarith
    calc |fiberDyadicIntervalAverage F I z|
        ≤ L⁻¹ * ∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| := habs
      _ ≤ L⁻¹ * ((∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| ^ p) ^ (1 / p) *
            L ^ (1 / q)) :=
          mul_le_mul_of_nonneg_left hholder (inv_nonneg.2 hlen.le)
      _ = (L⁻¹ * L ^ (1 / q)) *
            (∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| ^ p) ^ (1 / p) := by
          ring
      _ = (L ^ (1 / p))⁻¹ *
            (∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| ^ p) ^ (1 / p) := by
          rw [hLpow]
      _ = (L⁻¹ * ∫ u : ℝ in fiberDyadicInterval I, |F (u, z)| ^ p) ^ (1 / p) := by
          rw [Real.mul_rpow (inv_nonneg.2 hlen.le) hintp_nonneg,
            Real.inv_rpow hlen.le]
      _ = (fiberDyadicIntervalAverage (fun yz ↦ |F yz| ^ p) I z) ^ (1 / p) := by
          rw [hRHS]

end
end Twisted
end Auto
