/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/
import Auto.Twisted.Twisted
import LeanSpherical.Auto.HardyLittlewoodMaximal

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open Auto.HardyLittlewoodMaximal
open Auto.Spherical.Auxiliary
open scoped BigOperators ENNReal

noncomputable section

/-- The dimension-one tail in the interval-tail lemma, kept local while the
general `L^p` duality route is developed independently of the sibling scratch. -/
noncomputable def scratchLp_intervalTail (c r x : ℝ) : ℝ :=
  (1 + |(x - c) / r|) ^ (-2 : ℝ)

/-- Moving the center by at most one radius changes the exponent-two tail by
at most the harmless factor four. -/
theorem scratchLp_intervalTail_le_four_intervalTail_of_center_dist
    {c r x y : ℝ} (hr : 0 < r) (hy : |y - c| ≤ r) :
    scratchLp_intervalTail c (2 * r) x ≤
      4 * scratchLp_intervalTail y (2 * r) x := by
  have hs : 0 < 2 * r := by positivity
  have hdist : |x - y| ≤ |x - c| + r := by
    calc
      |x - y| ≤ |x - c| + |c - y| := abs_sub_le x c y
      _ = |x - c| + |y - c| := by rw [abs_sub_comm c y]
      _ ≤ |x - c| + r := by gcongr
  have hdiv : |x - y| / (2 * r) ≤ (|x - c| + r) / (2 * r) :=
    (div_le_div_iff_of_pos_right hs).2 hdist
  have hApos : 0 < 1 + |x - c| / (2 * r) := by positivity
  have hBpos : 0 < 1 + |x - y| / (2 * r) := by positivity
  have hbase : 1 + |x - y| / (2 * r) ≤
      2 * (1 + |x - c| / (2 * r)) := by
    calc
      1 + |x - y| / (2 * r) ≤ 1 + (|x - c| + r) / (2 * r) := by
        gcongr
      _ = 3 / 2 + |x - c| / (2 * r) := by
        field_simp [hs.ne']
        ring
      _ ≤ 2 * (1 + |x - c| / (2 * r)) := by
        have hnonneg : 0 ≤ |x - c| / (2 * r) :=
          div_nonneg (abs_nonneg _) hs.le
        nlinarith
  have hpow : (1 + |x - y| / (2 * r)) ^ 2 ≤
      4 * (1 + |x - c| / (2 * r)) ^ 2 := by
    calc
      (1 + |x - y| / (2 * r)) ^ 2 ≤
          (2 * (1 + |x - c| / (2 * r))) ^ 2 :=
        pow_le_pow_left₀ hBpos.le hbase 2
      _ = 4 * (1 + |x - c| / (2 * r)) ^ 2 := by ring
  have hleftpos : 0 < (1 + |x - y| / (2 * r)) ^ 2 := pow_pos hBpos _
  have hrightpos : 0 < 4 * (1 + |x - c| / (2 * r)) ^ 2 := by positivity
  have hinv : (4 * (1 + |x - c| / (2 * r)) ^ 2)⁻¹ ≤
      ((1 + |x - y| / (2 * r)) ^ 2)⁻¹ :=
    (inv_le_inv₀ hrightpos hleftpos).2 hpow
  have htailc : scratchLp_intervalTail c (2 * r) x =
      ((1 + |x - c| / (2 * r)) ^ 2)⁻¹ := by
    unfold scratchLp_intervalTail
    rw [abs_div, abs_of_pos hs, Real.rpow_neg hApos.le]
    exact congrArg Inv.inv (Real.rpow_natCast (1 + |x - c| / (2 * r)) 2)
  have htaily : scratchLp_intervalTail y (2 * r) x =
      ((1 + |x - y| / (2 * r)) ^ 2)⁻¹ := by
    unfold scratchLp_intervalTail
    rw [abs_div, abs_of_pos hs, Real.rpow_neg hBpos.le]
    exact congrArg Inv.inv (Real.rpow_natCast (1 + |x - y| / (2 * r)) 2)
  rw [htailc, htaily]
  calc
    ((1 + |x - c| / (2 * r)) ^ 2)⁻¹ =
        4 * (4 * (1 + |x - c| / (2 * r)) ^ 2)⁻¹ := by
      field_simp
    _ ≤ 4 * ((1 + |x - y| / (2 * r)) ^ 2)⁻¹ :=
      mul_le_mul_of_nonneg_left hinv (by norm_num)

/-- The exponent-two radial tail needed after the scale integration in the
one-fiber Calderón--Zygmund argument. -/
noncomputable def scratchLp_fiberTailTwo (z : FiberDyadicLine) : ℝ :=
  (1 + ‖z‖) ^ (-2 : ℝ)

/-- The real interval tail is literally the transported fiber tail.  The
positive-radius hypothesis is only used to normalize the scalar action. -/
theorem scratchLp_intervalTail_eq_fiberTailTwo (c r x : ℝ) (hr : 0 < r) :
    scratchLp_intervalTail c r x =
      scratchLp_fiberTailTwo
        (r⁻¹ • (realToFiberDyadicLine x - realToFiberDyadicLine c)) := by
  unfold scratchLp_intervalTail scratchLp_fiberTailTwo
  rw [norm_scaled_fiber_sub r c (realToFiberDyadicLine x) hr]
  simp

theorem scratchLp_fiberTailTwo_nonneg (z : FiberDyadicLine) :
    0 ≤ scratchLp_fiberTailTwo z := by
  unfold scratchLp_fiberTailTwo
  positivity

/-- The scaled translated exponent-two tail is integrable on a fiber. -/
theorem scratchLp_integrable_scaled_fiberTailTwo
    (q : FiberDyadicLine) {r : ℝ} (hr : 0 < r) :
    Integrable (fun y : FiberDyadicLine =>
      scratchLp_fiberTailTwo (r⁻¹ • (y - q))) := by
  have hbase : Integrable scratchLp_fiberTailTwo := by
    unfold scratchLp_fiberTailTwo
    exact integrable_one_add_norm (E := FiberDyadicLine) (μ := volume)
      (r := (2 : ℝ)) (by norm_num)
  exact (hbase.comp_smul (inv_ne_zero hr.ne')).comp_sub_right q

/-- A bounded measurable fiber remains integrable after multiplication by a
scaled exponent-two tail. -/
theorem scratchLp_integrable_weighted_fiberTailTwo
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (hGa : ∀ z, ‖G z‖ ≤ a)
    (q : FiberDyadicBase × FiberDyadicLine) {r : ℝ} (hr : 0 < r) :
    Integrable (fun y : FiberDyadicLine =>
      ‖G (q.1, y)‖ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) := by
  have htail := scratchLp_integrable_scaled_fiberTailTwo q.2 hr
  have htail_meas : Measurable (fun y : FiberDyadicLine =>
      scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) := by
    unfold scratchLp_fiberTailTwo
    fun_prop
  refine (htail.const_mul a).mono' ?_ ?_
  · exact ((hG.comp (measurable_const.prodMk measurable_id)).norm.mul htail_meas).aestronglyMeasurable
  · filter_upwards [] with y
    rw [Real.norm_eq_abs, abs_of_nonneg]
    · exact mul_le_mul_of_nonneg_right (hGa (q.1, y))
        (scratchLp_fiberTailTwo_nonneg _)
    · exact mul_nonneg (norm_nonneg _) (scratchLp_fiberTailTwo_nonneg _)

theorem scratchLp_fiberTailTwo_le_one (z : FiberDyadicLine) :
    scratchLp_fiberTailTwo z ≤ 1 := by
  unfold scratchLp_fiberTailTwo
  exact Real.rpow_le_one_of_one_le_of_nonpos
    (le_add_of_nonneg_right (norm_nonneg _)) (by norm_num)

/-- The dyadic annular decay needed to sum the exponent-two tail against a
fiber maximal function. -/
theorem scratchLp_fiberTailTwo_tail (z : FiberDyadicLine) (m : ℕ)
    (h : (2 : ℝ) ^ m ≤ |‖z‖ - 1|) :
    scratchLp_fiberTailTwo z ≤ (((2 : ℝ)⁻¹) ^ (1 + 1)) ^ m := by
  have hbase : (2 : ℝ) ^ m ≤ 1 + ‖z‖ := by
    by_cases hm : m = 0
    · subst m
      norm_num
    · have hmpos : 0 < m := Nat.pos_of_ne_zero hm
      have hpow_two : 2 ≤ (2 : ℝ) ^ m := by
        calc
          2 = (2 : ℝ) ^ 1 := by norm_num
          _ ≤ (2 : ℝ) ^ m := pow_le_pow_right₀ (by norm_num) (by omega)
      have hsub_nonneg : 0 ≤ ‖z‖ - 1 := by
        by_contra hneg
        have hsubneg : ‖z‖ - 1 < 0 := lt_of_not_ge hneg
        have habs_eq : |‖z‖ - 1| = 1 - ‖z‖ := by
          rw [abs_of_neg hsubneg]
          ring
        have habs_le : |‖z‖ - 1| ≤ 1 := by
          rw [habs_eq]
          linarith [norm_nonneg z]
        nlinarith
      rw [abs_of_nonneg hsub_nonneg] at h
      linarith
  have hdenom : (2 : ℝ) ^ (2 * m) ≤ (1 + ‖z‖) ^ 2 := by
    calc
      (2 : ℝ) ^ (2 * m) = ((2 : ℝ) ^ m) ^ 2 := by
        rw [← pow_mul]
        congr 1
        omega
      _ ≤ (1 + ‖z‖) ^ 2 :=
        pow_le_pow_left₀ (pow_nonneg (by norm_num) _) hbase 2
  have hdenom_pos : 0 < (2 : ℝ) ^ (2 * m) := pow_pos (by norm_num) _
  have htop_pos : 0 < (1 + ‖z‖) ^ 2 := pow_pos (by positivity) _
  have hinv : ((1 + ‖z‖) ^ 2)⁻¹ ≤ ((2 : ℝ) ^ (2 * m))⁻¹ :=
    (inv_le_inv₀ htop_pos hdenom_pos).2 hdenom
  have htail_eq : (((2 : ℝ)⁻¹) ^ (1 + 1)) ^ m =
      ((2 : ℝ) ^ (2 * m))⁻¹ := by
    norm_num
    rw [show (1 / 4 : ℝ) = (4 : ℝ)⁻¹ by norm_num, inv_pow]
    congr 1
    calc
      (4 : ℝ) ^ m = ((2 : ℝ) ^ 2) ^ m := by norm_num
      _ = (2 : ℝ) ^ (2 * m) := (pow_mul (2 : ℝ) 2 m).symm
  have htail_def : scratchLp_fiberTailTwo z = ((1 + ‖z‖) ^ 2)⁻¹ := by
    unfold scratchLp_fiberTailTwo
    rw [Real.rpow_neg (by positivity)]
    exact congrArg Inv.inv (Real.rpow_natCast (1 + ‖z‖) 2)
  calc
    scratchLp_fiberTailTwo z = ((1 + ‖z‖) ^ 2)⁻¹ := htail_def
    _ ≤ ((2 : ℝ) ^ (2 * m))⁻¹ := hinv
    _ = (((2 : ℝ)⁻¹) ^ (1 + 1)) ^ m := htail_eq.symm

theorem scratchLp_one_le_three_pow_ten_mul_fiberRadialBracket_of_norm_lt_two
    (z : FiberDyadicLine) (hz : ‖z‖ < 2) :
    1 ≤ (3 : ℝ) ^ 10 * fiberRadialBracket z := by
  have hbase_pos : 0 < 1 + ‖z‖ := by positivity
  have hbase : 1 + ‖z‖ ≤ 3 := by linarith
  have hpow : (1 + ‖z‖) ^ 10 ≤ (3 : ℝ) ^ 10 :=
    pow_le_pow_left₀ (by positivity) hbase 10
  have hdenom_pos : 0 < (1 + ‖z‖) ^ 10 := pow_pos hbase_pos _
  unfold fiberRadialBracket
  rw [Real.rpow_neg (by positivity)]
  have hdiv : 1 ≤ (3 : ℝ) ^ 10 / (1 + ‖z‖) ^ 10 :=
    (one_le_div₀ hdenom_pos).mpr hpow
  simpa [div_eq_mul_inv] using hdiv

private theorem scratchLp_exists_dyadic_annulus {t : ℝ} (ht : 2 ≤ t) :
    ∃ n : ℕ, (2 : ℝ) ^ n ≤ t ∧ t < (2 : ℝ) ^ (n + 1) := by
  have hpow : Filter.Tendsto (fun n : ℕ => (2 : ℝ) ^ n) Filter.atTop Filter.atTop :=
    tendsto_pow_atTop_atTop_of_one_lt (by norm_num)
  obtain ⟨m, hm⟩ := Filter.eventually_atTop.1 (hpow.eventually_gt_atTop t)
  have hexists : ∃ n : ℕ, t < (2 : ℝ) ^ (n + 1) := by
    refine ⟨m, ?_⟩
    apply (hm m le_rfl).trans_le
    rw [show m + 1 = Nat.succ m by omega, pow_succ]
    have hnonneg : 0 ≤ (2 : ℝ) ^ m := pow_nonneg (by norm_num) _
    nlinarith
  let n : ℕ := Nat.find hexists
  have hnupper : t < (2 : ℝ) ^ (n + 1) := Nat.find_spec hexists
  have hnpos : 0 < n := by
    by_contra h
    have hnzero : n = 0 := Nat.eq_zero_of_not_pos h
    have hsmall : t < 2 := by
      simpa [hnzero] using hnupper
    linarith
  have hnlower : (2 : ℝ) ^ n ≤ t := by
    by_contra h
    have hlt : t < (2 : ℝ) ^ n := lt_of_not_ge h
    have hpred : n - 1 + 1 = n := Nat.sub_add_cancel (Nat.succ_le_iff.2 hnpos)
    have : t < (2 : ℝ) ^ ((n - 1) + 1) := by simpa [hpred] using hlt
    exact (not_lt_of_ge (Nat.find_min' hexists this))
      (Nat.sub_lt hnpos (by omega))
  exact ⟨n, hnlower, hnupper⟩

private theorem scratchLp_fiber_shell_tail_two_coefficient
    (A r : ℝ) (n : ℕ) (hr : 0 < r) :
    (A * r⁻¹ * (((2 : ℝ)⁻¹) ^ (1 + 1)) ^ n) *
        (2 * ((2 : ℝ) ^ (n + 2) * r)) =
      A * (2 : ℝ) ^ 3 * (1 / 2 : ℝ) ^ n := by
  have hr0 : r ≠ 0 := hr.ne'
  rw [show 2 * ((2 : ℝ) ^ (n + 2) * r) =
      (2 : ℝ) ^ (n + 3) * r by
        rw [show n + 3 = (n + 2) + 1 by omega, pow_succ]
        ring]
  rw [show (((2 : ℝ)⁻¹) ^ (1 + 1)) ^ n =
      ((2 : ℝ)⁻¹) ^ ((1 + 1) * n) by rw [pow_mul]]
  rw [show ((2 : ℝ)⁻¹) ^ ((1 + 1) * n) =
      ((2 : ℝ) ^ ((1 + 1) * n))⁻¹ by rw [inv_pow]]
  rw [show (1 / 2 : ℝ) = ((2 : ℝ)⁻¹) ^ 1 by norm_num]
  rw [← pow_mul, inv_pow]
  norm_num
  field_simp
  ring

/-- The exponent-two interval tail is controlled, on every bounded measurable
fiber, by the existing dyadic fiber maximal operator.  This is the annular
comparison required in the `1 < p < ∞` interval-tail argument. -/
theorem scratchLp_fiberTailTwo_weighted_integral_le_dyadic_average_sup
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (q : FiberDyadicBase × FiberDyadicLine) {r : ℝ} (hr : 0 < r) :
    (∫ y : FiberDyadicLine,
      ‖G (q.1, y)‖ *
        (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2)))) ≤
      16 * (fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  let ρ : ℝ := ((2 : ℝ)⁻¹) ^ (1 + 1)
  let M : ℝ := fiberDyadicBallMaximal G q *
    (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal
  have hM : 0 ≤ M := by
    dsimp [M]
    exact mul_nonneg ENNReal.toReal_nonneg ENNReal.toReal_nonneg
  have hrinv_nonneg : 0 ≤ r⁻¹ := inv_nonneg.mpr hr.le
  have hρ_nonneg : 0 ≤ ρ := by
    dsimp [ρ]
    positivity
  have hρ_lt_one : ρ < 1 := by
    dsimp [ρ]
    norm_num
  have hρ_norm_lt_one : ‖ρ‖ < 1 := by
    rw [Real.norm_eq_abs, abs_of_nonneg hρ_nonneg]
    exact hρ_lt_one
  have hgeom : Summable fun n : ℕ => ρ ^ n :=
    summable_geometric_of_norm_lt_one hρ_norm_lt_one
  have hline_meas : Measurable (fun y : FiberDyadicLine => ‖G (q.1, y)‖) :=
    (hG.comp (measurable_const.prodMk measurable_id)).norm
  let F : ℕ → FiberDyadicLine → ℝ := fun n y =>
    (r⁻¹ * ρ ^ n) *
      (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)).indicator
        (fun z => ‖G (q.1, z)‖) y
  have hF_nonneg (n : ℕ) (y : FiberDyadicLine) : 0 ≤ F n y := by
    dsimp [F]
    apply mul_nonneg
    · exact mul_nonneg hrinv_nonneg (pow_nonneg hρ_nonneg _)
    · apply Set.indicator_nonneg
      intro z _
      exact norm_nonneg _
  have hF_le_major (n : ℕ) (y : FiberDyadicLine) :
      F n y ≤ (r⁻¹ * a) * ρ ^ n := by
    dsimp [F]
    have hind :
        (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)).indicator
          (fun z => ‖G (q.1, z)‖) y ≤ a := by
      by_cases hy : y ∈ Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)
      · simpa [hy] using hGa (q.1, y)
      · simp [hy, ha]
    calc
      (r⁻¹ * ρ ^ n) *
          (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)).indicator
            (fun z => ‖G (q.1, z)‖) y ≤
          (r⁻¹ * ρ ^ n) * a :=
        mul_le_mul_of_nonneg_left hind
          (mul_nonneg hrinv_nonneg (pow_nonneg hρ_nonneg _))
      _ = (r⁻¹ * a) * ρ ^ n := by ring
  have hF_pointwise_summable (y : FiberDyadicLine) :
      Summable fun n : ℕ => F n y := by
    refine Summable.of_nonneg_of_le
      (f := fun n : ℕ => (r⁻¹ * a) * ρ ^ n)
      (g := fun n : ℕ => F n y) ?_ ?_ ?_
    · intro n
      exact hF_nonneg n y
    · intro n
      exact hF_le_major n y
    · simpa [mul_assoc] using hgeom.mul_left (r⁻¹ * a)
  have hball_of_scaled_norm_lt (n : ℕ) (y : FiberDyadicLine)
      (hy : ‖r⁻¹ • (y - q.2)‖ < (2 : ℝ) ^ (n + 2)) :
      y ∈ Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r) := by
    rw [Metric.mem_ball, dist_eq_norm_sub]
    have hnorm : ‖y - q.2‖ = r * ‖r⁻¹ • (y - q.2)‖ := by
      rw [norm_smul_of_nonneg hrinv_nonneg]
      field_simp [hr.ne']
    calc
      ‖y - q.2‖ = r * ‖r⁻¹ • (y - q.2)‖ := hnorm
      _ < r * (2 : ℝ) ^ (n + 2) := mul_lt_mul_of_pos_left hy hr
      _ = (2 : ℝ) ^ (n + 2) * r := by ring
  have hpointwise (y : FiberDyadicLine) :
      ‖G (q.1, y)‖ *
          (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) ≤
        ∑' n : ℕ, F n y := by
    have hsum := hF_pointwise_summable y
    by_cases hy : ‖r⁻¹ • (y - q.2)‖ < 2
    · have hyball : y ∈ Metric.ball q.2 ((2 : ℝ) ^ (0 + 2) * r) := by
        apply hball_of_scaled_norm_lt 0 y
        calc
          ‖r⁻¹ • (y - q.2)‖ < 2 := hy
          _ < (2 : ℝ) ^ (0 + 2) := by norm_num
      have hterm :
          ‖G (q.1, y)‖ *
              (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) ≤ F 0 y := by
        have hW := scratchLp_fiberTailTwo_le_one (r⁻¹ • (y - q.2))
        calc
          ‖G (q.1, y)‖ *
              (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) ≤
              ‖G (q.1, y)‖ * r⁻¹ := by
            apply mul_le_mul_of_nonneg_left
            · simpa [mul_comm] using mul_le_mul_of_nonneg_left hW hrinv_nonneg
            · exact norm_nonneg _
          _ = F 0 y := by
            dsimp [F, ρ]
            rw [Set.indicator_of_mem hyball]
            norm_num
            ring
      exact hterm.trans (hsum.le_tsum 0 fun j _ => hF_nonneg j y)
    · have htwo : 2 ≤ ‖r⁻¹ • (y - q.2)‖ := le_of_not_gt hy
      obtain ⟨k, hklow, hkupper⟩ := scratchLp_exists_dyadic_annulus htwo
      have hkpos : 0 < k := by
        by_contra hk
        have hkzero : k = 0 := Nat.eq_zero_of_not_pos hk
        have hsmall : ‖r⁻¹ • (y - q.2)‖ < 2 := by
          simpa [hkzero] using hkupper
        exact (not_lt_of_ge htwo) hsmall
      let n : ℕ := k - 1
      have hnadd : n + 1 = k := by
        dsimp [n]
        omega
      have hnadd' : n + 2 = k + 1 := by omega
      have hlow : (2 : ℝ) ^ (n + 1) ≤ ‖r⁻¹ • (y - q.2)‖ := by
        simpa [hnadd] using hklow
      have hupp : ‖r⁻¹ • (y - q.2)‖ < (2 : ℝ) ^ (n + 2) := by
        simpa [hnadd'] using hkupper
      have hnorm_one : 1 ≤ ‖r⁻¹ • (y - q.2)‖ := by
        calc
          1 ≤ (2 : ℝ) ^ (n + 1) := one_le_pow₀ (by norm_num)
          _ ≤ ‖r⁻¹ • (y - q.2)‖ := hlow
      have hsub : (2 : ℝ) ^ n ≤ ‖r⁻¹ • (y - q.2)‖ - 1 := by
        have hpow_one : 1 ≤ (2 : ℝ) ^ n := one_le_pow₀ (by norm_num)
        rw [show (2 : ℝ) ^ (n + 1) = 2 * (2 : ℝ) ^ n by
          rw [pow_succ]
          ring] at hlow
        nlinarith
      have habs : (2 : ℝ) ^ n ≤ |‖r⁻¹ • (y - q.2)‖ - 1| := by
        rw [abs_of_nonneg (sub_nonneg.mpr hnorm_one)]
        exact hsub
      have hyball : y ∈ Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r) :=
        hball_of_scaled_norm_lt n y hupp
      have hterm :
          ‖G (q.1, y)‖ *
              (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) ≤ F n y := by
        have hW := scratchLp_fiberTailTwo_tail
          (r⁻¹ • (y - q.2)) n habs
        calc
          ‖G (q.1, y)‖ *
              (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) ≤
              ‖G (q.1, y)‖ * (r⁻¹ * ρ ^ n) := by
            apply mul_le_mul_of_nonneg_left
            · exact mul_le_mul_of_nonneg_left (by simpa [ρ] using hW) hrinv_nonneg
            · exact norm_nonneg _
          _ = F n y := by
            dsimp [F]
            rw [Set.indicator_of_mem hyball]
            ring
      exact hterm.trans (hsum.le_tsum n fun j _ => hF_nonneg j y)
  have hF_integrable (n : ℕ) : Integrable (F n) volume := by
    dsimp [F]
    have hline_int : IntegrableOn (fun y : FiberDyadicLine => ‖G (q.1, y)‖)
        (Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r)) volume := by
      refine IntegrableOn.of_bound measure_ball_lt_top hline_meas.aestronglyMeasurable a ?_
      filter_upwards [] with y
      rw [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg _)]
      exact hGa (q.1, y)
    exact (hline_int.integrable_indicator measurableSet_ball).const_mul
      (r⁻¹ * ρ ^ n)
  have hF_integral (n : ℕ) :
      (∫ y : FiberDyadicLine, F n y) =
        (r⁻¹ * ρ ^ n) *
          (∫ y in Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r), ‖G (q.1, y)‖) := by
    dsimp [F]
    rw [integral_const_mul, integral_indicator measurableSet_ball]
  have hF_integral_bound (n : ℕ) :
      (∫ y : FiberDyadicLine, F n y) ≤
        (M * (2 : ℝ) ^ 3) * (1 / 2 : ℝ) ^ n := by
    have hradius : 0 < (2 : ℝ) ^ (n + 2) * r :=
      mul_pos (pow_pos (by norm_num) _) hr
    rw [hF_integral]
    calc
      (r⁻¹ * ρ ^ n) *
          (∫ y in Metric.ball q.2 ((2 : ℝ) ^ (n + 2) * r), ‖G (q.1, y)‖) ≤
          (r⁻¹ * ρ ^ n) *
            (M * (2 * ((2 : ℝ) ^ (n + 2) * r))) :=
        mul_le_mul_of_nonneg_left
          (by
            simpa [M, mul_assoc] using
              (fiberDyadicBall_integral_le_dyadic_average_sup_any_radius
                G hG a ha hGa q hradius))
          (mul_nonneg hrinv_nonneg (pow_nonneg hρ_nonneg _))
      _ = (M * (2 : ℝ) ^ 3) * (1 / 2 : ℝ) ^ n := by
        dsimp [ρ]
        convert scratchLp_fiber_shell_tail_two_coefficient M r n hr using 1
        ring
  have hG_summable : Summable fun n : ℕ =>
      (M * (2 : ℝ) ^ 3) * (1 / 2 : ℝ) ^ n := by
    have heighth : ‖(1 / 2 : ℝ)‖ < 1 := by norm_num
    exact (summable_geometric_of_norm_lt_one heighth).mul_left
      (M * (2 : ℝ) ^ 3)
  have hF_summable_integral_norm : Summable fun n : ℕ =>
      ∫ y : FiberDyadicLine, ‖F n y‖ := by
    refine Summable.of_nonneg_of_le
      (f := fun n : ℕ => (M * (2 : ℝ) ^ 3) * (1 / 2 : ℝ) ^ n)
      (g := fun n : ℕ => ∫ y : FiberDyadicLine, ‖F n y‖) ?_ ?_ hG_summable
    · intro n
      exact integral_nonneg fun y => norm_nonneg _
    · intro n
      have hnorm : (∫ y : FiberDyadicLine, ‖F n y‖) =
          ∫ y : FiberDyadicLine, F n y := by
        apply integral_congr_ae
        filter_upwards with y
        rw [Real.norm_of_nonneg (hF_nonneg n y)]
      rw [hnorm]
      exact hF_integral_bound n
  have hF_enorm_sum_lt_top :
      (∑' n : ℕ, ∫⁻ y : FiberDyadicLine, ‖F n y‖ₑ) < ⊤ := by
    calc
      (∑' n : ℕ, ∫⁻ y : FiberDyadicLine, ‖F n y‖ₑ) =
          ∑' n : ℕ, ENNReal.ofReal (∫ y : FiberDyadicLine, ‖F n y‖) := by
        apply tsum_congr
        intro n
        exact (ofReal_integral_norm_eq_lintegral_enorm (hF_integrable n)).symm
      _ < ⊤ := hF_summable_integral_norm.tsum_ofReal_lt_top
  have htsum_measurable : AEStronglyMeasurable
      (fun y : FiberDyadicLine => ∑' n : ℕ, F n y) volume :=
    AEStronglyMeasurable.tsum fun n => (hF_integrable n).aestronglyMeasurable
  have htsum_integrable : Integrable (fun y : FiberDyadicLine => ∑' n : ℕ, F n y) volume := by
    refine ⟨htsum_measurable, ?_⟩
    rw [hasFiniteIntegral_iff_enorm]
    calc
      ∫⁻ y : FiberDyadicLine, ‖∑' n : ℕ, F n y‖ₑ ≤
          ∫⁻ y : FiberDyadicLine, ∑' n : ℕ, ‖F n y‖ₑ :=
        lintegral_mono fun y => enorm_tsum_le_tsum_enorm
      _ = ∑' n : ℕ, ∫⁻ y : FiberDyadicLine, ‖F n y‖ₑ :=
        lintegral_tsum fun n => (hF_integrable n).aestronglyMeasurable.enorm
      _ < ⊤ := hF_enorm_sum_lt_top
  have htsum_integral :
      (∫ y : FiberDyadicLine, ∑' n : ℕ, F n y) =
        ∑' n : ℕ, ∫ y : FiberDyadicLine, F n y := by
    exact (MeasureTheory.integral_tsum_of_summable_integral_norm
      hF_integrable hF_summable_integral_norm).symm
  have hF_summable_integral : Summable fun n : ℕ =>
      ∫ y : FiberDyadicLine, F n y := by
    refine Summable.of_nonneg_of_le
      (f := fun n : ℕ => (M * (2 : ℝ) ^ 3) * (1 / 2 : ℝ) ^ n)
      (g := fun n : ℕ => ∫ y : FiberDyadicLine, F n y) ?_ ?_ hG_summable
    · intro n
      exact integral_nonneg fun y => hF_nonneg n y
    · intro n
      exact hF_integral_bound n
  have hD_nonneg : 0 ≤ M * (2 : ℝ) ^ 3 := by positivity
  have heighth : ‖(1 / 2 : ℝ)‖ < 1 := by norm_num
  have hsum_half : ∑' n : ℕ, (1 / 2 : ℝ) ^ n = 2 := by
    rw [(hasSum_geometric_of_norm_lt_one heighth).tsum_eq]
    norm_num
  have hsum_integrals_bound :
      (∑' n : ℕ, ∫ y : FiberDyadicLine, F n y) ≤
        2 * (M * (2 : ℝ) ^ 3) := by
    calc
      (∑' n : ℕ, ∫ y : FiberDyadicLine, F n y) ≤
          ∑' n : ℕ, (M * (2 : ℝ) ^ 3) * (1 / 2 : ℝ) ^ n :=
        Summable.tsum_le_tsum (fun n => hF_integral_bound n)
          hF_summable_integral hG_summable
      _ = (M * (2 : ℝ) ^ 3) * ∑' n : ℕ, (1 / 2 : ℝ) ^ n := by
        rw [tsum_mul_left]
      _ = (M * (2 : ℝ) ^ 3) * 2 := by rw [hsum_half]
      _ = 2 * (M * (2 : ℝ) ^ 3) := by ring
  have hleft_nonneg (y : FiberDyadicLine) :
      0 ≤ ‖G (q.1, y)‖ *
        (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) := by
    exact mul_nonneg (norm_nonneg _)
      (mul_nonneg hrinv_nonneg (scratchLp_fiberTailTwo_nonneg _))
  calc
    (∫ y : FiberDyadicLine,
        ‖G (q.1, y)‖ *
          (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2)))) ≤
        ∫ y : FiberDyadicLine, ∑' n : ℕ, F n y :=
      integral_mono_of_nonneg
        (Filter.Eventually.of_forall hleft_nonneg) htsum_integrable
        (Filter.Eventually.of_forall hpointwise)
    _ = ∑' n : ℕ, ∫ y : FiberDyadicLine, F n y := htsum_integral
    _ ≤ 2 * (M * (2 : ℝ) ^ 3) := hsum_integrals_bound
    _ = 16 * (fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
      dsimp [M]
      ring

/-- Removing the normalization factor from the tail costs exactly one radius. -/
theorem scratchLp_fiberTailTwo_pairing_le_dyadic_average_sup
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (q : FiberDyadicBase × FiberDyadicLine) {r : ℝ} (hr : 0 < r) :
    (∫ y : FiberDyadicLine,
      ‖G (q.1, y)‖ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) ≤
      16 * r * (fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  have hmain := scratchLp_fiberTailTwo_weighted_integral_le_dyadic_average_sup
    G hG a ha hGa q hr
  calc
    (∫ y : FiberDyadicLine,
        ‖G (q.1, y)‖ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2))) =
        ∫ y : FiberDyadicLine,
          r * (‖G (q.1, y)‖ *
            (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2)))) := by
      apply integral_congr_ae
      filter_upwards with y
      field_simp [hr.ne']
    _ = r * (∫ y : FiberDyadicLine,
        ‖G (q.1, y)‖ *
          (r⁻¹ * scratchLp_fiberTailTwo (r⁻¹ • (y - q.2)))) := by
      rw [integral_const_mul]
    _ ≤ r * (16 * (fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal)) :=
      mul_le_mul_of_nonneg_left hmain hr.le
    _ = 16 * r * (fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by ring

/-- If `y` lies in the radius-`r` interval about `c`, pairing the doubled
interval tail with a bounded fiber is controlled at the point `y` by the
fiber dyadic maximal function.  This is the pointwise input averaged over
each bad interval in the disjoint-tail argument. -/
theorem scratchLp_intervalTail_pairing_le_fiberDyadicBallMaximal
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (z : FiberDyadicBase) {c r y : ℝ} (hr : 0 < r) (hy : |y - c| ≤ r) :
    (∫ x : FiberDyadicLine,
      ‖G (z, x)‖ * scratchLp_intervalTail c (2 * r)
        (realToFiberDyadicLine.symm x)) ≤
      128 * r * (fiberDyadicBallMaximal G (z, realToFiberDyadicLine y) *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  let q : FiberDyadicBase × FiberDyadicLine := (z, realToFiberDyadicLine y)
  have hdouble : 0 < 2 * r := by positivity
  have htail_integrable := scratchLp_integrable_weighted_fiberTailTwo
    G hG a hGa q (r := 2 * r) hdouble
  have htail_le (x : FiberDyadicLine) :
      scratchLp_intervalTail c (2 * r) (realToFiberDyadicLine.symm x) ≤
        4 * scratchLp_fiberTailTwo ((2 * r)⁻¹ • (x - q.2)) := by
    calc
      scratchLp_intervalTail c (2 * r) (realToFiberDyadicLine.symm x) ≤
          4 * scratchLp_intervalTail y (2 * r)
            (realToFiberDyadicLine.symm x) :=
        scratchLp_intervalTail_le_four_intervalTail_of_center_dist hr hy
      _ = 4 * scratchLp_fiberTailTwo ((2 * r)⁻¹ • (x - q.2)) := by
        rw [scratchLp_intervalTail_eq_fiberTailTwo y (2 * r)
          (realToFiberDyadicLine.symm x) hdouble]
        dsimp [q]
        simp
  have hleft_nonneg (x : FiberDyadicLine) :
      0 ≤ ‖G (z, x)‖ * scratchLp_intervalTail c (2 * r)
        (realToFiberDyadicLine.symm x) := by
    exact mul_nonneg (norm_nonneg _) (by
      unfold scratchLp_intervalTail
      positivity)
  have hpointwise (x : FiberDyadicLine) :
      ‖G (z, x)‖ * scratchLp_intervalTail c (2 * r)
        (realToFiberDyadicLine.symm x) ≤
        4 * (‖G (q.1, x)‖ *
          scratchLp_fiberTailTwo ((2 * r)⁻¹ • (x - q.2))) := by
    dsimp [q]
    calc
      ‖G (z, x)‖ * scratchLp_intervalTail c (2 * r)
          (realToFiberDyadicLine.symm x) ≤
          ‖G (z, x)‖ *
            (4 * scratchLp_fiberTailTwo ((2 * r)⁻¹ •
              (x - realToFiberDyadicLine y))) :=
        mul_le_mul_of_nonneg_left (htail_le x) (norm_nonneg _)
      _ = 4 * (‖G (z, x)‖ * scratchLp_fiberTailTwo ((2 * r)⁻¹ •
          (x - realToFiberDyadicLine y))) := by ring
  have hpair := scratchLp_fiberTailTwo_pairing_le_dyadic_average_sup
    G hG a ha hGa q hdouble
  calc
    (∫ x : FiberDyadicLine,
        ‖G (z, x)‖ * scratchLp_intervalTail c (2 * r)
          (realToFiberDyadicLine.symm x)) ≤
        ∫ x : FiberDyadicLine,
          4 * (‖G (q.1, x)‖ *
            scratchLp_fiberTailTwo ((2 * r)⁻¹ • (x - q.2))) :=
      integral_mono_of_nonneg
        (Filter.Eventually.of_forall hleft_nonneg) (htail_integrable.const_mul 4)
        (Filter.Eventually.of_forall hpointwise)
    _ = 4 * (∫ x : FiberDyadicLine,
        ‖G (q.1, x)‖ *
          scratchLp_fiberTailTwo ((2 * r)⁻¹ • (x - q.2))) := by
      rw [integral_const_mul]
    _ ≤ 4 * (16 * (2 * r) * (fiberDyadicBallMaximal G q *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal)) :=
      mul_le_mul_of_nonneg_left hpair (by norm_num)
    _ = 128 * r * (fiberDyadicBallMaximal G (z, realToFiberDyadicLine y) *
        (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
      dsimp [q]
      ring

/-- Averaging the point-pairing estimate over its radius-`r` interval yields
the form that sums over a finite disjoint interval family. -/
theorem scratchLp_intervalTail_pairing_average_le
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (z : FiberDyadicBase) {c r : ℝ} (hr : 0 < r) :
    (∫ x : FiberDyadicLine,
      ‖G (z, x)‖ * scratchLp_intervalTail c (2 * r)
        (realToFiberDyadicLine.symm x)) ≤
      64 * (∫ u in Ioo (c - r) (c + r),
        fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) *
          (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  let V : ℝ := (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal
  let M : ℝ → ℝ := fun u =>
    fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) * V
  let A : ℝ := ∫ x : FiberDyadicLine,
    ‖G (z, x)‖ * scratchLp_intervalTail c (2 * r)
      (realToFiberDyadicLine.symm x)
  have hV : 0 ≤ V := by
    dsimp [V]
    exact ENNReal.toReal_nonneg
  have hM_nonneg (u : ℝ) : 0 ≤ M u := by
    dsimp [M]
    exact mul_nonneg ENNReal.toReal_nonneg hV
  have hM_meas : Measurable M := by
    dsimp [M]
    exact ((fiberDyadicBallMaximal_measurable G hG).comp
      (measurable_const.prodMk realToFiberDyadicLine.measurable)).mul measurable_const
  have hM_bound (u : ℝ) : M u ≤ a * V := by
    dsimp [M]
    exact mul_le_mul_of_nonneg_right
      (fiberDyadicBallMaximal_top_bound G a ha hGa
        (z, realToFiberDyadicLine u)) hV
  have hM_int : IntegrableOn M (Ioo (c - r) (c + r)) volume := by
    refine IntegrableOn.of_bound measure_Ioo_lt_top hM_meas.aestronglyMeasurable
      (a * V) ?_
    filter_upwards [] with u
    rw [Real.norm_eq_abs, abs_of_nonneg (hM_nonneg u)]
    exact hM_bound u
  have hA_nonneg : 0 ≤ A := by
    dsimp [A]
    exact integral_nonneg fun x => mul_nonneg (norm_nonneg _) (by
      unfold scratchLp_intervalTail
      positivity)
  have hpoint (u : ℝ) (hu : u ∈ Ioo (c - r) (c + r)) :
      A ≤ 128 * r * M u := by
    have huc : |u - c| ≤ r := by
      exact abs_le.mpr ⟨by linarith [hu.1], by linarith [hu.2]⟩
    simpa [A, M, V] using
      (scratchLp_intervalTail_pairing_le_fiberDyadicBallMaximal
        G hG a ha hGa z hr huc)
  have havg :
      (∫ u in Ioo (c - r) (c + r), A) ≤
        ∫ u in Ioo (c - r) (c + r), 128 * r * M u := by
    exact integral_mono_of_nonneg
      (Filter.Eventually.of_forall fun _ => hA_nonneg)
      (hM_int.const_mul (128 * r))
      (ae_restrict_of_forall_mem measurableSet_Ioo hpoint)
  have hvol : (volume (Ioo (c - r) (c + r))).toReal = 2 * r := by
    rw [Real.volume_Ioo, ENNReal.toReal_ofReal (by linarith [hr])]
    ring
  have hconst : (∫ _u in Ioo (c - r) (c + r), A) = (2 * r) * A := by
    rw [setIntegral_const, smul_eq_mul]
    change (volume (Ioo (c - r) (c + r))).toReal * A = (2 * r) * A
    rw [hvol]
  have hright :
      (∫ u in Ioo (c - r) (c + r), 128 * r * M u) =
        (128 * r) * (∫ u in Ioo (c - r) (c + r), M u) := by
    rw [integral_const_mul]
  apply le_of_mul_le_mul_left (a := 2 * r) ?_ (by positivity : 0 < 2 * r)
  calc
    (2 * r) * A = ∫ _u in Ioo (c - r) (c + r), A := hconst.symm
    _ ≤ ∫ u in Ioo (c - r) (c + r), 128 * r * M u := havg
    _ = (128 * r) * (∫ u in Ioo (c - r) (c + r), M u) := hright
    _ = (2 * r) *
        (64 * (∫ u in Ioo (c - r) (c + r), M u)) := by ring

/-- The averaged interval pairing sums over every finite family; disjointness
is only needed in the subsequent union-of-intervals rewrite. -/
theorem scratchLp_finset_intervalTail_pairing_average_le
    {ι : Type*} (S : Finset ι) (c r : ι → ℝ)
    (hr : ∀ i ∈ S, 0 < r i)
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (z : FiberDyadicBase) :
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
      ‖G (z, x)‖ * scratchLp_intervalTail (c i) (2 * r i)
        (realToFiberDyadicLine.symm x)) ≤
      64 * ∑ i ∈ S, ∫ u in Ioo (c i - r i) (c i + r i),
        fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) *
          (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal := by
  calc
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
        ‖G (z, x)‖ * scratchLp_intervalTail (c i) (2 * r i)
          (realToFiberDyadicLine.symm x)) ≤
        ∑ i ∈ S, 64 * (∫ u in Ioo (c i - r i) (c i + r i),
          fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) *
            (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
      apply Finset.sum_le_sum
      intro i hi
      exact scratchLp_intervalTail_pairing_average_le G hG a ha hGa z (hr i hi)
    _ = 64 * ∑ i ∈ S, ∫ u in Ioo (c i - r i) (c i + r i),
        fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) *
          (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal := by
      rw [Finset.mul_sum]

/-- For a finite pairwise-disjoint family of radius intervals, the summed
tail pairings are controlled by one maximal-function integral over their
union.  This is the finite disjoint-interval terminal used before Hölder. -/
theorem scratchLp_finset_pairwiseDisjoint_intervalTail_pairing_le
    {ι : Type*} (S : Finset ι) (c r : ι → ℝ)
    (hr : ∀ i ∈ S, 0 < r i)
    (hdisj : (↑S : Set ι).PairwiseDisjoint
      (fun i => Ioo (c i - r i) (c i + r i)))
    (G : FiberDyadicBase × FiberDyadicLine → ℂ) (hG : Measurable G)
    (a : ℝ) (ha : 0 ≤ a) (hGa : ∀ z, ‖G z‖ ≤ a)
    (z : FiberDyadicBase) :
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
      ‖G (z, x)‖ * scratchLp_intervalTail (c i) (2 * r i)
        (realToFiberDyadicLine.symm x)) ≤
      64 * (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i),
        fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) *
          (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  classical
  let V : ℝ := (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal
  let M : ℝ → ℝ := fun u =>
    fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) * V
  have hV : 0 ≤ V := by
    dsimp [V]
    exact ENNReal.toReal_nonneg
  have hM_nonneg (u : ℝ) : 0 ≤ M u := by
    dsimp [M]
    exact mul_nonneg ENNReal.toReal_nonneg hV
  have hM_meas : Measurable M := by
    dsimp [M]
    exact ((fiberDyadicBallMaximal_measurable G hG).comp
      (measurable_const.prodMk realToFiberDyadicLine.measurable)).mul measurable_const
  have hM_bound (u : ℝ) : M u ≤ a * V := by
    dsimp [M]
    exact mul_le_mul_of_nonneg_right
      (fiberDyadicBallMaximal_top_bound G a ha hGa
        (z, realToFiberDyadicLine u)) hV
  have hM_int (i : ι) (hi : i ∈ S) :
      IntegrableOn M (Ioo (c i - r i) (c i + r i)) volume := by
    refine IntegrableOn.of_bound measure_Ioo_lt_top hM_meas.aestronglyMeasurable
      (a * V) ?_
    filter_upwards [] with u
    rw [Real.norm_eq_abs, abs_of_nonneg (hM_nonneg u)]
    exact hM_bound u
  have hsum := scratchLp_finset_intervalTail_pairing_average_le S c r hr
    G hG a ha hGa z
  have hunion :
      (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i), M u) =
        ∑ i ∈ S, ∫ u in Ioo (c i - r i) (c i + r i), M u := by
    exact integral_biUnion_finset S
      (fun i _ => measurableSet_Ioo) hdisj hM_int
  calc
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
        ‖G (z, x)‖ * scratchLp_intervalTail (c i) (2 * r i)
          (realToFiberDyadicLine.symm x)) ≤
        64 * ∑ i ∈ S, ∫ u in Ioo (c i - r i) (c i + r i), M u := by
      simpa [M, V] using hsum
    _ = 64 * (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i), M u) := by
      rw [hunion]
    _ = 64 * (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i),
        fiberDyadicBallMaximal G (z, realToFiberDyadicLine u) *
          (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
      rfl

/-! ### A one-dimensional strong bound for bounded cutoff tests

The product-fiber maximal theorem in `Twisted` already contains the hard
Marcinkiewicz argument.  For the interval-tail dual test we need its literal
one-dimensional specialization on a single fiber.  Rather than appeal to the
Schwartz-only theorem upstream, the following small transport exposes that
specialization for every bounded measurable line function. -/

private theorem scratchLp_line_dyadicBallMaximal_measurable
    (g : FiberDyadicLine → ℂ) (hg : Measurable g) :
    Measurable (dyadicBallMaximal 1 g) := by
  let G : FiberDyadicBase × FiberDyadicLine → ℂ := fun q => g q.2
  let z0 : FiberDyadicBase := 0
  have hG : Measurable G := hg.comp measurable_snd
  have hM := fiberDyadicBallMaximal_measurable G hG
  have hcomp : Measurable (fun x : FiberDyadicLine =>
      fiberDyadicBallMaximal G (z0, x)) :=
    hM.comp ((measurable_const : Measurable fun _ : FiberDyadicLine => z0).prodMk
      measurable_id)
  simpa [G, fiberDyadicBallMaximal] using hcomp

private theorem scratchLp_line_dyadicBallMaximal_top_bound
    (g : FiberDyadicLine → ℂ) (a : ℝ) (ha : 0 ≤ a)
    (hg : ∀ x, ‖g x‖ ≤ a) :
    ∀ x : FiberDyadicLine, dyadicBallMaximal 1 g x ≤ a := by
  let G : FiberDyadicBase × FiberDyadicLine → ℂ := fun q => g q.2
  have hG : ∀ q, ‖G q‖ ≤ a := by
    intro q
    exact hg q.2
  intro x
  have h := fiberDyadicBallMaximal_top_bound G a ha hG (0, x)
  simpa [G, fiberDyadicBallMaximal] using h

private theorem scratchLp_line_dyadicBallMaximal_subadditive
    (g h : FiberDyadicLine → ℂ) (hg : Measurable g) (hh : Measurable h)
    (hgb : ∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖g x‖ ≤ a)
    (hhb : ∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖h x‖ ≤ a) :
    ∀ x : FiberDyadicLine, dyadicBallMaximal 1 (g + h) x ≤
      dyadicBallMaximal 1 g x + dyadicBallMaximal 1 h x := by
  let G : FiberDyadicBase × FiberDyadicLine → ℂ := fun q => g q.2
  let H : FiberDyadicBase × FiberDyadicLine → ℂ := fun q => h q.2
  have hG : Measurable G := hg.comp measurable_snd
  have hH : Measurable H := hh.comp measurable_snd
  obtain ⟨a, ha, hga⟩ := hgb
  obtain ⟨b, hb, hhb⟩ := hhb
  have hGb : ∃ A : ℝ, 0 ≤ A ∧ ∀ q, ‖G q‖ ≤ A := by
    refine ⟨a, ha, ?_⟩
    intro q
    exact hga q.2
  have hHb : ∃ A : ℝ, 0 ≤ A ∧ ∀ q, ‖H q‖ ≤ A := by
    refine ⟨b, hb, ?_⟩
    intro q
    exact hhb q.2
  intro x
  have hsub := fiberDyadicBallMaximal_subadditive G H hG hH hGb hHb (0, x)
  change dyadicBallMaximal 1 (fun y => g y + h y) x ≤
    dyadicBallMaximal 1 g x + dyadicBallMaximal 1 h x
  simpa [G, H, fiberDyadicBallMaximal] using hsub

/-- The literal line dyadic maximal function has the full strong bound on
bounded measurable input.  This is the exact maximal-function API needed by
the finite interval-tail dual test. -/
theorem scratchLp_line_dyadicBallMaximal_lintegral_bound
    (g : FiberDyadicLine → ℂ) (hg : Measurable g)
    (hgb : ∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖g x‖ ≤ a)
    {p : ℝ} (hp : 1 < p) :
    (∫⁻ x : FiberDyadicLine,
      ENNReal.ofReal (dyadicBallMaximal 1 g x ^ p)) ≤
      ENNReal.ofReal p *
        (2 * ENNReal.ofReal 4 * (ENNReal.ofReal (p - 1))⁻¹ *
          (ENNReal.ofReal (2 : ℝ)) ^ (p - 1) *
          ∫⁻ x : FiberDyadicLine, (ENNReal.ofReal ‖g x‖) ^ p) := by
  let D : ENNReal := ENNReal.ofReal 4
  have hnonneg : ∀ (f : FiberDyadicLine → ℂ) x,
      0 ≤ dyadicBallMaximal 1 f x := fun _ _ => ENNReal.toReal_nonneg
  have hsub : ∀ (f h : FiberDyadicLine → ℂ), Measurable f → Measurable h →
      (∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖f x‖ ≤ a) →
      (∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖h x‖ ≤ a) →
      ∀ x, dyadicBallMaximal 1 (f + h) x ≤
        dyadicBallMaximal 1 f x + dyadicBallMaximal 1 h x := by
    intro f h hf hh hfb hhb x
    exact scratchLp_line_dyadicBallMaximal_subadditive f h hf hh hfb hhb x
  have hweak : ∀ (f : FiberDyadicLine → ℂ), Measurable f →
      (∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖f x‖ ≤ a) → ∀ {s : ℝ}, 0 < s →
      ENNReal.ofReal s * volume {x | s < dyadicBallMaximal 1 f x} ≤
        D * ∫⁻ x, ENNReal.ofReal ‖f x‖ := by
    intro f _hf _hfb s hs
    simpa [D] using
      (dyadic_ball_maximal_toReal_weak_one (d := 1) (by norm_num) f hs)
  have htop : ∀ (f : FiberDyadicLine → ℂ) (a : ℝ), 0 ≤ a →
      (∀ x, ‖f x‖ ≤ a) → ∀ x, dyadicBallMaximal 1 f x ≤ a := by
    intro f a ha hfa x
    exact scratchLp_line_dyadicBallMaximal_top_bound f a ha hfa x
  simpa [D] using
    (marcinkiewicz_weak_one_top (dyadicBallMaximal 1) hnonneg hsub D hweak htop
      hp g hg hgb (scratchLp_line_dyadicBallMaximal_measurable g hg).aemeasurable)

/-- The strong line maximal estimate in `MemLp` form. -/
theorem scratchLp_line_dyadicBallMaximal_memLp
    (g : FiberDyadicLine → ℂ) (hg : Measurable g)
    (hgb : ∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖g x‖ ≤ a)
    {p : ℝ} (hp : 1 < p)
    (hgp : MemLp g (ENNReal.ofReal p) volume) :
    MemLp (dyadicBallMaximal 1 g) (ENNReal.ofReal p) volume := by
  have hp0 : 0 < p := by linarith
  have hpEN0 : ENNReal.ofReal p ≠ 0 := ENNReal.ofReal_ne_zero_iff.mpr hp0
  have hpENT : ENNReal.ofReal p ≠ ⊤ := ENNReal.ofReal_ne_top
  have hinput : (∫⁻ x : FiberDyadicLine,
      (ENNReal.ofReal ‖g x‖) ^ p) < ∞ := by
    have h := (eLpNorm_lt_top_iff_lintegral_rpow_enorm_lt_top hpEN0 hpENT).mp hgp.2
    simpa [ENNReal.toReal_ofReal hp0.le, enorm_eq_nnnorm] using h
  have hinv : (ENNReal.ofReal (p - 1))⁻¹ < ∞ := by
    apply ENNReal.inv_lt_top.mpr
    exact ENNReal.ofReal_pos.mpr (by linarith)
  have hpow : (ENNReal.ofReal (2 : ℝ)) ^ (p - 1) < ∞ := by
    apply ENNReal.rpow_lt_top_of_nonneg
    · linarith
    · exact ENNReal.ofReal_ne_top
  have htwofour : (2 : ENNReal) * ENNReal.ofReal 4 < ∞ :=
    ENNReal.mul_lt_top (by norm_num) ENNReal.ofReal_lt_top
  have htwofourinv : (2 : ENNReal) * ENNReal.ofReal 4 *
      (ENNReal.ofReal (p - 1))⁻¹ < ∞ :=
    ENNReal.mul_lt_top htwofour hinv
  have hcoef : 2 * ENNReal.ofReal 4 * (ENNReal.ofReal (p - 1))⁻¹ *
      (ENNReal.ofReal (2 : ℝ)) ^ (p - 1) < ∞ := by
    exact ENNReal.mul_lt_top htwofourinv hpow
  have hright : ENNReal.ofReal p *
      (2 * ENNReal.ofReal 4 * (ENNReal.ofReal (p - 1))⁻¹ *
        (ENNReal.ofReal (2 : ℝ)) ^ (p - 1) *
        ∫⁻ x : FiberDyadicLine, (ENNReal.ofReal ‖g x‖) ^ p) < ∞ := by
    apply ENNReal.mul_lt_top ENNReal.ofReal_lt_top
    exact ENNReal.mul_lt_top hcoef hinput
  apply memLp_of_lintegral_ofReal_rpow_lt_top
    (dyadicBallMaximal 1 g)
    (scratchLp_line_dyadicBallMaximal_measurable g hg).aemeasurable
    (fun _ ↦ ENNReal.toReal_nonneg) hp0
  apply lt_of_le_of_lt (scratchLp_line_dyadicBallMaximal_lintegral_bound g hg hgb hp)
  exact hright

/-- Transport the strong line maximal estimate back to the literal real
coordinate used by the interval family. -/
theorem scratchLp_real_dyadicBallMaximal_memLp
    (g : FiberDyadicLine → ℂ) (hg : Measurable g)
    (hgb : ∃ a : ℝ, 0 ≤ a ∧ ∀ x, ‖g x‖ ≤ a)
    {p : ℝ} (hp : 1 < p)
    (hgp : MemLp g (ENNReal.ofReal p) volume) :
    MemLp (fun u : ℝ => dyadicBallMaximal 1 g (realToFiberDyadicLine u))
      (ENNReal.ofReal p) volume := by
  have h := scratchLp_line_dyadicBallMaximal_memLp g hg hgb hp hgp
  exact h.comp_measurePreserving realToFiberDyadicLine_measurePreserving

/-- The finite disjoint-interval testing inequality with a genuinely
one-dimensional cutoff.  It is the source tail estimate after the passive
fiber coordinate has been eliminated. -/
theorem scratchLp_finset_pairwiseDisjoint_intervalTail_lineTesting_le
    {ι : Type*} (S : Finset ι) (c r : ι → ℝ)
    (hr : ∀ i ∈ S, 0 < r i)
    (hdisj : (↑S : Set ι).PairwiseDisjoint
      (fun i => Ioo (c i - r i) (c i + r i)))
    (g : FiberDyadicLine → ℂ) (hg : Measurable g)
    (a : ℝ) (ha : 0 ≤ a) (hga : ∀ x, ‖g x‖ ≤ a) :
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
      ‖g x‖ * scratchLp_intervalTail (c i) (2 * r i)
        (realToFiberDyadicLine.symm x)) ≤
      64 * (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i),
        dyadicBallMaximal 1 g (realToFiberDyadicLine u) *
          (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal) := by
  let G : FiberDyadicBase × FiberDyadicLine → ℂ := fun q => g q.2
  have hG : Measurable G := hg.comp measurable_snd
  have hGa : ∀ q, ‖G q‖ ≤ a := by
    intro q
    exact hga q.2
  have h := scratchLp_finset_pairwiseDisjoint_intervalTail_pairing_le
    S c r hr hdisj G hG a ha hGa (0 : FiberDyadicBase)
  simpa [G, fiberDyadicBallMaximal] using h

private theorem scratchLp_measure_union_finset_intervals_lt_top
    {ι : Type*} (S : Finset ι) (c r : ι → ℝ) :
    volume (⋃ i ∈ S, Ioo (c i - r i) (c i + r i)) < ∞ := by
  calc
    volume (⋃ i ∈ S, Ioo (c i - r i) (c i + r i)) ≤
        ∑ i ∈ S, volume (Ioo (c i - r i) (c i + r i)) :=
      measure_biUnion_finset_le S (fun i => Ioo (c i - r i) (c i + r i))
    _ < ∞ := ENNReal.sum_lt_top.2 fun i hi => measure_Ioo_lt_top

/-- The source's finite-​interval dual test, now closed by the literal
strong line maximal theorem.  This is deliberately a bounded-cutoff
statement: it is exactly the input to the standard `L^p` duality passage,
without relying on an unexposed library theorem identifying the dual norm. -/
theorem scratchLp_finset_pairwiseDisjoint_intervalTail_holder_cutoff_le
    {ι : Type*} (S : Finset ι) (c r : ι → ℝ)
    (hr : ∀ i ∈ S, 0 < r i)
    (hdisj : (↑S : Set ι).PairwiseDisjoint
      (fun i => Ioo (c i - r i) (c i + r i)))
    {p q : ℝ} (hpq : q.HolderConjugate p) (hq : 1 < q)
    (g : FiberDyadicLine → ℂ) (hg : Measurable g)
    (a : ℝ) (ha : 0 ≤ a) (hga : ∀ x, ‖g x‖ ≤ a)
    (hgp : MemLp g (ENNReal.ofReal q) volume) :
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
      ‖g x‖ * scratchLp_intervalTail (c i) (2 * r i)
        (realToFiberDyadicLine.symm x)) ≤
      64 * (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal *
        (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i),
          (dyadicBallMaximal 1 g (realToFiberDyadicLine u)) ^ q) ^ (1 / q) *
        (volume (⋃ i ∈ S, Ioo (c i - r i) (c i + r i))).toReal ^ (1 / p) := by
  let U : Set ℝ := ⋃ i ∈ S, Ioo (c i - r i) (c i + r i)
  let M : ℝ → ℝ := fun u => dyadicBallMaximal 1 g (realToFiberDyadicLine u)
  let V : ℝ := (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal
  have hUfinite : volume U < ∞ := by
    simpa [U] using scratchLp_measure_union_finset_intervals_lt_top S c r
  letI : IsFiniteMeasure (volume.restrict U) := ⟨by
    simpa only [Measure.restrict_apply_univ] using hUfinite⟩
  have hMmem : MemLp M (ENNReal.ofReal q) volume := by
    simpa [M] using scratchLp_real_dyadicBallMaximal_memLp
      g hg ⟨a, ha, hga⟩ hq hgp
  have hMnonneg (u : ℝ) : 0 ≤ M u := by
    dsimp [M]
    exact ENNReal.toReal_nonneg
  have hVnonneg : 0 ≤ V := by
    dsimp [V]
    exact ENNReal.toReal_nonneg
  have htest := scratchLp_finset_pairwiseDisjoint_intervalTail_lineTesting_le
    S c r hr hdisj g hg a ha hga
  have htest' :
      (∑ i ∈ S, ∫ x : FiberDyadicLine,
        ‖g x‖ * scratchLp_intervalTail (c i) (2 * r i)
          (realToFiberDyadicLine.symm x)) ≤
        (64 * V) * ∫ u in U, M u := by
    calc
      (∑ i ∈ S, ∫ x : FiberDyadicLine,
          ‖g x‖ * scratchLp_intervalTail (c i) (2 * r i)
            (realToFiberDyadicLine.symm x)) ≤
          64 * (∫ u in U, M u * V) := by
        simpa [U, M, V] using htest
      _ = (64 * V) * ∫ u in U, M u := by
        rw [integral_mul_const]
        ring
  have hholder := integral_mul_norm_le_Lp_mul_Lq hpq
    (hMmem.restrict U)
    (memLp_const (1 : ℝ) : MemLp (fun _ : ℝ => (1 : ℝ))
      (ENNReal.ofReal p) (volume.restrict U))
  have hleft : (∫ u in U, M u) =
      ∫ u, ‖M u‖ * ‖(1 : ℝ)‖ ∂(volume.restrict U) := by
    apply integral_congr_ae
    filter_upwards with u
    rw [Real.norm_of_nonneg (hMnonneg u), norm_one, mul_one]
  have hfirst :
      (∫ u, ‖M u‖ ^ q ∂(volume.restrict U)) =
        ∫ u in U, (M u) ^ q := by
    apply integral_congr_ae
    filter_upwards with u
    rw [Real.norm_of_nonneg (hMnonneg u)]
  have hsecond :
      (∫ u, ‖(1 : ℝ)‖ ^ p ∂(volume.restrict U)) =
        (volume U).toReal := by
    rw [norm_one, Real.one_rpow]
    change (∫ _u in U, (1 : ℝ)) = (volume U).toReal
    rw [setIntegral_const, smul_eq_mul]
    simp [Measure.real]
  have hcut : (∫ u in U, M u) ≤
      (∫ u in U, (M u) ^ q) ^ (1 / q) *
        (volume U).toReal ^ (1 / p) := by
    calc
      (∫ u in U, M u) =
          ∫ u, ‖M u‖ * ‖(1 : ℝ)‖ ∂(volume.restrict U) := hleft
      _ ≤ (∫ u, ‖M u‖ ^ q ∂(volume.restrict U)) ^ (1 / q) *
          (∫ u, ‖(1 : ℝ)‖ ^ p ∂(volume.restrict U)) ^ (1 / p) := hholder
      _ = (∫ u in U, (M u) ^ q) ^ (1 / q) *
          (volume U).toReal ^ (1 / p) := by rw [hfirst, hsecond]
  calc
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
        ‖g x‖ * scratchLp_intervalTail (c i) (2 * r i)
          (realToFiberDyadicLine.symm x)) ≤
        (64 * V) * ∫ u in U, M u := htest'
    _ ≤ (64 * V) *
        ((∫ u in U, (M u) ^ q) ^ (1 / q) *
          (volume U).toReal ^ (1 / p)) :=
      mul_le_mul_of_nonneg_left hcut (mul_nonneg (by norm_num) hVnonneg)
    _ = 64 * (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal *
        (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i),
          (dyadicBallMaximal 1 g (realToFiberDyadicLine u)) ^ q) ^ (1 / q) *
        (volume (⋃ i ∈ S, Ioo (c i - r i) (c i + r i))).toReal ^ (1 / p) := by
      simp [U, M, V]
      ring

/-- The same cutoff terminal stated with the canonical interval tail used by
the scale-integrated bad-fiber estimate.  This is a definitional bridge, but
keeping it named removes all local-tail rewriting at the scale interface. -/
theorem scratchLp_finset_pairwiseDisjoint_canonicalIntervalTail_holder_cutoff_le
    {ι : Type*} (S : Finset ι) (c r : ι → ℝ)
    (hr : ∀ i ∈ S, 0 < r i)
    (hdisj : (↑S : Set ι).PairwiseDisjoint
      (fun i => Ioo (c i - r i) (c i + r i)))
    {p q : ℝ} (hpq : q.HolderConjugate p) (hq : 1 < q)
    (g : FiberDyadicLine → ℂ) (hg : Measurable g)
    (a : ℝ) (ha : 0 ≤ a) (hga : ∀ x, ‖g x‖ ≤ a)
    (hgp : MemLp g (ENNReal.ofReal q) volume) :
    (∑ i ∈ S, ∫ x : FiberDyadicLine,
      ‖g x‖ * intervalTail (c i) (2 * r i)
        (realToFiberDyadicLine.symm x)) ≤
      64 * (volume (Metric.ball (0 : FiberDyadicLine) 1)).toReal *
        (∫ u in ⋃ i ∈ S, Ioo (c i - r i) (c i + r i),
          (dyadicBallMaximal 1 g (realToFiberDyadicLine u)) ^ q) ^ (1 / q) *
        (volume (⋃ i ∈ S, Ioo (c i - r i) (c i + r i))).toReal ^ (1 / p) := by
  simpa only [scratchLp_intervalTail, intervalTail] using
    scratchLp_finset_pairwiseDisjoint_intervalTail_holder_cutoff_le
      S c r hr hdisj hpq hq g hg a ha hga hgp

end
end Twisted
end Auto
