/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Codex.
-/

import Auto.Twisted.FiniteEndpointMeasureScratch

namespace Auto
namespace Twisted

open scoped BigOperators

noncomputable section

/-! ## A common four-vertex decay rate for output layers

For a fixed output dyadic layer, weak-one endpoint information supplies one
scalar estimate at each of the three edge vertices.  The simplex selector is
independent of the output layer.  This file makes that uniformity explicit:
all layers receive the same strict input-dyadic rate.  A separate finite
output-level cover is still needed to sum the layers.
-/

/-- The three normalized edge estimates for every output layer imply a
single strict dyadic rate shared by all layers.  The hypotheses are the
literal scalar layer contributions which a weak-one distribution estimate
provides after restricting the output to one dyadic height band. -/
theorem scratch_fourVertex_family_normalizedDyadic_edges_to_decay
    {β0 β1 β2 β3 : ℝ} (b : ExponentSimplex β0 β1 β2 β3)
    (δ : ℝ) (hδ : 0 < δ)
    (hδ1 : δ ≤ β1 - b.b1) (hδ2 : δ ≤ β2 - b.b2)
    (hδ3 : δ ≤ β3 - b.b3)
    {ω : Type*}
    (s₁ s₂ s₃ : Finset scratchSignedDyadicLevel)
    (W : ω → scratchSignedDyadicLevel → scratchSignedDyadicLevel →
      scratchSignedDyadicLevel → ℝ)
    (C : ℝ) (hC : 0 ≤ C)
    (amp₁ m₁ : scratchSignedDyadicLevel → ℝ)
    (amp₂ m₂ : scratchSignedDyadicLevel → ℝ)
    (amp₃ m₃ : scratchSignedDyadicLevel → ℝ)
    (hmass₁ : ∀ i ∈ s₁, m₁ i = (2 : ℝ) ^ (-(i.2 : ℝ)))
    (hmass₂ : ∀ j ∈ s₂, m₂ j = (2 : ℝ) ^ (-(j.2 : ℝ)))
    (hmass₃ : ∀ k ∈ s₃, m₃ k = (2 : ℝ) ^ (-(k.2 : ℝ)))
    (hnormal₁ : ∀ i ∈ s₁, amp₁ i * m₁ i ^ β1 = 1)
    (hnormal₂ : ∀ j ∈ s₂, amp₂ j * m₂ j ^ β2 = 1)
    (hnormal₃ : ∀ k ∈ s₃, amp₃ k * m₃ k ^ β3 = 1)
    (hEdge₁ : ∀ ell i, i ∈ s₁ → ∀ j, j ∈ s₂ → ∀ k, k ∈ s₃ →
      W ell i j k ≤ C *
        (amp₁ i * m₁ i ^ (b.b1 + b.b0)) *
          (amp₂ j * m₂ j ^ b.b2) * (amp₃ k * m₃ k ^ b.b3))
    (hEdge₂ : ∀ ell i, i ∈ s₁ → ∀ j, j ∈ s₂ → ∀ k, k ∈ s₃ →
      W ell i j k ≤ C *
        (amp₁ i * m₁ i ^ b.b1) *
          (amp₂ j * m₂ j ^ (b.b2 + b.b0)) * (amp₃ k * m₃ k ^ b.b3))
    (hEdge₃ : ∀ ell i, i ∈ s₁ → ∀ j, j ∈ s₂ → ∀ k, k ∈ s₃ →
      W ell i j k ≤ C *
        (amp₁ i * m₁ i ^ b.b1) *
          (amp₂ j * m₂ j ^ b.b2) * (amp₃ k * m₃ k ^ (b.b3 + b.b0))) :
    ∃ η : ℝ, 0 < η ∧ ∀ ell i, i ∈ s₁ → ∀ j, j ∈ s₂ → ∀ k, k ∈ s₃ →
      W ell i j k ≤ C * ((2 : ℝ) ^ (-η)) ^ (i.2 + j.2 + k.2) := by
  rcases scratch_fourVertex_uniform_geometric_selector b δ hδ hδ1 hδ2 hδ3 with
    ⟨η, hη, hselector⟩
  refine ⟨η, hη, ?_⟩
  intro ell i hi j hj k hk
  let n₁ : ℝ := i.2
  let n₂ : ℝ := j.2
  let n₃ : ℝ := k.2
  have hn₁ : 0 ≤ n₁ := by
    dsimp only [n₁]
    positivity
  have hn₂ : 0 ≤ n₂ := by
    dsimp only [n₂]
    positivity
  have hn₃ : 0 ≤ n₃ := by
    dsimp only [n₃]
    positivity
  have hcast : n₁ + n₂ + n₃ = ((i.2 + j.2 + k.2 : ℕ) : ℝ) := by
    dsimp only [n₁, n₂, n₃]
    norm_num [Nat.cast_add]
  rcases hselector n₁ n₂ n₃ hn₁ hn₂ hn₃ with hsel₁ | hsel₂ | hsel₃
  · have hfactor :
        (amp₁ i * m₁ i ^ (b.b1 + b.b0)) *
            (amp₂ j * m₂ j ^ b.b2) * (amp₃ k * m₃ k ^ b.b3) =
          (2 : ℝ) ^ (-(n₁ * (b.b1 + b.b0 - β1) +
            n₂ * (b.b2 - β2) + n₃ * (b.b3 - β3))) := by
          simpa only [n₁, n₂, n₃] using
            scratch_three_normalized_dyadic_endpoint_factors
              (i.2 : ℝ) (j.2 : ℝ) (k.2 : ℝ) β1 β2 β3
              (b.b1 + b.b0) b.b2 b.b3
              (amp₁ i) (amp₂ j) (amp₃ k) (m₁ i) (m₂ j) (m₃ k)
              (hmass₁ i hi) (hmass₂ j hj) (hmass₃ k hk)
              (hnormal₁ i hi) (hnormal₂ j hj) (hnormal₃ k hk)
    have hpow :
        (2 : ℝ) ^ (-(n₁ * (b.b1 + b.b0 - β1) +
          n₂ * (b.b2 - β2) + n₃ * (b.b3 - β3))) ≤
          ((2 : ℝ) ^ (-η)) ^ (n₁ + n₂ + n₃) := by
      simpa only [n₁, n₂, n₃] using hsel₁
    calc
      W ell i j k ≤ C *
          ((2 : ℝ) ^ (-(n₁ * (b.b1 + b.b0 - β1) +
            n₂ * (b.b2 - β2) + n₃ * (b.b3 - β3)))) := by
              rw [← hfactor]
              simpa only [mul_assoc] using hEdge₁ ell i hi j hj k hk
      _ ≤ C * ((2 : ℝ) ^ (-η)) ^ (n₁ + n₂ + n₃) :=
        mul_le_mul_of_nonneg_left hpow hC
      _ = C * ((2 : ℝ) ^ (-η)) ^ (i.2 + j.2 + k.2) := by
        rw [hcast, Real.rpow_natCast]
  · have hfactor :
        (amp₁ i * m₁ i ^ b.b1) *
            (amp₂ j * m₂ j ^ (b.b2 + b.b0)) * (amp₃ k * m₃ k ^ b.b3) =
          (2 : ℝ) ^ (-(n₁ * (b.b1 - β1) +
            n₂ * (b.b2 + b.b0 - β2) + n₃ * (b.b3 - β3))) := by
          simpa only [n₁, n₂, n₃] using
            scratch_three_normalized_dyadic_endpoint_factors
              (i.2 : ℝ) (j.2 : ℝ) (k.2 : ℝ) β1 β2 β3
              b.b1 (b.b2 + b.b0) b.b3
              (amp₁ i) (amp₂ j) (amp₃ k) (m₁ i) (m₂ j) (m₃ k)
              (hmass₁ i hi) (hmass₂ j hj) (hmass₃ k hk)
              (hnormal₁ i hi) (hnormal₂ j hj) (hnormal₃ k hk)
    have hpow :
        (2 : ℝ) ^ (-(n₁ * (b.b1 - β1) +
          n₂ * (b.b2 + b.b0 - β2) + n₃ * (b.b3 - β3))) ≤
          ((2 : ℝ) ^ (-η)) ^ (n₁ + n₂ + n₃) := by
      simpa only [n₁, n₂, n₃] using hsel₂
    calc
      W ell i j k ≤ C *
          ((2 : ℝ) ^ (-(n₁ * (b.b1 - β1) +
            n₂ * (b.b2 + b.b0 - β2) + n₃ * (b.b3 - β3)))) := by
              rw [← hfactor]
              simpa only [mul_assoc] using hEdge₂ ell i hi j hj k hk
      _ ≤ C * ((2 : ℝ) ^ (-η)) ^ (n₁ + n₂ + n₃) :=
        mul_le_mul_of_nonneg_left hpow hC
      _ = C * ((2 : ℝ) ^ (-η)) ^ (i.2 + j.2 + k.2) := by
        rw [hcast, Real.rpow_natCast]
  · have hfactor :
        (amp₁ i * m₁ i ^ b.b1) *
            (amp₂ j * m₂ j ^ b.b2) * (amp₃ k * m₃ k ^ (b.b3 + b.b0)) =
          (2 : ℝ) ^ (-(n₁ * (b.b1 - β1) +
            n₂ * (b.b2 - β2) + n₃ * (b.b3 + b.b0 - β3))) := by
          simpa only [n₁, n₂, n₃] using
            scratch_three_normalized_dyadic_endpoint_factors
              (i.2 : ℝ) (j.2 : ℝ) (k.2 : ℝ) β1 β2 β3
              b.b1 b.b2 (b.b3 + b.b0)
              (amp₁ i) (amp₂ j) (amp₃ k) (m₁ i) (m₂ j) (m₃ k)
              (hmass₁ i hi) (hmass₂ j hj) (hmass₃ k hk)
              (hnormal₁ i hi) (hnormal₂ j hj) (hnormal₃ k hk)
    have hpow :
        (2 : ℝ) ^ (-(n₁ * (b.b1 - β1) +
          n₂ * (b.b2 - β2) + n₃ * (b.b3 + b.b0 - β3))) ≤
          ((2 : ℝ) ^ (-η)) ^ (n₁ + n₂ + n₃) := by
      simpa only [n₁, n₂, n₃] using hsel₃
    calc
      W ell i j k ≤ C *
          ((2 : ℝ) ^ (-(n₁ * (b.b1 - β1) +
            n₂ * (b.b2 - β2) + n₃ * (b.b3 + b.b0 - β3)))) := by
              rw [← hfactor]
              simpa only [mul_assoc] using hEdge₃ ell i hi j hj k hk
      _ ≤ C * ((2 : ℝ) ^ (-η)) ^ (n₁ + n₂ + n₃) :=
        mul_le_mul_of_nonneg_left hpow hC
      _ = C * ((2 : ℝ) ^ (-η)) ^ (i.2 + j.2 + k.2) := by
        rw [hcast, Real.rpow_natCast]

end
end Twisted
end Auto
