/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## The gauge bound on the closed box

Source: `lem:symbol_derivatives`.  The derivative bound has to be checked
wherever a derivative can be nonzero, which is the *closed* box rather than the
open one, so the gauge bound is recorded there too.
-/

theorem rpow_inv_le_two {a : ℝ} (ha : 0 ≤ a) (h : a ≤ 2) {w : ℕ} (hw : 0 < w) :
    a ^ ((w : ℝ))⁻¹ ≤ 2 := by
  have hwpos : (0 : ℝ) < (w : ℝ) := by exact_mod_cast hw
  have hw1 : (1 : ℝ) ≤ (w : ℝ) := by exact_mod_cast hw
  have hinvpos : 0 < ((w : ℝ))⁻¹ := inv_pos.mpr hwpos
  have hinvle : ((w : ℝ))⁻¹ ≤ 1 := by
    rw [inv_le_one_iff₀]
    exact Or.inr hw1
  calc a ^ ((w : ℝ))⁻¹ ≤ (2 : ℝ) ^ ((w : ℝ))⁻¹ :=
        Real.rpow_le_rpow ha h hinvpos.le
    _ ≤ (2 : ℝ) ^ (1 : ℝ) :=
        Real.rpow_le_rpow_of_exponent_le (by norm_num) hinvle
    _ = 2 := Real.rpow_one 2

/-- **The gauge bound on the closed box.** -/
theorem scale_mul_radius_le_of_dilated_coords_le_two
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (ξ : E3)
    (h : ∀ j : Fin 3, |t ^ α.weight j * ξ j| ≤ 2) :
    t * α.radius ξ ≤ 6 := by
  rw [← α.radius_dilate ht ξ]
  have hterm : ∀ i : Fin 3,
      |(α.dilate t ξ) i| ^ ((α.weight i : ℝ))⁻¹ ≤ 2 := by
    intro i
    refine rpow_inv_le_two (abs_nonneg _) ?_ (α.weight_pos i)
    have hcoord : (α.dilate t ξ) i = t ^ α.weight i * ξ i := rfl
    rw [hcoord]
    exact h i
  calc α.radius (α.dilate t ξ)
      = ∑ i : Fin 3, |(α.dilate t ξ) i| ^ ((α.weight i : ℝ))⁻¹ := rfl
    _ ≤ ∑ _i : Fin 3, (2 : ℝ) := Finset.sum_le_sum fun i _ ↦ hterm i
    _ = 6 := by simp; norm_num

theorem norm_coordinateDirection (i : Fin 3) :
    ‖Anisotropy.coordinateDirection i‖ = 1 := by
  unfold Anisotropy.coordinateDirection
  simp [EuclideanSpace.basisFun]

/-- **The anisotropic derivative bound for the mode symbol.**  Combining the
exact scale factor, the uniform profile bound and the gauge bound on the
closed box gives `eq:symbol` for the mode symbol, with a constant independent
of the scale. -/
theorem norm_iteratedFDeriv_thirdModeFrequencySymbol_coordinate_le
    (α : Anisotropy) (ν : Fin 3 → ℤ) {t : ℝ} (ht : 0 < t) {ξ : E3}
    (hξ : ξ ≠ 0) (k : ℕ) (σ : Fin k → Fin 3) {C : ℝ} (hC : 0 ≤ C)
    (hprof : ∀ η : E3,
      ‖iteratedFDeriv ℝ k (coneModeProfile (standardModeOfInt ν)) η‖ ≤ C) :
    ‖(iteratedFDeriv ℝ k
        (thirdModeFrequencySymbol α (standardModeOfInt ν) t) ξ)
          (fun r ↦ Anisotropy.coordinateDirection (σ r))‖
      ≤ (C * 6 ^ α.derivativeWeight σ) *
          (α.radius ξ) ^ (-((α.derivativeWeight σ : ℕ) : ℝ)) := by
  set d : ℕ := α.derivativeWeight σ with hd
  have hrad : 0 < α.radius ξ := radius_pos_of_ne_zero α hξ
  have hrpow : (α.radius ξ) ^ (-((d : ℕ) : ℝ)) = ((α.radius ξ) ^ d)⁻¹ := by
    rw [Real.rpow_neg hrad.le, Real.rpow_natCast]
  by_cases hbox : ∀ j : Fin 3, |t ^ α.weight j * ξ j| ≤ 2
  · -- on the closed box the gauge is comparable to the inverse scale
    have hgauge : t * α.radius ξ ≤ 6 :=
      scale_mul_radius_le_of_dilated_coords_le_two α ht ξ hbox
    have hchain := iteratedFDeriv_thirdModeFrequencySymbol_coordinate
      α (standardModeOfInt ν) t ξ k σ
    have hvec : ‖(iteratedFDeriv ℝ k
        (coneModeProfile (standardModeOfInt ν)) (α.dilate t ξ))
          (fun r ↦ Anisotropy.coordinateDirection (σ r))‖ ≤ C := by
      refine le_trans (ContinuousMultilinearMap.le_opNorm _ _) ?_
      have hprod : ∏ r : Fin k, ‖Anisotropy.coordinateDirection (σ r)‖ = 1 := by
        rw [Finset.prod_congr rfl fun r _ ↦ norm_coordinateDirection (σ r)]
        simp
      rw [hprod, mul_one]
      exact hprof _
    have hLHS : ‖(iteratedFDeriv ℝ k
        (thirdModeFrequencySymbol α (standardModeOfInt ν) t) ξ)
          (fun r ↦ Anisotropy.coordinateDirection (σ r))‖ ≤ t ^ d * C := by
      rw [hchain, norm_smul, Real.norm_eq_abs, abs_of_pos (pow_pos ht d)]
      exact mul_le_mul_of_nonneg_left hvec (pow_pos ht d).le
    refine le_trans hLHS ?_
    rw [hrpow, ← div_eq_mul_inv, le_div_iff₀ (pow_pos hrad d)]
    have hpow : (t * α.radius ξ) ^ d ≤ 6 ^ d :=
      pow_le_pow_left₀ (by positivity) hgauge d
    calc t ^ d * C * (α.radius ξ) ^ d
        = C * (t * α.radius ξ) ^ d := by rw [mul_pow]; ring
      _ ≤ C * 6 ^ d := mul_le_mul_of_nonneg_left hpow hC
  · -- off the closed box every derivative vanishes
    push_neg at hbox
    obtain ⟨j, hj⟩ := hbox
    rw [iteratedFDeriv_thirdModeFrequencySymbol_eq_zero_of_two_lt
      α ν t ξ j hj k]
    simp only [ContinuousMultilinearMap.zero_apply, norm_zero]
    positivity


end
end Twisted
end Auto
