/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal

noncomputable section

/-! ## The four-fold geometric mean of the endpoint layer sizes

Source: `ext:interpolation` with the weights `eq:weights`.  Combining the four
exponent exchanges with the weights collapses the whole four-fold weighted
geometric mean back to the single target-exponent size: the pure powers of the
dyadic level cancel because the weights sum to one, and the target-size powers
recombine because the endpoint reciprocals average to the target reciprocal.
-/

/-- **The weighted geometric mean collapses.**  With weights summing to one and
exchange ratios averaging to one, the four endpoint sizes have weighted
geometric mean exactly the target size. -/
theorem rpow_four_weighted_mean_eq
    {a N : ℝ≥0∞} (ha : a ≠ 0) (ha' : a ≠ ∞) (hN : N ≠ 0) (hN' : N ≠ ∞)
    {ρ₀ ρ₁ ρ₂ ρ₃ ϑ₀ ϑ₁ ϑ₂ ϑ₃ : ℝ}
    (h₀ : 0 ≤ ϑ₀) (h₁ : 0 ≤ ϑ₁) (h₂ : 0 ≤ ϑ₂) (h₃ : 0 ≤ ϑ₃)
    (hϑ : ϑ₀ + ϑ₁ + ϑ₂ + ϑ₃ = 1)
    (hρ : ϑ₀ * ρ₀ + ϑ₁ * ρ₁ + ϑ₂ * ρ₂ + ϑ₃ * ρ₃ = 1) :
    (a ^ (1 - ρ₀) * N ^ ρ₀) ^ ϑ₀ * (a ^ (1 - ρ₁) * N ^ ρ₁) ^ ϑ₁ *
        (a ^ (1 - ρ₂) * N ^ ρ₂) ^ ϑ₂ * (a ^ (1 - ρ₃) * N ^ ρ₃) ^ ϑ₃ = N := by
  have step : ∀ ρ ϑ : ℝ, 0 ≤ ϑ →
      (a ^ (1 - ρ) * N ^ ρ) ^ ϑ = a ^ ((1 - ρ) * ϑ) * N ^ (ρ * ϑ) := by
    intro ρ ϑ hϑ'
    rw [ENNReal.mul_rpow_of_nonneg _ _ hϑ', ← ENNReal.rpow_mul, ← ENNReal.rpow_mul]
  rw [step ρ₀ ϑ₀ h₀, step ρ₁ ϑ₁ h₁, step ρ₂ ϑ₂ h₂, step ρ₃ ϑ₃ h₃]
  have hgroup :
      a ^ ((1 - ρ₀) * ϑ₀) * N ^ (ρ₀ * ϑ₀) * (a ^ ((1 - ρ₁) * ϑ₁) * N ^ (ρ₁ * ϑ₁)) *
          (a ^ ((1 - ρ₂) * ϑ₂) * N ^ (ρ₂ * ϑ₂)) *
          (a ^ ((1 - ρ₃) * ϑ₃) * N ^ (ρ₃ * ϑ₃))
        = (a ^ ((1 - ρ₀) * ϑ₀) * a ^ ((1 - ρ₁) * ϑ₁) * a ^ ((1 - ρ₂) * ϑ₂) *
            a ^ ((1 - ρ₃) * ϑ₃)) *
          (N ^ (ρ₀ * ϑ₀) * N ^ (ρ₁ * ϑ₁) * N ^ (ρ₂ * ϑ₂) * N ^ (ρ₃ * ϑ₃)) := by
    ring
  rw [hgroup,
    rpow_four_mul_eq_one ha ha' (by linear_combination hϑ - hρ :
      (1 - ρ₀) * ϑ₀ + (1 - ρ₁) * ϑ₁ + (1 - ρ₂) * ϑ₂ + (1 - ρ₃) * ϑ₃ = 0),
    one_mul, ← ENNReal.rpow_add _ _ hN hN', ← ENNReal.rpow_add _ _ hN hN',
    ← ENNReal.rpow_add _ _ hN hN',
    show ρ₀ * ϑ₀ + ρ₁ * ϑ₁ + ρ₂ * ϑ₂ + ρ₃ * ϑ₃ = 1 by linear_combination hρ,
    ENNReal.rpow_one]

end
end Twisted
end Auto
