/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto.Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators Convolution ENNReal RealInnerProductSpace Topology

noncomputable section

/-- A translated square times an integrable absolute tail is integrable on
the two-variable product space.  This is the analytic Fubini fact needed to
discharge the fixed `(p₂,r)` condition in the global-energy identity. -/
theorem scratch_integrable_square_shifted_mul_abs
    (B ψ : ℝ → ℝ) (s u : ℝ)
    (hBcont : Continuous B)
    (hBsq : Integrable (fun q : ℝ ↦ B q ^ 2))
    (hψcont : Continuous ψ)
    (hψ : Integrable (fun r : ℝ ↦ |ψ (r + u)|)) :
    Integrable (fun z : ℝ × ℝ ↦
      B (z.1 + z.2 * s) ^ 2 * |ψ (z.2 + u)|)
      ((volume : Measure ℝ).prod volume) := by
  let G : ℝ × ℝ → ℝ := fun z ↦
    B (z.2 + z.1 * s) ^ 2 * |ψ (z.1 + u)|
  have hGcont : Continuous G := by
    apply Continuous.mul
    · exact (hBcont.comp
        ((continuous_snd.add (continuous_fst.mul continuous_const)))).pow 2
    · exact (hψcont.comp (continuous_fst.add continuous_const)).abs
  have hGin : ∀ᵐ r : ℝ,
      Integrable (fun p : ℝ ↦ G (r, p)) := by
    filter_upwards [] with r
    have hshift : Integrable (fun p : ℝ ↦ B (p + r * s) ^ 2) := by
      simpa only using hBsq.comp_add_right (r * s)
    simpa only [G] using hshift.mul_const |ψ (r + u)|
  have hGnorm : Integrable (fun r : ℝ ↦ ∫ p : ℝ, ‖G (r, p)‖) := by
    have hconst : Integrable (fun r : ℝ ↦
        (∫ q : ℝ, B q ^ 2) * |ψ (r + u)|) := hψ.const_mul _
    apply hconst.congr
    filter_upwards [] with r
    have hBnonneg (q : ℝ) : 0 ≤ B q ^ 2 := sq_nonneg _
    have htailnonneg : 0 ≤ |ψ (r + u)| := abs_nonneg _
    symm
    calc
      (∫ p : ℝ, ‖G (r, p)‖) =
          ∫ p : ℝ, B (p + r * s) ^ 2 * |ψ (r + u)| := by
            apply integral_congr_ae
            filter_upwards [] with p
            dsimp [G]
            exact abs_of_nonneg (mul_nonneg (hBnonneg _) htailnonneg)
      _ = (∫ p : ℝ, B (p + r * s) ^ 2) * |ψ (r + u)| := by
            rw [integral_mul_const]
      _ = (∫ q : ℝ, B q ^ 2) * |ψ (r + u)| := by
            exact congrArg (fun x : ℝ ↦ x * |ψ (r + u)|)
              (integral_add_right_eq_self (μ := volume)
                (fun q : ℝ ↦ B q ^ 2) (r * s))
  have hG : Integrable G ((volume : Measure ℝ).prod volume) := by
    exact (integrable_prod_iff hGcont.aestronglyMeasurable).mpr ⟨hGin, hGnorm⟩
  have hswap : Integrable (G ∘ Prod.swap)
      ((volume : Measure ℝ).prod volume) := hG.swap
  apply hswap.congr
  filter_upwards [] with z
  rfl

/-- An integrable real function with a uniform absolute bound has integrable
square. -/
theorem scratch_integrable_sq_of_integrable_bounded
    (B : ℝ → ℝ) (hB : Integrable B)
    (C : ℝ) (hC : 0 ≤ C) (hbound : ∀ q : ℝ, |B q| ≤ C) :
    Integrable (fun q : ℝ ↦ B q ^ 2) := by
  have hmajor : Integrable (fun q : ℝ ↦ C * |B q|) :=
    hB.norm.const_mul C
  apply Integrable.mono hmajor
    (hB.aestronglyMeasurable.pow 2)
  filter_upwards [] with q
  have hBnonneg : 0 ≤ |B q| := abs_nonneg _
  change |B q ^ 2| ≤ abs (C * |B q|)
  rw [abs_of_nonneg (sq_nonneg _),
    abs_of_nonneg (mul_nonneg hC hBnonneg)]
  rw [← sq_abs]
  nlinarith [hbound q]

/-- A real Schwartz third-coordinate fiber satisfies the fixed-scale
`(p₂,r)` integrability required by the global second-energy reduction. -/
theorem scratch_integrable_modelSecondFiberReduced_p2_r_of_real_schwartz
    (α : Anisotropy) (u : E3) (f : SchwartzMap E3 ℝ)
    (x₁ x₂ t : ℝ) (ht : 0 < t) :
    Integrable (fun z : ℝ × ℝ ↦
      (modelSecondFiberReduced α f x₁ x₂ z.1 t z.2) ^ 2 *
        |conePsiPhysicalReal (z.2 + u 2)|)
      ((volume : Measure ℝ).prod volume) := by
  let F : SchwartzMap ℝ ℂ :=
    modelThirdSchwartzFiber (complexifyRealSchwartz f) x₁ x₂
  let g : ℝ → ℝ := fun v ↦ f (modelPoint x₁ x₂ v)
  let s : ℝ := t ^ α.weight 2
  let K : ℝ → ℂ := fun v ↦ (gaussianDerivAt s 0 v : ℂ)
  let Cfun : ℝ → ℂ := fun q ↦
    ∫ v : ℝ, F v * (gaussianDerivAt s q v : ℂ)
  let B : ℝ → ℝ := fun q ↦
    ∫ v : ℝ, g v * gaussianDerivAt s q v
  have hs : 0 < s := by
    dsimp [s]
    exact pow_pos ht _
  have hFreal (v : ℝ) : F v = (g v : ℂ) := by
    dsimp [F, g]
    simp
  have hK : Integrable K := by
    dsimp [K]
    exact (integrable_gaussianDerivAt hs 0).ofReal
  have hconv : Integrable ((F : ℝ → ℂ) ⋆[ContinuousLinearMap.mul ℂ ℂ] K) :=
    F.integrable.integrable_convolution (ContinuousLinearMap.mul ℂ ℂ) hK
  have hCfun_eq (q : ℝ) : Cfun q =
      -((F : ℝ → ℂ) ⋆[ContinuousLinearMap.mul ℂ ℂ] K) q := by
    dsimp [Cfun, K]
    exact gaussianDerivAt_fiber_eq_neg_convolution F s q
  have hCfun : Integrable Cfun := by
    apply hconv.neg.congr
    filter_upwards [] with q
    symm
    exact hCfun_eq q
  have hconvcont : Continuous ((F : ℝ → ℂ) ⋆[ContinuousLinearMap.mul ℂ ℂ] K) :=
    (bddAbove_norm_complex_gaussianDerivAt s 0).continuous_convolution_right_of_integrable
        (ContinuousLinearMap.mul ℂ ℂ) F.integrable
        (continuous_complex_gaussianDerivAt s 0)
  have hCfuncont : Continuous Cfun := by
    apply hconvcont.neg.congr
    intro q
    symm
    exact hCfun_eq q
  obtain ⟨C, hC⟩ := bddAbove_norm_complex_gaussianDerivAt s 0
  have hKbound (v : ℝ) : ‖K v‖ ≤ C := by
    exact hC ⟨v, rfl⟩
  have hCfunbound (q : ℝ) : ‖Cfun q‖ ≤ (∫ v : ℝ, ‖F v‖) * C := by
    have hmajor : Integrable (fun v : ℝ ↦ ‖F v‖ * C) :=
      F.integrable.norm.mul_const C
    calc
      ‖Cfun q‖ ≤ ∫ v : ℝ,
          ‖F v * (gaussianDerivAt s q v : ℂ)‖ :=
        norm_integral_le_integral_norm _
      _ ≤ ∫ v : ℝ, ‖F v‖ * C := by
        apply MeasureTheory.integral_mono_of_nonneg
        · filter_upwards [] with v
          exact norm_nonneg _
        · exact hmajor
        filter_upwards [] with v
        rw [norm_mul]
        apply mul_le_mul_of_nonneg_left
        · rw [gaussianDerivAt_reflect]
          push_cast
          simpa [K, Complex.norm_real, Real.norm_eq_abs] using hKbound (q - v)
        · exact norm_nonneg _
      _ = (∫ v : ℝ, ‖F v‖) * C := by
        rw [integral_mul_const]
  have hB_eq (q : ℝ) : Cfun q = (B q : ℂ) := by
    dsimp [Cfun, B]
    exact complexFiberIntegral_eq_real F g hFreal s q
  have hB : Integrable B := by
    apply hCfun.re.congr
    filter_upwards [] with q
    exact congrArg Complex.re (hB_eq q)
  have hBcont : Continuous B := by
    apply (Complex.continuous_re.comp hCfuncont).congr
    intro q
    exact congrArg Complex.re (hB_eq q)
  have hDnonneg : 0 ≤ (∫ v : ℝ, ‖F v‖) * C := by
    exact (norm_nonneg (Cfun 0)).trans (hCfunbound 0)
  have hBbound (q : ℝ) : |B q| ≤ (∫ v : ℝ, ‖F v‖) * C := by
    calc
      |B q| = ‖(B q : ℂ)‖ := by simp
      _ = ‖Cfun q‖ := by rw [hB_eq q]
      _ ≤ _ := hCfunbound q
  have hBsq : Integrable (fun q : ℝ ↦ B q ^ 2) :=
    scratch_integrable_sq_of_integrable_bounded B hB
      ((∫ v : ℝ, ‖F v‖) * C) hDnonneg hBbound
  have htail : Integrable (fun r : ℝ ↦
      |conePsiPhysicalReal (r + u 2)|) :=
    integrable_abs_conePsiPhysicalReal.comp_add_right (u 2)
  have hmain := scratch_integrable_square_shifted_mul_abs
    B conePsiPhysicalReal s (u 2) hBcont hBsq
    conePsiPhysicalReal.continuous htail
  apply hmain.congr
  filter_upwards [] with z
  dsimp [B, g, s]
  rfl

/-- For a real Schwartz input, all post-Tonelli scalar and fixed-fiber
integrability conditions in the global second-energy identity are automatic.
The original joint density is the sole remaining global Fubini hypothesis. -/
theorem scratch_modelEnergyTwoOn_global_eq_of_real_schwartz_of_joint
    (α : Anisotropy) (u : E3) (f : SchwartzMap E3 ℝ)
    (hjoint : Integrable (fun q : (E3 × ℝ) × ModelE5 ↦
      modelEnergyTwoIntegrand α u f q.1 q.2)
      ((cubeScaleMeasure.restrict (Set.univ ×ˢ Set.Ioi (0 : ℝ))).prod volume)) :
    modelEnergyTwoOn α (Set.univ ×ˢ Set.Ioi (0 : ℝ)) u f =
      (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2 *
        conePsiPhysicalRealL1 * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ x : E3, f x ^ 2 := by
  apply modelEnergyTwoOn_global_eq_of_joint_and_fixedFiber α u f hjoint
  intro x₁ x₂ t ht
  exact scratch_integrable_modelSecondFiberReduced_p2_r_of_real_schwartz
    α u f x₁ x₂ t ht

end

end Auto.Twisted
