/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto.Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators ENNReal RealInnerProductSpace Topology

noncomputable section

/-- Fubini in the literal three-coordinate order used by the final
one-dimensional square-function identity. -/
theorem scratch_integral_real_cube_eq_nested
    (H : ℝ × (ℝ × ℝ) → ℝ)
    (hH : Integrable H
      ((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume))) :
    (∫ z : ℝ × (ℝ × ℝ), H z
      ∂((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume))) =
      ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ v : ℝ, H (x₁, (x₂, v)) := by
  let K : ℝ → ℝ := fun x₁ ↦
    ∫ x₂ : ℝ, ∫ v : ℝ, H (x₁, (x₂, v))
  have hpair (x₁ : ℝ)
      (hx₁ : Integrable (fun q : ℝ × ℝ ↦ H (x₁, q))
        ((volume : Measure ℝ).prod volume)) :
      (∫ q : ℝ × ℝ, H (x₁, q)
        ∂((volume : Measure ℝ).prod volume)) = K x₁ := by
    calc
      (∫ q : ℝ × ℝ, H (x₁, q)
        ∂((volume : Measure ℝ).prod volume)) =
          ∫ x₂ : ℝ, ∫ v : ℝ, H (x₁, (x₂, v)) := by
            exact integral_prod _ hx₁
      _ = K x₁ := by rfl
  have hK : Integrable K (volume : Measure ℝ) := by
    have hleft := hH.integral_prod_left
    apply hleft.congr
    filter_upwards [hH.prod_right_ae] with x₁ hx₁
    exact hpair x₁ hx₁
  calc
    (∫ z : ℝ × (ℝ × ℝ), H z
      ∂((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume))) =
        ∫ x₁ : ℝ, ∫ q : ℝ × ℝ, H (x₁, q)
          ∂((volume : Measure ℝ).prod volume) :=
      integral_prod _ hH
    _ = ∫ x₁ : ℝ, K x₁ := by
      apply integral_congr_ae
      filter_upwards [hH.prod_right_ae] with x₁ hx₁
      exact hpair x₁ hx₁
    _ = ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ v : ℝ, H (x₁, (x₂, v)) := by
      rfl

/-- The coordinate parametrization used by the third-coordinate fibers is
the inverse of `e3Coordinates`. -/
theorem scratch_modelPoint_e3Coordinates
    (x : E3) : modelPoint (x 0) (x 1) (x 2) = x := by
  ext i
  fin_cases i <;> simp

/-- The ambient squared norm of an integrable real input is exactly its
three-coordinate iterated integral. -/
theorem scratch_integral_modelPoint_sq_eq
    (f : E3 → ℝ)
    (hf : Integrable (fun x : E3 ↦ f x ^ 2)) :
    (∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ v : ℝ,
      f (modelPoint x₁ x₂ v) ^ 2) =
      ∫ x : E3, f x ^ 2 := by
  let G : ℝ × (ℝ × ℝ) → ℝ := fun z ↦
    f (modelPoint z.1 z.2.1 z.2.2) ^ 2
  have hG : Integrable G
      ((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume)) := by
    let e := e3Coordinates
    have hmp : MeasurePreserving e (volume : Measure E3)
        ((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume)) := by
      simpa only [e] using e3Coordinates_measurePreserving
    have hcomp : (fun z : ℝ × (ℝ × ℝ) ↦ G z) =
        (fun x : E3 ↦ f x ^ 2) ∘ e.symm := by
      funext z
      rcases z with ⟨x₁, x₂, v⟩
      simp only [Function.comp_apply, G]
      congr 2
      apply e.injective
      simp only [e, e3Coordinates_apply]
      exact Prod.ext rfl (Prod.ext rfl rfl)
    have htrans :=
      (MeasurePreserving.symm e hmp).integrable_comp_of_integrable hf
    apply htrans.congr
    filter_upwards [] with z
    exact (congrFun hcomp z).symm
  calc
    (∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ v : ℝ,
      f (modelPoint x₁ x₂ v) ^ 2) =
        ∫ z : ℝ × (ℝ × ℝ), G z
          ∂((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume)) := by
            exact (scratch_integral_real_cube_eq_nested G hG).symm
    _ = ∫ x : E3, f x ^ 2 := by
      let e := e3Coordinates
      have hmp : MeasurePreserving e (volume : Measure E3)
          ((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume)) := by
        simpa only [e] using e3Coordinates_measurePreserving
      have hpoint (x : E3) : G (e x) = f x ^ 2 := by
        simp only [G, e, e3Coordinates_apply]
        rw [scratch_modelPoint_e3Coordinates]
      calc
        (∫ z : ℝ × (ℝ × ℝ), G z
          ∂((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume))) =
            ∫ x : E3, G (e x) := by
              exact (hmp.integral_comp' G).symm
        _ = ∫ x : E3, f x ^ 2 := by
          apply integral_congr_ae
          filter_upwards [] with x
          exact hpoint x

/-- On the global positive-scale region the product restriction in
`cubeScaleMeasure` is exactly the product of Lebesgue measure and the
restricted logarithmic scale measure. -/
theorem scratch_cubeScaleMeasure_restrict_global_eq :
    cubeScaleMeasure.restrict (Set.univ ×ˢ Set.Ioi (0 : ℝ)) =
      (volume : Measure E3).prod
        (((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
          (Set.Ioi (0 : ℝ))) := by
  unfold cubeScaleMeasure
  rw [← Measure.prod_restrict]
  simp

/-- Joint integrability transports the global second energy to the literal
nine scalar coordinates.  This is the exact Tonelli bridge before the
scalar mass and one-dimensional square-function reductions. -/
theorem scratch_modelEnergyTwoOn_eq_reordered_nested
    (α : Anisotropy) (u : E3) (f : E3 → ℝ)
    (hjoint : Integrable (fun q : (E3 × ℝ) × ModelE5 ↦
      modelEnergyTwoIntegrand α u f q.1 q.2)
      ((cubeScaleMeasure.restrict (Set.univ ×ˢ Set.Ioi (0 : ℝ))).prod volume)) :
    modelEnergyTwoOn α (Set.univ ×ˢ Set.Ioi (0 : ℝ)) u f =
      ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
        ∫ t : ℝ in Set.Ioi (0 : ℝ),
          (∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
            (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
              modelEnergyDensityReordered α u x₁ x₂ t p₀ p₁ y₁ y₂ r
          ) ∂((volume : Measure ℝ).withDensity cubeScaleDensity) := by
  let ν : Measure ℝ :=
    (((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
      (Set.Ioi (0 : ℝ)))
  let G : (E3 × ℝ) × ModelE5 → ℝ := fun q ↦
    modelEnergyTwoIntegrand α u f q.1 q.2
  let μouter : Measure ScratchModelEnergyOuter :=
    ((volume : Measure ℝ).prod volume).prod ((volume : Measure ℝ).prod ν)
  let μinner : Measure ScratchModelEnergyInner :=
    ((volume : Measure ℝ).prod volume).prod
      ((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume))
  have hjoint' : Integrable G (((volume : Measure E3).prod ν).prod volume) := by
    simpa only [G, ν, scratch_cubeScaleMeasure_restrict_global_eq] using hjoint
  have htrans : Integrable (fun w : ScratchModelEnergyOuter × ScratchModelEnergyInner ↦
      G (modelEnergyCoordinateReorder.symm w)) (μouter.prod μinner) := by
    have hmp := modelEnergyCoordinateReorder_measurePreserving_scale ν
    exact (MeasurePreserving.symm modelEnergyCoordinateReorder hmp).integrable_comp_of_integrable
      hjoint'
  let K : ScratchModelEnergyOuter → ℝ := fun w ↦
    ∫ v : ScratchModelEnergyInner,
      G (modelEnergyCoordinateReorder.symm (w, v)) ∂μinner
  have hK : Integrable K μouter := by
    exact htrans.integral_prod_left
  let L : ScratchModelEnergyOuter → ℝ := fun w ↦
    ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
      (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2 *
        modelEnergyDensityReordered α u w.1.1 w.1.2 w.2.2
          p₀ p₁ y₁ y₂ r
  have hKL : K =ᵐ[μouter] L := by
    filter_upwards [htrans.prod_right_ae] with w hw
    dsimp [K, L]
    calc
      (∫ v : ScratchModelEnergyInner,
        G (modelEnergyCoordinateReorder.symm (w, v)) ∂μinner) =
          ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
            G (modelEnergyCoordinateReorder.symm
              (w, ((p₀, p₁), (y₁, (y₂, r))))) := by
              exact integral_ScratchModelEnergyInner_eq_nested _ hw
      _ = ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
          (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2 *
            modelEnergyDensityReordered α u w.1.1 w.1.2 w.2.2
              p₀ p₁ y₁ y₂ r := by
            apply integral_congr_ae
            filter_upwards [] with p₀
            apply integral_congr_ae
            filter_upwards [] with p₁
            apply integral_congr_ae
            filter_upwards [] with y₁
            apply integral_congr_ae
            filter_upwards [] with y₂
            apply integral_congr_ae
            filter_upwards [] with r
            rcases w with ⟨⟨x₁, x₂⟩, ⟨p₂, t⟩⟩
            exact modelEnergyTwoIntegrand_reorder_symm
              α u f x₁ x₂ p₂ t p₀ p₁ y₁ y₂ r
  have hL : Integrable L μouter := hK.congr hKL
  calc
    modelEnergyTwoOn α (Set.univ ×ˢ Set.Ioi (0 : ℝ)) u f =
        ∫ q : (E3 × ℝ) × ModelE5, G q
          ∂(((volume : Measure E3).prod ν).prod volume) := by
            rw [modelEnergyTwoOn_eq_jointIntegral_of_integrable α
              (Set.univ ×ˢ Set.Ioi (0 : ℝ)) u f hjoint]
            simp only [G, ν, scratch_cubeScaleMeasure_restrict_global_eq]
    _ = ∫ w : ScratchModelEnergyOuter, K w ∂μouter := by
          exact integral_modelEnergyCoordinateReorder_fubini ν G hjoint'
    _ = ∫ w : ScratchModelEnergyOuter, L w ∂μouter := by
          exact integral_congr_ae hKL
    _ = ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
        ∫ t : ℝ, L ((x₁, x₂), (p₂, t)) ∂ν := by
          exact integral_ScratchModelEnergyOuter_eq_nested ν L hL
    _ = ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
        ∫ t : ℝ in Set.Ioi (0 : ℝ),
          (∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
            (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
              modelEnergyDensityReordered α u x₁ x₂ t p₀ p₁ y₁ y₂ r
          ) ∂((volume : Measure ℝ).withDensity cubeScaleDensity) := by
          dsimp [ν, L]

/-- The post-scalar outer density is integrable whenever the original global
joint energy density is integrable.  Thus the only genuinely new analytic
condition in the terminal square-function calculation is the fixed-fiber
translation integrability. -/
theorem scratch_integrable_reordered_scalar_of_joint
    (α : Anisotropy) (u : E3) (f : E3 → ℝ)
    (hjoint : Integrable (fun q : (E3 × ℝ) × ModelE5 ↦
      modelEnergyTwoIntegrand α u f q.1 q.2)
      ((cubeScaleMeasure.restrict (Set.univ ×ˢ Set.Ioi (0 : ℝ))).prod volume)) :
    Integrable (fun w : ScratchModelEnergyOuter ↦
      (∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
        (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2) *
        (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2)
      (((volume : Measure ℝ).prod volume).prod
        ((volume : Measure ℝ).prod
          (((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
            (Set.Ioi (0 : ℝ))))) := by
  let ν : Measure ℝ :=
    ((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
      (Set.Ioi (0 : ℝ))
  let G : (E3 × ℝ) × ModelE5 → ℝ := fun q ↦
    modelEnergyTwoIntegrand α u f q.1 q.2
  let μouter : Measure ScratchModelEnergyOuter :=
    ((volume : Measure ℝ).prod volume).prod ((volume : Measure ℝ).prod ν)
  let μinner : Measure ScratchModelEnergyInner :=
    ((volume : Measure ℝ).prod volume).prod
      ((volume : Measure ℝ).prod ((volume : Measure ℝ).prod volume))
  have hjoint' : Integrable G (((volume : Measure E3).prod ν).prod volume) := by
    simpa only [G, ν, scratch_cubeScaleMeasure_restrict_global_eq] using hjoint
  have htrans : Integrable (fun w : ScratchModelEnergyOuter × ScratchModelEnergyInner ↦
      G (modelEnergyCoordinateReorder.symm w)) (μouter.prod μinner) := by
    have hmp := modelEnergyCoordinateReorder_measurePreserving_scale ν
    exact (MeasurePreserving.symm modelEnergyCoordinateReorder hmp).integrable_comp_of_integrable
      hjoint'
  let K : ScratchModelEnergyOuter → ℝ := fun w ↦
    ∫ v : ScratchModelEnergyInner,
      G (modelEnergyCoordinateReorder.symm (w, v)) ∂μinner
  have hK : Integrable K μouter := htrans.integral_prod_left
  have htν : ∀ᵐ t : ℝ ∂ν, 0 < t := by
    dsimp [ν]
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    exact ht
  have htpt : ∀ᵐ pt : ℝ × ℝ ∂((volume : Measure ℝ).prod ν), 0 < pt.2 := by
    rw [Measure.ae_prod_iff_ae_ae]
    · filter_upwards [] with p₂
      exact htν
    · exact measurableSet_Ioi.preimage measurable_snd
  have htouter : ∀ᵐ w : ScratchModelEnergyOuter ∂μouter, 0 < w.2.2 := by
    rw [Measure.ae_prod_iff_ae_ae]
    · filter_upwards [] with x
      exact htpt
    · exact measurableSet_Ioi.preimage (measurable_snd.comp measurable_snd)
  let H : ScratchModelEnergyOuter → ℝ := fun w ↦
    (∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
      (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2) *
        (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2
  have hKH : K =ᵐ[μouter] H := by
    filter_upwards [htrans.prod_right_ae, htouter] with w hw ht
    dsimp [K, H]
    calc
      (∫ v : ScratchModelEnergyInner,
        G (modelEnergyCoordinateReorder.symm (w, v)) ∂μinner) =
          ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
            G (modelEnergyCoordinateReorder.symm
              (w, ((p₀, p₁), (y₁, (y₂, r))))) := by
              exact integral_ScratchModelEnergyInner_eq_nested _ hw
      _ = ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
          (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2 *
            modelEnergyDensityReordered α u w.1.1 w.1.2 w.2.2
              p₀ p₁ y₁ y₂ r := by
            apply integral_congr_ae
            filter_upwards [] with p₀
            apply integral_congr_ae
            filter_upwards [] with p₁
            apply integral_congr_ae
            filter_upwards [] with y₁
            apply integral_congr_ae
            filter_upwards [] with y₂
            apply integral_congr_ae
            filter_upwards [] with r
            rcases w with ⟨⟨x₁, x₂⟩, ⟨p₂, t⟩⟩
            exact modelEnergyTwoIntegrand_reorder_symm
              α u f x₁ x₂ p₂ t p₀ p₁ y₁ y₂ r
      _ = (∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
          (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2) *
          (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2 := by
            rcases w with ⟨⟨x₁, x₂⟩, ⟨p₂, t⟩⟩
            exact modelEnergy_reordered_inner_scalar_reduction
              α u f x₁ x₂ p₂ t ht
  simpa only [H, ν] using hK.congr hKH

/-- After the harmless scalar variables have been removed, the remaining
positive-scale integral is the global third-coordinate square function.
The two hypotheses are precisely the product-Fubini condition and the
fixed-fiber translation condition used by the scalar reductions. -/
theorem scratch_reordered_scalar_energy_eq_global_L2
    (α : Anisotropy) (u : E3) (f : SchwartzMap E3 ℝ)
    (hscalar : Integrable (fun w : ScratchModelEnergyOuter ↦
      (∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
        (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2) *
        (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2)
      (((volume : Measure ℝ).prod volume).prod
        ((volume : Measure ℝ).prod
          (((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
            (Set.Ioi (0 : ℝ))))))
    (hpr : ∀ (x₁ x₂ t : ℝ), 0 < t → Integrable (fun z : ℝ × ℝ ↦
      (modelSecondFiberReduced α f x₁ x₂ z.1 t z.2) ^ 2 *
        |conePsiPhysicalReal (z.2 + u 2)|)
      ((volume : Measure ℝ).prod volume)) :
    (∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
      ∫ t : ℝ in Set.Ioi (0 : ℝ),
        ((∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
          (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2) *
          (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2)
        ∂((volume : Measure ℝ).withDensity cubeScaleDensity)) =
      (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2 *
        conePsiPhysicalRealL1 * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ x : E3, f x ^ 2 := by
  let ν : Measure ℝ :=
    ((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
      (Set.Ioi (0 : ℝ))
  let A : ℝ := (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2
  let P : ℝ := conePsiPhysicalRealL1
  let Q : ℝ → ℝ → ℝ → ℝ := fun x₁ x₂ t ↦
    ∫ q : ℝ, (∫ v : ℝ, f (modelPoint x₁ x₂ v) *
      gaussianDerivAt (t ^ α.weight 2) q v) ^ 2
  let H : ScratchModelEnergyOuter → ℝ := fun w ↦
    A * ∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
      (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2
  have hH : Integrable H
      (((volume : Measure ℝ).prod volume).prod
        ((volume : Measure ℝ).prod ν)) := by
    apply hscalar.congr
    filter_upwards [] with w
    dsimp [H, A]
    ring
  have hswap (x : ℝ × ℝ)
      (hx : Integrable (fun pt : ℝ × ℝ ↦ H (x, pt))
        ((volume : Measure ℝ).prod ν)) :
      (∫ p₂ : ℝ, ∫ t : ℝ, H (x, (p₂, t)) ∂ν) =
        ∫ t : ℝ, (∫ p₂ : ℝ, H (x, (p₂, t))) ∂ν := by
    have hx' : Integrable (Function.uncurry
        (fun p₂ : ℝ ↦ fun t : ℝ ↦ H (x, (p₂, t))))
        ((volume : Measure ℝ).prod ν) := by
      apply hx.congr
      filter_upwards [] with pt
      rcases pt with ⟨p₂, t⟩
      rfl
    simpa only using (integral_integral_swap hx')
  let J : ℝ × ℝ → ℝ := fun x ↦
    ∫ t : ℝ, (∫ p₂ : ℝ, H (x, (p₂, t))) ∂ν
  have hJ : Integrable J ((volume : Measure ℝ).prod volume) := by
    have hleft := hH.integral_prod_left
    apply hleft.congr
    filter_upwards [hH.prod_right_ae] with x hx
    calc
      (∫ pt : ℝ × ℝ, H (x, pt) ∂((volume : Measure ℝ).prod ν)) =
          ∫ p₂ : ℝ, ∫ t : ℝ, H (x, (p₂, t)) ∂ν :=
        integral_prod _ hx
      _ = J x := hswap x hx
  have hJvalue (x₁ x₂ : ℝ) :
      J (x₁, x₂) =
        A * P * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ v : ℝ, f (modelPoint x₁ x₂ v) ^ 2 := by
    dsimp [J, ν]
    change (∫ t : ℝ in Set.Ioi (0 : ℝ),
      (∫ p₂ : ℝ, H ((x₁, x₂), (p₂, t)))
      ∂((volume : Measure ℝ).withDensity cubeScaleDensity)) = _
    calc
      (∫ t : ℝ in Set.Ioi (0 : ℝ),
        (∫ p₂ : ℝ, H ((x₁, x₂), (p₂, t)))
        ∂((volume : Measure ℝ).withDensity cubeScaleDensity)) =
          ∫ t : ℝ in Set.Ioi (0 : ℝ), A * (P * Q x₁ x₂ t)
            ∂((volume : Measure ℝ).withDensity cubeScaleDensity) := by
            apply setIntegral_congr_fun measurableSet_Ioi
            intro t ht
            dsimp [H]
            rw [integral_const_mul]
            calc
              A * ∫ p₂ : ℝ, ∫ r : ℝ,
                |conePsiPhysicalReal (r + u 2)| *
                  (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 =
                  A * ∫ p₂ : ℝ, ∫ r : ℝ,
                    (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
                      |conePsiPhysicalReal (r + u 2)| := by
                        congr 1
                        apply integral_congr_ae
                        filter_upwards [] with p₂
                        apply integral_congr_ae
                        filter_upwards [] with r
                        ring
              _ = A * (P * Q x₁ x₂ t) := by
                    rw [show (∫ p₂ : ℝ, ∫ r : ℝ,
                      (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
                        |conePsiPhysicalReal (r + u 2)|) = P * Q x₁ x₂ t by
                      dsimp [P, Q]
                      exact modelSecondFiberReduced_p2_r_reduction α u f x₁ x₂ t
                        (hpr x₁ x₂ t ht)]
      _ = ∫ t : ℝ in Set.Ioi (0 : ℝ),
          (A * P * Q x₁ x₂ t)
            ∂((volume : Measure ℝ).withDensity cubeScaleDensity) := by
            apply setIntegral_congr_fun measurableSet_Ioi
            intro t ht
            ring
      _ = ∫ t : ℝ in Set.Ioi (0 : ℝ),
          (A * P * Q x₁ x₂ t) / t := by
            exact integral_Ioi_withDensity_cubeScaleDensity_eq
              (fun t : ℝ ↦ A * P * Q x₁ x₂ t)
      _ = A * P * ∫ t : ℝ in Set.Ioi (0 : ℝ), Q x₁ x₂ t / t := by
            rw [show (fun t : ℝ ↦ (A * P * Q x₁ x₂ t) / t) =
              fun t : ℝ ↦ (A * P) * (Q x₁ x₂ t / t) by
                funext t
                ring,
              integral_const_mul]
      _ = A * P * ((Real.pi / (α.weight 2 : ℝ)) *
          ∫ v : ℝ, f (modelPoint x₁ x₂ v) ^ 2) := by
            rw [show (∫ t : ℝ in Set.Ioi (0 : ℝ), Q x₁ x₂ t / t) =
              ∫ t : ℝ in Set.Ioi (0 : ℝ), ∫ q : ℝ,
                (∫ v : ℝ, f (modelPoint x₁ x₂ v) *
                  gaussianDerivAt (t ^ α.weight 2) q v) ^ 2 / t by
                apply setIntegral_congr_fun measurableSet_Ioi
                intro t ht
                dsimp [Q]
                rw [integral_div],
              modelThird_square_function_of_real_schwartz α f x₁ x₂]
      _ = A * P * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ v : ℝ, f (modelPoint x₁ x₂ v) ^ 2 := by ring
  have hfsq : Integrable (fun x : E3 ↦ f x ^ 2) := by
    exact (memLp_two_iff_integrable_sq
      f.continuous.aestronglyMeasurable).mp (f.memLp 2 volume)
  calc
    (∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
      ∫ t : ℝ in Set.Ioi (0 : ℝ),
        ((∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
          (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2) *
          (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2)
        ∂((volume : Measure ℝ).withDensity cubeScaleDensity)) =
        ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
          ∫ t : ℝ in Set.Ioi (0 : ℝ),
            H ((x₁, x₂), (p₂, t))
            ∂((volume : Measure ℝ).withDensity cubeScaleDensity) := by
            dsimp [H, A, ν]
            apply integral_congr_ae
            filter_upwards [] with x₁
            apply integral_congr_ae
            filter_upwards [] with x₂
            apply integral_congr_ae
            filter_upwards [] with p₂
            apply integral_congr_ae
            filter_upwards [] with t
            ring
    _ = ∫ w : ScratchModelEnergyOuter, H w
        ∂(((volume : Measure ℝ).prod volume).prod
          ((volume : Measure ℝ).prod ν)) := by
          exact (integral_ScratchModelEnergyOuter_eq_nested ν H hH).symm
    _ = ∫ x : ℝ × ℝ, ∫ pt : ℝ × ℝ, H (x, pt)
        ∂((volume : Measure ℝ).prod ν) := by
          exact integral_prod _ hH
    _ = ∫ x : ℝ × ℝ, J x := by
          apply integral_congr_ae
          filter_upwards [hH.prod_right_ae] with x hx
          calc
            (∫ pt : ℝ × ℝ, H (x, pt)
              ∂((volume : Measure ℝ).prod ν)) =
                ∫ p₂ : ℝ, ∫ t : ℝ, H (x, (p₂, t)) ∂ν :=
              integral_prod _ hx
            _ = J x := hswap x hx
    _ = ∫ x₁ : ℝ, ∫ x₂ : ℝ, J (x₁, x₂) := by
          exact integral_prod _ hJ
    _ = ∫ x₁ : ℝ, ∫ x₂ : ℝ,
        A * P * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ v : ℝ, f (modelPoint x₁ x₂ v) ^ 2 := by
          apply integral_congr_ae
          filter_upwards [] with x₁
          apply integral_congr_ae
          filter_upwards [] with x₂
          exact hJvalue x₁ x₂
    _ = A * P * (Real.pi / (α.weight 2 : ℝ)) *
        ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ v : ℝ,
          f (modelPoint x₁ x₂ v) ^ 2 := by
          let C : ℝ := A * P * (Real.pi / (α.weight 2 : ℝ))
          calc
            (∫ x₁ : ℝ, ∫ x₂ : ℝ,
              A * P * (Real.pi / (α.weight 2 : ℝ)) *
                ∫ v : ℝ, f (modelPoint x₁ x₂ v) ^ 2) =
                ∫ x₁ : ℝ, ∫ x₂ : ℝ,
                  C * ∫ v : ℝ, f (modelPoint x₁ x₂ v) ^ 2 := by
                    apply integral_congr_ae
                    filter_upwards [] with x₁
                    apply integral_congr_ae
                    filter_upwards [] with x₂
                    rfl
            _ = ∫ x₁ : ℝ, C * (∫ x₂ : ℝ, ∫ v : ℝ,
                f (modelPoint x₁ x₂ v) ^ 2) := by
                  apply integral_congr_ae
                  filter_upwards [] with x₁
                  rw [integral_const_mul]
            _ = C * ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ v : ℝ,
                f (modelPoint x₁ x₂ v) ^ 2 := by
                  rw [integral_const_mul]
            _ = A * P * (Real.pi / (α.weight 2 : ℝ)) *
                ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ v : ℝ,
                  f (modelPoint x₁ x₂ v) ^ 2 := by
                    rfl
    _ = A * P * (Real.pi / (α.weight 2 : ℝ)) *
        ∫ x : E3, f x ^ 2 := by
          rw [scratch_integral_modelPoint_sq_eq f hfsq]
    _ = (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2 *
        conePsiPhysicalRealL1 * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ x : E3, f x ^ 2 := by
          rfl

/-- Conditional full form of the blueprint's global second-energy identity
for a real Schwartz input.  The hypotheses are exactly the two unresolved
global integrability discharges: the original joint density and the scalar
post-Tonelli `(x₁,x₂,p₂,t)` density. -/
theorem scratch_modelEnergyTwoOn_global_eq_of_real_schwartz
    (α : Anisotropy) (u : E3) (f : SchwartzMap E3 ℝ)
    (hjoint : Integrable (fun q : (E3 × ℝ) × ModelE5 ↦
      modelEnergyTwoIntegrand α u f q.1 q.2)
      ((cubeScaleMeasure.restrict (Set.univ ×ˢ Set.Ioi (0 : ℝ))).prod volume))
    (hscalar : Integrable (fun w : ScratchModelEnergyOuter ↦
      (∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
        (modelSecondFiberReduced α f w.1.1 w.1.2 w.2.1 w.2.2 r) ^ 2) *
        (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2)
      (((volume : Measure ℝ).prod volume).prod
        ((volume : Measure ℝ).prod
          (((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
            (Set.Ioi (0 : ℝ))))))
    (hpr : ∀ (x₁ x₂ t : ℝ), 0 < t → Integrable (fun z : ℝ × ℝ ↦
      (modelSecondFiberReduced α f x₁ x₂ z.1 t z.2) ^ 2 *
        |conePsiPhysicalReal (z.2 + u 2)|)
      ((volume : Measure ℝ).prod volume)) :
    modelEnergyTwoOn α (Set.univ ×ˢ Set.Ioi (0 : ℝ)) u f =
      (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2 *
        conePsiPhysicalRealL1 * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ x : E3, f x ^ 2 := by
  calc
    modelEnergyTwoOn α (Set.univ ×ˢ Set.Ioi (0 : ℝ)) u f =
      ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
        ∫ t : ℝ in Set.Ioi (0 : ℝ),
          (∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
            (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
              modelEnergyDensityReordered α u x₁ x₂ t p₀ p₁ y₁ y₂ r)
          ∂((volume : Measure ℝ).withDensity cubeScaleDensity) :=
      scratch_modelEnergyTwoOn_eq_reordered_nested α u f hjoint
    _ = ∫ x₁ : ℝ, ∫ x₂ : ℝ, ∫ p₂ : ℝ,
        ∫ t : ℝ in Set.Ioi (0 : ℝ),
          ((∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
            (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2) *
            (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2)
          ∂((volume : Measure ℝ).withDensity cubeScaleDensity) := by
            apply integral_congr_ae
            filter_upwards [] with x₁
            apply integral_congr_ae
            filter_upwards [] with x₂
            apply integral_congr_ae
            filter_upwards [] with p₂
            apply setIntegral_congr_fun measurableSet_Ioi
            intro t ht
            exact modelEnergy_reordered_inner_scalar_reduction
              α u f x₁ x₂ p₂ t ht
    _ = (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2 *
        conePsiPhysicalRealL1 * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ x : E3, f x ^ 2 :=
      scratch_reordered_scalar_energy_eq_global_L2 α u f hscalar hpr

/-- Source-facing conditional global second-energy identity.  All Tonelli
and scalar-mass side conditions are discharged from `hjoint`; only the
fixed-fiber translation integrability remains as an explicit analytic
hypothesis. -/
theorem scratch_modelEnergyTwoOn_global_eq_of_joint_and_fixedFiber
    (α : Anisotropy) (u : E3) (f : SchwartzMap E3 ℝ)
    (hjoint : Integrable (fun q : (E3 × ℝ) × ModelE5 ↦
      modelEnergyTwoIntegrand α u f q.1 q.2)
      ((cubeScaleMeasure.restrict (Set.univ ×ˢ Set.Ioi (0 : ℝ))).prod volume))
    (hpr : ∀ (x₁ x₂ t : ℝ), 0 < t → Integrable (fun z : ℝ × ℝ ↦
      (modelSecondFiberReduced α f x₁ x₂ z.1 t z.2) ^ 2 *
        |conePsiPhysicalReal (z.2 + u 2)|)
      ((volume : Measure ℝ).prod volume)) :
    modelEnergyTwoOn α (Set.univ ×ˢ Set.Ioi (0 : ℝ)) u f =
      (∫ z : ℝ, |conePhiPhysicalReal z|) ^ 2 *
        conePsiPhysicalRealL1 * (Real.pi / (α.weight 2 : ℝ)) *
          ∫ x : E3, f x ^ 2 := by
  exact scratch_modelEnergyTwoOn_global_eq_of_real_schwartz α u f hjoint
    (scratch_integrable_reordered_scalar_of_joint α u f hjoint) hpr

end

end Auto.Twisted
