/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto.Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators ENNReal RealInnerProductSpace Topology

noncomputable section

/-- The `p₂,r` scalar calculation in the source order.  Joint integrability
is exactly the Fubini condition needed to exchange these two variables. -/
theorem scratch_integral_square_shifted_with_conePsi_of_integrable
    (B : ℝ → ℝ) (s u : ℝ)
    (hB : Integrable (fun z : ℝ × ℝ ↦
      B (z.1 + z.2 * s) ^ 2 * |conePsiPhysicalReal (z.2 + u)|)
      ((volume : Measure ℝ).prod volume)) :
    (∫ p : ℝ, ∫ r : ℝ,
      B (p + r * s) ^ 2 * |conePsiPhysicalReal (r + u)|) =
      conePsiPhysicalRealL1 * ∫ q : ℝ, B q ^ 2 := by
  calc
    (∫ p : ℝ, ∫ r : ℝ,
      B (p + r * s) ^ 2 * |conePsiPhysicalReal (r + u)|) =
        ∫ r : ℝ, ∫ p : ℝ,
          B (p + r * s) ^ 2 * |conePsiPhysicalReal (r + u)| := by
          exact integral_integral_swap hB
    _ = ∫ r : ℝ, |conePsiPhysicalReal (r + u)| *
        (∫ p : ℝ, B (p + r * s) ^ 2) := by
          apply integral_congr_ae
          filter_upwards [] with r
          rw [show (fun p : ℝ ↦
            B (p + r * s) ^ 2 * |conePsiPhysicalReal (r + u)|) =
              fun p : ℝ ↦ B (p + r * s) ^ 2 *
                |conePsiPhysicalReal (r + u)| by rfl,
            integral_mul_const]
          ring
    _ = conePsiPhysicalRealL1 * ∫ q : ℝ, B q ^ 2 :=
      integral_shifted_square_with_conePsi B s u

/-- The four scalar `φ`/Gaussian variables can be integrated while retaining
an arbitrary innermost scalar tail.  This is the literal `p₀,p₁,y₁,y₂,r`
order of the reordered model energy. -/
theorem scratch_integral_two_modelPhi_gaussian_pairs_source_order_with_tail
    {s₀ s₁ : ℝ} (hs₀ : 0 < s₀) (hs₁ : 0 < s₁)
    (c₀ c₁ x₀ x₁ : ℝ) (H : ℝ → ℝ) :
    (∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₀ : ℝ, ∫ y₁ : ℝ, ∫ r : ℝ,
      |modelPhiAt s₀ (p₀ + c₀) x₀| * gaussianAt s₀ p₀ y₀ *
        |modelPhiAt s₁ (p₁ + c₁) x₁| * gaussianAt s₁ p₁ y₁ * H r) =
      (∫ r : ℝ, H r) * (∫ w : ℝ, |conePhiPhysicalReal w|) ^ 2 := by
  let R : ℝ := ∫ r : ℝ, H r
  calc
    (∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₀ : ℝ, ∫ y₁ : ℝ, ∫ r : ℝ,
      |modelPhiAt s₀ (p₀ + c₀) x₀| * gaussianAt s₀ p₀ y₀ *
        |modelPhiAt s₁ (p₁ + c₁) x₁| * gaussianAt s₁ p₁ y₁ * H r) =
        ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₀ : ℝ, ∫ y₁ : ℝ,
          |modelPhiAt s₀ (p₀ + c₀) x₀| * gaussianAt s₀ p₀ y₀ *
            |modelPhiAt s₁ (p₁ + c₁) x₁| * gaussianAt s₁ p₁ y₁ * R := by
          apply integral_congr_ae
          filter_upwards [] with p₀
          apply integral_congr_ae
          filter_upwards [] with p₁
          apply integral_congr_ae
          filter_upwards [] with y₀
          apply integral_congr_ae
          filter_upwards [] with y₁
          rw [show (fun r : ℝ ↦
            |modelPhiAt s₀ (p₀ + c₀) x₀| * gaussianAt s₀ p₀ y₀ *
              |modelPhiAt s₁ (p₁ + c₁) x₁| * gaussianAt s₁ p₁ y₁ * H r) =
              fun r : ℝ ↦
                (|modelPhiAt s₀ (p₀ + c₀) x₀| * gaussianAt s₀ p₀ y₀ *
                  |modelPhiAt s₁ (p₁ + c₁) x₁| * gaussianAt s₁ p₁ y₁) * H r by
                funext r
                ring,
            integral_const_mul]
    _ = ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₀ : ℝ, ∫ y₁ : ℝ,
        R * |modelPhiAt s₀ (p₀ + c₀) x₀| * gaussianAt s₀ p₀ y₀ *
          |modelPhiAt s₁ (p₁ + c₁) x₁| * gaussianAt s₁ p₁ y₁ := by
          apply integral_congr_ae
          filter_upwards [] with p₀
          apply integral_congr_ae
          filter_upwards [] with p₁
          apply integral_congr_ae
          filter_upwards [] with y₀
          apply integral_congr_ae
          filter_upwards [] with y₁
          ring
    _ = R * (∫ w : ℝ, |conePhiPhysicalReal w|) ^ 2 :=
      integral_two_modelPhi_gaussian_pairs_source_order hs₀ hs₁ c₀ c₁ x₀ x₁ R
    _ = (∫ r : ℝ, H r) * (∫ w : ℝ, |conePhiPhysicalReal w|) ^ 2 := by
      rfl

/-- The inner scalar variables in the reordered second-energy integrand
collapse to the remaining translated third-coordinate square function. -/
theorem scratch_modelEnergy_reordered_inner_scalar_reduction
    (α : Anisotropy) (u : E3) (f : E3 → ℝ)
    (x₁ x₂ p₂ t : ℝ) (ht : 0 < t) :
    (∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
      (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
        modelEnergyDensityReordered α u x₁ x₂ t p₀ p₁ y₁ y₂ r) =
      (∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
        (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2) *
        (∫ w : ℝ, |conePhiPhysicalReal w|) ^ 2 := by
  let s₀ : ℝ := t ^ α.weight 0
  let s₁ : ℝ := t ^ α.weight 1
  have hs₀ : 0 < s₀ := by
    dsimp [s₀]
    exact pow_pos ht _
  have hs₁ : 0 < s₁ := by
    dsimp [s₁]
    exact pow_pos ht _
  calc
    (∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
      (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
        modelEnergyDensityReordered α u x₁ x₂ t p₀ p₁ y₁ y₂ r) =
        ∫ p₀ : ℝ, ∫ p₁ : ℝ, ∫ y₁ : ℝ, ∫ y₂ : ℝ, ∫ r : ℝ,
          |modelPhiAt s₀ (p₀ + s₀ * u 0) x₁| * gaussianAt s₀ p₀ y₁ *
            |modelPhiAt s₁ (p₁ + s₁ * u 1) x₂| * gaussianAt s₁ p₁ y₂ *
              (|conePsiPhysicalReal (r + u 2)| *
                (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2) := by
          apply integral_congr_ae
          filter_upwards [] with p₀
          apply integral_congr_ae
          filter_upwards [] with p₁
          apply integral_congr_ae
          filter_upwards [] with y₁
          apply integral_congr_ae
          filter_upwards [] with y₂
          apply integral_congr_ae
          filter_upwards [] with r
          dsimp [s₀, s₁]
          unfold modelEnergyDensityReordered
          ring
    _ = (∫ r : ℝ, |conePsiPhysicalReal (r + u 2)| *
        (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2) *
        (∫ w : ℝ, |conePhiPhysicalReal w|) ^ 2 := by
          exact scratch_integral_two_modelPhi_gaussian_pairs_source_order_with_tail
            hs₀ hs₁ (s₀ * u 0) (s₁ * u 1) x₁ x₂
            (fun r : ℝ ↦ |conePsiPhysicalReal (r + u 2)| *
              (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2)

/-- After the scalar inner variables have been removed, Fubini in `(p₂,r)`
and translation reduce the remainder to the centered one-dimensional fiber
square function. -/
theorem scratch_modelSecondFiberReduced_p2_r_reduction
    (α : Anisotropy) (u : E3) (f : E3 → ℝ) (x₁ x₂ t : ℝ)
    (hpr : Integrable (fun z : ℝ × ℝ ↦
      (modelSecondFiberReduced α f x₁ x₂ z.1 t z.2) ^ 2 *
        |conePsiPhysicalReal (z.2 + u 2)|)
      ((volume : Measure ℝ).prod volume)) :
    (∫ p₂ : ℝ, ∫ r : ℝ,
      (modelSecondFiberReduced α f x₁ x₂ p₂ t r) ^ 2 *
        |conePsiPhysicalReal (r + u 2)|) =
      conePsiPhysicalRealL1 * ∫ q : ℝ,
        (∫ v : ℝ, f (modelPoint x₁ x₂ v) *
          gaussianDerivAt (t ^ α.weight 2) q v) ^ 2 := by
  let B : ℝ → ℝ := fun q ↦ ∫ v : ℝ,
    f (modelPoint x₁ x₂ v) * gaussianDerivAt (t ^ α.weight 2) q v
  have hB : Integrable (fun z : ℝ × ℝ ↦
      B (z.1 + z.2 * t ^ α.weight 2) ^ 2 *
        |conePsiPhysicalReal (z.2 + u 2)|)
      ((volume : Measure ℝ).prod volume) := by
    apply hpr.congr
    filter_upwards [] with z
    rcases z with ⟨p₂, r⟩
    rfl
  simpa only [B, modelSecondFiberReduced] using
    (scratch_integral_square_shifted_with_conePsi_of_integrable B
      (t ^ α.weight 2) (u 2) hB)

end

end Auto.Twisted
