/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## The torus coefficient bounds, with the constant hoisted

Source: `lem:fourier_series`.  Each coefficient bound passes a raw derivative
envelope through the integration-by-parts estimate, so hoisting the constant in
those envelopes hoists it here as well.
-/

theorem exists_uniform_mFourierCoeff_unitTorusLocalizedSymbol_bound_of_anisotropy
    (α : Anisotropy) (i : Fin 3) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (M : ℝ) (m : E3 → ℂ),
      Anisotropy.IsAnisotropicMultiplier α M m →
      ∀ t : ℝ, 0 < t → ∀ ν : Fin 3 → ℤ,
        ‖UnitAddTorus.mFourierCoeff (unitTorusLocalizedSymbol α m i t) ν‖ ≤ C * M := by
  rcases exists_uniform_raw_scaled_uniform_bound_of_anisotropy α i with ⟨C, hC, hraw⟩
  refine ⟨C, hC, ?_⟩
  intro M m hm t ht ν
  rw [scratch_mFourierCoeff_unitTorusLocalizedSymbol_eq_nestedRaw α M m hm i ht ν]
  apply scratch_norm_nestedRawUnitFourierCoeff_le_of_first_bound
    α m i t ν (C * M) (mul_nonneg hC hm.nonneg)
  intro y z
  apply scratch_norm_fourierCoeffOn_le_of_norm_le
    (by norm_num : -(1 / 2 : ℝ) < 1 / 2) (ν 0)
  intro x _
  exact hraw M m hm t ht x y z

theorem exists_uniform_mFourierCoeff_first_110_decay_of_anisotropy
    (α : Anisotropy) (i : Fin 3) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (M : ℝ) (m : E3 → ℂ),
      Anisotropy.IsAnisotropicMultiplier α M m →
      ∀ t : ℝ, 0 < t → ∀ ν : Fin 3 → ℤ, ν 0 ≠ 0 →
        ‖UnitAddTorus.mFourierCoeff (unitTorusLocalizedSymbol α m i t) ν‖ ≤
          (2 * Real.pi * |((ν 0 : ℤ) : ℝ)|)⁻¹ ^ 110 * (C * M) := by
  rcases exists_uniform_raw_first_scaled_110_deriv_bound_of_anisotropy α i with
    ⟨C, hC, hraw⟩
  refine ⟨C, hC, ?_⟩
  intro M m hm t ht ν hν
  apply scratch_norm_mFourierCoeff_unitTorusLocalizedSymbol_le_of_first_110_bound
    α M m hm i ht ν hν (C * M) (mul_nonneg hC hm.nonneg)
  intro x y z
  exact hraw M m hm t ht x y z

theorem exists_uniform_mFourierCoeff_middle_110_decay_of_anisotropy
    (α : Anisotropy) (i : Fin 3) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (M : ℝ) (m : E3 → ℂ),
      Anisotropy.IsAnisotropicMultiplier α M m →
      ∀ t : ℝ, 0 < t → ∀ ν : Fin 3 → ℤ, ν 1 ≠ 0 →
        ‖UnitAddTorus.mFourierCoeff (unitTorusLocalizedSymbol α m i t) ν‖ ≤
          (2 * Real.pi * |((ν 1 : ℤ) : ℝ)|)⁻¹ ^ 110 * (C * M) := by
  rcases exists_uniform_raw_middle_scaled_110_deriv_bound_of_anisotropy α i with
    ⟨C, hC, hraw⟩
  refine ⟨C, hC, ?_⟩
  intro M m hm t ht ν hν
  apply scratch_norm_mFourierCoeff_unitTorusLocalizedSymbol_le_of_middle_110_bound
    α M m hm i ht ν hν (C * M) (mul_nonneg hC hm.nonneg)
  intro x y z
  exact hraw M m hm t ht x y z

theorem exists_uniform_mFourierCoeff_last_110_decay_of_anisotropy
    (α : Anisotropy) (i : Fin 3) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (M : ℝ) (m : E3 → ℂ),
      Anisotropy.IsAnisotropicMultiplier α M m →
      ∀ t : ℝ, 0 < t → ∀ ν : Fin 3 → ℤ, ν 2 ≠ 0 →
        ‖UnitAddTorus.mFourierCoeff (unitTorusLocalizedSymbol α m i t) ν‖ ≤
          (2 * Real.pi * |((ν 2 : ℤ) : ℝ)|)⁻¹ ^ 110 * (C * M) := by
  rcases exists_uniform_raw_last_scaled_110_deriv_bound_of_anisotropy α i with
    ⟨C, hC, hraw⟩
  refine ⟨C, hC, ?_⟩
  intro M m hm t ht ν hν
  apply scratch_norm_mFourierCoeff_unitTorusLocalizedSymbol_le_of_last_110_bound
    α M m hm i ht ν hν (C * M) (mul_nonneg hC hm.nonneg)
  intro x y z
  exact hraw M m hm t ht x y z

end
end Twisted
end Auto
