/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators ENNReal RealInnerProductSpace Topology

noncomputable section

/-- A real Schwartz tuple, viewed as the bounded continuous input required by
the finite active stopping-forest theorem. -/
abbrev ScratchInitialModelSchwartzInput := Fin 4 → SchwartzMap E3 ℝ

noncomputable def scratchInitialModelRealInput
    (F : ScratchInitialModelSchwartzInput) : ModelRealInput :=
  fun j ↦ F j

/-- The continuity hypotheses in the finite forest theorem are automatic for
real Schwartz inputs. -/
theorem scratch_initialModelRealInput_continuous
    (F : ScratchInitialModelSchwartzInput) :
    ∀ j : Fin 4, Continuous (scratchInitialModelRealInput F j) := by
  intro j
  exact (F j).continuous

/-- The uniform boundedness hypotheses in the finite forest theorem are
automatic for real Schwartz inputs. -/
theorem scratch_initialModelRealInput_bounded
    (F : ScratchInitialModelSchwartzInput) :
    ∀ j : Fin 4, ∃ B : ℝ, 0 ≤ B ∧
      ∀ y : E3, |scratchInitialModelRealInput F j y| ≤ B := by
  intro j
  refine ⟨SchwartzMap.seminorm ℝ 0 0 (F j), ?_, ?_⟩
  · exact (norm_nonneg ((F j) 0)).trans
      (SchwartzMap.norm_le_seminorm ℝ (F j) (0 : E3))
  · intro y
    simpa only [scratchInitialModelRealInput, Real.norm_eq_abs] using
      (SchwartzMap.norm_le_seminorm ℝ (F j) y)

/-- The four scalar dyadic level sums left by the finite stopping argument. -/
noncomputable def scratchSourceStoppingCoordinateEnvelope
    (α : Anisotropy) (S : BoxCollection α) (f : ModelRealInput)
    (q σ : Fin 4 → ℝ)
    (hpos : ∀ r ∈ S, ∀ j,
      0 < stoppingData α S (sourceStoppingExponent j) (f j) r) : ℝ :=
  ∑ j : Fin 4,
    ∑ m ∈ (activeStoppingLevels α S sourceStoppingExponent f hpos).filter
        (fun n ↦ sourceStoppingDominantIndex q σ n = j) |>.image
          (fun n ↦ n j),
      sourceStoppingDominantFiberEnvelope q σ j m *
        (volume (sourceStoppingMaximalLevelSetAt α f j m)).toReal

/-- Coordinatewise finiteness of the scalar maximal level regions supplies
the finite-measure hypothesis at the dominant coordinate of every stopping
level. -/
theorem scratch_dominantMaximalLevel_finite_of_coordinateLevel_finite
    (α : Anisotropy) (f : ModelRealInput) (q σ : Fin 4 → ℝ)
    (hfinite : ∀ (j : Fin 4) (m : ℤ),
      volume (sourceStoppingMaximalLevelSetAt α f j m) ≠ ∞) :
    ∀ n : Fin 4 → ℤ,
      volume (sourceStoppingDominantMaximalLevelSet α f q σ n) ≠ ∞ := by
  intro n
  simpa only [sourceStoppingDominantMaximalLevelSet] using
    hfinite (sourceStoppingDominantIndex q σ n)
      (n (sourceStoppingDominantIndex q σ n))

/-- The bounded-continuous active stopping-forest estimate with its
finite-measure condition reduced to the four scalar maximal level families. -/
theorem scratch_activeStoppingForest_bound_of_coordinateLevel_finite
    (α : Anisotropy) (S : BoxCollection α) (hS : IsConvexCollection α S)
    (u : E3) (c : ℝ → ℝ) (f : ModelRealInput)
    (q σ : Fin 4 → ℝ) (hq : ∀ j, 0 < q j)
    (hpos : ∀ r ∈ S, ∀ j,
      0 < stoppingData α S (sourceStoppingExponent j) (f j) r)
    (hcont : ∀ j, Continuous (f j))
    (hbound : ∀ j, ∃ B : ℝ, 0 ≤ B ∧ ∀ y, |f j y| ≤ B)
    (hfinite : ∀ (j : Fin 4) (m : ℤ),
      volume (sourceStoppingMaximalLevelSetAt α f j m) ≠ ∞)
    (hcs : sourceStoppingTreeCS α S hS u c f)
    (henergy : sourceStoppingTreeEnergyIntegrability α S hS u f)
    (hint : Integrable (fun pt : E3 × ℝ ↦
      c pt.2 * (∫ z : ModelE5,
        modelFirstFiber α f pt.1 pt.2 z *
          modelSecondFiber α (f 3) pt.1 pt.2 z *
            modelSignedDensity α u pt.1 pt.2 z))
      (cubeScaleMeasure.restrict (collectionRegion α S))) :
    ∃ C : ℝ, 0 ≤ C ∧
      |expandedModelLocalForm α S u c f| ≤
        C * sourceWeight u ^ 75 *
          scratchSourceStoppingCoordinateEnvelope α S f q σ hpos := by
  rcases activeStoppingForest_form_bound_of_boundedContinuous
    α S hS u c f q σ hq hpos hcont hbound
      (scratch_dominantMaximalLevel_finite_of_coordinateLevel_finite
        α f q σ hfinite) hcs henergy hint with ⟨C, hC, hCbound⟩
  refine ⟨C, hC, ?_⟩
  simpa only [scratchSourceStoppingCoordinateEnvelope] using hCbound

/-- The same active-forest conclusion specialized to real Schwartz input;
continuity and uniform boundedness are discharged here rather than remaining
as terminal assumptions. -/
theorem scratch_activeStoppingForest_bound_of_realSchwartz
    (α : Anisotropy) (S : BoxCollection α) (hS : IsConvexCollection α S)
    (u : E3) (c : ℝ → ℝ) (F : ScratchInitialModelSchwartzInput)
    (q σ : Fin 4 → ℝ) (hq : ∀ j, 0 < q j)
    (hpos : ∀ r ∈ S, ∀ j,
      0 < stoppingData α S (sourceStoppingExponent j)
        (scratchInitialModelRealInput F j) r)
    (hfinite : ∀ (j : Fin 4) (m : ℤ),
      volume (sourceStoppingMaximalLevelSetAt α
        (scratchInitialModelRealInput F) j m) ≠ ∞)
    (hcs : sourceStoppingTreeCS α S hS u c (scratchInitialModelRealInput F))
    (henergy : sourceStoppingTreeEnergyIntegrability α S hS u
      (scratchInitialModelRealInput F))
    (hint : Integrable (fun pt : E3 × ℝ ↦
      c pt.2 * (∫ z : ModelE5,
        modelFirstFiber α (scratchInitialModelRealInput F) pt.1 pt.2 z *
          modelSecondFiber α (scratchInitialModelRealInput F 3) pt.1 pt.2 z *
            modelSignedDensity α u pt.1 pt.2 z))
      (cubeScaleMeasure.restrict (collectionRegion α S))) :
    ∃ C : ℝ, 0 ≤ C ∧
      |expandedModelLocalForm α S u c (scratchInitialModelRealInput F)| ≤
        C * sourceWeight u ^ 75 *
          scratchSourceStoppingCoordinateEnvelope α S
            (scratchInitialModelRealInput F) q σ hpos := by
  exact scratch_activeStoppingForest_bound_of_coordinateLevel_finite
    α S hS u c (scratchInitialModelRealInput F) q σ hq hpos
    (scratch_initialModelRealInput_continuous F)
    (scratch_initialModelRealInput_bounded F) hfinite hcs henergy hint

/-- The exact distributional interface remaining after the finite stopping
argument.  A maximal-function proof supplies this inequality with the desired
product of `L^p` norms as `W`. -/
theorem scratch_initialModel_bound_of_coordinateEnvelope_bound
    (α : Anisotropy) (S : BoxCollection α) (hS : IsConvexCollection α S)
    (u : E3) (c : ℝ → ℝ) (f : ModelRealInput)
    (q σ : Fin 4 → ℝ) (hq : ∀ j, 0 < q j)
    (hpos : ∀ r ∈ S, ∀ j,
      0 < stoppingData α S (sourceStoppingExponent j) (f j) r)
    (hcont : ∀ j, Continuous (f j))
    (hbound : ∀ j, ∃ B : ℝ, 0 ≤ B ∧ ∀ y, |f j y| ≤ B)
    (hfinite : ∀ (j : Fin 4) (m : ℤ),
      volume (sourceStoppingMaximalLevelSetAt α f j m) ≠ ∞)
    (hcs : sourceStoppingTreeCS α S hS u c f)
    (henergy : sourceStoppingTreeEnergyIntegrability α S hS u f)
    (hint : Integrable (fun pt : E3 × ℝ ↦
      c pt.2 * (∫ z : ModelE5,
        modelFirstFiber α f pt.1 pt.2 z *
          modelSecondFiber α (f 3) pt.1 pt.2 z *
            modelSignedDensity α u pt.1 pt.2 z))
      (cubeScaleMeasure.restrict (collectionRegion α S)))
    (W : ℝ)
    (hdistribution : scratchSourceStoppingCoordinateEnvelope α S f q σ hpos ≤ W) :
    ∃ C : ℝ, 0 ≤ C ∧
      |expandedModelLocalForm α S u c f| ≤ C * sourceWeight u ^ 75 * W := by
  rcases scratch_activeStoppingForest_bound_of_coordinateLevel_finite
    α S hS u c f q σ hq hpos hcont hbound hfinite hcs henergy hint with
      ⟨C, hC, hCbound⟩
  refine ⟨C, hC, hCbound.trans ?_⟩
  apply mul_le_mul_of_nonneg_left hdistribution
  exact mul_nonneg hC (pow_nonneg (sourceWeight_nonneg u) _)

/-- The exact bridge from finite active-forest estimates to the literal
full-scale model form.  Its `hlocalization` hypothesis is deliberately only
the finite-scale identification: the global expanded six-variable expression
is never required to be absolutely integrable. -/
theorem scratch_modelFullForm_bound_of_profile_and_truncationForest_bound
    {a C : ℝ} (ha : 0 < a)
    (α : Anisotropy) (u : E3) (c : ℝ → ℝ)
    (F : ModelSchwartzInput) (f : ModelRealInput) (B : ℝ)
    (hc : ∀ t : ℝ, |c t| ≤ 1)
    (hmeas : AEStronglyMeasurable
      (fun t : ℝ ↦ c t * ModelSpatialProfile α u F t)
      (((volume : Measure ℝ).withDensity cubeScaleDensity).restrict
        (Set.Ioi (0 : ℝ))))
    (hprofile : ∀ t : ℝ, 0 < t →
      |ModelSpatialProfile α u F t| ≤ C * min (t ^ a) (t ^ (-a)))
    (hlocalization : ∀ N : ℕ,
      ModelScaleTruncation α u c F N =
        expandedModelLocalForm α (truncationCollection α N) u c f)
    (hforest : ∀ N : ℕ,
      |expandedModelLocalForm α (truncationCollection α N) u c f| ≤ B) :
    |ModelFullForm α u c F| ≤ B := by
  apply modelFullForm_bound_of_profile_and_uniform_truncation_bound
    ha α u c F B hc hmeas hprofile
  intro N
  rw [hlocalization N]
  exact hforest N

end

end Twisted
end Auto
