/- Copyright (c) 2026 Joris Roos. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter TopologicalSpace Topology
open scoped BigOperators ENNReal RealInnerProductSpace

noncomputable section

/-! ## Global initial-model assembly -/

/-- The two-index limit only needs finite-forest bounds for the actual
measurable scale cutoffs of the given coefficient. -/
theorem scratch_modelFullForm_bound_of_restrictedForest
    (α : Anisotropy) (u : E3) (c : ℝ → ℝ) (F : ModelSchwartzInput)
    (B : ℝ) (hcmeas : Measurable c) (hc : ∀ t : ℝ, |c t| ≤ 1)
    (hfull : ∀ N : ℕ, Integrable
      (modelFiberFullyExpandedIntegrand α u c (InitialModelRealInput F))
      (((cubeScaleMeasure.restrict
        (Set.univ ×ˢ truncationScaleSet N)).prod
          (volume : Measure ModelE5)).prod
        ((volume : Measure ℝ).prod volume)))
    (hforest : ∀ N M : ℕ,
      |expandedModelLocalForm α (truncationCollection α M) u
        (RestrictScaleCoefficient c (truncationScaleSet N))
        (InitialModelRealInput F)| ≤ B) :
    |ModelFullForm α u c F| ≤ B := by
  have hscale := tendsto_ModelScaleTruncation_of_realSchwartz
    α u c F hcmeas hc
  have hscaleAbs : Tendsto (fun N ↦ |ModelScaleTruncation α u c F N|)
      atTop (𝓝 |ModelFullForm α u c F|) := by
    exact (continuous_abs.tendsto _).comp hscale
  apply le_of_tendsto hscaleAbs
  filter_upwards [] with N
  apply modelScaleTruncation_bound_of_twoIndex_localization
    α u c F B N
  · exact tendsto_expandedModelLocalForm_twoIndex_of_fullyExpanded_auto
      α u c F N (hfull N)
  · exact hforest N

/-- A fixed uniform finite-forest constant and a scalar stopping-envelope
bound yield the full real Schwartz model estimate. -/
theorem scratch_modelFullForm_bound_of_initial_stoppingEnvelope_of_uniformForest
    (α : Anisotropy) (C : ℝ) (hC : 0 ≤ C)
    (hforest : ∀ S (hS : IsConvexCollection α S) u c
      (F : InitialModelSchwartzInput) (q σ : Fin 4 → ℝ)
      (hq : ∀ j, 0 < q j)
      (hpos : ∀ r ∈ S, ∀ j,
        0 < stoppingData α S (sourceStoppingExponent j)
          (InitialModelRealInput F j) r)
      (hcmeas : Measurable c) (hc : ∀ t, |c t| ≤ 1)
      (hfinite : ∀ (j : Fin 4) (m : ℤ),
        volume (sourceStoppingMaximalLevelSetAt α
          (InitialModelRealInput F) j m) ≠ ∞),
      |expandedModelLocalForm α S u c (InitialModelRealInput F)| ≤
        C * sourceWeight u ^ 75 *
          SourceStoppingCoordinateEnvelope α S (InitialModelRealInput F)
            q σ hpos)
    (u : E3) (c : ℝ → ℝ) (F : InitialModelSchwartzInput)
    (q σ : Fin 4 → ℝ) (W : ℝ)
    (hq : ∀ j, 0 < q j) (hFnonzero : ∀ j, F j ≠ 0)
    (hcmeas : Measurable c) (hc : ∀ t : ℝ, |c t| ≤ 1)
    (hfull : ∀ N : ℕ, Integrable
      (modelFiberFullyExpandedIntegrand α u c (InitialModelRealInput F))
      (((cubeScaleMeasure.restrict
        (Set.univ ×ˢ truncationScaleSet N)).prod
          (volume : Measure ModelE5)).prod
        ((volume : Measure ℝ).prod volume)))
    (hdistribution : ∀ M : ℕ,
      SourceStoppingCoordinateEnvelope α (truncationCollection α M)
        (InitialModelRealInput F) q σ
        (initialModel_sourceStoppingData_all_pos_of_ne_zero
          α (truncationCollection α M) F hFnonzero) ≤ W) :
    |ModelFullForm α u c F| ≤ C * sourceWeight u ^ 75 * W := by
  apply scratch_modelFullForm_bound_of_restrictedForest
    α u c F (C * sourceWeight u ^ 75 * W) hcmeas hc hfull
  intro N M
  let d : ℝ → ℝ := RestrictScaleCoefficient c (truncationScaleSet N)
  let hpos : ∀ r ∈ truncationCollection α M, ∀ j,
      0 < stoppingData α (truncationCollection α M)
        (sourceStoppingExponent j) (InitialModelRealInput F j) r :=
    initialModel_sourceStoppingData_all_pos_of_ne_zero
      α (truncationCollection α M) F hFnonzero
  have hdmeas : Measurable d := by
    exact measurable_RestrictScaleCoefficient c (truncationScaleSet N)
      hcmeas measurableSet_Ioc
  have hd : ∀ t : ℝ, |d t| ≤ 1 := by
    exact abs_restrictScaleCoefficient_le_one c (truncationScaleSet N) hc
  have hfinite : ∀ (j : Fin 4) (m : ℤ),
      volume (sourceStoppingMaximalLevelSetAt α
        (InitialModelRealInput F) j m) ≠ ∞ := by
    exact sourceStopping_coordinateLevel_finite_of_initialModelRealSchwartz α F
  have hlocal := hforest (truncationCollection α M)
    (isConvexCollection_truncationCollection α M) u d F q σ hq hpos
    hdmeas hd hfinite
  change |expandedModelLocalForm α (truncationCollection α M) u d
    (InitialModelRealInput F)| ≤ C * sourceWeight u ^ 75 * W
  calc
    |expandedModelLocalForm α (truncationCollection α M) u d
        (InitialModelRealInput F)| ≤
        C * sourceWeight u ^ 75 *
          SourceStoppingCoordinateEnvelope α (truncationCollection α M)
            (InitialModelRealInput F) q σ hpos := hlocal
    _ ≤ C * sourceWeight u ^ 75 * W := by
      apply mul_le_mul_of_nonneg_left (hdistribution M)
      exact mul_nonneg hC (pow_nonneg (sourceWeight_nonneg u) _)

end
end Twisted
end Auto
