/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal

noncomputable section

/-! ## Layer sizes in the `L^p` seminorms

Source: `ext:interpolation`.  The endpoint hypotheses are stated with `L^{p}`
norms of the inputs, so the layer size estimates are recorded again in that
form: a layer's `L^p` norm is `2^k` times the `1/p`-th power of its annulus
measure, up to the single factor of two separating the two ends of the annulus.
This is the exchange rate between the four endpoint exponent vectors.
-/

/-- **Layer upper size in `L^p`.** -/
theorem eLpNorm_dyadicLayer_le
    {X : Type*} [MeasurableSpace X] (μ : Measure X) {f : X → ℝ}
    (hf : Measurable f) (k : ℤ) {p : ℝ≥0∞} (hp : p ≠ 0) (hp_top : p ≠ ∞) :
    eLpNorm (dyadicLayer f k) p μ
      ≤ ENNReal.ofReal ((2 : ℝ) ^ (k + 1)) *
          μ (dyadicLayerSet f k) ^ (1 / p.toReal) := by
  have hS := measurableSet_dyadicLayerSet hf k
  have hpos : (0 : ℝ) < (2 : ℝ) ^ (k + 1) := zpow_pos (by norm_num) _
  have hmono : ∀ x, ‖dyadicLayer f k x‖ ≤
      ‖(dyadicLayerSet f k).indicator (fun _ ↦ (2 : ℝ) ^ (k + 1)) x‖ := by
    intro x
    by_cases hx : x ∈ dyadicLayerSet f k
    · rw [Set.indicator_of_mem hx]
      simpa [Real.norm_eq_abs, abs_of_pos hpos] using (abs_dyadicLayer_lt f k x).le
    · have hzero : dyadicLayer f k x = 0 := by
        by_contra hne
        exact hx ((dyadicLayer_ne_zero_iff_mem f k x).mp hne)
      rw [Set.indicator_of_notMem hx, hzero]
  calc eLpNorm (dyadicLayer f k) p μ
      ≤ eLpNorm ((dyadicLayerSet f k).indicator
          (fun _ ↦ (2 : ℝ) ^ (k + 1))) p μ := eLpNorm_mono hmono
    _ = ‖((2 : ℝ) ^ (k + 1))‖ₑ * μ (dyadicLayerSet f k) ^ (1 / p.toReal) :=
        eLpNorm_indicator_const hS hp hp_top
    _ = ENNReal.ofReal ((2 : ℝ) ^ (k + 1)) *
          μ (dyadicLayerSet f k) ^ (1 / p.toReal) := by
        rw [Real.enorm_eq_ofReal hpos.le]

/-- **Layer lower size in `L^p`.** -/
theorem le_eLpNorm_dyadicLayer
    {X : Type*} [MeasurableSpace X] (μ : Measure X) {f : X → ℝ}
    (hf : Measurable f) (k : ℤ) {p : ℝ≥0∞} (hp : p ≠ 0) (hp_top : p ≠ ∞) :
    ENNReal.ofReal ((2 : ℝ) ^ k) * μ (dyadicLayerSet f k) ^ (1 / p.toReal)
      ≤ eLpNorm (dyadicLayer f k) p μ := by
  have hS := measurableSet_dyadicLayerSet hf k
  have hpos : (0 : ℝ) < (2 : ℝ) ^ k := zpow_pos (by norm_num) _
  have hmono : ∀ x, ‖(dyadicLayerSet f k).indicator (fun _ ↦ (2 : ℝ) ^ k) x‖
      ≤ ‖dyadicLayer f k x‖ := by
    intro x
    by_cases hx : x ∈ dyadicLayerSet f k
    · rw [Set.indicator_of_mem hx]
      have hne : dyadicLayer f k x ≠ 0 := (dyadicLayer_ne_zero_iff_mem f k x).mpr hx
      simpa [Real.norm_eq_abs, abs_of_pos hpos] using le_abs_dyadicLayer f k x hne
    · rw [Set.indicator_of_notMem hx]
      simp
  calc ENNReal.ofReal ((2 : ℝ) ^ k) * μ (dyadicLayerSet f k) ^ (1 / p.toReal)
      = ‖((2 : ℝ) ^ k)‖ₑ * μ (dyadicLayerSet f k) ^ (1 / p.toReal) := by
        rw [Real.enorm_eq_ofReal hpos.le]
    _ = eLpNorm ((dyadicLayerSet f k).indicator (fun _ ↦ (2 : ℝ) ^ k)) p μ :=
        (eLpNorm_indicator_const hS hp hp_top).symm
    _ ≤ eLpNorm (dyadicLayer f k) p μ := eLpNorm_mono hmono

end
end Twisted
end Auto
