/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal

noncomputable section

/-! ## Trading one endpoint exponent for another

Source: `ext:interpolation` together with `lem:exponent_simplex`.  A layer's
size at an endpoint exponent `1/p_{a,j}` is its size at the target exponent
`1/p_j` raised to the ratio of the two, times a pure power of the dyadic level.
Because the weights of `eq:weights` exhibit the target reciprocal as the convex
combination of the four endpoint reciprocals, those pure powers of the level
cancel exactly in the four-fold weighted geometric mean — this is precisely why
the four vertices of the tetrahedron are needed and why no two of them suffice.
-/

/-- **Exponent exchange.**  Writing `a = 2^k` for the dyadic level and `m` for
the annulus measure, the endpoint size `a * m^{β_a}` is a power of the target
size `a * m^{β}` times a pure power of the level. -/
theorem dyadicLevel_measure_rpow_exchange
    (k : ℤ) (m : ℝ≥0∞) {β βa : ℝ} (hβ : 0 < β) (hβa : 0 ≤ βa) :
    ENNReal.ofReal ((2 : ℝ) ^ k) * m ^ βa
      = ENNReal.ofReal ((2 : ℝ) ^ k) ^ (1 - βa / β) *
          (ENNReal.ofReal ((2 : ℝ) ^ k) * m ^ β) ^ (βa / β) := by
  set a : ℝ≥0∞ := ENNReal.ofReal ((2 : ℝ) ^ k) with ha
  have hapos : (0 : ℝ) < (2 : ℝ) ^ k := zpow_pos (by norm_num) _
  have ha0 : a ≠ 0 := by
    rw [ha]; exact ne_of_gt (ENNReal.ofReal_pos.mpr hapos)
  have hatop : a ≠ ∞ := by rw [ha]; exact ENNReal.ofReal_ne_top
  have hρ : 0 ≤ βa / β := div_nonneg hβa hβ.le
  rw [ENNReal.mul_rpow_of_nonneg _ _ hρ, ← mul_assoc, ← ENNReal.rpow_add _ _ ha0 hatop,
    ← ENNReal.rpow_mul]
  rw [show (1 : ℝ) - βa / β + βa / β = 1 by ring, ENNReal.rpow_one,
    show β * (βa / β) = βa by field_simp]

/-- **The level powers cancel in the four-fold mean.**  If the target
reciprocal is the convex combination of the four endpoint reciprocals with the
weights of `eq:weights`, the exchange exponents `1 - β_{a}/β` average to zero. -/
theorem sum_weights_exchange_eq_zero
    {β βa₀ βa₁ βa₂ βa₃ ϑ₀ ϑ₁ ϑ₂ ϑ₃ : ℝ} (hβ : 0 < β)
    (hϑ : ϑ₀ + ϑ₁ + ϑ₂ + ϑ₃ = 1)
    (hmix : ϑ₀ * βa₀ + ϑ₁ * βa₁ + ϑ₂ * βa₂ + ϑ₃ * βa₃ = β) :
    ϑ₀ * (1 - βa₀ / β) + ϑ₁ * (1 - βa₁ / β) + ϑ₂ * (1 - βa₂ / β)
        + ϑ₃ * (1 - βa₃ / β) = 0 := by
  field_simp
  linear_combination β * hϑ - hmix

/-- Four powers of one finite nonzero quantity whose exponents sum to zero
multiply to one. -/
theorem rpow_four_mul_eq_one {a : ℝ≥0∞} (ha : a ≠ 0) (ha' : a ≠ ∞)
    {e₀ e₁ e₂ e₃ : ℝ} (h : e₀ + e₁ + e₂ + e₃ = 0) :
    a ^ e₀ * a ^ e₁ * a ^ e₂ * a ^ e₃ = 1 := by
  rw [← ENNReal.rpow_add _ _ ha ha', ← ENNReal.rpow_add _ _ ha ha',
    ← ENNReal.rpow_add _ _ ha ha', h, ENNReal.rpow_zero]

/-- **The four-fold cancellation.**  With the weights of `eq:weights`, the pure
powers of the dyadic level produced by the four exponent exchanges cancel
identically, leaving only the target-exponent sizes. -/
theorem prod_dyadicLevel_exchange_eq_one
    (k : ℤ) {β βa₀ βa₁ βa₂ βa₃ ϑ₀ ϑ₁ ϑ₂ ϑ₃ : ℝ} (hβ : 0 < β)
    (hϑ : ϑ₀ + ϑ₁ + ϑ₂ + ϑ₃ = 1)
    (hmix : ϑ₀ * βa₀ + ϑ₁ * βa₁ + ϑ₂ * βa₂ + ϑ₃ * βa₃ = β) :
    ENNReal.ofReal ((2 : ℝ) ^ k) ^ (ϑ₀ * (1 - βa₀ / β)) *
        ENNReal.ofReal ((2 : ℝ) ^ k) ^ (ϑ₁ * (1 - βa₁ / β)) *
        ENNReal.ofReal ((2 : ℝ) ^ k) ^ (ϑ₂ * (1 - βa₂ / β)) *
        ENNReal.ofReal ((2 : ℝ) ^ k) ^ (ϑ₃ * (1 - βa₃ / β)) = 1 := by
  have hapos : (0 : ℝ) < (2 : ℝ) ^ k := zpow_pos (by norm_num) _
  refine rpow_four_mul_eq_one (a := ENNReal.ofReal ((2 : ℝ) ^ k))
    (ne_of_gt (ENNReal.ofReal_pos.mpr hapos)) ENNReal.ofReal_ne_top ?_
  exact sum_weights_exchange_eq_zero hβ hϑ hmix


end
end Twisted
end Auto
