/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators ENNReal RealInnerProductSpace Topology

noncomputable section

/-! ## Section 6: Schwartz maximal-function bridges

This scratch development keeps the source's literal all-positive-scales
anisotropic maxima.  The initial block isolates elementary fixed-scale and
finite-scale facts which are reusable independently of the remaining
Hardy--Littlewood iteration.
-/

/-- The real-valued Schwartz inputs used in the initial model range have an
explicit polynomial tail in the Euclidean norm.  This is the real analogue of
the earlier complex Schwartz decay extractor, stated here because Section 6
uses real second and fourth moments. -/
theorem scratch_realSchwartz_decay_norm
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (f : SchwartzMap E ℝ) (r : ℕ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ x : E, |f x| ≤ C / (1 + ‖x‖) ^ r := by
  let C : ℝ := 2 ^ r *
    (Finset.Iic (r, 0)).sup (fun q ↦ SchwartzMap.seminorm ℝ q.1 q.2) f
  have hC : 0 ≤ C := by
    have h := SchwartzMap.one_add_le_sup_seminorm_apply (𝕜 := ℝ)
      (m := (r, 0)) le_rfl le_rfl f (0 : E)
    have hnonneg : 0 ≤ (1 + ‖(0 : E)‖) ^ r *
        ‖iteratedFDeriv ℝ 0 f (0 : E)‖ :=
      mul_nonneg (pow_nonneg (by positivity) _) (norm_nonneg _)
    exact hnonneg.trans (by simpa [C] using h)
  refine ⟨C, hC, fun x ↦ ?_⟩
  apply (le_div_iff₀ (by positivity)).mpr
  rw [mul_comm]
  simpa [C, Real.norm_eq_abs, norm_iteratedFDeriv_zero] using
    (SchwartzMap.one_add_le_sup_seminorm_apply (𝕜 := ℝ)
      (m := (r, 0)) le_rfl le_rfl f x)

/-- The Euclidean norm on the literal three-coordinate source space is at
most the coordinate `ℓ¹` norm.  Keeping this elementary comparison explicit
lets later kernel estimates reduce spatial escape to one coordinate. -/
theorem scratch_norm_le_sum_abs (v : E3) :
    ‖v‖ ≤ |v 0| + |v 1| + |v 2| := by
  rw [EuclideanSpace.norm_eq]
  apply (Real.sqrt_le_iff).mpr
  constructor
  · positivity
  rw [Fin.sum_univ_three]
  simp only [Real.norm_eq_abs]
  have h01 : 0 ≤ |v 0| * |v 1| := mul_nonneg (abs_nonneg _) (abs_nonneg _)
  have h02 : 0 ≤ |v 0| * |v 2| := mul_nonneg (abs_nonneg _) (abs_nonneg _)
  have h12 : 0 ≤ |v 1| * |v 2| := mul_nonneg (abs_nonneg _) (abs_nonneg _)
  nlinarith

/-- The product of the three coordinate Japanese brackets dominates one plus
their sum. -/
theorem scratch_one_add_sum_le_prod_one_add
    (a : Fin 3 → ℝ) (ha : ∀ i, 0 ≤ a i) :
    1 + ∑ i, a i ≤ ∏ i, (1 + a i) := by
  rw [Fin.sum_univ_three, Fin.prod_univ_three]
  have h01 : 0 ≤ a 0 * a 1 := mul_nonneg (ha _) (ha _)
  have h02 : 0 ≤ a 0 * a 2 := mul_nonneg (ha _) (ha _)
  have h12 : 0 ≤ a 1 * a 2 := mul_nonneg (ha _) (ha _)
  have h012 : 0 ≤ a 0 * a 1 * a 2 :=
    mul_nonneg h01 (ha _)
  nlinarith

/-- The product bracket on `E3` dominates the usual radial Japanese bracket.
This is the source's elementary product-to-radial tail comparison. -/
theorem scratch_one_add_norm_le_prod_one_add_abs (v : E3) :
    1 + ‖v‖ ≤ ∏ i : Fin 3, (1 + |v i|) := by
  calc
    1 + ‖v‖ ≤ 1 + ∑ i, |v i| := by
      gcongr
      simpa only [Fin.sum_univ_three] using scratch_norm_le_sum_abs v
    _ ≤ ∏ i : Fin 3, (1 + |v i|) :=
      scratch_one_add_sum_le_prod_one_add (fun i ↦ |v i|)
        (fun _ ↦ abs_nonneg _)

/-- After positive coordinate rescaling, the product bracket still dominates
the radial bracket at the sum of the three scales. -/
theorem scratch_one_add_norm_div_sum_le_prod_scaled
    (v : E3) (s : Fin 3 → ℝ) (hs : ∀ i, 0 < s i) :
    1 + ‖v‖ / (∑ i, s i) ≤ ∏ i, (1 + |v i / s i|) := by
  let S : ℝ := ∑ i, s i
  have hS : 0 < S := by
    dsimp only [S]
    exact Finset.sum_pos (fun i _ ↦ hs i) (by simp)
  have hsiS (i : Fin 3) : s i ≤ S := by
    dsimp only [S]
    exact Finset.single_le_sum (fun j _ ↦ (hs j).le) (Finset.mem_univ i)
  have hcoord (i : Fin 3) : |v i| / S ≤ |v i / s i| := by
    rw [abs_div, abs_of_pos (hs i)]
    apply (div_le_div_iff₀ hS (hs i)).mpr
    exact mul_le_mul_of_nonneg_left (hsiS i) (abs_nonneg _)
  calc
    1 + ‖v‖ / S ≤ 1 + (∑ i, |v i|) / S := by
      apply add_le_add_right
      exact div_le_div_of_nonneg_right
        (by simpa only [Fin.sum_univ_three] using scratch_norm_le_sum_abs v) hS.le
    _ = 1 + ∑ i, |v i| / S := by rw [Finset.sum_div]
    _ ≤ 1 + ∑ i, |v i / s i| := by
      apply add_le_add_right
      exact Finset.sum_le_sum fun i _ ↦ hcoord i
    _ ≤ ∏ i, (1 + |v i / s i|) :=
      scratch_one_add_sum_le_prod_one_add (fun i ↦ |v i / s i|)
        (fun _ ↦ abs_nonneg _)

/-- A finite product commutes with the fixed negative bracket exponent on
nonnegative factors. -/
theorem scratch_prod_rpow_neg_ten
    (a : Fin 3 → ℝ) (ha : ∀ i, 0 ≤ a i) :
    (∏ i, (a i) ^ (-10 : ℝ)) = (∏ i, a i) ^ (-10 : ℝ) := by
  rw [Fin.prod_univ_three]
  rw [← Real.mul_rpow (ha 0) (ha 1)]
  rw [← Real.mul_rpow (mul_nonneg (ha 0) (ha 1)) (ha 2)]
  rw [Fin.prod_univ_three]

/-- The unnormalized product of three rescaled bracket kernels is controlled
by one radial bracket. -/
theorem scratch_prod_bracketKernel_le_radial
    (v : E3) (s : Fin 3 → ℝ) (hs : ∀ i, 0 < s i) :
    (∏ i, bracketKernel (v i / s i)) ≤
      (1 + ‖v‖ / (∑ i, s i)) ^ (-10 : ℝ) := by
  have hS : 0 < ∑ i, s i :=
    Finset.sum_pos (fun i _ ↦ hs i) (by simp)
  have hbracket : ∀ i : Fin 3, bracketKernel (v i / s i) =
      (1 + |v i / s i|) ^ (-10 : ℝ) := by
    intro i
    rfl
  rw [show (∏ i, bracketKernel (v i / s i)) =
      ∏ i, (1 + |v i / s i|) ^ (-10 : ℝ) by
        apply Finset.prod_congr rfl
        intro i _
        exact hbracket i]
  rw [scratch_prod_rpow_neg_ten (fun i ↦ 1 + |v i / s i|)
    (fun i ↦ by positivity)]
  exact Real.rpow_le_rpow_of_nonpos
    (add_pos_of_pos_of_nonneg zero_lt_one (div_nonneg (norm_nonneg _) hS.le))
    (scratch_one_add_norm_div_sum_le_prod_scaled v s hs)
    (by norm_num)

/-- At each fixed positive anisotropic scale, the literal product comparison
kernel has a radial polynomial tail in the center variable. -/
theorem scratch_anisotropicBracketKernel_le_radial
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (p y : E3) :
    anisotropicBracketKernel α t p y ≤
      (∏ i : Fin 3, (t ^ α.weight i)⁻¹) *
        (1 + ‖y - p‖ / (∑ i : Fin 3, t ^ α.weight i)) ^ (-10 : ℝ) := by
  have hs (i : Fin 3) : 0 < t ^ α.weight i := pow_pos ht _
  have hrewrite (i : Fin 3) :
      bracketKernelAt (t ^ α.weight i) (p i) (y i) =
        (t ^ α.weight i)⁻¹ * bracketKernel ((y - p) i / (t ^ α.weight i)) := by
    simp only [bracketKernelAt, kernelAt, kernelDilate, smul_eq_mul,
      PiLp.sub_apply]
  calc
    anisotropicBracketKernel α t p y =
        ∏ i : Fin 3, ((t ^ α.weight i)⁻¹ *
          bracketKernel ((y - p) i / (t ^ α.weight i))) := by
      unfold anisotropicBracketKernel
      apply Finset.prod_congr rfl
      intro i _
      exact hrewrite i
    _ = (∏ i : Fin 3, (t ^ α.weight i)⁻¹) *
        ∏ i : Fin 3, bracketKernel ((y - p) i / (t ^ α.weight i)) := by
      rw [Finset.prod_mul_distrib]
    _ ≤ (∏ i : Fin 3, (t ^ α.weight i)⁻¹) *
        (1 + ‖y - p‖ / (∑ i : Fin 3, t ^ α.weight i)) ^ (-10 : ℝ) := by
      apply mul_le_mul_of_nonneg_left
        (scratch_prod_bracketKernel_le_radial (y - p)
          (fun i ↦ t ^ α.weight i) hs)
      apply Finset.prod_nonneg
      intro i _
      exact inv_nonneg.mpr (hs i).le

/-- A fixed anisotropic comparison kernel vanishes when its center escapes to
spatial infinity.  This is the pointwise tail input for dominated convergence
in the fixed-scale second and fourth moments. -/
theorem scratch_tendsto_anisotropicBracketKernel_center
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (y : E3) :
    Tendsto (fun p : E3 ↦ anisotropicBracketKernel α t p y)
      (cocompact E3) (𝓝 0) := by
  let S : ℝ := ∑ i : Fin 3, t ^ α.weight i
  let C : ℝ := ∏ i : Fin 3, (t ^ α.weight i)⁻¹
  have hS : 0 < S := by
    dsimp only [S]
    exact Finset.sum_pos (fun i _ ↦ pow_pos ht _) (by simp)
  have hC : 0 ≤ C := by
    dsimp only [C]
    apply Finset.prod_nonneg
    intro i _
    exact inv_nonneg.mpr (pow_pos ht _).le
  have hdist : Tendsto (fun p : E3 ↦ ‖y - p‖)
      (cocompact E3) atTop := by
    convert tendsto_dist_left_cocompact_atTop y using 1
    ext p
    exact (dist_eq_norm_sub y p).symm
  have hbase : Tendsto (fun p : E3 ↦ 1 + ‖y - p‖ / S)
      (cocompact E3) atTop := by
    exact tendsto_atTop_add_const_left _ 1
      (hdist.atTop_div_const hS)
  have htail : Tendsto (fun p : E3 ↦
      (1 + ‖y - p‖ / S) ^ (-10 : ℝ))
      (cocompact E3) (𝓝 0) := by
    exact (tendsto_rpow_neg_atTop (by norm_num : 0 < (10 : ℝ))).comp hbase
  have hmajor : Tendsto (fun p : E3 ↦ C *
      (1 + ‖y - p‖ / S) ^ (-10 : ℝ))
      (cocompact E3) (𝓝 0) := by
    simpa only [mul_zero] using tendsto_const_nhds.mul htail
  apply squeeze_zero
  · intro p
    exact anisotropicBracketKernel_nonneg α ht.le p y
  · intro p
    simpa only [S, C] using
      scratch_anisotropicBracketKernel_le_radial α ht p y
  · exact hmajor

/-- Each one-dimensional comparison bracket is at most one before its scale
normalization. -/
theorem scratch_bracketKernel_le_one (x : ℝ) : bracketKernel x ≤ 1 := by
  unfold bracketKernel
  apply Real.rpow_le_one_of_one_le_of_nonpos
  · linarith [abs_nonneg x]
  · norm_num

/-- The literal anisotropic kernel is bounded by its product scale density. -/
theorem scratch_anisotropicBracketKernel_le_scaleDensity
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (p y : E3) :
    anisotropicBracketKernel α t p y ≤
      ∏ i : Fin 3, (t ^ α.weight i)⁻¹ := by
  have hs (i : Fin 3) : 0 < t ^ α.weight i := pow_pos ht _
  calc
    anisotropicBracketKernel α t p y =
        ∏ i : Fin 3, ((t ^ α.weight i)⁻¹ *
          bracketKernel ((y i - p i) / (t ^ α.weight i))) := by
      unfold anisotropicBracketKernel bracketKernelAt kernelAt kernelDilate
      apply Finset.prod_congr rfl
      intro i _
      simp only [smul_eq_mul]
    _ ≤ ∏ i : Fin 3, ((t ^ α.weight i)⁻¹ * 1) := by
      apply Finset.prod_le_prod
      · intro i _
        exact mul_nonneg (inv_nonneg.mpr (hs i).le) (bracketKernel_nonneg _)
      · intro i _
        exact mul_le_mul_of_nonneg_left
          (scratch_bracketKernel_le_one _) (inv_nonneg.mpr (hs i).le)
    _ = ∏ i : Fin 3, (t ^ α.weight i)⁻¹ := by simp

/-- Dominated convergence turns the fixed-kernel tail into a tail for a
fixed-scale second moment.  The hypotheses are deliberately analytic rather
than Schwartz-specific, so the later Schwartz corollary has no hidden gap. -/
theorem scratch_tendsto_cubeSecondMoment_fixedScale
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (f : E3 → ℝ)
    (hfcont : Continuous f) (hfSq : Integrable (fun y : E3 ↦ f y ^ 2)) :
    Tendsto (fun p : E3 ↦ cubeSecondMoment α t p f)
      (cocompact E3) (𝓝 0) := by
  letI : (cocompact E3).IsCountablyGenerated := by
    rw [← comap_dist_left_atTop_eq_cocompact (0 : E3)]
    infer_instance
  let C : ℝ := ∏ i : Fin 3, (t ^ α.weight i)⁻¹
  have hC : 0 ≤ C := by
    dsimp only [C]
    apply Finset.prod_nonneg
    intro i _
    exact inv_nonneg.mpr (pow_pos ht _).le
  have hbound : Integrable (fun y : E3 ↦ C * f y ^ 2) :=
    hfSq.const_mul C
  have hdc := tendsto_integral_filter_of_dominated_convergence
    (μ := volume) (l := cocompact E3)
    (F := fun p y ↦ f y ^ 2 * anisotropicBracketKernel α t p y)
    (f := fun _ : E3 ↦ (0 : ℝ))
    (fun y ↦ C * f y ^ 2)
    (Filter.Eventually.of_forall (fun p ↦
      ((hfcont.pow 2).mul (continuous_anisotropicBracketKernel α ht p)).aestronglyMeasurable))
    (Filter.Eventually.of_forall (fun p ↦ Filter.Eventually.of_forall (fun y ↦ by
      rw [Real.norm_eq_abs,
        abs_of_nonneg (mul_nonneg (sq_nonneg _)
          (anisotropicBracketKernel_nonneg α ht.le p y))]
      simpa only [mul_comm] using mul_le_mul_of_nonneg_left
        (scratch_anisotropicBracketKernel_le_scaleDensity α ht p y) (sq_nonneg _))))
    hbound
    (Filter.Eventually.of_forall (fun y ↦ by
      have hkernel := scratch_tendsto_anisotropicBracketKernel_center α ht y
      simpa only [mul_zero] using tendsto_const_nhds.mul hkernel))
  simpa only [cubeSecondMoment, integral_zero] using hdc

/-- Fixed-scale exponent-two anisotropic averages of a real Schwartz input
vanish at spatial infinity. -/
theorem scratch_tendsto_cubeSecondMoment_fixedScale_of_realSchwartz
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (f : SchwartzMap E3 ℝ) :
    Tendsto (fun p : E3 ↦ cubeSecondMoment α t p f)
      (cocompact E3) (𝓝 0) := by
  apply scratch_tendsto_cubeSecondMoment_fixedScale α ht f f.continuous
  have hmem : MemLp f (2 : ℝ≥0∞) volume := f.memLp 2 volume
  simpa only [Real.norm_eq_abs, sq_abs] using
    hmem.integrable_norm_pow (by norm_num : (2 : ℕ) ≠ 0)

/-! ### One-dimensional scale-uniform comparison -/

/-- A positive-scale bracket kernel is bounded by its scale density. -/
theorem scratch_bracketKernelAt_le_inv_scale {s : ℝ} (hs : 0 < s)
    (p y : ℝ) :
    bracketKernelAt s p y ≤ s⁻¹ := by
  unfold bracketKernelAt kernelAt kernelDilate
  change s⁻¹ * bracketKernel ((y - p) / s) ≤ s⁻¹
  simpa using mul_le_mul_of_nonneg_left
    (scratch_bracketKernel_le_one ((y - p) / s)) (inv_nonneg.mpr hs.le)

/-- Away from the center, a small-scale bracket kernel has a uniform
polynomial bound.  The deliberately generous constant keeps later
annular bookkeeping elementary. -/
theorem scratch_bracketKernelAt_le_remote
    {s p y : ℝ} (hs : 0 < s) (hp : 1 ≤ |p|)
    (hscale : s ≤ |p| / 4) (hy : |y| ≤ |p| / 2) :
    bracketKernelAt s p y ≤ (2 : ℝ) ^ 10 / |p| := by
  have hp0 : 0 < |p| := lt_of_lt_of_le zero_lt_one hp
  have hdist : |p| / 2 ≤ |y - p| := by
    have htri : |p| ≤ |y| + |y - p| := by
      calc
        |p| = |y + (p - y)| := by
          congr 1
          ring
        _ ≤ |y| + |p - y| := abs_add_le _ _
        _ = |y| + |y - p| := by rw [abs_sub_comm]
    linarith
  have hratio : |p| / (2 * s) ≤ |(y - p) / s| := by
    rw [abs_div, abs_of_pos hs]
    calc
      |p| / (2 * s) = (|p| / 2) / s := by field_simp
      _ ≤ |y - p| / s := div_le_div_of_nonneg_right hdist hs.le
  have hbase : |p| / (2 * s) ≤ 1 + |(y - p) / s| := by
    linarith [abs_nonneg ((y - p) / s)]
  have hbasepos : 0 < |p| / (2 * s) := by positivity
  have hpow : (1 + |(y - p) / s|) ^ 10 ≥
      (|p| / (2 * s)) ^ 10 := by
    exact pow_le_pow_left₀ (by positivity) hbase 10
  rw [bracketKernelAt, kernelAt, kernelDilate, smul_eq_mul,
    bracketKernel_eq_inv_pow]
  have hinv : ((1 + |(y - p) / s|) ^ 10)⁻¹ ≤
      ((|p| / (2 * s)) ^ 10)⁻¹ := by
    exact inv_anti₀ (pow_pos hbasepos 10) hpow
  calc
    s⁻¹ * ((1 + |(y - p) / s|) ^ 10)⁻¹ ≤
        s⁻¹ * ((|p| / (2 * s)) ^ 10)⁻¹ :=
      mul_le_mul_of_nonneg_left hinv (inv_nonneg.mpr hs.le)
    _ = (2 : ℝ) ^ 10 * s ^ 9 / |p| ^ 10 := by
      field_simp
    _ ≤ (2 : ℝ) ^ 10 / |p| := by
      have hsle : s ≤ |p| := le_trans hscale (by nlinarith)
      have hspow : s ^ 9 ≤ |p| ^ 9 :=
        pow_le_pow_left₀ hs.le hsle 9
      have hquot : s ^ 9 / |p| ^ 10 ≤ 1 / |p| := by
        apply (div_le_div_iff₀ (pow_pos hp0 10) hp0).mpr
        calc
          s ^ 9 * |p| ≤ |p| ^ 9 * |p| :=
            mul_le_mul_of_nonneg_right hspow hp0.le
          _ = 1 * |p| ^ 10 := by ring
      calc
        (2 : ℝ) ^ 10 * s ^ 9 / |p| ^ 10 =
            (2 : ℝ) ^ 10 * (s ^ 9 / |p| ^ 10) := by ring
        _ ≤ (2 : ℝ) ^ 10 * (1 / |p|) :=
          mul_le_mul_of_nonneg_left hquot (by positivity)
        _ = (2 : ℝ) ^ 10 / |p| := by ring

/-- The unit bracket itself has the matching remote-center estimate. -/
theorem scratch_bracketKernel_le_remote
    {p y : ℝ} (hp : 1 ≤ |p|) (hy : |p| / 2 ≤ |y|) :
    bracketKernel y ≤ (2 : ℝ) ^ 10 / |p| := by
  have hp0 : 0 < |p| := lt_of_lt_of_le zero_lt_one hp
  have hbase : |p| / 2 ≤ 1 + |y| := by linarith
  have hbasepos : 0 < |p| / 2 := by positivity
  have hpow : (|p| / 2) ^ 10 ≤ (1 + |y|) ^ 10 :=
    pow_le_pow_left₀ (by positivity) hbase 10
  rw [bracketKernel_eq_inv_pow]
  calc
    ((1 + |y|) ^ 10)⁻¹ ≤ ((|p| / 2) ^ 10)⁻¹ :=
      inv_anti₀ (pow_pos hbasepos 10) hpow
    _ = (2 : ℝ) ^ 10 / |p| ^ 10 := by
      field_simp
    _ ≤ (2 : ℝ) ^ 10 / |p| := by
      have hpow : 1 ≤ |p| ^ 9 :=
        one_le_pow₀ hp
      have hquot : 1 / |p| ^ 10 ≤ 1 / |p| := by
        apply (div_le_div_iff₀ (pow_pos hp0 10) hp0).mpr
        calc
          1 * |p| ≤ |p| ^ 9 * |p| :=
            mul_le_mul_of_nonneg_right hpow hp0.le
          _ = 1 * |p| ^ 10 := by ring
      calc
        (2 : ℝ) ^ 10 / |p| ^ 10 = (2 : ℝ) ^ 10 * (1 / |p| ^ 10) := by ring
        _ ≤ (2 : ℝ) ^ 10 * (1 / |p|) :=
          mul_le_mul_of_nonneg_left hquot (by positivity)
        _ = (2 : ℝ) ^ 10 / |p| := by ring

/-- Products of a unit bracket and a positive-scale bracket kernel are
integrable; this is the basic one-dimensional Fubini input. -/
theorem scratch_integrable_bracketKernel_mul_bracketKernelAt
    {s : ℝ} (hs : 0 < s) (p : ℝ) :
    Integrable (fun y : ℝ ↦ bracketKernel y * bracketKernelAt s p y) := by
  refine (integrable_bracketKernelAt hs p).mono
    ((continuous_bracketKernel.mul (continuous_bracketKernelAt hs.ne' p)).aestronglyMeasurable) ?_
  filter_upwards [] with y
  rw [Real.norm_eq_abs,
    abs_of_nonneg (mul_nonneg (bracketKernel_nonneg _)
      (bracketKernelAt_nonneg hs.le)),
    Real.norm_eq_abs, abs_of_nonneg (bracketKernelAt_nonneg hs.le)]
  exact (mul_le_of_le_one_left (bracketKernelAt_nonneg hs.le)
    (scratch_bracketKernel_le_one _))

/-- The product bracket average is bounded by the mass of either factor. -/
theorem scratch_integral_bracketKernel_mul_bracketKernelAt_le_mass
    {s : ℝ} (hs : 0 < s) (p : ℝ) :
    ∫ y : ℝ, bracketKernel y * bracketKernelAt s p y ≤ 2 / 9 := by
  have hleft := scratch_integrable_bracketKernel_mul_bracketKernelAt hs p
  have hright := integrable_bracketKernelAt hs p
  calc
    (∫ y : ℝ, bracketKernel y * bracketKernelAt s p y) ≤
        ∫ y : ℝ, bracketKernelAt s p y :=
      MeasureTheory.integral_mono_ae hleft hright
        (Filter.Eventually.of_forall fun y ↦
          mul_le_of_le_one_left (bracketKernelAt_nonneg hs.le)
            (scratch_bracketKernel_le_one _))
    _ = 2 / 9 := integral_bracketKernelAt hs p

/-- At scales no smaller than the escaping coordinate, the product average
is controlled directly by scale density. -/
theorem scratch_integral_bracketKernel_mul_bracketKernelAt_le_largeScale
    {s p : ℝ} (hs : 0 < s) (hp : 1 ≤ |p|) (hscale : |p| / 4 ≤ s) :
    ∫ y : ℝ, bracketKernel y * bracketKernelAt s p y ≤
      (4 / |p|) * (2 / 9) := by
  have hp0 : 0 < |p| := lt_of_lt_of_le zero_lt_one hp
  have hquot : s⁻¹ ≤ 4 / |p| := by
    calc
      s⁻¹ ≤ (|p| / 4)⁻¹ := inv_anti₀ (by positivity) hscale
      _ = 4 / |p| := by field_simp
  have hleft := scratch_integrable_bracketKernel_mul_bracketKernelAt hs p
  have hright : Integrable (fun y : ℝ ↦ (4 / |p|) * bracketKernel y) :=
    integrable_bracketKernel.const_mul _
  calc
    (∫ y : ℝ, bracketKernel y * bracketKernelAt s p y) ≤
        ∫ y : ℝ, (4 / |p|) * bracketKernel y :=
      MeasureTheory.integral_mono_ae hleft hright
        (Filter.Eventually.of_forall fun y ↦ by
          have hK := scratch_bracketKernelAt_le_inv_scale hs p y
          calc
            bracketKernel y * bracketKernelAt s p y ≤
                bracketKernel y * (4 / |p|) :=
              mul_le_mul_of_nonneg_left (hK.trans hquot) (bracketKernel_nonneg _)
            _ = (4 / |p|) * bracketKernel y := by ring)
    _ = (4 / |p|) * (2 / 9) := by
      rw [MeasureTheory.integral_const_mul, integral_bracketKernel]

/-- At smaller scales, either the center kernel is remote or the unit
bracket is remote.  This pointwise dichotomy is the core of the uniform
one-dimensional tail estimate. -/
theorem scratch_bracketKernel_mul_bracketKernelAt_le_smallScale
    {s p y : ℝ} (hs : 0 < s) (hp : 1 ≤ |p|)
    (hscale : s ≤ |p| / 4) :
    bracketKernel y * bracketKernelAt s p y ≤
      ((2 : ℝ) ^ 10 / |p|) *
        (bracketKernel y + bracketKernelAt s p y) := by
  have hp0 : 0 < |p| := lt_of_lt_of_le zero_lt_one hp
  have hcoeff : 0 ≤ (2 : ℝ) ^ 10 / |p| :=
    div_nonneg (by positivity) hp0.le
  by_cases hy : |y| ≤ |p| / 2
  · have hK := scratch_bracketKernelAt_le_remote hs hp hscale hy
    calc
      bracketKernel y * bracketKernelAt s p y ≤
          bracketKernel y * ((2 : ℝ) ^ 10 / |p|) :=
        mul_le_mul_of_nonneg_left hK (bracketKernel_nonneg _)
      _ = ((2 : ℝ) ^ 10 / |p|) * bracketKernel y := by ring
      _ ≤ ((2 : ℝ) ^ 10 / |p|) *
          (bracketKernel y + bracketKernelAt s p y) :=
        mul_le_mul_of_nonneg_left
          (le_add_of_nonneg_right (bracketKernelAt_nonneg hs.le)) hcoeff
  · have hy' : |p| / 2 ≤ |y| := le_of_lt (lt_of_not_ge hy)
    have hB := scratch_bracketKernel_le_remote hp hy'
    calc
      bracketKernel y * bracketKernelAt s p y ≤
          ((2 : ℝ) ^ 10 / |p|) * bracketKernelAt s p y :=
        mul_le_mul_of_nonneg_right hB (bracketKernelAt_nonneg hs.le)
      _ ≤ ((2 : ℝ) ^ 10 / |p|) *
          (bracketKernel y + bracketKernelAt s p y) :=
        mul_le_mul_of_nonneg_left
          (le_add_of_nonneg_left (bracketKernel_nonneg _)) hcoeff

/-- The small-scale dichotomy integrates without any unproved Fubini
interchange: both summands have explicit mass. -/
theorem scratch_integral_bracketKernel_mul_bracketKernelAt_le_smallScale
    {s p : ℝ} (hs : 0 < s) (hp : 1 ≤ |p|)
    (hscale : s ≤ |p| / 4) :
    ∫ y : ℝ, bracketKernel y * bracketKernelAt s p y ≤
      ((2 : ℝ) ^ 10 / |p|) * ((2 / 9) + (2 / 9)) := by
  have hleft := scratch_integrable_bracketKernel_mul_bracketKernelAt hs p
  have hsum : Integrable (fun y : ℝ ↦ bracketKernel y + bracketKernelAt s p y) :=
    integrable_bracketKernel.add (integrable_bracketKernelAt hs p)
  have hright := hsum.const_mul ((2 : ℝ) ^ 10 / |p|)
  calc
    (∫ y : ℝ, bracketKernel y * bracketKernelAt s p y) ≤
        ∫ y : ℝ, ((2 : ℝ) ^ 10 / |p|) *
          (bracketKernel y + bracketKernelAt s p y) :=
      MeasureTheory.integral_mono_ae hleft hright
        (Filter.Eventually.of_forall
          (fun y ↦ scratch_bracketKernel_mul_bracketKernelAt_le_smallScale
            hs hp hscale))
    _ = ((2 : ℝ) ^ 10 / |p|) *
        ((∫ y : ℝ, bracketKernel y) + ∫ y : ℝ, bracketKernelAt s p y) := by
      rw [MeasureTheory.integral_const_mul, MeasureTheory.integral_add
        integrable_bracketKernel (integrable_bracketKernelAt hs p)]
    _ = ((2 : ℝ) ^ 10 / |p|) * ((2 / 9) + (2 / 9)) := by
      rw [integral_bracketKernel, integral_bracketKernelAt hs p]

/-- A single, scale-uniform one-dimensional polynomial envelope.  This is
the precise replacement for the annular-decomposition step in the source:
the constant is intentionally coarse, while the decay is uniform over every
positive dilation. -/
theorem scratch_integral_bracketKernel_mul_bracketKernelAt_le_uniform
    {s : ℝ} (hs : 0 < s) (p : ℝ) :
    ∫ y : ℝ, bracketKernel y * bracketKernelAt s p y ≤
      (2 : ℝ) ^ 13 / (1 + |p|) := by
  by_cases hp : 1 ≤ |p|
  · have hp0 : 0 < |p| := lt_of_lt_of_le zero_lt_one hp
    have hP : ∫ y : ℝ, bracketKernel y * bracketKernelAt s p y ≤
        (2 : ℝ) ^ 12 / |p| := by
      by_cases hscale : s ≤ |p| / 4
      · calc
          (∫ y : ℝ, bracketKernel y * bracketKernelAt s p y) ≤
              ((2 : ℝ) ^ 10 / |p|) * ((2 / 9) + (2 / 9)) :=
            scratch_integral_bracketKernel_mul_bracketKernelAt_le_smallScale
              hs hp hscale
          _ = ((2 : ℝ) ^ 10 * ((2 / 9) + (2 / 9))) / |p| := by ring
          _ ≤ (2 : ℝ) ^ 12 / |p| := by
            apply div_le_div_of_nonneg_right _ hp0.le
            norm_num
      · have hscale' : |p| / 4 ≤ s := le_of_not_ge hscale
        calc
          (∫ y : ℝ, bracketKernel y * bracketKernelAt s p y) ≤
              (4 / |p|) * (2 / 9) :=
            scratch_integral_bracketKernel_mul_bracketKernelAt_le_largeScale
              hs hp hscale'
          _ = (4 * (2 / 9)) / |p| := by ring
          _ ≤ (2 : ℝ) ^ 12 / |p| := by
            apply div_le_div_of_nonneg_right _ hp0.le
            norm_num
    calc
      (∫ y : ℝ, bracketKernel y * bracketKernelAt s p y) ≤
          (2 : ℝ) ^ 12 / |p| := hP
      _ = 4096 / |p| := by norm_num
      _ ≤ 8192 / (1 + |p|) := by
        apply (div_le_div_iff₀ hp0 (by positivity)).mpr
        nlinarith
      _ = (2 : ℝ) ^ 13 / (1 + |p|) := by norm_num
  · have hp' : |p| ≤ 1 := le_of_not_ge hp
    calc
      (∫ y : ℝ, bracketKernel y * bracketKernelAt s p y) ≤ 2 / 9 :=
        scratch_integral_bracketKernel_mul_bracketKernelAt_le_mass hs p
      _ ≤ 8192 / (1 + |p|) := by
        apply (le_div_iff₀ (by positivity)).mpr
        nlinarith [abs_nonneg p]
      _ = (2 : ℝ) ^ 13 / (1 + |p|) := by norm_num

/-! ### Product Schwartz envelopes -/

/-- The product of the three coordinate Japanese brackets is at most the
third power of the Euclidean bracket. -/
theorem scratch_prod_one_add_abs_le_one_add_norm_cube (v : E3) :
    (∏ i : Fin 3, (1 + |v i|)) ≤ (1 + ‖v‖) ^ 3 := by
  have hcoord (i : Fin 3) : |v i| ≤ ‖v‖ := by
    simpa only [Real.norm_eq_abs] using PiLp.norm_apply_le v i
  rw [Fin.prod_univ_three]
  have h0 : 1 + |v 0| ≤ 1 + ‖v‖ := by linarith [hcoord 0]
  have h1 : 1 + |v 1| ≤ 1 + ‖v‖ := by linarith [hcoord 1]
  have h2 : 1 + |v 2| ≤ 1 + ‖v‖ := by linarith [hcoord 2]
  calc
    (1 + |v 0|) * (1 + |v 1|) * (1 + |v 2|) ≤
        (1 + ‖v‖) * (1 + ‖v‖) * (1 + ‖v‖) := by gcongr
    _ = (1 + ‖v‖) ^ 3 := by ring

/-- A radial order-thirty bracket is dominated by the product of the three
literal coordinate brackets. -/
theorem scratch_radial_bracket_neg_thirty_le_prod_bracketKernel (v : E3) :
    (1 + ‖v‖) ^ (-30 : ℝ) ≤ ∏ i : Fin 3, bracketKernel (v i) := by
  have hprod := scratch_prod_one_add_abs_le_one_add_norm_cube v
  have hprodpos : 0 < ∏ i : Fin 3, (1 + |v i|) := by positivity
  rw [show (∏ i : Fin 3, bracketKernel (v i)) =
      (∏ i : Fin 3, (1 + |v i|)) ^ (-10 : ℝ) by
        simpa only [bracketKernel] using
          scratch_prod_rpow_neg_ten (fun i ↦ 1 + |v i|)
            (fun _ ↦ by positivity)]
  calc
    (1 + ‖v‖) ^ (-30 : ℝ) = ((1 + ‖v‖) ^ 3) ^ (-10 : ℝ) := by
      rw [← Real.rpow_natCast (1 + ‖v‖) 3, ← Real.rpow_mul (by positivity)]
      norm_num
    _ ≤ (∏ i : Fin 3, (1 + |v i|)) ^ (-10 : ℝ) :=
      Real.rpow_le_rpow_of_nonpos hprodpos hprod (by norm_num)

/-- Squared real Schwartz data have a separable three-coordinate bracket
envelope.  Its coefficient is explicit enough for the scale-uniform
convolution calculation, but no choice of a Schwartz seminorm is exposed to
the eventual maximal-function statement. -/
theorem scratch_realSchwartz_sq_le_prod_bracketKernel
    (f : SchwartzMap E3 ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ y : E3,
      f y ^ 2 ≤ C * ∏ i : Fin 3, bracketKernel (y i) := by
  rcases scratch_realSchwartz_decay_norm f 15 with ⟨A, hA, hdecay⟩
  refine ⟨A ^ 2, pow_nonneg hA _, fun y ↦ ?_⟩
  have hB : 0 < 1 + ‖y‖ := by positivity
  have hdivnonneg : 0 ≤ A / (1 + ‖y‖) ^ 15 :=
    div_nonneg hA (pow_nonneg hB.le _)
  have hsq : |f y| ^ 2 ≤ (A / (1 + ‖y‖) ^ 15) ^ 2 :=
    (sq_le_sq₀ (abs_nonneg _) hdivnonneg).mpr (hdecay y)
  have hradial : f y ^ 2 ≤ A ^ 2 * (1 + ‖y‖) ^ (-30 : ℝ) := by
    calc
      f y ^ 2 = |f y| ^ 2 := by rw [← sq_abs]
      _ ≤ (A / (1 + ‖y‖) ^ 15) ^ 2 := hsq
      _ = A ^ 2 * (1 + ‖y‖) ^ (-30 : ℝ) := by
        rw [div_pow]
        rw [show (1 + ‖y‖) ^ (-30 : ℝ) =
            ((1 + ‖y‖) ^ 30)⁻¹ by
              rw [Real.rpow_neg hB.le]
              congr 1
              exact Real.rpow_natCast _ _]
        field_simp
  calc
    f y ^ 2 ≤ A ^ 2 * (1 + ‖y‖) ^ (-30 : ℝ) := hradial
    _ ≤ A ^ 2 * ∏ i : Fin 3, bracketKernel (y i) :=
      mul_le_mul_of_nonneg_left
        (scratch_radial_bracket_neg_thirty_le_prod_bracketKernel y)
        (pow_nonneg hA _)

/-- The same separable bracket envelope also controls the fourth power of a
real Schwartz input (after enlarging its coefficient once). -/
theorem scratch_realSchwartz_rpow_four_le_prod_bracketKernel
    (f : SchwartzMap E3 ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ y : E3,
      |f y| ^ (4 : ℝ) ≤ C * ∏ i : Fin 3, bracketKernel (y i) := by
  rcases scratch_realSchwartz_sq_le_prod_bracketKernel f with ⟨C, hC, henv⟩
  refine ⟨C ^ 2, pow_nonneg hC _, fun y ↦ ?_⟩
  let P : ℝ := ∏ i : Fin 3, bracketKernel (y i)
  have hP0 : 0 ≤ P := by
    dsimp only [P]
    exact Finset.prod_nonneg fun i _ ↦ bracketKernel_nonneg _
  have hP1 : P ≤ 1 := by
    dsimp only [P]
    apply Finset.prod_le_one
    · intro i _
      exact bracketKernel_nonneg _
    · intro i _
      exact scratch_bracketKernel_le_one _
  have hCP : 0 ≤ C * P := mul_nonneg hC hP0
  have hsquare : (f y ^ 2) ^ 2 ≤ (C * P) ^ 2 := by
    have hdiff : 0 ≤ (C * P - f y ^ 2) * (C * P + f y ^ 2) :=
      mul_nonneg (sub_nonneg.mpr (henv y)) (add_nonneg hCP (sq_nonneg _))
    nlinarith
  have hP2 : P ^ 2 ≤ P := by
    have hdiff : 0 ≤ P * (1 - P) :=
      mul_nonneg hP0 (sub_nonneg.mpr hP1)
    nlinarith
  calc
    |f y| ^ (4 : ℝ) = (f y ^ 2) ^ 2 := by
      calc
        |f y| ^ (4 : ℝ) = |f y| ^ (4 : ℕ) := Real.rpow_natCast _ _
        _ = (|f y| ^ 2) ^ 2 := by ring
        _ = (f y ^ 2) ^ 2 := by rw [sq_abs]
    _ ≤ (C * P) ^ 2 := hsquare
    _ = C ^ 2 * P ^ 2 := by ring
    _ ≤ C ^ 2 * P := mul_le_mul_of_nonneg_left hP2 (sq_nonneg _)
    _ = C ^ 2 * ∏ i : Fin 3, bracketKernel (y i) := by rfl

/-- The separable bracket envelope times the literal anisotropic kernel is
integrable.  This is the exact product-measure statement needed to iterate
the one-dimensional scale-uniform estimate. -/
theorem scratch_integrable_prod_bracketKernel_mul_anisotropicBracketKernel
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (p : E3) :
    Integrable (fun y : E3 ↦
      (∏ i : Fin 3, bracketKernel (y i)) *
        anisotropicBracketKernel α t p y) := by
  rw [← (PiLp.volume_preserving_toLp (Fin 3)).integrable_comp_emb
    (MeasurableEquiv.toLp 2 _).measurableEmbedding]
  change Integrable (fun x : Fin 3 → ℝ ↦
    (∏ i : Fin 3, bracketKernel (x i)) *
      ∏ i : Fin 3, bracketKernelAt (t ^ α.weight i) (p i) (x i))
  have hprod (x : Fin 3 → ℝ) :
      (∏ i : Fin 3, bracketKernel (x i)) *
        ∏ i : Fin 3, bracketKernelAt (t ^ α.weight i) (p i) (x i) =
      ∏ i : Fin 3, bracketKernel (x i) *
        bracketKernelAt (t ^ α.weight i) (p i) (x i) := by
    rw [Finset.prod_mul_distrib]
  refine Integrable.congr (Integrable.fintype_prod fun i ↦
    scratch_integrable_bracketKernel_mul_bracketKernelAt
      (pow_pos ht _) (p i)) (Filter.Eventually.of_forall fun x ↦ (hprod x).symm)

/-- Fubini factors the separable envelope against the literal anisotropic
kernel into the three one-dimensional bracket convolutions. -/
theorem scratch_integral_prod_bracketKernel_mul_anisotropicBracketKernel
    (α : Anisotropy) {t : ℝ} (_ht : 0 < t) (p : E3) :
    ∫ y : E3, (∏ i : Fin 3, bracketKernel (y i)) *
        anisotropicBracketKernel α t p y =
      ∏ i : Fin 3, ∫ x : ℝ,
        bracketKernel x * bracketKernelAt (t ^ α.weight i) (p i) x := by
  rw [← (PiLp.volume_preserving_toLp (Fin 3)).integral_comp
    (MeasurableEquiv.toLp 2 _).measurableEmbedding]
  change (∫ x : Fin 3 → ℝ,
    (∏ i : Fin 3, bracketKernel (x i)) *
      ∏ i : Fin 3, bracketKernelAt (t ^ α.weight i) (p i) (x i)) = _
  have hprod (x : Fin 3 → ℝ) :
      (∏ i : Fin 3, bracketKernel (x i)) *
        ∏ i : Fin 3, bracketKernelAt (t ^ α.weight i) (p i) (x i) =
      ∏ i : Fin 3, bracketKernel (x i) *
        bracketKernelAt (t ^ α.weight i) (p i) (x i) := by
    rw [Finset.prod_mul_distrib]
  calc
    (∫ x : Fin 3 → ℝ,
      (∏ i : Fin 3, bracketKernel (x i)) *
        ∏ i : Fin 3, bracketKernelAt (t ^ α.weight i) (p i) (x i)) =
        ∫ x : Fin 3 → ℝ, ∏ i : Fin 3, bracketKernel (x i) *
          bracketKernelAt (t ^ α.weight i) (p i) (x i) :=
      integral_congr_ae (Filter.Eventually.of_forall hprod)
    _ = ∏ i : Fin 3, ∫ x : ℝ,
        bracketKernel x * bracketKernelAt (t ^ α.weight i) (p i) x :=
      integral_fintype_prod_volume_eq_prod
        (fun i (x : ℝ) ↦ bracketKernel x *
          bracketKernelAt (t ^ α.weight i) (p i) x)

/-- A separable product bracket envelope for `f²` gives a scale-uniform
three-dimensional estimate for every literal anisotropic average. -/
theorem scratch_cubeSecondMoment_le_uniform_product_envelope
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (p : E3)
    (f : SchwartzMap E3 ℝ) {C : ℝ} (hC : 0 ≤ C)
    (henv : ∀ y : E3, f y ^ 2 ≤ C * ∏ i : Fin 3, bracketKernel (y i)) :
    cubeSecondMoment α t p f ≤ C *
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
  let R : E3 → ℝ := fun y ↦
    (∏ i : Fin 3, bracketKernel (y i)) *
      anisotropicBracketKernel α t p y
  have hR : Integrable R :=
    scratch_integrable_prod_bracketKernel_mul_anisotropicBracketKernel α ht p
  have hleft : Integrable (fun y : E3 ↦
      f y ^ 2 * anisotropicBracketKernel α t p y) := by
    refine (hR.const_mul C).mono
      ((f.continuous.pow 2).mul
        (continuous_anisotropicBracketKernel α ht p)).aestronglyMeasurable ?_
    filter_upwards [] with y
    have hK : 0 ≤ anisotropicBracketKernel α t p y :=
      anisotropicBracketKernel_nonneg α ht.le p y
    have hRnonneg : 0 ≤ R y := by
      dsimp only [R]
      exact mul_nonneg (Finset.prod_nonneg fun i _ ↦ bracketKernel_nonneg _)
        hK
    rw [Real.norm_eq_abs,
      abs_of_nonneg (mul_nonneg (sq_nonneg _) hK),
      Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hC hRnonneg)]
    calc
      f y ^ 2 * anisotropicBracketKernel α t p y ≤
          (C * ∏ i : Fin 3, bracketKernel (y i)) *
            anisotropicBracketKernel α t p y :=
        mul_le_mul_of_nonneg_right (henv y) hK
      _ = C * R y := by
        dsimp only [R]
        ring
  have hright : Integrable (fun y : E3 ↦ C * R y) := hR.const_mul C
  have hfacnonneg (i : Fin 3) : 0 ≤
      ∫ x : ℝ, bracketKernel x * bracketKernelAt
        (t ^ α.weight i) (p i) x := by
    apply integral_nonneg
    intro x
    exact mul_nonneg (bracketKernel_nonneg _)
      (bracketKernelAt_nonneg (pow_pos ht _).le)
  have hfacbound (i : Fin 3) :
      ∫ x : ℝ, bracketKernel x * bracketKernelAt
        (t ^ α.weight i) (p i) x ≤
        (2 : ℝ) ^ 13 / (1 + |p i|) :=
    scratch_integral_bracketKernel_mul_bracketKernelAt_le_uniform
      (pow_pos ht _) (p i)
  have hprod : (∏ i : Fin 3, ∫ x : ℝ,
      bracketKernel x * bracketKernelAt (t ^ α.weight i) (p i) x) ≤
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
    apply Finset.prod_le_prod
    · intro i _
      exact hfacnonneg i
    · intro i _
      exact hfacbound i
  calc
    cubeSecondMoment α t p f = ∫ y : E3,
        f y ^ 2 * anisotropicBracketKernel α t p y := rfl
    _ ≤ ∫ y : E3, C * R y :=
      MeasureTheory.integral_mono_ae hleft hright
        (Filter.Eventually.of_forall fun y ↦ by
          have hK : 0 ≤ anisotropicBracketKernel α t p y :=
            anisotropicBracketKernel_nonneg α ht.le p y
          calc
            f y ^ 2 * anisotropicBracketKernel α t p y ≤
                (C * ∏ i : Fin 3, bracketKernel (y i)) *
                  anisotropicBracketKernel α t p y :=
              mul_le_mul_of_nonneg_right (henv y) hK
            _ = C * R y := by
              dsimp only [R]
              ring)
    _ = C * ∫ y : E3, R y := by rw [MeasureTheory.integral_const_mul]
    _ = C * ∏ i : Fin 3, ∫ x : ℝ,
        bracketKernel x * bracketKernelAt (t ^ α.weight i) (p i) x := by
      rw [scratch_integral_prod_bracketKernel_mul_anisotropicBracketKernel α ht p]
    _ ≤ C * ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) :=
      mul_le_mul_of_nonneg_left hprod hC

/-- Real Schwartz data satisfy a scale-uniform separable tail estimate for
their exponent-two anisotropic averages. -/
theorem scratch_cubeSecondMoment_le_uniform_of_realSchwartz
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (p : E3)
    (f : SchwartzMap E3 ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧
      cubeSecondMoment α t p f ≤ C *
        ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
  rcases scratch_realSchwartz_sq_le_prod_bracketKernel f with ⟨C, hC, henv⟩
  exact ⟨C, hC,
    scratch_cubeSecondMoment_le_uniform_product_envelope α ht p f hC henv⟩

/-- The preceding bound chooses one coefficient uniformly over all positive
anisotropic scales, which is exactly what is needed to pass through the
literal real supremum in `anisotropicMaximalTwoPower`. -/
theorem scratch_cubeSecondMoment_uniform_of_realSchwartz
    (α : Anisotropy) (f : SchwartzMap E3 ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (t : ℝ), 0 < t → ∀ p : E3,
      cubeSecondMoment α t p f ≤ C *
        ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
  rcases scratch_realSchwartz_sq_le_prod_bracketKernel f with ⟨C, hC, henv⟩
  refine ⟨C, hC, fun t ht p ↦ ?_⟩
  exact scratch_cubeSecondMoment_le_uniform_product_envelope
    α ht p f hC henv

/-- The exponent-two all-positive-scales supremum inherits the same explicit
Schwartz envelope. -/
theorem scratch_anisotropicMaximalTwoPower_le_uniform_of_realSchwartz
    (α : Anisotropy) (f : SchwartzMap E3 ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ p : E3,
      anisotropicMaximalTwoPower α f p ≤ C *
        ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
  rcases scratch_cubeSecondMoment_uniform_of_realSchwartz α f with
    ⟨C, hC, hmoment⟩
  refine ⟨C, hC, fun p ↦ ?_⟩
  unfold anisotropicMaximalTwoPower
  apply csSup_le
  · exact ⟨cubeSecondMoment α 1 p f, ⟨1, by norm_num, rfl⟩⟩
  · rintro a ⟨t, ht, rfl⟩
    exact hmoment t ht p

/-- The product envelope itself is bounded by one radial reciprocal bracket,
so it vanishes along the cocompact filter. -/
theorem scratch_prod_maximalEnvelope_le_radial (p : E3) :
    (∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|))) ≤
      ((2 : ℝ) ^ 13) ^ 3 / (1 + ‖p‖) := by
  have hdenom : 1 + ‖p‖ ≤ ∏ i : Fin 3, (1 + |p i|) :=
    scratch_one_add_norm_le_prod_one_add_abs p
  have hdenompos : 0 < 1 + ‖p‖ := by positivity
  have hinv : (∏ i : Fin 3, (1 + |p i|))⁻¹ ≤ (1 + ‖p‖)⁻¹ :=
    inv_anti₀ hdenompos hdenom
  calc
    (∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|))) =
        ∏ i : Fin 3, ((2 : ℝ) ^ 13 * (1 + |p i|)⁻¹) := by
      apply Finset.prod_congr rfl
      intro i _
      ring
    _ = (∏ _i : Fin 3, (2 : ℝ) ^ 13) *
        ∏ i : Fin 3, (1 + |p i|)⁻¹ := by
      rw [Finset.prod_mul_distrib]
    _ = ((2 : ℝ) ^ 13) ^ 3 *
        (∏ i : Fin 3, (1 + |p i|))⁻¹ := by
      rw [Finset.prod_const, Finset.prod_inv_distrib]
      norm_num
    _ ≤ ((2 : ℝ) ^ 13) ^ 3 * (1 + ‖p‖)⁻¹ :=
      mul_le_mul_of_nonneg_left hinv (by positivity)
    _ = ((2 : ℝ) ^ 13) ^ 3 / (1 + ‖p‖) := by ring

/-- Any nonnegative multiple of the explicit product envelope vanishes at
spatial infinity. -/
theorem scratch_tendsto_uniform_maximalEnvelope
    (C : ℝ) (hC : 0 ≤ C) :
    Tendsto (fun p : E3 ↦ C *
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)))
      (cocompact E3) (𝓝 0) := by
  have hnorm : Tendsto (fun p : E3 ↦ ‖p‖) (cocompact E3) atTop :=
    tendsto_norm_cocompact_atTop
  have hbase : Tendsto (fun p : E3 ↦ 1 + ‖p‖)
      (cocompact E3) atTop :=
    tendsto_atTop_add_const_left _ 1 hnorm
  have hinv : Tendsto (fun p : E3 ↦ (1 + ‖p‖)⁻¹)
      (cocompact E3) (𝓝 0) :=
    tendsto_inv_atTop_zero.comp hbase
  have hradial : Tendsto (fun p : E3 ↦ C *
      (((2 : ℝ) ^ 13) ^ 3 / (1 + ‖p‖)))
      (cocompact E3) (𝓝 0) := by
    have hconst : Tendsto (fun p : E3 ↦ C * ((2 : ℝ) ^ 13) ^ 3)
        (cocompact E3) (𝓝 (C * ((2 : ℝ) ^ 13) ^ 3)) := tendsto_const_nhds
    simpa [div_eq_mul_inv, mul_assoc] using hconst.mul hinv
  apply squeeze_zero
  · intro p
    exact mul_nonneg hC (Finset.prod_nonneg fun i _ ↦ by positivity)
  · intro p
    exact mul_le_mul_of_nonneg_left
      (scratch_prod_maximalEnvelope_le_radial p) hC
  · exact hradial

/-- The full literal exponent-two anisotropic maximal function of a real
Schwartz input tends to zero at spatial infinity.  This closes the tail
branch of the source stopping-time finiteness interface without invoking an
external maximal theorem. -/
theorem scratch_tendsto_anisotropicMaximalTwo_of_realSchwartz
    (α : Anisotropy) (f : SchwartzMap E3 ℝ) :
    Tendsto (anisotropicMaximalTwo α f) (cocompact E3) (𝓝 0) := by
  rcases scratch_anisotropicMaximalTwoPower_le_uniform_of_realSchwartz α f
    with ⟨C, hC, hbound⟩
  have henv : Tendsto (fun p : E3 ↦ C *
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)))
      (cocompact E3) (𝓝 0) :=
    scratch_tendsto_uniform_maximalEnvelope C hC
  have hsqrtenv : Tendsto (fun p : E3 ↦
      √(C * ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|))) )
      (cocompact E3) (𝓝 0) := by
    convert (Real.continuous_sqrt.tendsto 0).comp henv using 1
    · ext p
      rfl
    · simp only [Real.sqrt_zero]
  change Tendsto (fun p : E3 ↦ √(anisotropicMaximalTwoPower α f p))
    (cocompact E3) (𝓝 0)
  apply squeeze_zero
  · intro p
    exact Real.sqrt_nonneg _
  · intro p
    exact Real.sqrt_le_sqrt (hbound p)
  · exact hsqrtenv

/-- The same product-envelope/Fubini calculation applies to the literal
fourth moments. -/
theorem scratch_fourthMoment_le_uniform_product_envelope
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (p : E3)
    (f : SchwartzMap E3 ℝ) {C : ℝ} (hC : 0 ≤ C)
    (henv : ∀ y : E3, |f y| ^ (4 : ℝ) ≤ C *
      ∏ i : Fin 3, bracketKernel (y i)) :
    fourthMoment α t p f ≤ C *
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
  let R : E3 → ℝ := fun y ↦
    (∏ i : Fin 3, bracketKernel (y i)) *
      anisotropicBracketKernel α t p y
  have hR : Integrable R :=
    scratch_integrable_prod_bracketKernel_mul_anisotropicBracketKernel α ht p
  have hleft : Integrable (fun y : E3 ↦
      |f y| ^ (4 : ℝ) * anisotropicBracketKernel α t p y) := by
    refine (hR.const_mul C).mono
      ((f.continuous.abs.rpow_const (fun _ ↦ Or.inr (by norm_num))).mul
        (continuous_anisotropicBracketKernel α ht p)).aestronglyMeasurable ?_
    filter_upwards [] with y
    have hK : 0 ≤ anisotropicBracketKernel α t p y :=
      anisotropicBracketKernel_nonneg α ht.le p y
    have hRnonneg : 0 ≤ R y := by
      dsimp only [R]
      exact mul_nonneg (Finset.prod_nonneg fun i _ ↦ bracketKernel_nonneg _)
        hK
    rw [Real.norm_eq_abs,
      abs_of_nonneg (mul_nonneg (Real.rpow_nonneg (abs_nonneg _) _) hK),
      Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hC hRnonneg)]
    calc
      |f y| ^ (4 : ℝ) * anisotropicBracketKernel α t p y ≤
          (C * ∏ i : Fin 3, bracketKernel (y i)) *
            anisotropicBracketKernel α t p y :=
        mul_le_mul_of_nonneg_right (henv y) hK
      _ = C * R y := by
        dsimp only [R]
        ring
  have hright : Integrable (fun y : E3 ↦ C * R y) := hR.const_mul C
  have hfacnonneg (i : Fin 3) : 0 ≤
      ∫ x : ℝ, bracketKernel x * bracketKernelAt
        (t ^ α.weight i) (p i) x := by
    apply integral_nonneg
    intro x
    exact mul_nonneg (bracketKernel_nonneg _)
      (bracketKernelAt_nonneg (pow_pos ht _).le)
  have hfacbound (i : Fin 3) :
      ∫ x : ℝ, bracketKernel x * bracketKernelAt
        (t ^ α.weight i) (p i) x ≤
        (2 : ℝ) ^ 13 / (1 + |p i|) :=
    scratch_integral_bracketKernel_mul_bracketKernelAt_le_uniform
      (pow_pos ht _) (p i)
  have hprod : (∏ i : Fin 3, ∫ x : ℝ,
      bracketKernel x * bracketKernelAt (t ^ α.weight i) (p i) x) ≤
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
    apply Finset.prod_le_prod
    · intro i _
      exact hfacnonneg i
    · intro i _
      exact hfacbound i
  calc
    fourthMoment α t p f = ∫ y : E3,
        |f y| ^ (4 : ℝ) * anisotropicBracketKernel α t p y := rfl
    _ ≤ ∫ y : E3, C * R y :=
      MeasureTheory.integral_mono_ae hleft hright
        (Filter.Eventually.of_forall fun y ↦ by
          have hK : 0 ≤ anisotropicBracketKernel α t p y :=
            anisotropicBracketKernel_nonneg α ht.le p y
          calc
            |f y| ^ (4 : ℝ) * anisotropicBracketKernel α t p y ≤
                (C * ∏ i : Fin 3, bracketKernel (y i)) *
                  anisotropicBracketKernel α t p y :=
              mul_le_mul_of_nonneg_right (henv y) hK
            _ = C * R y := by
              dsimp only [R]
              ring)
    _ = C * ∫ y : E3, R y := by rw [MeasureTheory.integral_const_mul]
    _ = C * ∏ i : Fin 3, ∫ x : ℝ,
        bracketKernel x * bracketKernelAt (t ^ α.weight i) (p i) x := by
      rw [scratch_integral_prod_bracketKernel_mul_anisotropicBracketKernel α ht p]
    _ ≤ C * ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) :=
      mul_le_mul_of_nonneg_left hprod hC

/-- A single fourth-moment envelope coefficient works simultaneously at all
positive anisotropic scales. -/
theorem scratch_fourthMoment_uniform_of_realSchwartz
    (α : Anisotropy) (f : SchwartzMap E3 ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (t : ℝ), 0 < t → ∀ p : E3,
      fourthMoment α t p f ≤ C *
        ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
  rcases scratch_realSchwartz_rpow_four_le_prod_bracketKernel f with
    ⟨C, hC, henv⟩
  refine ⟨C, hC, fun t ht p ↦ ?_⟩
  exact scratch_fourthMoment_le_uniform_product_envelope α ht p f hC henv

/-- The exponent-four all-positive-scales maximal power inherits the same
explicit product tail. -/
theorem scratch_anisotropicMaximalFourPower_le_uniform_of_realSchwartz
    (α : Anisotropy) (f : SchwartzMap E3 ℝ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ p : E3,
      anisotropicMaximalFourPower α f p ≤ C *
        ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) := by
  rcases scratch_fourthMoment_uniform_of_realSchwartz α f with
    ⟨C, hC, hmoment⟩
  refine ⟨C, hC, fun p ↦ ?_⟩
  unfold anisotropicMaximalFourPower
  apply csSup_le
  · exact ⟨fourthMoment α 1 p f, ⟨1, by norm_num, rfl⟩⟩
  · rintro a ⟨t, ht, rfl⟩
    exact hmoment t ht p

/-- Taking the positive fourth root preserves the cocompact tail of the
explicit maximal envelope. -/
theorem scratch_tendsto_uniform_maximalEnvelope_rpow_four_inv
    (C : ℝ) (hC : 0 ≤ C) :
    Tendsto (fun p : E3 ↦ (C *
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|))) ^ ((4 : ℝ)⁻¹))
      (cocompact E3) (𝓝 0) := by
  have henv := scratch_tendsto_uniform_maximalEnvelope C hC
  have hcont := (Real.continuous_rpow_const
    (by positivity : 0 ≤ (4 : ℝ)⁻¹)).tendsto 0
  convert hcont.comp henv using 1
  · ext p
    rfl
  · rw [Real.zero_rpow (by positivity : (4 : ℝ)⁻¹ ≠ 0)]

/-- The full literal exponent-four anisotropic maximal function of a real
Schwartz input tends to zero at spatial infinity. -/
theorem scratch_tendsto_anisotropicMaximalFour_of_realSchwartz
    (α : Anisotropy) (f : SchwartzMap E3 ℝ) :
    Tendsto (anisotropicMaximalFour α f) (cocompact E3) (𝓝 0) := by
  rcases scratch_anisotropicMaximalFourPower_le_uniform_of_realSchwartz α f
    with ⟨C, hC, hbound⟩
  rcases scratch_fourthMoment_uniform_of_realSchwartz α f with
    ⟨D, hD, hmoment⟩
  have henv : Tendsto (fun p : E3 ↦ (C *
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|))) ^ ((4 : ℝ)⁻¹))
      (cocompact E3) (𝓝 0) :=
    scratch_tendsto_uniform_maximalEnvelope_rpow_four_inv C hC
  have hHnonneg (p : E3) : 0 ≤ C *
      ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|)) :=
    mul_nonneg hC (Finset.prod_nonneg fun i _ ↦ by positivity)
  have hmaxnonneg (p : E3) : 0 ≤ anisotropicMaximalFourPower α f p := by
    let H : ℝ := D * ∏ i : Fin 3, ((2 : ℝ) ^ 13 / (1 + |p i|))
    have hbdd : BddAbove {a : ℝ | ∃ t : ℝ, 0 < t ∧
        a = fourthMoment α t p f} := by
      refine ⟨H, ?_⟩
      rintro a ⟨t, ht, rfl⟩
      exact hmoment t ht p
    calc
      0 ≤ fourthMoment α 1 p f := fourthMoment_nonneg α (by norm_num) p f
      _ ≤ anisotropicMaximalFourPower α f p := by
        unfold anisotropicMaximalFourPower
        apply le_csSup hbdd
        exact ⟨1, by norm_num, rfl⟩
  change Tendsto (fun p : E3 ↦
      (anisotropicMaximalFourPower α f p) ^ ((4 : ℝ)⁻¹))
    (cocompact E3) (𝓝 0)
  apply squeeze_zero
  · intro p
    exact Real.rpow_nonneg (hmaxnonneg p) _
  · intro p
    exact Real.rpow_le_rpow (hmaxnonneg p) (hbound p) (by positivity)
  · exact henv

/-- All four literal stopping maximal functions of an initial real Schwartz
tuple vanish at spatial infinity. -/
theorem scratch_tendsto_sourceStoppingMaximal_of_initialModelRealSchwartz
    (α : Anisotropy) (F : InitialModelSchwartzInput) :
    ∀ j : Fin 4, Tendsto (sourceStoppingMaximal α (InitialModelRealInput F) j)
      (cocompact E3) (𝓝 0) := by
  apply tendsto_sourceStoppingMaximal_of_tails α (InitialModelRealInput F)
  · simpa only [InitialModelRealInput] using
      scratch_tendsto_anisotropicMaximalTwo_of_realSchwartz α (F 3)
  · intro j hj
    simpa only [InitialModelRealInput] using
      scratch_tendsto_anisotropicMaximalFour_of_realSchwartz α (F j)

/-- Consequently, every source stopping level of an initial real Schwartz
tuple has finite Lebesgue measure.  This is the direct tail-based discharge
of the formerly external maximal-function hypothesis. -/
theorem scratch_sourceStopping_coordinateLevel_finite_of_initialModelRealSchwartz
    (α : Anisotropy) (F : InitialModelSchwartzInput) :
    ∀ (j : Fin 4) (m : ℤ),
      volume (sourceStoppingMaximalLevelSetAt α
        (InitialModelRealInput F) j m) ≠ ∞ := by
  apply sourceStopping_coordinateLevel_finite_of_maximal_tails
    α (InitialModelRealInput F)
  · simpa only [InitialModelRealInput] using
      scratch_tendsto_anisotropicMaximalTwo_of_realSchwartz α (F 3)
  · intro j hj
    simpa only [InitialModelRealInput] using
      scratch_tendsto_anisotropicMaximalFour_of_realSchwartz α (F j)

/-- The finite active stopping-forest estimate now has its last stopping
finiteness hypothesis discharged for a nonzero real Schwartz tuple. -/
theorem scratch_activeStoppingForest_bound_of_realSchwartz_auto_of_ne_zero
    (α : Anisotropy) (S : BoxCollection α) (hS : IsConvexCollection α S)
    (u : E3) (c : ℝ → ℝ) (F : InitialModelSchwartzInput)
    (q σ : Fin 4 → ℝ) (hq : ∀ j, 0 < q j)
    (hFnonzero : ∀ j, F j ≠ 0)
    (hcmeas : Measurable c) (hc : ∀ t : ℝ, |c t| ≤ 1) :
    ∃ C : ℝ, 0 ≤ C ∧
      |expandedModelLocalForm α S u c (InitialModelRealInput F)| ≤
        C * sourceWeight u ^ 75 *
          SourceStoppingCoordinateEnvelope α S
            (InitialModelRealInput F) q σ
              (initialModel_sourceStoppingData_all_pos_of_ne_zero
                α S F hFnonzero) := by
  apply activeStoppingForest_bound_of_realSchwartz_auto_of_ne_zero
    α S hS u c F q σ hq hFnonzero hcmeas hc
  exact scratch_sourceStopping_coordinateLevel_finite_of_initialModelRealSchwartz α F

end

end Twisted
end Auto
