/- Copyright (c) 2026 Joris Roos. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory
open scoped ENNReal

noncomputable section

/-! ## Positivity interface for scalar stopping distributions

These elementary facts expose the positivity needed to feed the literal
stopping maximal functions into the finite layer-cake lemma.  They do not
assert the missing strong maximal inequality.
-/

/-- The fourth-power maximal envelope is nonnegative on bounded continuous
data because it dominates its positive unit-scale moment. -/
theorem scratch_anisotropicMaximalFourPower_nonneg_of_boundedContinuous
    (α : Anisotropy) (f : E3 → ℝ) (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B) (p : E3) :
    0 ≤ anisotropicMaximalFourPower α f p := by
  calc
    0 ≤ fourthMoment α 1 p f := fourthMoment_nonneg α (by norm_num) p f
    _ ≤ anisotropicMaximalFourPower α f p := by
      unfold anisotropicMaximalFourPower
      apply le_csSup (bddAbove_anisotropicMaximalFourPower
        α f hfcont B hB hfB p)
      exact ⟨1, by norm_num, rfl⟩

/-- The literal fourth-root maximal size is nonnegative on bounded continuous
data. -/
theorem scratch_anisotropicMaximalFour_nonneg_of_boundedContinuous
    (α : Anisotropy) (f : E3 → ℝ) (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B) (p : E3) :
    0 ≤ anisotropicMaximalFour α f p := by
  exact Real.rpow_nonneg
    (scratch_anisotropicMaximalFourPower_nonneg_of_boundedContinuous
      α f hfcont B hB hfB p) _

/-- Every literal stopping maximal function is nonnegative when its four
input components are bounded and continuous. -/
theorem scratch_sourceStoppingMaximal_nonneg_of_boundedContinuous
    (α : Anisotropy) (f : ModelRealInput) (hcont : ∀ j, Continuous (f j))
    (hbound : ∀ j, ∃ B : ℝ, 0 ≤ B ∧ ∀ y, |f j y| ≤ B)
    (j : Fin 4) (p : E3) :
    0 ≤ sourceStoppingMaximal α f j p := by
  by_cases hj : j = 3
  · subst j
    simp only [sourceStoppingMaximal, ↓reduceIte]
    exact Real.sqrt_nonneg _
  · rcases hbound j with ⟨B, hB, hfB⟩
    simp only [sourceStoppingMaximal, hj, ite_false]
    exact scratch_anisotropicMaximalFour_nonneg_of_boundedContinuous
      α (f j) (hcont j) B hB hfB p

/-- A strict literal stopping level lies in the non-strict power level set
needed by the finite scalar layer-cake estimate. -/
theorem scratch_sourceStoppingMaximalLevelSetAt_subset_rpowLevel
    (α : Anisotropy) (f : ModelRealInput) (hcont : ∀ j, Continuous (f j))
    (hbound : ∀ j, ∃ B : ℝ, 0 ≤ B ∧ ∀ y, |f j y| ≤ B)
    (j : Fin 4) (m : ℤ) {r : ℝ} (hr : 0 < r) :
    sourceStoppingMaximalLevelSetAt α f j m ⊆
      {p | (sourceStoppingComparisonConstant j * (2 : ℝ) ^ (m - 1)) ^ r ≤
        (sourceStoppingMaximal α f j p) ^ r} := by
  intro p hp
  have htheta : 0 ≤ sourceStoppingComparisonConstant j * (2 : ℝ) ^ (m - 1) :=
    (mul_pos (sourceStoppingComparisonConstant_pos j) (zpow_pos (by norm_num) _)).le
  have hmax : 0 ≤ sourceStoppingMaximal α f j p :=
    scratch_sourceStoppingMaximal_nonneg_of_boundedContinuous α f hcont hbound j p
  have hlevel : sourceStoppingComparisonConstant j * (2 : ℝ) ^ (m - 1) <
      sourceStoppingMaximal α f j p := hp
  exact Real.rpow_le_rpow htheta hlevel.le hr.le

end

end Twisted
end Auto
