/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto.Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators ENNReal RealInnerProductSpace

noncomputable section

/-- The scalar fourth moment used to instantiate the `s = 4` branch of the
anisotropic maximal-size estimate. -/
noncomputable def scratch_fourthMoment
    (α : Anisotropy) (t : ℝ) (p : E3) (f : E3 → ℝ) : ℝ :=
  ∫ y : E3, |f y| ^ (4 : ℝ) * anisotropicBracketKernel α t p y

/-- Bounded continuous data make the fourth-moment integrand integrable at
every positive anisotropic center--scale point. -/
theorem scratch_integrable_fourthMoment_integrand
    (α : Anisotropy) {t : ℝ} (ht : 0 < t) (p : E3) (f : E3 → ℝ)
    (hfcont : Continuous f)
    (hfbound : ∃ B : ℝ, 0 ≤ B ∧ ∀ y, |f y| ≤ B) :
    Integrable (fun y : E3 ↦ |f y| ^ (4 : ℝ) *
      anisotropicBracketKernel α t p y) := by
  rcases hfbound with ⟨B, hB, hfB⟩
  let K : E3 → ℝ := anisotropicBracketKernel α t p
  have hK : Integrable K := integrable_anisotropicBracketKernel α ht p
  have hmeas : AEStronglyMeasurable
      (fun y : E3 ↦ |f y| ^ (4 : ℝ) * K y) :=
    ((hfcont.abs.rpow_const (fun _ ↦ Or.inr (by norm_num))).mul
      (continuous_anisotropicBracketKernel α ht p)).aestronglyMeasurable
  refine (hK.const_mul (B ^ (4 : ℝ))).mono hmeas ?_
  filter_upwards [] with y
  have hpow : |f y| ^ (4 : ℝ) ≤ B ^ (4 : ℝ) :=
    Real.rpow_le_rpow (abs_nonneg _) (hfB y) (by norm_num)
  have hKnonneg : 0 ≤ K y :=
    anisotropicBracketKernel_nonneg α ht.le p y
  rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg
    (Real.rpow_nonneg (abs_nonneg _) _) hKnonneg),
    Real.norm_eq_abs, abs_of_nonneg (mul_nonneg
      (Real.rpow_nonneg hB _) hKnonneg)]
  exact mul_le_mul_of_nonneg_right hpow hKnonneg

/-- The fourth moment is nonnegative at every nonnegative scale. -/
theorem scratch_fourthMoment_nonneg
    (α : Anisotropy) {t : ℝ} (ht : 0 ≤ t) (p : E3) (f : E3 → ℝ) :
    0 ≤ scratch_fourthMoment α t p f := by
  unfold scratch_fourthMoment
  apply integral_nonneg
  intro y
  exact mul_nonneg (Real.rpow_nonneg (abs_nonneg _) _)
    (anisotropicBracketKernel_nonneg α ht p y)

/-- At a literal box center and scale, the scalar fourth moment is exactly
the fourth local power. -/
theorem scratch_fourthMoment_at_box_eq_boxLocalPower
    (α : Anisotropy) (q : AnisoBox α) (f : E3 → ℝ) :
    scratch_fourthMoment α (boxLength q) (boxCenter α q) f =
      boxLocalPower α 4 f q := by
  unfold scratch_fourthMoment boxLocalPower
  rfl

/-- The exponent-four maximal power, before taking its literal fourth root.
This is the `s = 4` specialization of the source maximal-size definition. -/
noncomputable def scratch_anisotropicMaximalFourPower
    (α : Anisotropy) (f : E3 → ℝ) (p : E3) : ℝ :=
  sSup {a : ℝ | ∃ t : ℝ, 0 < t ∧ a = scratch_fourthMoment α t p f}

/-- The literal fourth-root maximal size used in the stopping construction. -/
noncomputable def scratch_anisotropicMaximalFour
    (α : Anisotropy) (f : E3 → ℝ) (p : E3) : ℝ :=
  scratch_anisotropicMaximalFourPower α f p ^ ((4 : ℝ)⁻¹)

/-- Bounded continuous inputs make the real supremum defining the fourth
maximal power bounded above. -/
theorem scratch_bddAbove_anisotropicMaximalFourPower
    (α : Anisotropy) (f : E3 → ℝ) (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B) (p : E3) :
    BddAbove {a : ℝ | ∃ t : ℝ, 0 < t ∧
      a = scratch_fourthMoment α t p f} := by
  refine ⟨B ^ (4 : ℝ) * (2 / 9 : ℝ) ^ 3, ?_⟩
  rintro a ⟨t, ht, rfl⟩
  let K : E3 → ℝ := anisotropicBracketKernel α t p
  have hleft : Integrable (fun y : E3 ↦ |f y| ^ (4 : ℝ) * K y) := by
    simpa [K] using scratch_integrable_fourthMoment_integrand α ht p f
      hfcont ⟨B, hB, hfB⟩
  have hright : Integrable (fun y : E3 ↦ B ^ (4 : ℝ) * K y) := by
    exact (integrable_anisotropicBracketKernel α ht p).const_mul _
  have hpointwise (y : E3) :
      |f y| ^ (4 : ℝ) * K y ≤ B ^ (4 : ℝ) * K y := by
    have hK : 0 ≤ K y := anisotropicBracketKernel_nonneg α ht.le p y
    have hpow : |f y| ^ (4 : ℝ) ≤ B ^ (4 : ℝ) :=
      Real.rpow_le_rpow (abs_nonneg _) (hfB y) (by norm_num)
    exact mul_le_mul_of_nonneg_right hpow hK
  calc
    scratch_fourthMoment α t p f = ∫ y : E3, |f y| ^ (4 : ℝ) * K y := by rfl
    _ ≤ ∫ y : E3, B ^ (4 : ℝ) * K y :=
      MeasureTheory.integral_mono_ae hleft hright
        (Filter.Eventually.of_forall hpointwise)
    _ = B ^ (4 : ℝ) * ∫ y : E3, K y := by
      rw [MeasureTheory.integral_const_mul]
    _ = B ^ (4 : ℝ) * (2 / 9 : ℝ) ^ 3 := by
      rw [integral_anisotropicBracketKernel α ht p]

/-- Each positive-scale fourth moment is bounded by the literal maximal
power. -/
theorem scratch_fourthMoment_le_anisotropicMaximalFourPower
    (α : Anisotropy) (f : E3 → ℝ) (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B)
    (p : E3) {t : ℝ} (ht : 0 < t) :
    scratch_fourthMoment α t p f ≤ scratch_anisotropicMaximalFourPower α f p := by
  unfold scratch_anisotropicMaximalFourPower
  apply le_csSup (scratch_bddAbove_anisotropicMaximalFourPower
    α f hfcont B hB hfB p)
  exact ⟨t, ht, rfl⟩

/-- The fixed-scale comparison gives the fourth-power form of the source
maximal-size estimate on each box. -/
theorem scratch_boxLocalPower_four_le_anisotropicMaximalFourPower
    (α : Anisotropy) (q : AnisoBox α) {p : E3}
    (hp : p ∈ boxSet α q) (f : E3 → ℝ)
    (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B) :
    (2 / 3 : ℝ) ^ 30 * boxLocalPower α 4 f q ≤
      scratch_anisotropicMaximalFourPower α f p := by
  let K₀ : E3 → ℝ :=
    anisotropicBracketKernel α (boxLength q) (boxCenter α q)
  let Kp : E3 → ℝ := anisotropicBracketKernel α (boxLength q) p
  have hleft : Integrable (fun y : E3 ↦
      (2 / 3 : ℝ) ^ 30 * (|f y| ^ (4 : ℝ) * K₀ y)) := by
    exact (scratch_integrable_fourthMoment_integrand α (boxLength_pos q)
      (boxCenter α q) f hfcont ⟨B, hB, hfB⟩).const_mul _
  have hright : Integrable (fun y : E3 ↦ |f y| ^ (4 : ℝ) * Kp y) := by
    exact scratch_integrable_fourthMoment_integrand α (boxLength_pos q)
      p f hfcont ⟨B, hB, hfB⟩
  have hpointwise (y : E3) :
      (2 / 3 : ℝ) ^ 30 * (|f y| ^ (4 : ℝ) * K₀ y) ≤
        |f y| ^ (4 : ℝ) * Kp y := by
    have hkernel : (2 / 3 : ℝ) ^ 30 * K₀ y ≤ Kp y := by
      exact boxCenterKernel_le_anisotropicBracketKernel α q
        (boxSet_subset_boxClosedSet α q hp) y
    calc
      (2 / 3 : ℝ) ^ 30 * (|f y| ^ (4 : ℝ) * K₀ y) =
          |f y| ^ (4 : ℝ) * ((2 / 3 : ℝ) ^ 30 * K₀ y) := by ring
      _ ≤ |f y| ^ (4 : ℝ) * Kp y :=
        mul_le_mul_of_nonneg_left hkernel (Real.rpow_nonneg (abs_nonneg _) _)
  calc
    (2 / 3 : ℝ) ^ 30 * boxLocalPower α 4 f q =
        ∫ y : E3, (2 / 3 : ℝ) ^ 30 *
          (|f y| ^ (4 : ℝ) * K₀ y) := by
            change (2 / 3 : ℝ) ^ 30 *
                (∫ y : E3, |f y| ^ (4 : ℝ) * K₀ y) = _
            rw [← MeasureTheory.integral_const_mul]
    _ ≤ ∫ y : E3, |f y| ^ (4 : ℝ) * Kp y :=
      MeasureTheory.integral_mono_ae hleft hright
        (Filter.Eventually.of_forall hpointwise)
    _ = scratch_fourthMoment α (boxLength q) p f := by rfl
    _ ≤ scratch_anisotropicMaximalFourPower α f p :=
      scratch_fourthMoment_le_anisotropicMaximalFourPower α f hfcont
        B hB hfB p (boxLength_pos q)

/-- Maximal stopping roots which are covered by a measurable region have
total box mass at most the volume of that region.  This is the finite,
pairwise-disjoint packing step in the stopping-time argument. -/
theorem scratch_sum_boxMass_stoppingRoots_le_measure {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ) (E : Set E3)
    (hcover : ∀ Q ∈ stoppingRoots α S s f n, boxSet α Q ⊆ E) :
    ∑ Q ∈ stoppingRoots α S s f n, ENNReal.ofReal (boxMass α Q) ≤ volume E := by
  calc
    ∑ Q ∈ stoppingRoots α S s f n, ENNReal.ofReal (boxMass α Q) =
        ∑ Q ∈ stoppingRoots α S s f n, volume (boxSet α Q) := by
          apply Finset.sum_congr rfl
          intro Q hQ
          rw [volume_boxSet_eq_boxMass]
    _ = volume (⋃ Q ∈ stoppingRoots α S s f n, boxSet α Q) := by
      symm
      exact MeasureTheory.measure_biUnion_finset
        (pairwiseDisjoint_stoppingRoots α S s f n)
        (fun Q _ ↦ measurableSet_boxSet α Q)
    _ ≤ volume E := by
      apply MeasureTheory.measure_mono
      intro x hx
      rcases Set.mem_iUnion.mp hx with ⟨Q, hx⟩
      rcases Set.mem_iUnion.mp hx with ⟨hQ, hxQ⟩
      exact hcover Q (by simpa using hQ) hxQ

/-- The exponent-four maximal-size estimate in literal fourth-root form.
The comparison constant is kept as the fourth root of the fixed-scale
power constant, which is definitionally suited to the stopping argument. -/
theorem scratch_boxLocalSize_four_le_anisotropicMaximalFour
    (α : Anisotropy) (q : AnisoBox α) {p : E3}
    (hp : p ∈ boxSet α q) (f : E3 → ℝ)
    (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B) :
    ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) * boxLocalSize α 4 f q ≤
      scratch_anisotropicMaximalFour α f p := by
  have hpower : 0 ≤ boxLocalPower α 4 f q := by
    unfold boxLocalPower
    apply integral_nonneg
    intro y
    exact mul_nonneg (Real.rpow_nonneg (abs_nonneg (f y)) _)
      (anisotropicBracketKernel_nonneg α (boxLength_pos q).le
        (boxCenter α q) y)
  have hmax : 0 ≤ scratch_anisotropicMaximalFourPower α f p := by
    calc
      0 ≤ scratch_fourthMoment α 1 p f :=
        scratch_fourthMoment_nonneg α (by norm_num) p f
      _ ≤ scratch_anisotropicMaximalFourPower α f p :=
        scratch_fourthMoment_le_anisotropicMaximalFourPower α f hfcont
          B hB hfB p (by norm_num)
  have hcomparison :
      (2 / 3 : ℝ) ^ 30 * boxLocalPower α 4 f q ≤
        scratch_anisotropicMaximalFourPower α f p :=
    scratch_boxLocalPower_four_le_anisotropicMaximalFourPower α q hp f
      hfcont B hB hfB
  change ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) *
      (boxLocalPower α 4 f q) ^ ((4 : ℝ)⁻¹) ≤
        (scratch_anisotropicMaximalFourPower α f p) ^ ((4 : ℝ)⁻¹)
  rw [← Real.mul_rpow (pow_nonneg (by norm_num) _) hpower]
  exact Real.rpow_le_rpow
    (mul_nonneg (pow_nonneg (by norm_num) _) hpower) hcomparison (by norm_num)

/-- The fourth-root comparison constant is the source constant
`(2/3)^(30/4)`. -/
theorem scratch_fourthMaximalComparisonConstant_eq :
    ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) =
      (2 / 3 : ℝ) ^ ((30 : ℝ) / 4) := by
  rw [← Real.rpow_natCast]
  rw [← Real.rpow_mul (by norm_num)]
  congr 1

/-- A finite ancestor supremum inherits any common upper bound after
multiplication by a nonnegative scalar. -/
theorem scratch_mul_stoppingData_le_of_ancestor_bound
    (α : Anisotropy) (S : BoxCollection α) (s : ℝ) (f : E3 → ℝ)
    (c M : ℝ) {q : AnisoBox α} (hq : q ∈ S) (hc : 0 ≤ c)
    (hbound : ∀ r ∈ stoppingAncestors α S q,
      c * boxLocalSize α s f r ≤ M) :
    c * stoppingData α S s f q ≤ M := by
  rw [stoppingData_eq_sup' α S s f hq]
  rw [Finset.mul₀_sup' hc (boxLocalSize α s f)
    (stoppingAncestors α S q) (stoppingAncestors_nonempty α S hq)]
  apply Finset.sup'_le
  intro r hr
  exact hbound r hr

/-- The exponent-two stopping datum is pointwise controlled by the
anisotropic maximal size at every point of its box. -/
theorem scratch_stoppingData_two_le_anisotropicMaximalTwo
    (α : Anisotropy) (S : BoxCollection α) {q : AnisoBox α}
    (hq : q ∈ S) {p : E3} (hp : p ∈ boxSet α q) (f : E3 → ℝ)
    (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B) :
    (2 / 3 : ℝ) ^ 15 * stoppingData α S 2 f q ≤
      anisotropicMaximalTwo α f p := by
  classical
  apply scratch_mul_stoppingData_le_of_ancestor_bound α S 2 f
    ((2 / 3 : ℝ) ^ 15) (anisotropicMaximalTwo α f p) hq
    (pow_nonneg (by norm_num) _)
  intro r hr
  rw [stoppingAncestors, Finset.mem_filter] at hr
  exact boxLocalSize_two_le_anisotropicMaximalTwo α r (hr.2 hp) f
    hfcont B hB hfB

/-- The exponent-four stopping datum is pointwise controlled by the literal
fourth-root anisotropic maximal size at every point of its box. -/
theorem scratch_stoppingData_four_le_anisotropicMaximalFour
    (α : Anisotropy) (S : BoxCollection α) {q : AnisoBox α}
    (hq : q ∈ S) {p : E3} (hp : p ∈ boxSet α q) (f : E3 → ℝ)
    (hfcont : Continuous f)
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f y| ≤ B) :
    ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) * stoppingData α S 4 f q ≤
      scratch_anisotropicMaximalFour α f p := by
  classical
  apply scratch_mul_stoppingData_le_of_ancestor_bound α S 4 f
    (((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹))
    (scratch_anisotropicMaximalFour α f p) hq
    (Real.rpow_nonneg (pow_nonneg (by norm_num) _) _)
  intro r hr
  rw [stoppingAncestors, Finset.mem_filter] at hr
  exact scratch_boxLocalSize_four_le_anisotropicMaximalFour α r (hr.2 hp) f
    hfcont B hB hfB

/-- A stopping root lies in the corresponding maximal superlevel set as
soon as its ancestor datum admits a pointwise maximal bound. -/
theorem scratch_stoppingRoot_boxSet_subset_maximalLevel {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (Q : AnisoBox α) (hQ : Q ∈ stoppingRoots α S s f n)
    (j : Fin d) (c : ℝ) (M : E3 → ℝ) (hc : 0 < c)
    (hdata : ∀ p ∈ boxSet α Q,
      c * stoppingData α S (s j) (f j) Q ≤ M p) :
    boxSet α Q ⊆ {p | c * (2 : ℝ) ^ (n j - 1) < M p} := by
  intro p hp
  have hQlevel : Q ∈ stoppingLevel α S s f n :=
    (mem_stoppingRoots_iff α S s f n Q).mp hQ |>.1
  have hlower : (2 : ℝ) ^ (n j - 1) <
      stoppingData α S (s j) (f j) Q :=
    (mem_stoppingLevel_iff α S s f n Q).mp hQlevel |>.2 j |>.1
  exact (mul_lt_mul_of_pos_left hlower hc).trans_le (hdata p hp)

/-- In the `s = 2` branch, every stopping root is covered by the exact
anisotropic maximal superlevel region used in the finite packing sum. -/
theorem scratch_stoppingRoot_two_boxSet_subset_maximalLevel {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (Q : AnisoBox α) (hQ : Q ∈ stoppingRoots α S s f n)
    (j : Fin d) (hsj : s j = 2)
    (hfcont : Continuous (f j))
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f j y| ≤ B) :
    boxSet α Q ⊆ {p |
      (2 / 3 : ℝ) ^ 15 * (2 : ℝ) ^ (n j - 1) <
        anisotropicMaximalTwo α (f j) p} := by
  apply scratch_stoppingRoot_boxSet_subset_maximalLevel α S s f n Q hQ j
    ((2 / 3 : ℝ) ^ 15) (anisotropicMaximalTwo α (f j))
    (pow_pos (by norm_num) _)
  intro p hp
  simpa [hsj] using scratch_stoppingData_two_le_anisotropicMaximalTwo
    α S ((mem_stoppingLevel_iff α S s f n Q).mp
      ((mem_stoppingRoots_iff α S s f n Q).mp hQ).1 |>.1) hp (f j)
      hfcont B hB hfB

/-- The same stopping-root coverage is available for the `s = 4` branch. -/
theorem scratch_stoppingRoot_four_boxSet_subset_maximalLevel {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (Q : AnisoBox α) (hQ : Q ∈ stoppingRoots α S s f n)
    (j : Fin d) (hsj : s j = 4)
    (hfcont : Continuous (f j))
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f j y| ≤ B) :
    boxSet α Q ⊆ {p |
      ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) *
          (2 : ℝ) ^ (n j - 1) <
        scratch_anisotropicMaximalFour α (f j) p} := by
  apply scratch_stoppingRoot_boxSet_subset_maximalLevel α S s f n Q hQ j
    (((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹))
    (scratch_anisotropicMaximalFour α (f j))
    (Real.rpow_pos_of_pos (pow_pos (by norm_num) _) _)
  intro p hp
  simpa [hsj] using scratch_stoppingData_four_le_anisotropicMaximalFour
    α S ((mem_stoppingLevel_iff α S s f n Q).mp
      ((mem_stoppingRoots_iff α S s f n Q).mp hQ).1 |>.1) hp (f j)
      hfcont B hB hfB

/-- The pairwise-disjoint roots of an exponent-two stopping level satisfy
the finite maximal-superlevel packing bound. -/
theorem scratch_sum_boxMass_stoppingRoots_two_le_maximalLevelMeasure {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (j : Fin d) (hsj : s j = 2)
    (hfcont : Continuous (f j))
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f j y| ≤ B) :
    ∑ Q ∈ stoppingRoots α S s f n, ENNReal.ofReal (boxMass α Q) ≤
      volume {p |
        (2 / 3 : ℝ) ^ 15 * (2 : ℝ) ^ (n j - 1) <
          anisotropicMaximalTwo α (f j) p} := by
  apply scratch_sum_boxMass_stoppingRoots_le_measure α S s f n
  intro Q hQ
  exact scratch_stoppingRoot_two_boxSet_subset_maximalLevel α S s f n Q hQ
    j hsj hfcont B hB hfB

/-- The corresponding finite packing bound for the exponent-four stopping
branch. -/
theorem scratch_sum_boxMass_stoppingRoots_four_le_maximalLevelMeasure {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (j : Fin d) (hsj : s j = 4)
    (hfcont : Continuous (f j))
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f j y| ≤ B) :
    ∑ Q ∈ stoppingRoots α S s f n, ENNReal.ofReal (boxMass α Q) ≤
      volume {p |
        ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) *
            (2 : ℝ) ^ (n j - 1) <
          scratch_anisotropicMaximalFour α (f j) p} := by
  apply scratch_sum_boxMass_stoppingRoots_le_measure α S s f n
  intro Q hQ
  exact scratch_stoppingRoot_four_boxSet_subset_maximalLevel α S s f n Q hQ
    j hsj hfcont B hB hfB

/-- The finite root packing inequality in real box masses, once the covering
region has finite volume. -/
theorem scratch_sum_boxMass_stoppingRoots_le_measure_toReal {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ) (E : Set E3)
    (hEtop : volume E ≠ ∞)
    (hcover : ∀ Q ∈ stoppingRoots α S s f n, boxSet α Q ⊆ E) :
    ∑ Q ∈ stoppingRoots α S s f n, boxMass α Q ≤ (volume E).toReal := by
  have hpack := scratch_sum_boxMass_stoppingRoots_le_measure α S s f n E hcover
  have hsum_nonneg : 0 ≤ ∑ Q ∈ stoppingRoots α S s f n, boxMass α Q := by
    apply Finset.sum_nonneg
    intro Q hQ
    exact (boxMass_pos α Q).le
  have hsumtop :
      (∑ Q ∈ stoppingRoots α S s f n, ENNReal.ofReal (boxMass α Q)) ≠ ∞ :=
    ENNReal.sum_ne_top.mpr fun Q _ ↦ ENNReal.ofReal_ne_top
  have hpack' : ENNReal.ofReal
      (∑ Q ∈ stoppingRoots α S s f n, boxMass α Q) ≤ volume E := by
    rw [ENNReal.ofReal_sum_of_nonneg]
    · exact hpack
    · intro Q hQ
      exact (boxMass_pos α Q).le
  have hsumtop' : ENNReal.ofReal
      (∑ Q ∈ stoppingRoots α S s f n, boxMass α Q) ≠ ∞ := by
    rw [ENNReal.ofReal_sum_of_nonneg]
    · exact hsumtop
    · intro Q hQ
      exact (boxMass_pos α Q).le
  have hreal := (ENNReal.toReal_le_toReal
    hsumtop' hEtop).mpr hpack'
  simpa [ENNReal.toReal_ofReal hsum_nonneg] using hreal

/-- Every local size is nonnegative, independently of the exponent. -/
theorem scratch_boxLocalSize_nonneg
    (α : Anisotropy) (s : ℝ) (f : E3 → ℝ) (q : AnisoBox α) :
    0 ≤ boxLocalSize α s f q := by
  unfold boxLocalSize boxLocalPower
  apply Real.rpow_nonneg
  apply integral_nonneg
  intro y
  exact mul_nonneg (Real.rpow_nonneg (abs_nonneg (f y)) _)
    (anisotropicBracketKernel_nonneg α (boxLength_pos q).le
      (boxCenter α q) y)

/-- Every finite tree local size is nonnegative. -/
theorem scratch_treeLocalSize_nonneg
    {α : Anisotropy} (T : FiniteConvexTree α) (s : ℝ) (f : E3 → ℝ) :
    0 ≤ treeLocalSize T s f := by
  unfold treeLocalSize collectionLocalSize
  rw [dif_pos T.nonempty]
  rcases T.nonempty with ⟨q, hq⟩
  exact (scratch_boxLocalSize_nonneg α s f q).trans
    (Finset.le_sup' (boxLocalSize α s f) hq)

/-- At one stopping level, the local-size product of a root tree is bounded
by the product of its dyadic level thresholds. -/
theorem scratch_stoppingRoot_treeLocalSize_product_le {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (hconvex : IsConvexCollection α (stoppingLevel α S s f n))
    (Q : AnisoBox α) (hQ : Q ∈ stoppingRoots α S s f n) :
    (∏ j : Fin d,
      treeLocalSize (stoppingTree α S s f n hconvex Q hQ) (s j) (f j)) ≤
      ∏ j : Fin d, (2 : ℝ) ^ n j := by
  apply Finset.prod_le_prod
  · intro j _
    exact scratch_treeLocalSize_nonneg
      (stoppingTree α S s f n hconvex Q hQ) (s j) (f j)
  · intro j _
    exact stoppingTreeLocalSize_le α S s f n hconvex Q hQ j

/-- The weighted contribution of one stopping root is bounded by its box
mass times the product of the corresponding dyadic thresholds. -/
theorem scratch_stoppingRoot_weight_le_levelWeight {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (hconvex : IsConvexCollection α (stoppingLevel α S s f n))
    (Q : AnisoBox α) (hQ : Q ∈ stoppingRoots α S s f n) :
    boxMass α Q *
        (∏ j : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q hQ) (s j) (f j)) ≤
      (∏ j : Fin d, (2 : ℝ) ^ n j) * boxMass α Q := by
  calc
    boxMass α Q *
        (∏ j : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q hQ) (s j) (f j)) ≤
        boxMass α Q * (∏ j : Fin d, (2 : ℝ) ^ n j) :=
      mul_le_mul_of_nonneg_left
        (scratch_stoppingRoot_treeLocalSize_product_le α S s f n hconvex Q hQ)
        (boxMass_pos α Q).le
    _ = (∏ j : Fin d, (2 : ℝ) ^ n j) * boxMass α Q := by ring

/-- The finite weighted sum of all roots at one stopping level reduces to
the root mass sum and the product of dyadic thresholds. -/
theorem scratch_sum_stoppingRoot_weights_le_levelWeight {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (hconvex : IsConvexCollection α (stoppingLevel α S s f n)) :
    (∑ Q ∈ (stoppingRoots α S s f n).attach,
      boxMass α Q.1 *
        (∏ j : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q.1 Q.2) (s j) (f j))) ≤
      (∏ j : Fin d, (2 : ℝ) ^ n j) *
        (∑ Q ∈ (stoppingRoots α S s f n).attach, boxMass α Q.1) := by
  calc
    (∑ Q ∈ (stoppingRoots α S s f n).attach,
      boxMass α Q.1 *
        (∏ j : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q.1 Q.2) (s j) (f j))) ≤
        ∑ Q ∈ (stoppingRoots α S s f n).attach,
          (∏ j : Fin d, (2 : ℝ) ^ n j) * boxMass α Q.1 := by
      apply Finset.sum_le_sum
      intro Q _
      exact scratch_stoppingRoot_weight_le_levelWeight α S s f n hconvex Q.1 Q.2
    _ = (∏ j : Fin d, (2 : ℝ) ^ n j) *
        (∑ Q ∈ (stoppingRoots α S s f n).attach, boxMass α Q.1) := by
      rw [Finset.mul_sum]

/-- Combining root disjointness with the one-level size estimate bounds the
weighted stopping-root sum by any finite-volume covering region. -/
theorem scratch_sum_stoppingRoot_weights_le_levelWeight_mul_measure_toReal
    {d : ℕ} (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (hconvex : IsConvexCollection α (stoppingLevel α S s f n))
    (E : Set E3) (hEtop : volume E ≠ ∞)
    (hcover : ∀ Q ∈ stoppingRoots α S s f n, boxSet α Q ⊆ E) :
    (∑ Q ∈ (stoppingRoots α S s f n).attach,
      boxMass α Q.1 *
        (∏ j : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q.1 Q.2) (s j) (f j))) ≤
      (∏ j : Fin d, (2 : ℝ) ^ n j) * (volume E).toReal := by
  calc
    (∑ Q ∈ (stoppingRoots α S s f n).attach,
      boxMass α Q.1 *
        (∏ j : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q.1 Q.2) (s j) (f j))) ≤
        (∏ j : Fin d, (2 : ℝ) ^ n j) *
          (∑ Q ∈ (stoppingRoots α S s f n).attach, boxMass α Q.1) :=
      scratch_sum_stoppingRoot_weights_le_levelWeight α S s f n hconvex
    _ = (∏ j : Fin d, (2 : ℝ) ^ n j) *
          (∑ Q ∈ stoppingRoots α S s f n, boxMass α Q) := by
      rw [Finset.sum_attach]
    _ ≤ (∏ j : Fin d, (2 : ℝ) ^ n j) * (volume E).toReal := by
      apply mul_le_mul_of_nonneg_left
        (scratch_sum_boxMass_stoppingRoots_le_measure_toReal
          α S s f n E hEtop hcover)
      apply Finset.prod_nonneg
      intro j _
      exact zpow_nonneg (by norm_num) _

/-- The finite forest sum over any finite family of stopping levels reduces
to the corresponding finite family of weighted covering-region measures.
This is the exact finite rearrangement before the source's discrete
layer-cake estimate. -/
theorem scratch_sum_stoppingRoot_weights_over_levels_le
    {d : ℕ} (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (N : Finset (Fin d → ℤ))
    (hconvex : ∀ n, IsConvexCollection α (stoppingLevel α S s f n))
    (E : (Fin d → ℤ) → Set E3) (hEtop : ∀ n, volume (E n) ≠ ∞)
    (hcover : ∀ n Q, Q ∈ stoppingRoots α S s f n → boxSet α Q ⊆ E n) :
    (∑ n ∈ N,
      ∑ Q ∈ (stoppingRoots α S s f n).attach,
        boxMass α Q.1 *
          (∏ j : Fin d,
            treeLocalSize (stoppingTree α S s f n (hconvex n) Q.1 Q.2)
              (s j) (f j))) ≤
      ∑ n ∈ N,
        (∏ j : Fin d, (2 : ℝ) ^ n j) * (volume (E n)).toReal := by
  apply Finset.sum_le_sum
  intro n hn
  exact scratch_sum_stoppingRoot_weights_le_levelWeight_mul_measure_toReal
    α S s f n (hconvex n) (E n) (hEtop n) (hcover n)

/-- The complete one-level weighted packing estimate in the `s = 2`
coordinate branch. -/
theorem scratch_sum_stoppingRoot_weights_two_le_maximalLevelMeasure
    {d : ℕ} (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (hconvex : IsConvexCollection α (stoppingLevel α S s f n))
    (j : Fin d) (hsj : s j = 2)
    (hfcont : Continuous (f j))
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f j y| ≤ B)
    (hEtop : volume {p |
      (2 / 3 : ℝ) ^ 15 * (2 : ℝ) ^ (n j - 1) <
        anisotropicMaximalTwo α (f j) p} ≠ ∞) :
    (∑ Q ∈ (stoppingRoots α S s f n).attach,
      boxMass α Q.1 *
        (∏ k : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q.1 Q.2) (s k) (f k))) ≤
      (∏ k : Fin d, (2 : ℝ) ^ n k) *
        (volume {p |
          (2 / 3 : ℝ) ^ 15 * (2 : ℝ) ^ (n j - 1) <
            anisotropicMaximalTwo α (f j) p}).toReal := by
  apply scratch_sum_stoppingRoot_weights_le_levelWeight_mul_measure_toReal
    α S s f n hconvex _ hEtop
  intro Q hQ
  exact scratch_stoppingRoot_two_boxSet_subset_maximalLevel α S s f n Q hQ
    j hsj hfcont B hB hfB

/-- The complete one-level weighted packing estimate in the `s = 4`
coordinate branch. -/
theorem scratch_sum_stoppingRoot_weights_four_le_maximalLevelMeasure
    {d : ℕ} (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (n : Fin d → ℤ)
    (hconvex : IsConvexCollection α (stoppingLevel α S s f n))
    (j : Fin d) (hsj : s j = 4)
    (hfcont : Continuous (f j))
    (B : ℝ) (hB : 0 ≤ B) (hfB : ∀ y, |f j y| ≤ B)
    (hEtop : volume {p |
      ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) *
          (2 : ℝ) ^ (n j - 1) <
        scratch_anisotropicMaximalFour α (f j) p} ≠ ∞) :
    (∑ Q ∈ (stoppingRoots α S s f n).attach,
      boxMass α Q.1 *
        (∏ k : Fin d,
          treeLocalSize (stoppingTree α S s f n hconvex Q.1 Q.2) (s k) (f k))) ≤
      (∏ k : Fin d, (2 : ℝ) ^ n k) *
        (volume {p |
          ((2 / 3 : ℝ) ^ 30) ^ ((4 : ℝ)⁻¹) *
              (2 : ℝ) ^ (n j - 1) <
            scratch_anisotropicMaximalFour α (f j) p}).toReal := by
  apply scratch_sum_stoppingRoot_weights_le_levelWeight_mul_measure_toReal
    α S s f n hconvex _ hEtop
  intro Q hQ
  exact scratch_stoppingRoot_four_boxSet_subset_maximalLevel α S s f n Q hQ
    j hsj hfcont B hB hfB

/-- Every positive real number lies in exactly one dyadic half-open level
interval in the convention of the stopping data. -/
theorem scratch_exists_dyadicLevel_of_pos {a : ℝ} (ha : 0 < a) :
    ∃ n : ℤ, (2 : ℝ) ^ (n - 1) < a ∧ a ≤ (2 : ℝ) ^ n := by
  rcases exists_mem_Ioc_zpow ha (by norm_num : (1 : ℝ) < 2) with ⟨m, hm⟩
  refine ⟨m + 1, ?_⟩
  simpa using hm

/-- The dyadic stopping index of a positive real number is unique. -/
theorem scratch_dyadicLevel_unique {a : ℝ} {n m : ℤ}
    (hn : (2 : ℝ) ^ (n - 1) < a ∧ a ≤ (2 : ℝ) ^ n)
    (hm : (2 : ℝ) ^ (m - 1) < a ∧ a ≤ (2 : ℝ) ^ m) : n = m := by
  apply le_antisymm
  · by_contra hnm
    have hlt : m < n := lt_of_not_ge hnm
    have hmlt : m ≤ n - 1 := by omega
    have hpow : (2 : ℝ) ^ m ≤ (2 : ℝ) ^ (n - 1) :=
      zpow_le_zpow_right₀ (by norm_num) hmlt
    exact (not_lt_of_ge (hm.2.trans hpow)) hn.1
  · by_contra hmn
    have hlt : n < m := lt_of_not_ge hmn
    have hnlt : n ≤ m - 1 := by omega
    have hpow : (2 : ℝ) ^ n ≤ (2 : ℝ) ^ (m - 1) :=
      zpow_le_zpow_right₀ (by norm_num) hnlt
    exact (not_lt_of_ge (hn.2.trans hpow)) hm.1

/-- Positive stopping data place a box in some vector-valued stopping
level, exactly as in the source finite forest construction. -/
theorem scratch_exists_stoppingLevel_of_positiveData {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) {q : AnisoBox α} (hq : q ∈ S)
    (hpos : ∀ j, 0 < stoppingData α S (s j) (f j) q) :
    ∃ n : Fin d → ℤ, q ∈ stoppingLevel α S s f n := by
  choose n hn using fun j ↦
    scratch_exists_dyadicLevel_of_pos (hpos j)
  refine ⟨n, ?_⟩
  rw [mem_stoppingLevel_iff]
  exact ⟨hq, hn⟩

/-- A box belongs to at most one vector-valued stopping level. -/
theorem scratch_stoppingLevel_unique_of_mem {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) {q : AnisoBox α} {n m : Fin d → ℤ}
    (hn : q ∈ stoppingLevel α S s f n)
    (hm : q ∈ stoppingLevel α S s f m) : n = m := by
  ext j
  exact scratch_dyadicLevel_unique
    ((mem_stoppingLevel_iff α S s f n q).mp hn |>.2 j)
    ((mem_stoppingLevel_iff α S s f m q).mp hm |>.2 j)

/-- Choose the unique stopping-level vector for each box under the source
positivity hypothesis on all stopping data. -/
noncomputable def scratch_stoppingLevelIndex {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q)
    (q : {q : AnisoBox α // q ∈ S}) : Fin d → ℤ :=
  Classical.choose (scratch_exists_stoppingLevel_of_positiveData α S s f q.2
    (hpos q.1 q.2))

/-- The chosen index really places its box in the indicated stopping level. -/
theorem scratch_mem_stoppingLevelIndex {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q)
    (q : {q : AnisoBox α // q ∈ S}) :
    q.1 ∈ stoppingLevel α S s f
      (scratch_stoppingLevelIndex α S s f hpos q) :=
  Classical.choose_spec (scratch_exists_stoppingLevel_of_positiveData α S s f q.2
    (hpos q.1 q.2))

/-- The finite set of all stopping level vectors which actually occur in the
ambient finite collection. -/
noncomputable def scratch_activeStoppingLevels {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q) :
    Finset (Fin d → ℤ) :=
  S.attach.image (scratch_stoppingLevelIndex α S s f hpos)

/-- Distinct stopping-level vectors give disjoint finite collections. -/
theorem scratch_pairwiseDisjoint_stoppingLevels {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ) (N : Finset (Fin d → ℤ)) :
    (↑N : Set (Fin d → ℤ)).PairwiseDisjoint (stoppingLevel α S s f) := by
  intro n hn m hm hne
  change Disjoint (stoppingLevel α S s f n) (stoppingLevel α S s f m)
  rw [Finset.disjoint_left]
  intro q hqn hqm
  exact hne (scratch_stoppingLevel_unique_of_mem α S s f hqn hqm)

/-- The active finite stopping levels partition the ambient collection. -/
theorem scratch_boxCollection_eq_biUnion_activeStoppingLevels {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q) :
    S = (scratch_activeStoppingLevels α S s f hpos).biUnion
      (stoppingLevel α S s f) := by
  classical
  ext q
  constructor
  · intro hq
    let qS : {q : AnisoBox α // q ∈ S} := ⟨q, hq⟩
    refine Finset.mem_biUnion.mpr ⟨
      scratch_stoppingLevelIndex α S s f hpos qS, ?_, ?_⟩
    · exact Finset.mem_image.mpr ⟨qS, by simp, rfl⟩
    · exact scratch_mem_stoppingLevelIndex α S s f hpos qS
  · intro hq
    rcases Finset.mem_biUnion.mp hq with ⟨n, hn, hqlevel⟩
    exact (mem_stoppingLevel_iff α S s f n q).mp hqlevel |>.1

/-- Every finite sum over the ambient collection splits exactly over the
active stopping levels. -/
theorem scratch_sum_boxCollection_eq_sum_activeStoppingLevels {d : ℕ}
    {M : Type*} [AddCommMonoid M]
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q)
    (w : AnisoBox α → M) :
    (∑ q ∈ S, w q) =
      ∑ n ∈ scratch_activeStoppingLevels α S s f hpos,
        ∑ q ∈ stoppingLevel α S s f n, w q := by
  calc
    (∑ q ∈ S, w q) =
        ∑ q ∈ (scratch_activeStoppingLevels α S s f hpos).biUnion
          (stoppingLevel α S s f), w q :=
      congrArg (fun U : BoxCollection α ↦ ∑ q ∈ U, w q)
        (scratch_boxCollection_eq_biUnion_activeStoppingLevels α S s f hpos)
    _ = ∑ n ∈ scratch_activeStoppingLevels α S s f hpos,
        ∑ q ∈ stoppingLevel α S s f n, w q :=
      Finset.sum_biUnion
        (scratch_pairwiseDisjoint_stoppingLevels α S s f
          (scratch_activeStoppingLevels α S s f hpos))

/-- Combining the two finite partitions gives the literal forest sum over
all active level vectors and their maximal roots. -/
theorem scratch_sum_boxCollection_eq_sum_activeStoppingTrees {d : ℕ}
    {M : Type*} [AddCommMonoid M]
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q)
    (w : AnisoBox α → M) :
    (∑ q ∈ S, w q) =
      ∑ n ∈ scratch_activeStoppingLevels α S s f hpos,
        ∑ Q ∈ stoppingRoots α S s f n,
          ∑ q ∈ stoppingTreeBoxes α S s f n Q, w q := by
  calc
    (∑ q ∈ S, w q) =
        ∑ n ∈ scratch_activeStoppingLevels α S s f hpos,
          ∑ q ∈ stoppingLevel α S s f n, w q :=
      scratch_sum_boxCollection_eq_sum_activeStoppingLevels α S s f hpos w
    _ = ∑ n ∈ scratch_activeStoppingLevels α S s f hpos,
        ∑ Q ∈ stoppingRoots α S s f n,
          ∑ q ∈ stoppingTreeBoxes α S s f n Q, w q := by
      apply Finset.sum_congr rfl
      intro n hn
      exact sum_stoppingLevel_eq_sum_stoppingTrees α S s f n w

/-- The finite weighted stopping-forest sum over all levels actually
occupied by the ambient collection is bounded by the corresponding finite
sum of covering-region measures. -/
theorem scratch_sum_activeStoppingRoot_weights_le {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α)
    (hS : IsConvexCollection α S) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q)
    (E : (Fin d → ℤ) → Set E3) (hEtop : ∀ n, volume (E n) ≠ ∞)
    (hcover : ∀ n Q, Q ∈ stoppingRoots α S s f n → boxSet α Q ⊆ E n) :
    (∑ n ∈ scratch_activeStoppingLevels α S s f hpos,
      ∑ Q ∈ (stoppingRoots α S s f n).attach,
        boxMass α Q.1 *
          (∏ j : Fin d,
            treeLocalSize
              (stoppingTree α S s f n
                (isConvexCollection_stoppingLevel α S hS s f n) Q.1 Q.2)
              (s j) (f j))) ≤
      ∑ n ∈ scratch_activeStoppingLevels α S s f hpos,
        (∏ j : Fin d, (2 : ℝ) ^ n j) * (volume (E n)).toReal := by
  apply scratch_sum_stoppingRoot_weights_over_levels_le α S s f
    (scratch_activeStoppingLevels α S s f hpos)
    (fun n ↦ isConvexCollection_stoppingLevel α S hS s f n)
    E hEtop hcover

/-- The finite index set of all maximal stopping roots in all active levels. -/
noncomputable def scratch_activeStoppingForestRoots {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q) :
    Finset (Sigma fun _ : Fin d → ℤ ↦ AnisoBox α) :=
  (scratch_activeStoppingLevels α S s f hpos).sigma
    (stoppingRoots α S s f)

/-- Membership in the finite stopping forest is precisely active-level
membership together with maximal-root membership at that level. -/
theorem scratch_mem_activeStoppingForestRoots_iff {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q)
    (n : Fin d → ℤ) (Q : AnisoBox α) :
    ⟨n, Q⟩ ∈ scratch_activeStoppingForestRoots α S s f hpos ↔
      n ∈ scratch_activeStoppingLevels α S s f hpos ∧
        Q ∈ stoppingRoots α S s f n :=
  Finset.mem_sigma

/-- The box collections carried by distinct active forest roots are pairwise
disjoint, including roots from different stopping levels. -/
theorem scratch_pairwiseDisjoint_activeStoppingForestTreeBoxes {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q) :
    (↑(scratch_activeStoppingForestRoots α S s f hpos) :
      Set (Sigma fun _ : Fin d → ℤ ↦ AnisoBox α)).PairwiseDisjoint
      (fun z ↦ stoppingTreeBoxes α S s f z.1 z.2) := by
  rintro ⟨n, Q⟩ hQ ⟨m, R⟩ hR hne
  change ⟨n, Q⟩ ∈ scratch_activeStoppingForestRoots α S s f hpos at hQ
  change ⟨m, R⟩ ∈ scratch_activeStoppingForestRoots α S s f hpos at hR
  change Disjoint (stoppingTreeBoxes α S s f n Q)
    (stoppingTreeBoxes α S s f m R)
  rw [scratch_mem_activeStoppingForestRoots_iff] at hQ hR
  by_cases hnm : n = m
  · subst m
    have hQR : Q ≠ R := by
      intro hQR
      apply hne
      simp [hQR]
    exact stoppingTreeBoxes_disjoint_of_ne α S s f n Q R hQ.2 hR.2 hQR
  · rw [Finset.disjoint_left]
    intro q hqQ hqR
    have hqlevelQ : q ∈ stoppingLevel α S s f n :=
      (mem_stoppingTreeBoxes_iff α S s f n Q q).mp hqQ |>.1
    have hqlevelR : q ∈ stoppingLevel α S s f m :=
      (mem_stoppingTreeBoxes_iff α S s f m R q).mp hqR |>.1
    exact hnm (scratch_stoppingLevel_unique_of_mem α S s f hqlevelQ hqlevelR)

/-- The active stopping forest trees form an exact finite partition of the
ambient collection. -/
theorem scratch_boxCollection_eq_biUnion_activeStoppingForestTreeBoxes {d : ℕ}
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q) :
    S = (scratch_activeStoppingForestRoots α S s f hpos).biUnion
      (fun z ↦ stoppingTreeBoxes α S s f z.1 z.2) := by
  classical
  ext q
  constructor
  · intro hq
    have hqlevelUnion : q ∈
        (scratch_activeStoppingLevels α S s f hpos).biUnion
          (stoppingLevel α S s f) := by
      rw [← scratch_boxCollection_eq_biUnion_activeStoppingLevels α S s f hpos]
      exact hq
    rcases Finset.mem_biUnion.mp hqlevelUnion with ⟨n, hn, hqlevel⟩
    rcases exists_stoppingRoot_above α S s f n hqlevel with ⟨Q, hQ, hqQ⟩
    refine Finset.mem_biUnion.mpr ⟨⟨n, Q⟩, ?_, ?_⟩
    · exact Finset.mem_sigma.mpr ⟨hn, hQ⟩
    · exact (mem_stoppingTreeBoxes_iff α S s f n Q q).mpr ⟨hqlevel, hqQ⟩
  · intro hq
    rcases Finset.mem_biUnion.mp hq with ⟨z, hz, hqz⟩
    exact (mem_stoppingLevel_iff α S s f z.1 q).mp
      ((mem_stoppingTreeBoxes_iff α S s f z.1 z.2 q).mp hqz |>.1) |>.1

/-- Every finite box sum splits over the pairwise-disjoint active stopping
forest trees. -/
theorem scratch_sum_boxCollection_eq_sum_activeStoppingForestTreeBoxes {d : ℕ}
    {M : Type*} [AddCommMonoid M]
    (α : Anisotropy) (S : BoxCollection α) (s : Fin d → ℝ)
    (f : Fin d → E3 → ℝ)
    (hpos : ∀ q ∈ S, ∀ j, 0 < stoppingData α S (s j) (f j) q)
    (w : AnisoBox α → M) :
    (∑ q ∈ S, w q) =
      ∑ z ∈ scratch_activeStoppingForestRoots α S s f hpos,
        ∑ q ∈ stoppingTreeBoxes α S s f z.1 z.2, w q := by
  calc
    (∑ q ∈ S, w q) =
        ∑ q ∈ (scratch_activeStoppingForestRoots α S s f hpos).biUnion
          (fun z ↦ stoppingTreeBoxes α S s f z.1 z.2), w q :=
      congrArg (fun U : BoxCollection α ↦ ∑ q ∈ U, w q)
        (scratch_boxCollection_eq_biUnion_activeStoppingForestTreeBoxes
          α S s f hpos)
    _ = ∑ z ∈ scratch_activeStoppingForestRoots α S s f hpos,
        ∑ q ∈ stoppingTreeBoxes α S s f z.1 z.2, w q :=
      Finset.sum_biUnion
        (scratch_pairwiseDisjoint_activeStoppingForestTreeBoxes α S s f hpos)

end

end Auto.Twisted
