/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## Joint integrability of a mode against the frequency kernel

Source: the absolute-convergence paragraph of `thm:cone`, which justifies
Fubini between scales and modes.  For each mode the integrand is integrable in
the scale at every frequency, and its scale mass is bounded by the Calderón
constant over the active exponent uniformly in the frequency, so the frequency
integral of that mass is controlled by the kernel alone.
-/

/-- The mode integrand is jointly measurable in frequency and scale. -/
theorem measurable_thirdModeFrequencySymbol_kernel_prod
    (α : Anisotropy) (ν : standardModeLattice) (F : ModelComplexSchwartzInput) :
    Measurable (fun p : Frequency9 × ℝ ↦
      (thirdModeFrequencySymbol α ν p.2 (-frequencyDiagonal p.1) / (p.2 : ℂ)) *
        frequencyKernel (F 0) (F 1) (F 2) (F 3) p.1) := by
  have hdil : Continuous (fun p : Frequency9 × ℝ ↦
      α.dilate p.2 (-frequencyDiagonal p.1)) :=
    (continuous_dilate_uncurry α).comp
      (continuous_snd.prodMk (frequencyDiagonal.continuous.comp continuous_fst).neg)
  have hfun : (fun p : Frequency9 × ℝ ↦
        thirdModeFrequencySymbol α ν p.2 (-frequencyDiagonal p.1))
      = fun p : Frequency9 × ℝ ↦
        coneModeProfile ν (α.dilate p.2 (-frequencyDiagonal p.1)) := by
    funext p
    exact thirdModeFrequencySymbol_eq_coneModeProfile_dilate α ν p.2 _
  have hsym : Continuous (fun p : Frequency9 × ℝ ↦
      thirdModeFrequencySymbol α ν p.2 (-frequencyDiagonal p.1)) := by
    rw [hfun]
    exact (contDiff_coneModeProfile ν).continuous.comp hdil
  have hden : Measurable (fun p : Frequency9 × ℝ ↦ ((p.2 : ℝ) : ℂ)) :=
    Complex.measurable_ofReal.comp measurable_snd
  have hK : Measurable (fun p : Frequency9 × ℝ ↦
      frequencyKernel (F 0) (F 1) (F 2) (F 3) p.1) :=
    (frequencyKernel (F 0) (F 1) (F 2) (F 3)).continuous.measurable.comp measurable_fst
  exact (hsym.measurable.div hden).mul hK

/-- **Joint integrability of a mode against the frequency kernel.** -/
theorem integrable_thirdModeFrequencySymbol_kernel_prod
    (α : Anisotropy) (ν : standardModeLattice) (F : ModelComplexSchwartzInput) :
    Integrable (fun p : Frequency9 × ℝ ↦
        (thirdModeFrequencySymbol α ν p.2 (-frequencyDiagonal p.1) / (p.2 : ℂ)) *
          frequencyKernel (F 0) (F 1) (F 2) (F 3) p.1)
      ((frequencyMeasure : Measure Frequency9).prod
        ((volume : Measure ℝ).restrict (Ioi (0 : ℝ)))) := by
  letI : (volume : Measure (E3 × E3)).IsAddHaarMeasure :=
    Measure.prod.instIsAddHaarMeasure volume volume
  letI : (volume : Measure Frequency9).IsAddHaarMeasure :=
    Measure.prod.instIsAddHaarMeasure (volume : Measure (E3 × E3)) volume
  have hw : (0 : ℝ) < ((α.weight 2 : ℕ) : ℝ) := by exact_mod_cast α.weight_pos 2
  set K : Frequency9 → ℂ :=
    fun ζ ↦ frequencyKernel (F 0) (F 1) (F 2) (F 3) ζ with hKdef
  have hKint : Integrable K frequencyMeasure := by
    rw [frequencyMeasure_eq_volume]
    exact (frequencyKernel (F 0) (F 1) (F 2) (F 3)).integrable
  set f : Frequency9 × ℝ → ℂ := fun p ↦
    (thirdModeFrequencySymbol α ν p.2 (-frequencyDiagonal p.1) / (p.2 : ℂ)) * K p.1
    with hf
  have hmeas : AEStronglyMeasurable f
      ((frequencyMeasure : Measure Frequency9).prod
        ((volume : Measure ℝ).restrict (Ioi (0 : ℝ)))) :=
    (measurable_thirdModeFrequencySymbol_kernel_prod α ν F).aestronglyMeasurable
  refine (integrable_prod_iff hmeas).mpr ⟨?_, ?_⟩
  · refine Filter.Eventually.of_forall fun ζ ↦ ?_
    exact (integrableOn_thirdModeFrequencySymbol_div α ν (-frequencyDiagonal ζ)).mul_const (K ζ)
  · have hslice : ∀ ζ : Frequency9,
        (∫ t in Ioi (0 : ℝ), ‖f (ζ, t)‖)
          = (∫ t in Ioi (0 : ℝ),
              ‖thirdModeFrequencySymbol α ν t (-frequencyDiagonal ζ)‖ / t) * ‖K ζ‖ := by
      intro ζ
      rw [← integral_mul_const]
      refine setIntegral_congr_fun measurableSet_Ioi fun t ht ↦ ?_
      have ht0 : (0 : ℝ) < t := ht
      rw [hf]
      simp only [norm_mul, norm_div, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos ht0]
    have hbound : ∀ ζ : Frequency9,
        ‖∫ t in Ioi (0 : ℝ), ‖f (ζ, t)‖‖ ≤
          (cPsi ^ 3 / ((α.weight 2 : ℕ) : ℝ)) * ‖K ζ‖ := by
      intro ζ
      have hnn : 0 ≤ ∫ t in Ioi (0 : ℝ), ‖f (ζ, t)‖ :=
        setIntegral_nonneg measurableSet_Ioi fun t _ ↦ norm_nonneg _
      rw [Real.norm_eq_abs, abs_of_nonneg hnn, hslice ζ]
      exact mul_le_mul_of_nonneg_right
        (integral_norm_thirdModeFrequencySymbol_div_Ioi_le α ν (-frequencyDiagonal ζ))
        (norm_nonneg _)
    exact Integrable.mono'
      (hKint.norm.const_mul (cPsi ^ 3 / ((α.weight 2 : ℕ) : ℝ)))
      (hmeas.norm.integral_prod_right')
      (Filter.Eventually.of_forall hbound)

end
end Twisted
end Auto

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## The mode form is scale integrable

Source: `thm:cone`.  Joint integrability makes the mode's frequency integral
integrable in the scale, which is the premise the scale/mode interchange needs
term by term.
-/

/-- **The mode form is integrable in the scale.** -/
theorem integrableOn_modeFrequencyForm_div
    (α : Anisotropy) (ν : standardModeLattice) (F : ModelComplexSchwartzInput) :
    IntegrableOn (fun t : ℝ ↦
        ∫ ζ : Frequency9,
          (thirdModeFrequencySymbol α ν t (-frequencyDiagonal ζ) / (t : ℂ)) *
            frequencyKernel (F 0) (F 1) (F 2) (F 3) ζ ∂frequencyMeasure)
      (Ioi (0 : ℝ)) volume :=
  (integrable_thirdModeFrequencySymbol_kernel_prod α ν F).integral_prod_right

/-- The frequency and scale integrals exchange for each mode. -/
theorem integral_integral_swap_thirdModeFrequencySymbol
    (α : Anisotropy) (ν : standardModeLattice) (F : ModelComplexSchwartzInput) :
    (∫ ζ : Frequency9,
        (∫ t in Ioi (0 : ℝ),
          (thirdModeFrequencySymbol α ν t (-frequencyDiagonal ζ) / (t : ℂ)) *
            frequencyKernel (F 0) (F 1) (F 2) (F 3) ζ) ∂frequencyMeasure)
      = ∫ t in Ioi (0 : ℝ),
          ∫ ζ : Frequency9,
            (thirdModeFrequencySymbol α ν t (-frequencyDiagonal ζ) / (t : ℂ)) *
              frequencyKernel (F 0) (F 1) (F 2) (F 3) ζ ∂frequencyMeasure :=
  integral_integral_swap (integrable_thirdModeFrequencySymbol_kernel_prod α ν F)

end
end Twisted
end Auto
