/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## The scale-uniform multiplier certificate for the mode symbol

Source: `thm:cone`, whose bridge from the frequency representation to
`multiplierForm` is stated conditionally on "a uniform anisotropic multiplier
certificate for the scale-dependent cone symbol at every positive scale".
All four components are available, so the certificate is assembled here, with
a constant depending only on the anisotropy and the mode.
-/

/-- The mode symbol is smooth, being a fixed profile composed with a linear
map. -/
theorem contDiff_thirdModeFrequencySymbol
    (α : Anisotropy) (ν : standardModeLattice) (t : ℝ) :
    ContDiff ℝ ((⊤ : ℕ∞) : WithTop ℕ∞)
      (thirdModeFrequencySymbol α ν t) := by
  have hLcont : Continuous (α.dilateLinear t) :=
    LinearMap.continuous_of_finiteDimensional (α.dilateLinear t)
  let L : E3 →L[ℝ] E3 := { α.dilateLinear t with cont := hLcont }
  have hLapply : ∀ z : E3, L z = α.dilate t z := fun z ↦ α.dilateLinear_apply t z
  have hfun : thirdModeFrequencySymbol α ν t = coneModeProfile ν ∘ L := by
    funext z
    rw [Function.comp_apply, hLapply z]
    exact thirdModeFrequencySymbol_eq_coneModeProfile_dilate α ν t z
  rw [hfun]
  exact (contDiff_coneModeProfile ν).comp L.contDiff

/-- An ordered coordinate derivative has anisotropic order at most the number
of derivatives times the total weight. -/
theorem derivativeWeight_le (α : Anisotropy) {k : ℕ} (σ : Fin k → Fin 3) :
    α.derivativeWeight σ ≤ k * (α.weight 0 + α.weight 1 + α.weight 2) := by
  unfold Anisotropy.derivativeWeight
  have hb : ∀ r : Fin k,
      α.weight (σ r) ≤ α.weight 0 + α.weight 1 + α.weight 2 := by
    intro r
    rcases (by omega : (σ r : ℕ) = 0 ∨ (σ r : ℕ) = 1 ∨ (σ r : ℕ) = 2) with
      h | h | h
    · have : σ r = 0 := Fin.ext h
      rw [this]; omega
    · have : σ r = 1 := Fin.ext h
      rw [this]; omega
    · have : σ r = 2 := Fin.ext h
      rw [this]; omega
  calc ∑ r : Fin k, α.weight (σ r)
      ≤ ∑ _r : Fin k, (α.weight 0 + α.weight 1 + α.weight 2) :=
        Finset.sum_le_sum fun r _ ↦ hb r
    _ = k * (α.weight 0 + α.weight 1 + α.weight 2) := by
        rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, smul_eq_mul]

/-- **The scale-uniform multiplier certificate.**  There is a constant,
depending only on the anisotropy and the mode, for which the mode symbol is an
anisotropic multiplier at every positive scale.  This is the hypothesis the
one-mode and cone bridges of `thm:cone` were left conditional on. -/
theorem exists_isAnisotropicMultiplier_thirdModeFrequencySymbol
    (α : Anisotropy) (ν : Fin 3 → ℤ) :
    ∃ M : ℝ, ∀ t : ℝ, 0 < t →
      Anisotropy.IsAnisotropicMultiplier α M
        (thirdModeFrequencySymbol α (standardModeOfInt ν) t) := by
  classical
  choose Ck hCk0 hCk using fun k : ℕ ↦
    exists_bound_iteratedFDeriv_coneModeProfile (standardModeOfInt ν) k
  set W : ℕ := α.weight 0 + α.weight 1 + α.weight 2 with hW
  set Csum : ℝ := ∑ k ∈ Finset.range 111, Ck k with hCsum
  have hCsum0 : 0 ≤ Csum := Finset.sum_nonneg fun k _ ↦ hCk0 k
  refine ⟨Csum * 6 ^ (110 * W), fun t ht ↦ ?_⟩
  have hsmooth := contDiff_thirdModeFrequencySymbol α (standardModeOfInt ν) t
  refine ⟨by positivity, measurable_thirdModeFrequencySymbol α ν t,
    thirdModeFrequencySymbol_zero α (standardModeOfInt ν) t, ?_, ?_⟩
  · exact (hsmooth.of_le ENat.LEInfty.out).contDiffOn
  · intro k hk ξ hξ σ
    have hbound := norm_iteratedFDeriv_thirdModeFrequencySymbol_coordinate_le
      α ν ht hξ k σ (hCk0 k) (hCk k)
    refine le_trans hbound ?_
    have hrad : 0 < α.radius ξ := radius_pos_of_ne_zero α hξ
    have hrpownn : 0 ≤ (α.radius ξ) ^ (-((α.derivativeWeight σ : ℕ) : ℝ)) :=
      Real.rpow_nonneg hrad.le _
    refine mul_le_mul_of_nonneg_right ?_ hrpownn
    have hCkle : Ck k ≤ Csum := by
      refine Finset.single_le_sum (f := Ck) (fun i _ ↦ hCk0 i) ?_
      exact Finset.mem_range.mpr (by omega)
    have hdle : α.derivativeWeight σ ≤ 110 * W := by
      refine le_trans (derivativeWeight_le α σ) ?_
      exact Nat.mul_le_mul_right _ hk
    have hpowle : (6 : ℝ) ^ α.derivativeWeight σ ≤ 6 ^ (110 * W) :=
      pow_le_pow_right₀ (by norm_num) hdle
    exact mul_le_mul hCkle hpowle (by positivity) hCsum0


end
end Twisted
end Auto
