/- Copyright (c) 2026 Joris Roos. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto.Twisted

open scoped BigOperators

noncomputable section

/-! ## The missing corner in sequential unary interpolation

The Section 8 endpoint set consists only of the base vertex `b` and the
three one-coordinate vertices `b + b₀ e_m`.  A first unary interpolation
along one edge cannot be followed by interpolation in a second input without
the double-edge corner.  The following checked arithmetic makes that exact
gap explicit.
-/

/-- The base input-reciprocal vertex.  These local copies deliberately keep
the obstruction audit independent of the other interpolation scratch file. -/
def scratchObstruction_base {β0 β1 β2 β3 : ℝ}
    (b : ExponentSimplex β0 β1 β2 β3) : Fin 3 → ℝ :=
  fun j => if j = 0 then b.b1 else if j = 1 then b.b2 else b.b3

/-- The available one-coordinate edge vertices. -/
def scratchObstruction_edge {β0 β1 β2 β3 : ℝ}
    (b : ExponentSimplex β0 β1 β2 β3) (m : Fin 3) : Fin 3 → ℝ :=
  fun j => scratchObstruction_base b j + if j = m then b.b0 else 0

/-- Sum of the three input reciprocals, i.e. the output reciprocal. -/
def scratchObstruction_output (v : Fin 3 → ℝ) : ℝ := ∑ j, v j

/-- The reciprocal vector obtained by moving from the base vertex in both
the first and second input directions. -/
def scratch_simplexDoubleEdge01Vertex {β0 β1 β2 β3 : ℝ}
    (b : ExponentSimplex β0 β1 β2 β3) : Fin 3 → ℝ :=
  fun j => scratchObstruction_base b j +
    (if j = 0 then b.b0 else 0) + (if j = 1 then b.b0 else 0)

/-- The double-edge corner has output reciprocal `1 + b₀`, whereas the
available base and one-edge vertices have output reciprocals `1 - b₀` and
`1`, respectively. -/
theorem scratch_simplexDoubleEdge01Vertex_output
    {β0 β1 β2 β3 : ℝ} (b : ExponentSimplex β0 β1 β2 β3) :
    scratchObstruction_output (scratch_simplexDoubleEdge01Vertex b) =
      1 + b.b0 := by
  have h01 : (0 : Fin 3) ≠ 1 := by decide
  have h02 : (0 : Fin 3) ≠ 2 := by decide
  have h10 : (1 : Fin 3) ≠ 0 := by decide
  have h12 : (1 : Fin 3) ≠ 2 := by decide
  have h20 : (2 : Fin 3) ≠ 0 := by decide
  have h21 : (2 : Fin 3) ≠ 1 := by decide
  unfold scratchObstruction_output scratch_simplexDoubleEdge01Vertex
  simp only [Fin.sum_univ_three]
  simp [scratchObstruction_base, h01, h02, h10, h12, h20, h21]
  linarith [b.sum_eq_one]

private theorem scratchObstruction_base_output
    {β0 β1 β2 β3 : ℝ} (b : ExponentSimplex β0 β1 β2 β3) :
    scratchObstruction_output (scratchObstruction_base b) = 1 - b.b0 := by
  have h01 : (0 : Fin 3) ≠ 1 := by decide
  have h20 : (2 : Fin 3) ≠ 0 := by decide
  have h21 : (2 : Fin 3) ≠ 1 := by decide
  unfold scratchObstruction_output scratchObstruction_base
  simp only [Fin.sum_univ_three]
  simp [h01, h20, h21]
  linarith [b.sum_eq_one]

private theorem scratchObstruction_edge_output
    {β0 β1 β2 β3 : ℝ} (b : ExponentSimplex β0 β1 β2 β3)
    (m : Fin 3) : scratchObstruction_output (scratchObstruction_edge b m) = 1 := by
  have h01 : (0 : Fin 3) ≠ 1 := by decide
  have h02 : (0 : Fin 3) ≠ 2 := by decide
  have h10 : (1 : Fin 3) ≠ 0 := by decide
  have h12 : (1 : Fin 3) ≠ 2 := by decide
  have h20 : (2 : Fin 3) ≠ 0 := by decide
  have h21 : (2 : Fin 3) ≠ 1 := by decide
  fin_cases m <;>
    unfold scratchObstruction_output scratchObstruction_edge scratchObstruction_base <;>
    simp only [Fin.sum_univ_three] <;>
    simp [h01, h02, h10, h12, h20, h21] <;>
    linarith [b.sum_eq_one]

/-- The required two-coordinate corner is not one of the four supplied
vertices.  Consequently, the unary two-endpoint engine cannot be iterated
from the supplied endpoints alone: the second step would require this absent
corner as one of its endpoints. -/
theorem scratch_simplexDoubleEdge01Vertex_not_supplied
    {β0 β1 β2 β3 : ℝ} (b : ExponentSimplex β0 β1 β2 β3) :
    scratch_simplexDoubleEdge01Vertex b ≠ scratchObstruction_base b ∧
      ∀ m : Fin 3,
        scratch_simplexDoubleEdge01Vertex b ≠ scratchObstruction_edge b m := by
  constructor
  · intro h
    have hout := congrArg scratchObstruction_output h
    rw [scratch_simplexDoubleEdge01Vertex_output,
      scratchObstruction_base_output] at hout
    linarith [b.b0_pos]
  · intro m h
    have hout := congrArg scratchObstruction_output h
    rw [scratch_simplexDoubleEdge01Vertex_output,
      scratchObstruction_edge_output] at hout
    linarith [b.b0_pos]

end

end Auto.Twisted
