/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-! ## The starting estimate survives the approximation

Source: `lem:one_fiber`, where the starting estimate is applied to a field that
is not Schwartz by passing through approximants and identifying the limit with
the preliminary truncated bound.  The operator is continuous along uniformly
bounded pointwise-convergent inputs, and strong bounds survive an
almost-everywhere limit, so the estimate transfers to the limiting field.
-/

/-- **The strong estimate transfers to the limiting input.** -/
theorem lintegral_rpow_ModelTruncatedOperator_le_of_tendsto
    (α : Anisotropy) (u : E3) (c : ℝ → ℝ) (f : ModelOperatorRealInput)
    (m : Fin 3) (a b : ℝ)
    (g : ℕ → E3 → ℝ) (glim : E3 → ℝ) (Bm C : ℝ) (Bf : Fin 3 → ℝ)
    {R : ℝ} (hR : 0 < R) {K : ℝ≥0∞}
    (ha : 0 < a) (hC : 0 ≤ C) (hcm : Measurable c) (hcC : ∀ t : ℝ, |c t| ≤ C)
    (hf : ∀ j, Measurable (f j)) (hBf : ∀ j, 0 ≤ Bf j)
    (hfB : ∀ j, ∀ y : E3, |f j y| ≤ Bf j)
    (hgmeas : ∀ n, Measurable (g n)) (hBm : 0 ≤ Bm)
    (hgB : ∀ n, ∀ y : E3, |g n y| ≤ Bm)
    (htend : ∀ y : E3,
      Filter.Tendsto (fun n ↦ g n y) Filter.atTop (𝓝 (glim y)))
    (hopmeas : ∀ n, AEMeasurable
      (ModelTruncatedOperator α u c (modelOperatorReplace f m (g n)) a b) volume)
    (hbound : ∀ n, ∫⁻ x : E3, ENNReal.ofReal
        (|ModelTruncatedOperator α u c
          (modelOperatorReplace f m (g n)) a b x| ^ R) ≤ K) :
    ∫⁻ x : E3, ENNReal.ofReal
        (|ModelTruncatedOperator α u c
          (modelOperatorReplace f m glim) a b x| ^ R) ≤ K := by
  refine lintegral_rpow_le_of_ae_tendsto hR hopmeas ?_ hbound
  refine Filter.Eventually.of_forall fun x ↦ ?_
  exact tendsto_ModelTruncatedOperator_replace_of_tendsto α u c f m a b x
    g glim Bm C Bf ha hC hcm hcC hf hBf hfB hgmeas hBm hgB htend

end
end Twisted
end Auto
