/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

namespace Auto
namespace Twisted

open MeasureTheory Filter
open scoped BigOperators ENNReal

noncomputable section

/-! ## The scale-integrated passive factorization

Source: `lem:one_fiber`, blueprint lines 2495--2500.  Since the passive bounds
are uniform in the scale, they leave the active slot's absolute scale tail.
-/

/-- **Scale-integrated passive factorization.**  The truncated operator is
bounded by the two passive constants times the active slot's full
positive-scale tail, uniformly in the truncation. -/
theorem abs_ModelTruncatedOperator_le_passive_mul_scaleTail
    (α : Anisotropy) (u : E3) (c : ℝ → ℝ) (f : ModelOperatorRealInput)
    (m : Fin 3) (a b : ℝ) (x : E3) (K : Fin 3 → ℝ)
    (ha : 0 < a) (hcm : Measurable c) (hc : ∀ t : ℝ, |c t| ≤ 1)
    (hf : ∀ j, Measurable (f j)) (hK : ∀ j, 0 ≤ K j)
    (hpassive : ∀ t : ℝ, 0 < t → ∀ j : Fin 3, j ≠ m →
      |ModelCoordinateConvolution j (f j) (activeModelKernel 2 j u)
        (t ^ α.weight j) x| ≤ K j)
    (htail : IntegrableOn (fun t : ℝ ↦
      |ModelCoordinateConvolution m (f m) (activeModelKernel 2 m u)
        (t ^ α.weight m) x| * t⁻¹) (Set.Ioi (0 : ℝ))) :
    |ModelTruncatedOperator α u c f a b x| ≤
      (∏ j ∈ Finset.univ.erase m, K j) *
        ∫ t in Set.Ioi (0 : ℝ),
          |ModelCoordinateConvolution m (f m) (activeModelKernel 2 m u)
            (t ^ α.weight m) x| * t⁻¹ := by
  set P : ℝ := ∏ j ∈ Finset.univ.erase m, K j with hP
  have hPnonneg : 0 ≤ P := Finset.prod_nonneg fun j _ ↦ hK j
  set Am : ℝ → ℝ := fun t ↦ |ModelCoordinateConvolution m (f m)
    (activeModelKernel 2 m u) (t ^ α.weight m) x| with hAm
  have hAmnonneg : ∀ t : ℝ, 0 ≤ Am t := fun t ↦ abs_nonneg _
  have hptb : ∀ t : ℝ, 0 < t →
      |modelTruncatedOperatorIntegrand α u c f t x| ≤ P * Am t := fun t ht ↦
    abs_modelTruncatedOperatorIntegrand_le_passive α u c f t x m K
      (hc t) hK (fun j hj ↦ hpassive t ht j hj)
  have hslice : Measurable (fun t : ℝ ↦
      modelTruncatedOperatorIntegrand α u c f t x) :=
    (stronglyMeasurable_modelTruncatedOperatorIntegrand_joint_of_measurable
      α u c f hcm hf).measurable.comp (measurable_id.prodMk measurable_const)
  have hmeas : Measurable (fun t : ℝ ↦
      |modelTruncatedOperatorIntegrand α u c f t x| * t⁻¹) := by
    fun_prop
  have hmajor : IntegrableOn (fun t : ℝ ↦ P * (Am t * t⁻¹))
      (Set.Ioi (0 : ℝ)) := htail.const_mul P
  have hint : IntegrableOn (fun t : ℝ ↦
      |modelTruncatedOperatorIntegrand α u c f t x| * t⁻¹)
      (Set.Ioi (0 : ℝ)) := by
    refine Integrable.mono' hmajor hmeas.aestronglyMeasurable ?_
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    have htpos : (0 : ℝ) < t := ht
    rw [Real.norm_eq_abs, abs_of_nonneg (by positivity)]
    calc |modelTruncatedOperatorIntegrand α u c f t x| * t⁻¹
        ≤ (P * Am t) * t⁻¹ :=
          mul_le_mul_of_nonneg_right (hptb t htpos)
            (inv_nonneg.2 htpos.le)
      _ = P * (Am t * t⁻¹) := by ring
  calc |ModelTruncatedOperator α u c f a b x|
      ≤ ∫ t in Set.Ioi (0 : ℝ),
          |modelTruncatedOperatorIntegrand α u c f t x| * t⁻¹ :=
        abs_integral_modelScaleInterval_le_scaleTail ha _ hint
    _ ≤ ∫ t in Set.Ioi (0 : ℝ), P * (Am t * t⁻¹) := by
        apply setIntegral_mono_on hint hmajor measurableSet_Ioi
        intro t ht
        have htpos : (0 : ℝ) < t := ht
        calc |modelTruncatedOperatorIntegrand α u c f t x| * t⁻¹
            ≤ (P * Am t) * t⁻¹ :=
              mul_le_mul_of_nonneg_right (hptb t htpos)
                (inv_nonneg.2 htpos.le)
          _ = P * (Am t * t⁻¹) := by ring
    _ = P * ∫ t in Set.Ioi (0 : ℝ), Am t * t⁻¹ := integral_const_mul _ _

end
end Twisted
end Auto
