/- Copyright (c) 2026 Polona Durcik. All rights reserved.
License: Apache-2.0
This file was automatically generated by Codex.
-/

import Auto.Twisted.Twisted

namespace Auto.Twisted

open MeasureTheory Filter TopologicalSpace
open scoped BigOperators ENNReal RealInnerProductSpace Topology

noncomputable section

/-! ## Section 7: finite dyadic truncations and center--scale exhaustion

This scratch block follows `lem:model_convergence` in the Task 3 blueprint.
The root boxes are the eight level-`N` boxes indexed by `{-1,0}^3`; their
successive literal child generations supply all levels from `N` down to
`-N`.  The remaining declarations turn any increasing exhaustion by these
finite regions into convergence of the expanded real model form.
-/

/-- The eight level-`N` roots of the spatial truncation in the source. -/
def scratchTruncationRoots (α : Anisotropy) (N : ℕ) : BoxCollection α :=
  Finset.univ.image fun v : Fin 3 → Bool ↦
    ⟨(N : ℤ), fun i ↦ if v i then 0 else -1⟩

/-- The spatial box `B_N`, initially presented as the union of its eight
literal dyadic roots. -/
noncomputable def scratchTruncationSpatialSet (α : Anisotropy) (N : ℕ) : Set E3 :=
  ⋃ q ∈ scratchTruncationRoots α N, boxSet α q

/-- Apply one literal dyadic refinement simultaneously to a finite family. -/
def scratchRefineCollection (α : Anisotropy) (S : BoxCollection α) :
    BoxCollection α :=
  S.biUnion (boxChildren α)

/-- The `d`-th level in the finite truncation rooted at level `N`. -/
def scratchTruncationLevel (α : Anisotropy) (N d : ℕ) : BoxCollection α :=
  (scratchRefineCollection α)^[d] (scratchTruncationRoots α N)

/-- The literal finite collection `Q_N`: roots together with all descendants
through level `-N`. -/
def scratchTruncationCollection (α : Anisotropy) (N : ℕ) : BoxCollection α :=
  (Finset.range (2 * N + 1)).biUnion (scratchTruncationLevel α N)

theorem scratch_mem_truncationRoots_iff (α : Anisotropy) (N : ℕ)
    (q : AnisoBox α) :
    q ∈ scratchTruncationRoots α N ↔
      q.level = N ∧ ∃ v : Fin 3 → Bool,
        q.index = fun i ↦ if v i then 0 else -1 := by
  constructor
  · intro hq
    rcases Finset.mem_image.mp hq with ⟨v, -, rfl⟩
    exact ⟨rfl, ⟨v, rfl⟩⟩
  · rintro ⟨hlevel, v, hindex⟩
    have hq : q = ⟨(N : ℤ), fun i ↦ if v i then 0 else -1⟩ := by
      cases q
      simp only [AnisoBox.mk.injEq] at hlevel hindex ⊢
      exact ⟨by simpa using hlevel, hindex⟩
    subst q
    exact Finset.mem_image.mpr ⟨v, Finset.mem_univ _, rfl⟩

theorem scratch_refineCollection_mem_iff (α : Anisotropy)
    (S : BoxCollection α) (q : AnisoBox α) :
    q ∈ scratchRefineCollection α S ↔
      ∃ r ∈ S, q ∈ boxChildren α r := by
  simp only [scratchRefineCollection, Finset.mem_biUnion]

theorem scratch_mem_truncationLevel_zero (α : Anisotropy) (N : ℕ)
    (q : AnisoBox α) :
    q ∈ scratchTruncationLevel α N 0 ↔ q ∈ scratchTruncationRoots α N := by
  simp [scratchTruncationLevel]

theorem scratch_truncationLevel_succ (α : Anisotropy) (N d : ℕ) :
    scratchTruncationLevel α N (d + 1) =
      scratchRefineCollection α (scratchTruncationLevel α N d) := by
  simp only [scratchTruncationLevel, Function.iterate_succ_apply']

theorem scratch_truncationLevel_level (α : Anisotropy) (N d : ℕ)
    {q : AnisoBox α} (hq : q ∈ scratchTruncationLevel α N d) :
    q.level = (N : ℤ) - d := by
  induction d generalizing q with
  | zero =>
      rw [scratch_mem_truncationLevel_zero] at hq
      exact (scratch_mem_truncationRoots_iff α N q).mp hq |>.1
  | succ d ih =>
      rw [scratch_truncationLevel_succ, scratch_refineCollection_mem_iff] at hq
      rcases hq with ⟨r, hr, hqchild⟩
      rw [boxChildren_level α hqchild, ih hr]
      push_cast
      ring

theorem scratch_subset_truncationSpatialSet_of_mem_truncationLevel
    (α : Anisotropy) (N d : ℕ) {q : AnisoBox α}
    (hq : q ∈ scratchTruncationLevel α N d) :
    boxSet α q ⊆ scratchTruncationSpatialSet α N := by
  induction d generalizing q with
  | zero =>
      rw [scratch_mem_truncationLevel_zero] at hq
      intro x hx
      exact Set.mem_iUnion.2 ⟨q, Set.mem_iUnion.2 ⟨hq, hx⟩⟩
  | succ d ih =>
      rw [scratch_truncationLevel_succ, scratch_refineCollection_mem_iff] at hq
      rcases hq with ⟨r, hr, hqchild⟩
      rcases Finset.mem_image.mp hqchild with ⟨v, -, rfl⟩
      have hparent : boxSet α (boxChild α r v) ⊆ boxSet α r := by
        simpa only [boxParent_child] using boxSet_subset_parent α (boxChild α r v)
      exact hparent.trans (ih hr)

theorem scratch_truncationSpatialSet_subset_iUnion_level
    (α : Anisotropy) (N d : ℕ) :
    scratchTruncationSpatialSet α N ⊆
      ⋃ q ∈ scratchTruncationLevel α N d, boxSet α q := by
  induction d with
  | zero =>
      exact Set.Subset.rfl
  | succ d ih =>
      intro x hx
      rcases Set.mem_iUnion.1 (ih hx) with ⟨q, hx⟩
      rcases Set.mem_iUnion.1 hx with ⟨hq, hxq⟩
      rcases Set.mem_iUnion.1 (boxSet_subset_children_union α q hxq) with ⟨r, hxr⟩
      rcases Set.mem_iUnion.1 hxr with ⟨hr, hxr⟩
      refine Set.mem_iUnion.2 ⟨r, Set.mem_iUnion.2 ⟨?_, hxr⟩⟩
      rw [scratch_truncationLevel_succ, scratch_refineCollection_mem_iff]
      exact ⟨q, hq, hr⟩

theorem scratch_iUnion_truncationLevel_eq_spatialSet
    (α : Anisotropy) (N d : ℕ) :
    (⋃ q ∈ scratchTruncationLevel α N d, boxSet α q) =
      scratchTruncationSpatialSet α N := by
  apply Set.Subset.antisymm
  · rintro x hx
    rcases Set.mem_iUnion.1 hx with ⟨q, hx⟩
    rcases Set.mem_iUnion.1 hx with ⟨hq, hx⟩
    exact scratch_subset_truncationSpatialSet_of_mem_truncationLevel α N d hq hx
  · exact scratch_truncationSpatialSet_subset_iUnion_level α N d

theorem scratch_exists_root_of_mem_truncationLevel
    (α : Anisotropy) (N d : ℕ) {q : AnisoBox α}
    (hq : q ∈ scratchTruncationLevel α N d) :
    ∃ R ∈ scratchTruncationRoots α N, boxSet α q ⊆ boxSet α R := by
  induction d generalizing q with
  | zero =>
      rw [scratch_mem_truncationLevel_zero] at hq
      exact ⟨q, hq, Set.Subset.rfl⟩
  | succ d ih =>
      rw [scratch_truncationLevel_succ, scratch_refineCollection_mem_iff] at hq
      rcases hq with ⟨r, hr, hqchild⟩
      rcases ih hr with ⟨R, hR, hrR⟩
      rcases Finset.mem_image.mp hqchild with ⟨v, -, rfl⟩
      refine ⟨R, hR, ?_⟩
      have hparent : boxSet α (boxChild α r v) ⊆ boxSet α r := by
        simpa only [boxParent_child] using boxSet_subset_parent α (boxChild α r v)
      exact hparent.trans hrR

theorem scratch_mem_truncationLevel_of_root_subset
    (α : Anisotropy) (N d : ℕ) (q R : AnisoBox α)
    (hR : R ∈ scratchTruncationRoots α N)
    (hlevel : q.level = (N : ℤ) - d)
    (hsub : boxSet α q ⊆ boxSet α R) :
    q ∈ scratchTruncationLevel α N d := by
  induction d generalizing q with
  | zero =>
      rw [scratch_mem_truncationLevel_zero]
      have hRlevel : R.level = N :=
        (scratch_mem_truncationRoots_iff α N R).mp hR |>.1
      have hancestor := boxAncestor_eq_of_boxSet_subset α hsub
      have hdiff : (R.level - q.level).toNat = 0 := by
        rw [hRlevel, hlevel]
        norm_num
      have hqR : q = R := by
        simpa [boxAncestor, hdiff] using hancestor
      simpa only [hqR] using hR
  | succ d ih =>
      rw [scratch_truncationLevel_succ, scratch_refineCollection_mem_iff]
      have hRlevel : R.level = N :=
        (scratch_mem_truncationRoots_iff α N R).mp hR |>.1
      have hparentlevel : (boxParent α q).level = (N : ℤ) - d := by
        simp only [boxParent]
        rw [hlevel]
        push_cast
        ring
      have hinter : (boxSet α (boxParent α q) ∩ boxSet α R).Nonempty := by
        obtain ⟨x, hx⟩ := boxSet_nonempty α q
        exact ⟨x, boxSet_subset_parent α q hx, hsub hx⟩
      have hparentR : boxSet α (boxParent α q) ⊆ boxSet α R := by
        apply boxSet_nested_of_inter_nonempty α
        rw [hparentlevel, hRlevel]
        omega
        exact hinter
      have hparentmem : boxParent α q ∈ scratchTruncationLevel α N d :=
        ih (boxParent α q) hparentlevel hparentR
      have hchild : q ∈ boxChildren α (boxParent α q) := by
        rcases (boxParent_eq_iff_exists_boxChild α (boxParent α q) q).mp rfl with
          ⟨v, hv⟩
        exact Finset.mem_image.mpr ⟨v, Finset.mem_univ _, hv⟩
      exact ⟨boxParent α q, hparentmem, hchild⟩

theorem scratch_mem_truncationLevel_iff
    (α : Anisotropy) (N d : ℕ) (q : AnisoBox α) :
    q ∈ scratchTruncationLevel α N d ↔
      q.level = (N : ℤ) - d ∧
        ∃ R ∈ scratchTruncationRoots α N, boxSet α q ⊆ boxSet α R := by
  constructor
  · intro hq
    exact ⟨scratch_truncationLevel_level α N d hq,
      scratch_exists_root_of_mem_truncationLevel α N d hq⟩
  · rintro ⟨hlevel, R, hR, hsub⟩
    exact scratch_mem_truncationLevel_of_root_subset α N d q R hR hlevel hsub

theorem scratch_mem_truncationCollection_iff (α : Anisotropy) (N : ℕ)
    (q : AnisoBox α) :
    q ∈ scratchTruncationCollection α N ↔
      ∃ d ∈ Finset.range (2 * N + 1), q ∈ scratchTruncationLevel α N d := by
  simp only [scratchTruncationCollection, Finset.mem_biUnion]

theorem scratch_truncationCollection_box_subset (α : Anisotropy) (N : ℕ)
    {q : AnisoBox α} (hq : q ∈ scratchTruncationCollection α N) :
    boxSet α q ⊆ scratchTruncationSpatialSet α N := by
  rcases (scratch_mem_truncationCollection_iff α N q).mp hq with ⟨d, -, hqd⟩
  exact scratch_subset_truncationSpatialSet_of_mem_truncationLevel α N d hqd

theorem scratch_truncationCollection_level_bounds
    (α : Anisotropy) (N : ℕ) {q : AnisoBox α}
    (hq : q ∈ scratchTruncationCollection α N) :
    -(N : ℤ) ≤ q.level ∧ q.level ≤ N := by
  rcases (scratch_mem_truncationCollection_iff α N q).mp hq with ⟨d, hd, hqd⟩
  have hdlt : d < 2 * N + 1 := Finset.mem_range.mp hd
  have hlevel := scratch_truncationLevel_level α N d hqd
  constructor <;> rw [hlevel] <;> omega

theorem scratch_exists_root_of_mem_truncationCollection
    (α : Anisotropy) (N : ℕ) {q : AnisoBox α}
    (hq : q ∈ scratchTruncationCollection α N) :
    ∃ R ∈ scratchTruncationRoots α N, boxSet α q ⊆ boxSet α R := by
  rcases (scratch_mem_truncationCollection_iff α N q).mp hq with ⟨d, -, hqd⟩
  exact scratch_exists_root_of_mem_truncationLevel α N d hqd

theorem scratch_parent_mem_truncationRoots
    (α : Anisotropy) (N : ℕ) {R : AnisoBox α}
    (hR : R ∈ scratchTruncationRoots α N) :
    boxParent α R ∈ scratchTruncationRoots α (N + 1) := by
  rcases (scratch_mem_truncationRoots_iff α N R).mp hR with ⟨hlevel, v, hindex⟩
  apply (scratch_mem_truncationRoots_iff α (N + 1) (boxParent α R)).mpr
  refine ⟨?_, v, ?_⟩
  · simp only [boxParent]
    rw [hlevel]
    push_cast
    ring
  · funext i
    simp only [boxParent]
    rw [hindex]
    by_cases hv : v i
    · simp [hv]
    · have hpos : (0 : ℤ) < anisoRadix α i := by
        exact_mod_cast anisoRadix_pos α i
      have hdiv : (-1 : ℤ) / (anisoRadix α i : ℤ) = -1 := by
        change Int.ediv (-1) (anisoRadix α i : ℤ) = -1
        rw [Int.ediv_of_neg_of_pos (by norm_num) hpos]
        simp
      simpa [hv] using hdiv

/-- The source truncation `Q_N` is convex in the literal grid order. -/
theorem scratch_isConvexCollection_truncationCollection
    (α : Anisotropy) (N : ℕ) :
    IsConvexCollection α (scratchTruncationCollection α N) := by
  intro q r w hq hr hqw hwr
  have hqlevel := scratch_truncationCollection_level_bounds α N hq
  have hrlevel := scratch_truncationCollection_level_bounds α N hr
  have hwlower : -(N : ℤ) ≤ w.level := by
    have h : q.level ≤ w.level := level_le_of_boxSet_subset α hqw
    exact hqlevel.1.trans h
  have hwupper : w.level ≤ N := by
    have h : w.level ≤ r.level := level_le_of_boxSet_subset α hwr
    exact h.trans hrlevel.2
  rcases scratch_exists_root_of_mem_truncationCollection α N hr with ⟨R, hR, hrR⟩
  let d : ℕ := ((N : ℤ) - w.level).toNat
  have hdZ : (d : ℤ) = (N : ℤ) - w.level := by
    dsimp [d]
    exact Int.toNat_of_nonneg (sub_nonneg.mpr hwupper)
  have hdmem : d ∈ Finset.range (2 * N + 1) := by
    apply Finset.mem_range.mpr
    rw [show d = ((d : ℤ).toNat) by simp, hdZ]
    omega
  have hwlevel : w.level = (N : ℤ) - d := by
    rw [show (d : ℤ) = (N : ℤ) - w.level by exact hdZ]
    ring
  have hwR : boxSet α w ⊆ boxSet α R := hwr.trans hrR
  have hwd : w ∈ scratchTruncationLevel α N d :=
    scratch_mem_truncationLevel_of_root_subset α N d w R hR hwlevel hwR
  exact (scratch_mem_truncationCollection_iff α N w).mpr ⟨d, hdmem, hwd⟩

theorem scratch_truncationCollection_subset_succ
    (α : Anisotropy) (N : ℕ) :
    scratchTruncationCollection α N ⊆ scratchTruncationCollection α (N + 1) := by
  intro q hq
  rcases scratch_exists_root_of_mem_truncationCollection α N hq with ⟨R, hR, hqR⟩
  have hP : boxParent α R ∈ scratchTruncationRoots α (N + 1) :=
    scratch_parent_mem_truncationRoots α N hR
  have hqlevel := scratch_truncationCollection_level_bounds α N hq
  let d : ℕ := ((N + 1 : ℕ) - q.level).toNat
  have hdZ : (d : ℤ) = (N + 1 : ℕ) - q.level := by
    dsimp [d]
    exact Int.toNat_of_nonneg (by omega)
  have hdmem : d ∈ Finset.range (2 * (N + 1) + 1) := by
    apply Finset.mem_range.mpr
    rw [show d = ((d : ℤ).toNat) by simp, hdZ]
    omega
  have hqlevel' : q.level = (N + 1 : ℕ) - d := by
    rw [show (d : ℤ) = (N + 1 : ℕ) - q.level by exact hdZ]
    ring
  have hqP : boxSet α q ⊆ boxSet α (boxParent α R) :=
    hqR.trans (boxSet_subset_parent α R)
  have hqd : q ∈ scratchTruncationLevel α (N + 1) d :=
    scratch_mem_truncationLevel_of_root_subset α (N + 1) d q (boxParent α R)
      hP hqlevel' hqP
  exact (scratch_mem_truncationCollection_iff α (N + 1) q).mpr ⟨d, hdmem, hqd⟩

theorem scratch_monotone_truncationCollection (α : Anisotropy) :
    Monotone (scratchTruncationCollection α) :=
  monotone_nat_of_le_succ (scratch_truncationCollection_subset_succ α)

theorem scratch_collectionRegion_mono_of_truncationCollection
    (α : Anisotropy) :
    Monotone fun N ↦ collectionRegion α (scratchTruncationCollection α N) := by
  intro N M hNM z hz
  change z ∈ collectionRegion α (scratchTruncationCollection α N) at hz
  change z ∈ collectionRegion α (scratchTruncationCollection α M)
  rw [collectionRegion] at hz
  rw [collectionRegion]
  rcases Set.mem_iUnion.1 hz with ⟨q, hz⟩
  rcases Set.mem_iUnion.1 hz with ⟨hq, hz⟩
  exact Set.mem_iUnion.2 ⟨q, Set.mem_iUnion.2
    ⟨scratch_monotone_truncationCollection α hNM hq, hz⟩⟩

/-- The scale interval carried by the source truncation `Q_N`. -/
noncomputable def scratchTruncationScaleSet (N : ℕ) : Set ℝ :=
  Set.Ioc ((2 : ℝ) ^ (-(N : ℤ) - 1)) ((2 : ℝ) ^ (N : ℤ))

/-- The scale band assigned to the `d`-th descendant generation. -/
noncomputable def scratchTruncationBand (N d : ℕ) : Set ℝ :=
  Set.Ioc ((2 : ℝ) ^ ((N : ℤ) - d - 1)) ((2 : ℝ) ^ ((N : ℤ) - d))

theorem scratch_iUnion_truncationBand_range (N m : ℕ) :
    (⋃ d ∈ Finset.range (m + 1), scratchTruncationBand N d) =
      Set.Ioc ((2 : ℝ) ^ ((N : ℤ) - m - 1)) ((2 : ℝ) ^ (N : ℤ)) := by
  induction m with
  | zero =>
      simp [scratchTruncationBand]
  | succ m ih =>
      have hjoin : scratchTruncationBand N (m + 1) =
          Set.Ioc ((2 : ℝ) ^ ((N : ℤ) - (m + 1) - 1))
            ((2 : ℝ) ^ ((N : ℤ) - m - 1)) := by
        simp only [scratchTruncationBand, Nat.cast_add, Nat.cast_one]
        congr 2
        all_goals ring
      calc
        (⋃ d ∈ Finset.range (m.succ + 1), scratchTruncationBand N d) =
            scratchTruncationBand N (m + 1) ∪
              (⋃ d ∈ Finset.range (m + 1), scratchTruncationBand N d) := by
          ext t
          simp [Nat.succ_eq_add_one, Finset.range_add_one]
        _ = Set.Ioc ((2 : ℝ) ^ ((N : ℤ) - (m + 1) - 1))
                ((2 : ℝ) ^ ((N : ℤ) - m - 1)) ∪
              Set.Ioc ((2 : ℝ) ^ ((N : ℤ) - m - 1)) ((2 : ℝ) ^ (N : ℤ)) := by rw [ih, hjoin]
        _ = Set.Ioc ((2 : ℝ) ^ ((N : ℤ) - (m + 1) - 1)) ((2 : ℝ) ^ (N : ℤ)) := by
          rw [Set.Ioc_union_Ioc_eq_Ioc]
          · apply zpow_le_zpow_right₀ (by norm_num)
            omega
          · apply zpow_le_zpow_right₀ (by norm_num)
            omega
        _ = Set.Ioc ((2 : ℝ) ^ ((N : ℤ) - m.succ - 1)) ((2 : ℝ) ^ (N : ℤ)) := by
          simp only [Nat.cast_succ]

theorem scratch_iUnion_truncationBand_eq_scaleSet (N : ℕ) :
    (⋃ d ∈ Finset.range (2 * N + 1), scratchTruncationBand N d) =
      scratchTruncationScaleSet N := by
  have h := scratch_iUnion_truncationBand_range N (2 * N)
  rw [scratchTruncationScaleSet]
  convert h using 1
  congr 2
  all_goals
    push_cast
    ring

theorem scratch_boxScaleBand_eq_truncationBand
    (α : Anisotropy) (N d : ℕ) {q : AnisoBox α}
    (hq : q ∈ scratchTruncationLevel α N d) :
    boxScaleBand q = scratchTruncationBand N d := by
  unfold boxScaleBand scratchTruncationBand boxLength
  rw [scratch_truncationLevel_level α N d hq]
  congr 1
  rw [zpow_sub₀ (by norm_num : (2 : ℝ) ≠ 0)]
  rw [zpow_sub₀ (by norm_num : (2 : ℝ) ≠ 0)]
  rw [zpow_sub₀ (by norm_num : (2 : ℝ) ≠ 0)]
  norm_num

theorem scratch_iUnion_boxScaleRegion_truncationLevel_eq
    (α : Anisotropy) (N d : ℕ) :
    (⋃ q ∈ scratchTruncationLevel α N d, boxScaleRegion α q) =
      scratchTruncationSpatialSet α N ×ˢ scratchTruncationBand N d := by
  ext pt
  constructor
  · intro hpt
    rcases Set.mem_iUnion.1 hpt with ⟨q, hpt⟩
    rcases Set.mem_iUnion.1 hpt with ⟨hq, hp, ht⟩
    constructor
    · rw [← scratch_iUnion_truncationLevel_eq_spatialSet α N d]
      exact Set.mem_iUnion.2 ⟨q, Set.mem_iUnion.2 ⟨hq, hp⟩⟩
    · rw [← scratch_boxScaleBand_eq_truncationBand α N d hq]
      exact ht
  · rintro ⟨hp, ht⟩
    rw [← scratch_iUnion_truncationLevel_eq_spatialSet α N d] at hp
    rcases Set.mem_iUnion.1 hp with ⟨q, hp⟩
    rcases Set.mem_iUnion.1 hp with ⟨hq, hp⟩
    refine Set.mem_iUnion.2 ⟨q, Set.mem_iUnion.2 ⟨hq, hp, ?_⟩⟩
    rw [scratch_boxScaleBand_eq_truncationBand α N d hq]
    exact ht

theorem scratch_boxLength_le_truncationScaleTop
    (α : Anisotropy) (N : ℕ) {q : AnisoBox α}
    (hq : q ∈ scratchTruncationCollection α N) :
    boxLength q ≤ (2 : ℝ) ^ (N : ℤ) := by
  unfold boxLength
  exact zpow_le_zpow_right₀ (by norm_num)
    (scratch_truncationCollection_level_bounds α N hq).2

theorem scratch_truncationScaleBottom_le_boxLength_div
    (α : Anisotropy) (N : ℕ) {q : AnisoBox α}
    (hq : q ∈ scratchTruncationCollection α N) :
    (2 : ℝ) ^ (-(N : ℤ) - 1) ≤ boxLength q / 2 := by
  have hlevel := (scratch_truncationCollection_level_bounds α N hq).1
  have hpow : (2 : ℝ) ^ (-(N : ℤ) - 1) ≤
      (2 : ℝ) ^ (q.level - 1) :=
    zpow_le_zpow_right₀ (by norm_num) (by omega)
  calc
    (2 : ℝ) ^ (-(N : ℤ) - 1) ≤ (2 : ℝ) ^ (q.level - 1) := hpow
    _ = boxLength q / 2 := by
      unfold boxLength
      rw [zpow_sub₀ (by norm_num : (2 : ℝ) ≠ 0)]
      norm_num

/-- Every literal cell of `Q_N` lies in the expected spatial/scale slab.
The reverse inclusion is the remaining grid-partition part of the Section 7
exhaustion argument. -/
theorem scratch_collectionRegion_truncationCollection_subset_slab
    (α : Anisotropy) (N : ℕ) :
    collectionRegion α (scratchTruncationCollection α N) ⊆
      scratchTruncationSpatialSet α N ×ˢ scratchTruncationScaleSet N := by
  intro pt hpt
  rw [collectionRegion] at hpt
  rcases Set.mem_iUnion.1 hpt with ⟨q, hpt⟩
  rcases Set.mem_iUnion.1 hpt with ⟨hq, hp, ht⟩
  constructor
  · exact scratch_truncationCollection_box_subset α N hq hp
  · change pt.2 ∈ Set.Ioc ((2 : ℝ) ^ (-(N : ℤ) - 1)) ((2 : ℝ) ^ (N : ℤ))
    change pt.2 ∈ boxScaleBand q at ht
    change boxLength q / 2 < pt.2 ∧ pt.2 ≤ boxLength q at ht
    exact ⟨lt_of_le_of_lt
      (scratch_truncationScaleBottom_le_boxLength_div α N hq) ht.1,
      ht.2.trans (scratch_boxLength_le_truncationScaleTop α N hq)⟩

/-- Exact center--scale region of the finite source truncation:
`Ω_{Q_N}=B_N × (2^{-N-1},2^N]`. -/
theorem scratch_collectionRegion_truncationCollection_eq_slab
    (α : Anisotropy) (N : ℕ) :
    collectionRegion α (scratchTruncationCollection α N) =
      scratchTruncationSpatialSet α N ×ˢ scratchTruncationScaleSet N := by
  apply Set.Subset.antisymm
  · exact scratch_collectionRegion_truncationCollection_subset_slab α N
  · rintro pt ⟨hp, ht⟩
    rw [← scratch_iUnion_truncationBand_eq_scaleSet N] at ht
    rcases Set.mem_iUnion.1 ht with ⟨d, ht⟩
    rcases Set.mem_iUnion.1 ht with ⟨hd, ht⟩
    have hplevel : pt.1 ∈ ⋃ q ∈ scratchTruncationLevel α N d, boxSet α q :=
      scratch_truncationSpatialSet_subset_iUnion_level α N d hp
    rcases Set.mem_iUnion.1 hplevel with ⟨q, hplevel⟩
    rcases Set.mem_iUnion.1 hplevel with ⟨hq, hpq⟩
    have hqcoll : q ∈ scratchTruncationCollection α N :=
      (scratch_mem_truncationCollection_iff α N q).mpr ⟨d, hd, hq⟩
    rw [collectionRegion]
    refine Set.mem_iUnion.2 ⟨q, Set.mem_iUnion.2 ⟨hqcoll, ?_⟩⟩
    change pt.1 ∈ boxSet α q ∧ pt.2 ∈ boxScaleBand q
    refine ⟨hpq, ?_⟩
    rw [scratch_boxScaleBand_eq_truncationBand α N d hq]
    exact ht

theorem scratch_mem_truncationSpatialSet_of_coord_abs_lt
    (α : Anisotropy) (N : ℕ) (x : E3)
    (hbound : ∀ i : Fin 3,
      |(WithLp.ofLp x : Fin 3 → ℝ) i| <
        (2 : ℝ) ^ ((N : ℤ) * (α.weight i : ℤ))) :
    x ∈ scratchTruncationSpatialSet α N := by
  let v : Fin 3 → Bool := fun i ↦ decide (0 ≤ (WithLp.ofLp x : Fin 3 → ℝ) i)
  let R : AnisoBox α := ⟨(N : ℤ), fun i ↦ if v i then 0 else -1⟩
  have hR : R ∈ scratchTruncationRoots α N :=
    (scratch_mem_truncationRoots_iff α N R).mpr ⟨by simp [R], v, by simp [R]⟩
  refine Set.mem_iUnion.2 ⟨R, Set.mem_iUnion.2 ⟨hR, ?_⟩⟩
  rw [boxSet, Set.mem_preimage, Set.mem_pi]
  intro i _
  have hside : boxSide α R i =
      (2 : ℝ) ^ ((N : ℤ) * (α.weight i : ℤ)) := by
    simp [R, boxSide]
  have hspos : 0 < boxSide α R i := boxSide_pos α R i
  rw [boxInterval]
  by_cases hxi : 0 ≤ (WithLp.ofLp x : Fin 3 → ℝ) i
  · have hv : v i = true := by simp [v, hxi]
    have hxlt : (WithLp.ofLp x : Fin 3 → ℝ) i < boxSide α R i := by
      rw [hside]
      exact (le_abs_self _).trans_lt (hbound i)
    simpa [R, hv] using ⟨hxi, hxlt⟩
  · have hxneg : (WithLp.ofLp x : Fin 3 → ℝ) i < 0 := lt_of_not_ge hxi
    have hv : v i = false := by simp [v, hxi]
    have hxlo : -(boxSide α R i) < (WithLp.ofLp x : Fin 3 → ℝ) i := by
      rw [hside]
      exact (abs_lt.mp (hbound i)).1
    simpa [R, hv] using ⟨hxlo.le, hxneg⟩

theorem scratch_exists_mem_truncationSpatialSet
    (α : Anisotropy) (x : E3) :
    ∃ N : ℕ, x ∈ scratchTruncationSpatialSet α N := by
  let C : ℝ := ∑ i : Fin 3, |(WithLp.ofLp x : Fin 3 → ℝ) i|
  have hpow : Tendsto (fun N : ℕ ↦ (2 : ℝ) ^ N) atTop atTop :=
    tendsto_pow_atTop_atTop_of_one_lt (by norm_num)
  obtain ⟨N, hN⟩ := hpow.eventually_gt_atTop C |>.exists
  refine ⟨N, scratch_mem_truncationSpatialSet_of_coord_abs_lt α N x ?_⟩
  intro i
  have hcoord : |(WithLp.ofLp x : Fin 3 → ℝ) i| ≤ C := by
    dsimp [C]
    exact Finset.single_le_sum
      (s := Finset.univ)
      (f := fun j : Fin 3 ↦ |(WithLp.ofLp x : Fin 3 → ℝ) j|)
      (fun j _ ↦ abs_nonneg _) (Finset.mem_univ i)
  have hweight : N ≤ N * α.weight i := by
    calc
      N = N * 1 := by omega
      _ ≤ N * α.weight i := Nat.mul_le_mul_left N
        (Nat.succ_le_iff.mpr (α.weight_pos i))
  calc
    |(WithLp.ofLp x : Fin 3 → ℝ) i| ≤ C := hcoord
    _ < (2 : ℝ) ^ N := hN
    _ ≤ (2 : ℝ) ^ (N * α.weight i) :=
      pow_le_pow_right₀ (by norm_num) hweight
    _ = (2 : ℝ) ^ ((N : ℤ) * (α.weight i : ℤ)) := by
      have hexp : ((N * α.weight i : ℕ) : ℤ) =
          (N : ℤ) * (α.weight i : ℤ) := by
        push_cast
        ring
      rw [← hexp, zpow_natCast]

theorem scratch_truncationSpatialSet_subset_succ
    (α : Anisotropy) (N : ℕ) :
    scratchTruncationSpatialSet α N ⊆ scratchTruncationSpatialSet α (N + 1) := by
  intro x hx
  rw [scratchTruncationSpatialSet] at hx ⊢
  rcases Set.mem_iUnion.1 hx with ⟨R, hx⟩
  rcases Set.mem_iUnion.1 hx with ⟨hR, hx⟩
  refine Set.mem_iUnion.2 ⟨boxParent α R, Set.mem_iUnion.2
    ⟨scratch_parent_mem_truncationRoots α N hR, ?_⟩⟩
  exact boxSet_subset_parent α R hx

theorem scratch_monotone_truncationSpatialSet (α : Anisotropy) :
    Monotone (scratchTruncationSpatialSet α) :=
  monotone_nat_of_le_succ (scratch_truncationSpatialSet_subset_succ α)

theorem scratch_truncationScaleSet_subset_succ (N : ℕ) :
    scratchTruncationScaleSet N ⊆ scratchTruncationScaleSet (N + 1) := by
  intro t ht
  change t ∈ Set.Ioc ((2 : ℝ) ^ (-(N : ℤ) - 1)) ((2 : ℝ) ^ (N : ℤ)) at ht
  change t ∈ Set.Ioc ((2 : ℝ) ^ (-((N + 1 : ℕ) : ℤ) - 1))
    ((2 : ℝ) ^ ((N + 1 : ℕ) : ℤ))
  constructor
  · apply lt_of_le_of_lt _ ht.1
    apply zpow_le_zpow_right₀ (by norm_num)
    push_cast
    omega
  · exact ht.2.trans (zpow_le_zpow_right₀ (by norm_num) (by push_cast; omega))

theorem scratch_monotone_truncationScaleSet : Monotone scratchTruncationScaleSet :=
  monotone_nat_of_le_succ scratch_truncationScaleSet_subset_succ

theorem scratch_exists_mem_truncationScaleSet {t : ℝ} (ht : 0 < t) :
    ∃ N : ℕ, t ∈ scratchTruncationScaleSet N := by
  have hpow : Tendsto (fun N : ℕ ↦ (2 : ℝ) ^ N) atTop atTop :=
    tendsto_pow_atTop_atTop_of_one_lt (by norm_num)
  obtain ⟨N, hNt, hNinv⟩ :=
    ((hpow.eventually_gt_atTop t).and
      (hpow.eventually_gt_atTop t⁻¹)).exists
  refine ⟨N, ?_⟩
  change t ∈ Set.Ioc ((2 : ℝ) ^ (-(N : ℤ) - 1)) ((2 : ℝ) ^ (N : ℤ))
  refine ⟨?_, ?_⟩
  · have hinv : ((2 : ℝ) ^ (N : ℤ))⁻¹ < (t⁻¹)⁻¹ :=
      inv_strictAntiOn
        (show t⁻¹ ∈ Set.Ioi (0 : ℝ) from inv_pos.mpr ht)
        (show (2 : ℝ) ^ N ∈ Set.Ioi (0 : ℝ) from
          pow_pos (show (0 : ℝ) < 2 by norm_num) N)
        hNinv
    have hneg : (2 : ℝ) ^ (-(N : ℤ)) < t := by
      simpa [zpow_neg, inv_inv] using hinv
    have hstep : (2 : ℝ) ^ (-(N : ℤ) - 1) ≤ (2 : ℝ) ^ (-(N : ℤ)) :=
      zpow_le_zpow_right₀ (by norm_num) (by omega)
    exact lt_of_le_of_lt hstep hneg
  · simpa only [zpow_natCast] using hNt.le

/-- The finite source regions exhaust exactly `E₃ × (0,∞)`. -/
theorem scratch_iUnion_collectionRegion_truncationCollection
    (α : Anisotropy) :
    (⋃ N : ℕ, collectionRegion α (scratchTruncationCollection α N)) =
      Set.univ ×ˢ Set.Ioi (0 : ℝ) := by
  apply Set.Subset.antisymm
  · rintro pt hpt
    rcases Set.mem_iUnion.1 hpt with ⟨N, hpt⟩
    rw [scratch_collectionRegion_truncationCollection_eq_slab α N] at hpt
    rcases hpt with ⟨-, ht⟩
    constructor
    · exact Set.mem_univ _
    · change (0 : ℝ) < pt.2
      exact lt_trans
        (show (0 : ℝ) < (2 : ℝ) ^ (-(N : ℤ) - 1) by exact zpow_pos (by norm_num) _)
        ht.1
  · rintro pt ⟨-, ht⟩
    obtain ⟨Np, hp⟩ := scratch_exists_mem_truncationSpatialSet α pt.1
    obtain ⟨Nt, ht'⟩ := scratch_exists_mem_truncationScaleSet ht
    let N : ℕ := max Np Nt
    have hpN : pt.1 ∈ scratchTruncationSpatialSet α N :=
      scratch_monotone_truncationSpatialSet α (Nat.le_max_left _ _) hp
    have htN : pt.2 ∈ scratchTruncationScaleSet N :=
      scratch_monotone_truncationScaleSet (Nat.le_max_right _ _) ht'
    refine Set.mem_iUnion.2 ⟨N, ?_⟩
    rw [scratch_collectionRegion_truncationCollection_eq_slab α N]
    exact ⟨hpN, htN⟩

/-- A generic increasing finite collection exhaustion gives convergence of
the real expanded local form whenever its signed outer integrand is integrable
on the limiting region. -/
theorem scratch_tendsto_expandedModelLocalForm_of_monotone_exhaustion
    (α : Anisotropy) (S : ℕ → BoxCollection α) (u : E3) (c : ℝ → ℝ)
    (f : ModelRealInput) (V : Set (E3 × ℝ))
    (hmono : Monotone fun N ↦ collectionRegion α (S N))
    (hV : (⋃ N, collectionRegion α (S N)) = V)
    (hint : IntegrableOn (fun pt : E3 × ℝ ↦
      c pt.2 * (∫ z : ModelE5,
        modelFirstFiber α f pt.1 pt.2 z *
          modelSecondFiber α (f 3) pt.1 pt.2 z *
            modelSignedDensity α u pt.1 pt.2 z)) V cubeScaleMeasure) :
    Tendsto (fun N ↦ expandedModelLocalForm α (S N) u c f) atTop
      (𝓝 (-∫ pt in V,
        c pt.2 * (∫ z : ModelE5,
          modelFirstFiber α f pt.1 pt.2 z *
            modelSecondFiber α (f 3) pt.1 pt.2 z *
              modelSignedDensity α u pt.1 pt.2 z)
        ∂cubeScaleMeasure)) := by
  let g : E3 × ℝ → ℝ := fun pt ↦
    c pt.2 * (∫ z : ModelE5,
      modelFirstFiber α f pt.1 pt.2 z *
        modelSecondFiber α (f 3) pt.1 pt.2 z *
          modelSignedDensity α u pt.1 pt.2 z)
  have hlim := tendsto_setIntegral_of_monotone
    (μ := cubeScaleMeasure)
    (f := g)
    (fun N ↦ measurableSet_collectionRegion α (S N)) hmono (by
      simpa only [hV] using hint)
  rw [hV] at hlim
  simpa only [expandedModelLocalForm, g] using hlim.neg

/-- The Section 7 convergence bridge for the literal finite truncations. -/
theorem scratch_tendsto_expandedModelLocalForm_truncationCollection
    (α : Anisotropy) (u : E3) (c : ℝ → ℝ) (f : ModelRealInput)
    (hint : IntegrableOn (fun pt : E3 × ℝ ↦
      c pt.2 * (∫ z : ModelE5,
        modelFirstFiber α f pt.1 pt.2 z *
          modelSecondFiber α (f 3) pt.1 pt.2 z *
            modelSignedDensity α u pt.1 pt.2 z))
      (Set.univ ×ˢ Set.Ioi (0 : ℝ)) cubeScaleMeasure) :
    Tendsto (fun N ↦ expandedModelLocalForm α
      (scratchTruncationCollection α N) u c f) atTop
      (𝓝 (-∫ pt in Set.univ ×ˢ Set.Ioi (0 : ℝ),
        c pt.2 * (∫ z : ModelE5,
          modelFirstFiber α f pt.1 pt.2 z *
            modelSecondFiber α (f 3) pt.1 pt.2 z *
              modelSignedDensity α u pt.1 pt.2 z)
        ∂cubeScaleMeasure)) := by
  exact scratch_tendsto_expandedModelLocalForm_of_monotone_exhaustion
    α (scratchTruncationCollection α) u c f (Set.univ ×ˢ Set.Ioi (0 : ℝ))
    (scratch_collectionRegion_mono_of_truncationCollection α)
    (scratch_iUnion_collectionRegion_truncationCollection α) hint

end

end Auto.Twisted
