/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import DFR.Auto.Twisted.Twisted
import DFR.Auto.Twisted.ConventionsAndMainStatement.ConventionsAndMainStatement
import DFR.Auto.Twisted.FunctionSpacesAndFixedBumps.FunctionSpacesAndFixedBumps
import DFR.Auto.Twisted.DyadicGeometryAndLocalSizes.DyadicGeometryAndLocalSizes
import DFR.Auto.Twisted.CubicalTelescopingWithBoundaryTerms.CubicalTelescopingWithBoundaryTerms
import DFR.Auto.Twisted.TheModelFormAndItsLocalization.TheModelFormAndItsLocalization
import DFR.Auto.Twisted.StoppingTimeAndTheInitialExponentRange.StoppingTimeAndTheInitialExponentRange
import DFR.Auto.Twisted.FiberwiseCalderonZygmundDecomposition.FiberwiseCalderonZygmundDecomposition
import DFR.Auto.Twisted.ConeDecompositionMultiplierTheorem.ConeDecompositionMultiplierTheorem

/-!
# Task 3: the three-dimensional anisotropic twisted paraproduct

Top-level module for the formalization of
`blueprints/task_3_twisted_blueprint.tex`.

`Auto.Twisted.Twisted` carries the development itself.  One module per
blueprint section collects that section's labelled definitions and theorems in
the blueprint's own wording; see `automation/Status.md` for the
label-to-Lean map.
-/
