/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/

import Auto.Twisted.Twisted

/-!
# Fiberwise Calderon--Zygmund decomposition

Section 7 of `blueprints/task_3_twisted_blueprint.tex`.

The definitions of this section (`def:fiber_maximal`, `def:weak_norm`) are
already available in `Auto.Twisted`, and `ext:interpolation` is external; this
file carries the section's labelled theorems, stated in the blueprint's own
wording.
-/

namespace Auto
namespace Twisted

open MeasureTheory Filter Set
open scoped BigOperators ENNReal Topology

noncomputable section

/-- **`lem:fiber_kernel`** (Kernel bounds in one fiber).

For `j = 1,2,3` and `s > 0`,
`|f *_j (κ_j)_{s,su_j}(x)| ≤ C U(u)^{10} M^{(j)} f(x)`. -/
theorem lem_fiber_kernel :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (i j : Fin 3) (u : E3) (s : ℝ) (x : E3)
      (f : E3 → ℝ) (A : ℝ), 0 < s → Measurable f → 0 ≤ A →
      (∀ y : E3, |f y| ≤ A) →
      |ModelCoordinateConvolution j f (activeModelKernel i j u) s x| ≤
        C * dyadicBracketShellConstant * sourceWeight u ^ 10 *
          coordinateDyadicBallMaximal j (fun y ↦ (f y : ℂ)) x :=
  abs_activeModelCoordinateConvolution_le_coordinateDyadicBallMaximal 

/-- **`lem:fiber_cz`** (Measurable fiber decomposition).

Let `1 ≤ p < ∞`, `f ∈ L^p(E_3)`, `m ∈ {1,2,3}` and `H > 0`; with `Z_f`, the
dyadic fibers `D_1`, the averages `A_I` and the selection sets `S_I` as in the
source, the good part obeys the stated `L^P` bound. -/
theorem lem_fiber_cz
    {Z : Type*} [MeasurableSpace Z] (μ : Measure Z) [SFinite μ]
    (F : ℝ × Z → ℝ) {p P : ℝ} (hp : 1 ≤ p) (hpP : p ≤ P) {H : ℝ} (hH : 0 < H)
    (hmeas : Measurable F) :
    ∫⁻ w : ℝ × Z, ENNReal.ofReal (|fiberDyadicCountableGoodField F
        (sourceFiberFiniteMassSet F p)
        (fiberDyadicIntervalAverage (fun yz ↦ |F yz| ^ p)) H w| ^ P)
        ∂(volume.prod μ) ≤
      ENNReal.ofReal ((2 * H) ^ ((P - p) / p)) *
        ∫⁻ w : ℝ × Z, ENNReal.ofReal (|F w| ^ p) ∂(volume.prod μ) :=
  lintegral_prod_rpow_fiberDyadicCountableGoodField_le μ F hp hpP hH hmeas

/-- **`lem:interval_tails`** (Tails of disjoint intervals).

For pairwise disjoint bounded intervals of positive length with
`∑_I |I| < ∞`, put `h(x) = ∑_I (1 + |x - c_I|/|I|)^{-2}`.  For `1 ≤ p < ∞`,
`‖h‖_p ≤ C_p (∑_I |I|)^{1/p}`.

This is the case `p > 1`; the endpoint `p = 1` is
`integral_finset_double_intervalTails_le_of_radius_sum`. -/
theorem lem_interval_tails
    {ι : Type*} (S : Finset ι) (c r : ι → ℝ)
    (hr : ∀ i ∈ S, 0 < r i)
    (hdisj : (↑S : Set ι).PairwiseDisjoint
      (fun i ↦ Ioo (c i - r i) (c i + r i)))
    {p q : ℝ} (hpq : q.HolderConjugate p) (hq : 1 < q) :
    lpNorm (aux_lineIntervalTailSum S c r) (ENNReal.ofReal p)
        (volume : Measure FiberDyadicLine)
      ≤ C_lpNorm_finset_double_intervalTails_le_of_radius_sum q *
          (∑ i ∈ S, 2 * r i) ^ (1 / p) :=
  lpNorm_finset_double_intervalTails_le_of_radius_sum S c r hr hdisj hpq hq

/-- **`lem:one_fiber`** (One-fiber weak extension), equation `eq:one_fiber`.

`‖U(f_1,f_2,f_3)‖_{R,∞} ≤ C U(u)^{100} ‖f_m‖_p ∏_{j≠m} ‖f_j‖_{P_j}`. -/
theorem lem_one_fiber
    (α : Anisotropy) (q : Fin 4 → ℝ)
    (hq : ∀ j : Fin 4, 0 < q j)
    (hsum : ∑ j : Fin 4, (q j)⁻¹ = 1)
    (hqs : ∀ j : Fin 4, activeSourceStoppingExponent 2 j < q j)
    (hq1 : ∀ j : Fin 3, 1 ≤ q j.succ) (hq0 : 1 < q 0)
    (m j₁ j₂ : Fin 3)
    {P₁ P₂ p qc R : ℝ} {r23 : ENNReal}
    [ENNReal.HolderTriple (ENNReal.ofReal P₂) (ENNReal.ofReal p) r23]
    [ENNReal.HolderTriple (ENNReal.ofReal P₁) r23 (ENNReal.ofReal R)]
    (hR : 1 ≤ R) (hP₁ : 1 < P₁) (hP₂ : 1 < P₂)
    (hpq : qc.HolderConjugate p) (hqc : 1 < qc) :
    ∃ C₁ : ℝ, 0 < C₁ ∧
      ∀ (u : E3) (c : ℝ → ℝ) (f : ModelOperatorRealInput)
        (a b : ℝ) (N : Fin 3 → ℝ),
      (∀ F : Fin 3 → ℝ, (∏ j ∈ Finset.univ.erase m, F j) = F j₁ * F j₂) →
      (∀ j, 0 < N j) →
      0 < a → Measurable c → (∀ t : ℝ, |c t| ≤ 1) →
      (∀ jj, Measurable (f jj)) →
      (∀ jj, MemLp (f jj) (ENNReal.ofReal (q jj.succ)) (volume : Measure E3)) →
      1 ≤ p → p ≤ q m.succ →
      Integrable (fun x : E3 ↦ |f m x| ^ p) (volume : Measure E3) →
      (∫ x : E3, |f m x| ^ p) ≤ (N m) ^ p →
      (∀ jj, jj ≠ m →
        lpNorm (f jj) (ENNReal.ofReal (q jj.succ)) (volume : Measure E3) ≤ N jj) →
      eLpNorm (fun y ↦ (f j₁ y : ℂ)) (ENNReal.ofReal P₁) (volume : Measure E3)
        ≤ ENNReal.ofReal (N j₁) →
      eLpNorm (fun y ↦ (f j₂ y : ℂ)) (ENNReal.ofReal P₂) (volume : Measure E3)
        ≤ ENNReal.ofReal (N j₂) →
      (R * (1 / p - 1 / q m.succ)) * (q 0).conjExponent = (q 0).conjExponent - R →
      weakNorm volume (ModelTruncatedOperator α u c f a b) R
        ≤ ENNReal.ofReal (∏ j : Fin 3, N j) *
            ENNReal.ofReal ((4 + 2 * 2 ^ ((q 0).conjExponent / R - 1) + 2 * 1) *
              (C₁ * sourceWeight u ^ 100)) :=
  ModelTruncatedOperator_weakNorm_le_one_fiber_unbounded (r23 := r23) α q hq hsum
    hqs hq1 hq0 m j₁ j₂ hR hP₁ hP₂ hpq hqc

/-- **`lem:exponent_simplex`** (Exponent simplex).

Under `eq:extended_region` there exist `b_1,b_2,b_3 > 0` with `b_j < β_j`,
`b_1,b_2 < 1/4`, `b_3 < 1/2`, whose associated simplex has independent edge
vectors. -/
theorem lem_exponent_simplex
    (b : Fin 3 → ℝ) {b₀ : ℝ} (hb₀ : b₀ ≠ 0) :
    AffineIndependent ℝ (fun a : Fin 4 ↦
      (fun j : Fin 3 ↦ b j + if (a : ℕ) = (j : ℕ) + 1 then b₀ else 0)) :=
  affineIndependent_exponentSimplex_vertices b hb₀

end
end Twisted
end Auto
