/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
This file was automatically generated by Claude.
-/
import DFR.Auto.CDR.Sec4SmoothCaseConeDecomposition
import DFR.Auto.CDR.Sec4SmoothCase4CombiningTreesLimit
import DFR.Auto.BilinearMarcinkiewicz
import DFR.Auto.SmoothingIneq3D.Smoothing3D
import DFR.Auto.CDR.Sec4SmoothCaseModelKernels

/-!
# CDR, Section 4: Theorem 2

This file was automatically generated by Claude.

Formalization of the extension of the bounds for the truncated model operators of §4.4-4.5 of
M. Christ, P. Durcik, J. Roos, *Trilinear smoothing inequalities and a variant of the triangular
Hilbert transform*, arXiv:2008.10140v2 (lines 1869-1940 of the source), from the initial range
`2 < p, q`, `1 < r < 2` to the full range `1 < p, q < ∞`, `1/2 < r < 2`: the truncated model
operator (`Auto.CDR.modelOp`)
`U_{a,b}(f₁, f₂)(x, y) = ∫_{a<t≤b} c(t) (f₁ *₁ φ_{t^α})(x, y) (f₂ *₂ ρ_{t^β})(x, y) dt/t`
with `φ = corrK g Φ`, `ρ = corrK h (h ⋆ Ψ)` maps `L^p × L^q → L^r`, uniformly in the truncation,
in `c`, `|c| ≤ 1`, and in `Φ, Ψ` (through the decay of `Φ, Ψ` and the constant `A₀` of the
regularity bounds of `φ, ρ`).

## Main result

* `Auto.CDR.modelOp_full_range`.

## Proof

* Initial range (`FullRange.strong_initial`): the trilinear bound `modelForm_initial` (`pt2`) for
  real data and dyadic truncations is turned into the operator bound by duality
  (`Auto.eLpNorm_le_of_pairing_bound_of_measurable`, testing against the real and imaginary
  parts of the test function), extended to complex `c, f₁, f₂` by splitting into real and
  imaginary parts (eight real pieces, `r > 1`), and to arbitrary `0 < a < b` by replacing `c`
  with `c 1_{(a,b]}` on a dyadic interval `(2^{K₁}/2, 2^{K₂}] ⊇ (a, b]`.
* Interpolation (`FullRange.ustrong_phase1`, `FullRange.ustrong_phase2`): in reciprocal exponents
  `(s, t) = (1/p, 1/q)`, the weak bounds of the fiber-wise Calderón-Zygmund decomposition
  (`modelOp_weak_fiber1_uniform`, `modelOp_weak_fiber2_uniform`) at the four corners
  `(s ± δ, t ± δ)` of a small square, based at points where the strong bound is already known,
  give the strong bound at `(s, t)` by bilinear Marcinkiewicz interpolation. The first step
  reaches `0 < t < 1/2`, `max(0, 1/2 - t) < s < 1` (`fwrange-1`), the second one all
  `0 < s, t < 1` with `s + t > 1/2`. The interpolation constant must not depend on the operator,
  so the form `Auto.bilinear_marcinkiewicz_uniform` of the prerequisite, with the constant chosen
  before the operator, is used; the model operator is a bilinear
  operator on all simple functions since these are bounded (`FullRange.modelBil`).
* From simple functions with finite measure support to bounded measurable `L^p` functions
  (`FullRange.strongBound_of_simple`): approximation by `SimpleFunc.approxOn`, pointwise
  convergence of the model operator by dominated convergence, and Fatou's lemma for `eLpNorm`.
-/

namespace Auto

namespace CDR

namespace FullRange

open MeasureTheory Set Filter
open Auto.Twisted (kernelAt)
open scoped ENNReal Topology

noncomputable section

/-! ### Linearity of the truncated model operator -/

theorem norm_re_le (w : ℂ) : ‖((w.re : ℝ) : ℂ)‖ ≤ ‖w‖ := by
  rw [Complex.norm_real, Real.norm_eq_abs]; exact Complex.abs_re_le_norm _

theorem norm_im_le (w : ℂ) : ‖((w.im : ℝ) : ℂ)‖ ≤ ‖w‖ := by
  rw [Complex.norm_real, Real.norm_eq_abs]; exact Complex.abs_im_le_norm _

theorem norm_I_mul_im_le (w : ℂ) : ‖Complex.I * ((w.im : ℝ) : ℂ)‖ ≤ ‖w‖ := by
  rw [norm_mul, Complex.norm_I, one_mul]; exact norm_im_le w

theorem modelOp_add_right (α β : ℕ) {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1)
    {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ) (hφ : Integrable φ)
    (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {f₁ f g : ℝ × ℝ → ℂ} (h₁ : Measurable f₁)
    (hf : Measurable f) (hg : Measurable g) {M₁ M N : ℝ} (hM₁ : ∀ z, ‖f₁ z‖ ≤ M₁)
    (hM : ∀ z, ‖f z‖ ≤ M) (hN : ∀ z, ‖g z‖ ≤ N) (z : ℝ × ℝ) :
    modelOp α β c φ ρ a b f₁ (f + g) z =
      modelOp α β c φ ρ a b f₁ f z + modelOp α β c φ ρ a b f₁ g z := by
  rw [FiberCZ.modelOp_swap, FiberCZ.modelOp_swap α β c φ ρ a b f₁ f,
    FiberCZ.modelOp_swap α β c φ ρ a b f₁ g]
  exact FiberCZ.modelOp_add_left β α hc hc1 hρm hφm hρ hφ ha (hf.comp measurable_swap)
    (hg.comp measurable_swap) (h₁.comp measurable_swap) (fun _ => hM _) (fun _ => hN _)
    (fun _ => hM₁ _) z.swap

/-- Splitting `c` into real and imaginary parts. -/
theorem modelOp_re_im_c (α β : ℕ) {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1)
    {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ) (hφ : Integrable φ)
    (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {f₁ f₂ : ℝ × ℝ → ℂ} (h₁ : Measurable f₁)
    (h₂ : Measurable f₂) {M₁ M₂ : ℝ} (hM₁ : ∀ z, ‖f₁ z‖ ≤ M₁) (hM₂ : ∀ z, ‖f₂ z‖ ≤ M₂)
    (z : ℝ × ℝ) :
    modelOp α β c φ ρ a b f₁ f₂ z =
      modelOp α β (fun t => ((c t).re : ℂ)) φ ρ a b f₁ f₂ z +
        Complex.I * modelOp α β (fun t => ((c t).im : ℂ)) φ ρ a b f₁ f₂ z := by
  have hre : Measurable fun t => ((c t).re : ℂ) :=
    Complex.measurable_ofReal.comp (Complex.measurable_re.comp hc)
  have him : Measurable fun t => ((c t).im : ℂ) :=
    Complex.measurable_ofReal.comp (Complex.measurable_im.comp hc)
  have i1 := FiberCZ.integrableOn_integrand α β hre
    (fun t => (norm_re_le _).trans (hc1 t)) hφm hρm hφ hρ (b := b) ha h₁ h₂ hM₁ hM₂ z
  have i2 := (FiberCZ.integrableOn_integrand α β him
    (fun t => (norm_im_le _).trans (hc1 t)) hφm hρm hφ hρ (b := b) ha h₁ h₂ hM₁ hM₂ z).const_mul
      Complex.I
  rw [FiberCZ.modelOp_eq, FiberCZ.modelOp_eq, FiberCZ.modelOp_eq, ← integral_const_mul,
    ← integral_add i1 i2]
  refine integral_congr_ae (Eventually.of_forall fun t => ?_)
  simp only
  conv_lhs => rw [← Complex.re_add_im (c t)]
  ring

/-- Splitting `f₁` into real and imaginary parts. -/
theorem modelOp_re_im_left (α β : ℕ) {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1)
    {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ) (hφ : Integrable φ)
    (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {f₁ f₂ : ℝ × ℝ → ℂ} (h₁ : Measurable f₁)
    (h₂ : Measurable f₂) {M₁ M₂ : ℝ} (hM₁ : ∀ z, ‖f₁ z‖ ≤ M₁) (hM₂ : ∀ z, ‖f₂ z‖ ≤ M₂)
    (z : ℝ × ℝ) :
    modelOp α β c φ ρ a b f₁ f₂ z =
      modelOp α β c φ ρ a b (fun w => ((f₁ w).re : ℂ)) f₂ z +
        Complex.I * modelOp α β c φ ρ a b (fun w => ((f₁ w).im : ℂ)) f₂ z := by
  have hre : Measurable fun w => ((f₁ w).re : ℂ) :=
    Complex.measurable_ofReal.comp (Complex.measurable_re.comp h₁)
  have him : Measurable fun w => Complex.I * ((f₁ w).im : ℂ) :=
    measurable_const.mul (Complex.measurable_ofReal.comp (Complex.measurable_im.comp h₁))
  have e : f₁ = (fun w => ((f₁ w).re : ℂ)) + fun w => Complex.I * ((f₁ w).im : ℂ) := by
    funext w
    rw [Pi.add_apply]
    conv_lhs => rw [← Complex.re_add_im (f₁ w)]
    ring
  conv_lhs => rw [e]
  rw [FiberCZ.modelOp_add_left α β hc hc1 hφm hρm hφ hρ ha hre him h₂ (M := M₁) (N := M₁)
    (fun w => (norm_re_le _).trans (hM₁ w)) (fun w => (norm_I_mul_im_le _).trans (hM₁ w)) hM₂,
    FiberCZ.modelOp_smul_left]

/-- Splitting `f₂` into real and imaginary parts. -/
theorem modelOp_re_im_right (α β : ℕ) {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1)
    {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ) (hφ : Integrable φ)
    (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {f₁ f₂ : ℝ × ℝ → ℂ} (h₁ : Measurable f₁)
    (h₂ : Measurable f₂) {M₁ M₂ : ℝ} (hM₁ : ∀ z, ‖f₁ z‖ ≤ M₁) (hM₂ : ∀ z, ‖f₂ z‖ ≤ M₂)
    (z : ℝ × ℝ) :
    modelOp α β c φ ρ a b f₁ f₂ z =
      modelOp α β c φ ρ a b f₁ (fun w => ((f₂ w).re : ℂ)) z +
        Complex.I * modelOp α β c φ ρ a b f₁ (fun w => ((f₂ w).im : ℂ)) z := by
  have hre : Measurable fun w => ((f₂ w).re : ℂ) :=
    Complex.measurable_ofReal.comp (Complex.measurable_re.comp h₂)
  have him : Measurable fun w => Complex.I * ((f₂ w).im : ℂ) :=
    measurable_const.mul (Complex.measurable_ofReal.comp (Complex.measurable_im.comp h₂))
  have e : f₂ = (fun w => ((f₂ w).re : ℂ)) + fun w => Complex.I * ((f₂ w).im : ℂ) := by
    funext w
    rw [Pi.add_apply]
    conv_lhs => rw [← Complex.re_add_im (f₂ w)]
    ring
  conv_lhs => rw [e]
  rw [modelOp_add_right α β hc hc1 hφm hρm hφ hρ ha h₁ hre him (M := M₂) (N := M₂) hM₁
    (fun w => (norm_re_le _).trans (hM₂ w)) (fun w => (norm_I_mul_im_le _).trans (hM₂ w)),
    FiberCZ.modelOp_smul_right]

/-- `‖G + i H‖_r ≤ ‖G‖_r + ‖H‖_r` for `r ≥ 1`. -/
theorem eLpNorm_add_I_mul_le {F G H : ℝ × ℝ → ℂ} (hF : ∀ z, F z = G z + Complex.I * H z)
    (hG : AEStronglyMeasurable G) (hH : AEStronglyMeasurable H) {r : ℝ} (hr : 1 ≤ r) :
    eLpNorm F (ENNReal.ofReal r) volume ≤
      eLpNorm G (ENNReal.ofReal r) volume + eLpNorm H (ENNReal.ofReal r) volume := by
  have e : F = G + Complex.I • H := funext fun z => by
    rw [hF z, Pi.add_apply, Pi.smul_apply, smul_eq_mul]
  rw [e]
  refine (eLpNorm_add_le hG (hH.const_smul _) (by simpa using hr)).trans ?_
  rw [eLpNorm_const_smul]
  have h1 : ‖Complex.I‖ₑ = 1 := by
    rw [← ofReal_norm, Complex.norm_I, ENNReal.ofReal_one]
  rw [h1, one_mul]

theorem eLpNorm_re_le (f : ℝ × ℝ → ℂ) (p : ℝ≥0∞) :
    eLpNorm (fun z => (f z).re) p volume ≤ eLpNorm f p volume :=
  eLpNorm_mono fun z => by rw [Real.norm_eq_abs]; exact Complex.abs_re_le_norm _

theorem eLpNorm_im_le (f : ℝ × ℝ → ℂ) (p : ℝ≥0∞) :
    eLpNorm (fun z => (f z).im) p volume ≤ eLpNorm f p volume :=
  eLpNorm_mono fun z => by rw [Real.norm_eq_abs]; exact Complex.abs_im_le_norm _

theorem eLpNorm_ofReal_comp (u : ℝ × ℝ → ℝ) (p : ℝ≥0∞) :
    eLpNorm (fun z => (u z : ℂ)) p volume = eLpNorm u p volume :=
  eLpNorm_congr_norm_ae (Eventually.of_forall fun z => by simp)

/-! ### Real-valued data and duality -/

/-- The real truncated model integral (the inner integral of `modelForm_initial`). -/
def realModel (α β : ℕ) (c : ℝ → ℝ) (φ ρ : ℝ → ℝ) (a b : ℝ) (u v : ℝ × ℝ → ℝ)
    (z : ℝ × ℝ) : ℝ :=
  ∫ t in Ioc a b, c t * ((∫ x', u (x', z.2) * kernelAt φ (t ^ α) x' z.1) *
    (∫ y', v (z.1, y') * kernelAt ρ (t ^ β) y' z.2)) / t

theorem modelOp_ofReal (α β : ℕ) (c : ℝ → ℝ) (φ ρ : ℝ → ℝ) (a b : ℝ) (u v : ℝ × ℝ → ℝ) :
    modelOp α β (fun t => (c t : ℂ)) φ ρ a b (fun z => (u z : ℂ)) (fun z => (v z : ℂ)) =
      fun z => (realModel α β c φ ρ a b u v z : ℂ) :=
  funext fun z => (ofReal_integral_eq_modelOp α β c φ ρ a b u v z).symm

theorem integrable_of_isBounded_support {h : ℝ × ℝ → ℂ} (hh : Measurable h) {C : ℝ}
    (hC : ∀ x, ‖h x‖ ≤ C) (hs : Bornology.IsBounded (Function.support h)) : Integrable h := by
  have hfin : volume (Function.support h) < ⊤ := hs.measure_lt_top
  have hon : IntegrableOn h (Function.support h) :=
    Measure.integrableOn_of_bounded (M := C) hfin.ne hh.aestronglyMeasurable
      (Eventually.of_forall hC)
  exact (integrableOn_iff_integrable_of_support_subset subset_rfl).mp hon

theorem enorm_ofReal_eq (x : ℝ) : ‖(x : ℂ)‖ₑ = ENNReal.ofReal |x| := by
  rw [← ofReal_norm, Complex.norm_real, Real.norm_eq_abs]

/-- Duality for real data: a bound for the trilinear form against bounded integrable `f₃`
gives the `L^r` bound, `r > 1`. -/
theorem eLpNorm_realStage (α β : ℕ) {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ)
    {a b r p₃ : ℝ} (hr : 1 < r) (hconj : r⁻¹ + p₃⁻¹ = 1) {c : ℝ → ℝ} (hc : Measurable c)
    {u v : ℝ × ℝ → ℝ} (hu : Measurable u) (hv : Measurable v) {X : ℝ≥0∞}
    (H : ∀ f₃ : ℝ × ℝ → ℝ, Measurable f₃ → (∃ M, ∀ z, |f₃ z| ≤ M) → Integrable f₃ →
      ENNReal.ofReal |∫ z, f₃ z * realModel α β c φ ρ a b u v z| ≤
        X * eLpNorm f₃ (ENNReal.ofReal p₃) volume) :
    eLpNorm (modelOp α β (fun t => (c t : ℂ)) φ ρ a b (fun z => (u z : ℂ))
      (fun z => (v z : ℂ))) (ENNReal.ofReal r) volume ≤ 2 * X := by
  have hFm : Measurable fun z => (realModel α β c φ ρ a b u v z : ℂ) := by
    rw [← modelOp_ofReal]
    exact (FiberCZ.stronglyMeasurable_modelOp α β (Complex.measurable_ofReal.comp hc) hφm hρm a b
      (Complex.measurable_ofReal.comp hu) (Complex.measurable_ofReal.comp hv)).measurable
  have hRm : Measurable (realModel α β c φ ρ a b u v) := by
    have := Complex.measurable_re.comp hFm
    simpa [Function.comp_def] using this
  rw [modelOp_ofReal]
  refine Auto.eLpNorm_le_of_pairing_bound_of_measurable hr hconj hFm ?_
  rintro h hh ⟨Ch, hCh⟩ hsupp hint
  have hreM : Measurable fun z => (h z).re := Complex.measurable_re.comp hh
  have himM : Measurable fun z => (h z).im := Complex.measurable_im.comp hh
  have ih := integrable_of_isBounded_support hh hCh hsupp
  have i1 : Integrable fun z => realModel α β c φ ρ a b u v z * (h z).re :=
    hint.mono (hRm.mul hreM).aestronglyMeasurable (Eventually.of_forall fun z => by
      rw [Real.norm_eq_abs, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_mul]
      exact mul_le_mul_of_nonneg_left (Complex.abs_re_le_norm _) (abs_nonneg _))
  have i2 : Integrable fun z => realModel α β c φ ρ a b u v z * (h z).im :=
    hint.mono (hRm.mul himM).aestronglyMeasurable (Eventually.of_forall fun z => by
      rw [Real.norm_eq_abs, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_mul]
      exact mul_le_mul_of_nonneg_left (Complex.abs_im_le_norm _) (abs_nonneg _))
  have e : ∀ z, (realModel α β c φ ρ a b u v z : ℂ) * h z =
      ((realModel α β c φ ρ a b u v z * (h z).re : ℝ) : ℂ) +
        ((realModel α β c φ ρ a b u v z * (h z).im : ℝ) : ℂ) * Complex.I := by
    intro z
    conv_lhs => rw [← Complex.re_add_im (h z)]
    push_cast; ring
  simp_rw [e]
  rw [integral_add i1.ofReal (i2.ofReal.mul_const _), integral_mul_const, integral_complex_ofReal,
    integral_complex_ofReal]
  have b1 := H _ hreM ⟨Ch, fun z => (Complex.abs_re_le_norm _).trans (hCh z)⟩ ih.re
  have b2 := H _ himM ⟨Ch, fun z => (Complex.abs_im_le_norm _).trans (hCh z)⟩ ih.im
  have c1 : ∫ z, realModel α β c φ ρ a b u v z * (h z).re =
      ∫ z, (h z).re * realModel α β c φ ρ a b u v z :=
    integral_congr_ae (Eventually.of_forall fun z => mul_comm _ _)
  have c2 : ∫ z, realModel α β c φ ρ a b u v z * (h z).im =
      ∫ z, (h z).im * realModel α β c φ ρ a b u v z :=
    integral_congr_ae (Eventually.of_forall fun z => mul_comm _ _)
  have hI : ‖Complex.I‖ₑ = 1 := by rw [← ofReal_norm, Complex.norm_I, ENNReal.ofReal_one]
  calc _ ≤ ‖((∫ z, realModel α β c φ ρ a b u v z * (h z).re : ℝ) : ℂ)‖ₑ +
        ‖((∫ z, realModel α β c φ ρ a b u v z * (h z).im : ℝ) : ℂ) * Complex.I‖ₑ :=
        enorm_add_le _ _
    _ = ENNReal.ofReal |∫ z, (h z).re * realModel α β c φ ρ a b u v z| +
        ENNReal.ofReal |∫ z, (h z).im * realModel α β c φ ρ a b u v z| := by
        rw [enorm_mul, hI, mul_one, enorm_ofReal_eq, enorm_ofReal_eq, c1, c2]
    _ ≤ X * eLpNorm h (ENNReal.ofReal p₃) volume + X * eLpNorm h (ENNReal.ofReal p₃) volume := by
        gcongr
        · exact b1.trans (by gcongr; exact eLpNorm_re_le h _)
        · exact b2.trans (by gcongr; exact eLpNorm_im_le h _)
    _ = 2 * X * eLpNorm h (ENNReal.ofReal p₃) volume := by ring

/-! ### Complex data from real data -/

theorem stage_right (α β : ℕ) {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ)
    (hφ : Integrable φ) (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {r q : ℝ} (hr : 1 ≤ r)
    {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1) {f₁ : ℝ × ℝ → ℂ}
    (h₁ : Measurable f₁) {M₁ : ℝ} (hM₁ : ∀ z, ‖f₁ z‖ ≤ M₁) {Y : ℝ≥0∞}
    (H : ∀ v : ℝ × ℝ → ℝ, Measurable v → (∃ M, ∀ z, |v z| ≤ M) →
      eLpNorm (modelOp α β c φ ρ a b f₁ (fun z => (v z : ℂ))) (ENNReal.ofReal r) volume ≤
        Y * eLpNorm v (ENNReal.ofReal q) volume)
    {f₂ : ℝ × ℝ → ℂ} (h₂ : Measurable f₂) {M₂ : ℝ} (hM₂ : ∀ z, ‖f₂ z‖ ≤ M₂) :
    eLpNorm (modelOp α β c φ ρ a b f₁ f₂) (ENNReal.ofReal r) volume ≤
      2 * Y * eLpNorm f₂ (ENNReal.ofReal q) volume := by
  have hre : Measurable fun w => (f₂ w).re := Complex.measurable_re.comp h₂
  have him : Measurable fun w => (f₂ w).im := Complex.measurable_im.comp h₂
  refine (eLpNorm_add_I_mul_le (modelOp_re_im_right α β hc hc1 hφm hρm hφ hρ ha h₁ h₂ hM₁ hM₂)
    (FiberCZ.stronglyMeasurable_modelOp α β hc hφm hρm a b h₁
      (Complex.measurable_ofReal.comp hre)).aestronglyMeasurable
    (FiberCZ.stronglyMeasurable_modelOp α β hc hφm hρm a b h₁
      (Complex.measurable_ofReal.comp him)).aestronglyMeasurable hr).trans ?_
  calc _ ≤ Y * eLpNorm f₂ (ENNReal.ofReal q) volume +
        Y * eLpNorm f₂ (ENNReal.ofReal q) volume := by
        gcongr
        · exact (H _ hre ⟨M₂, fun z => (Complex.abs_re_le_norm _).trans (hM₂ z)⟩).trans
            (by gcongr; exact eLpNorm_re_le f₂ _)
        · exact (H _ him ⟨M₂, fun z => (Complex.abs_im_le_norm _).trans (hM₂ z)⟩).trans
            (by gcongr; exact eLpNorm_im_le f₂ _)
    _ = _ := by ring

theorem stage_left (α β : ℕ) {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ)
    (hφ : Integrable φ) (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {r p : ℝ} (hr : 1 ≤ r)
    {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1) {f₂ : ℝ × ℝ → ℂ}
    (h₂ : Measurable f₂) {M₂ : ℝ} (hM₂ : ∀ z, ‖f₂ z‖ ≤ M₂) {Y : ℝ≥0∞}
    (H : ∀ u : ℝ × ℝ → ℝ, Measurable u → (∃ M, ∀ z, |u z| ≤ M) →
      eLpNorm (modelOp α β c φ ρ a b (fun z => (u z : ℂ)) f₂) (ENNReal.ofReal r) volume ≤
        Y * eLpNorm u (ENNReal.ofReal p) volume)
    {f₁ : ℝ × ℝ → ℂ} (h₁ : Measurable f₁) {M₁ : ℝ} (hM₁ : ∀ z, ‖f₁ z‖ ≤ M₁) :
    eLpNorm (modelOp α β c φ ρ a b f₁ f₂) (ENNReal.ofReal r) volume ≤
      2 * Y * eLpNorm f₁ (ENNReal.ofReal p) volume := by
  have hre : Measurable fun w => (f₁ w).re := Complex.measurable_re.comp h₁
  have him : Measurable fun w => (f₁ w).im := Complex.measurable_im.comp h₁
  refine (eLpNorm_add_I_mul_le (modelOp_re_im_left α β hc hc1 hφm hρm hφ hρ ha h₁ h₂ hM₁ hM₂)
    (FiberCZ.stronglyMeasurable_modelOp α β hc hφm hρm a b
      (Complex.measurable_ofReal.comp hre) h₂).aestronglyMeasurable
    (FiberCZ.stronglyMeasurable_modelOp α β hc hφm hρm a b
      (Complex.measurable_ofReal.comp him) h₂).aestronglyMeasurable hr).trans ?_
  calc _ ≤ Y * eLpNorm f₁ (ENNReal.ofReal p) volume +
        Y * eLpNorm f₁ (ENNReal.ofReal p) volume := by
        gcongr
        · exact (H _ hre ⟨M₁, fun z => (Complex.abs_re_le_norm _).trans (hM₁ z)⟩).trans
            (by gcongr; exact eLpNorm_re_le f₁ _)
        · exact (H _ him ⟨M₁, fun z => (Complex.abs_im_le_norm _).trans (hM₁ z)⟩).trans
            (by gcongr; exact eLpNorm_im_le f₁ _)
    _ = _ := by ring

theorem stage_c (α β : ℕ) {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ)
    (hφ : Integrable φ) (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {r : ℝ} (hr : 1 ≤ r)
    {f₁ f₂ : ℝ × ℝ → ℂ} (h₁ : Measurable f₁) (h₂ : Measurable f₂) {M₁ M₂ : ℝ}
    (hM₁ : ∀ z, ‖f₁ z‖ ≤ M₁) (hM₂ : ∀ z, ‖f₂ z‖ ≤ M₂) {Y : ℝ≥0∞}
    (H : ∀ c : ℝ → ℝ, Measurable c → (∀ t, |c t| ≤ 1) →
      eLpNorm (modelOp α β (fun t => (c t : ℂ)) φ ρ a b f₁ f₂) (ENNReal.ofReal r) volume ≤ Y)
    {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1) :
    eLpNorm (modelOp α β c φ ρ a b f₁ f₂) (ENNReal.ofReal r) volume ≤ 2 * Y := by
  have hre : Measurable fun t => (c t).re := Complex.measurable_re.comp hc
  have him : Measurable fun t => (c t).im := Complex.measurable_im.comp hc
  refine (eLpNorm_add_I_mul_le (modelOp_re_im_c α β hc hc1 hφm hρm hφ hρ ha h₁ h₂ hM₁ hM₂)
    (FiberCZ.stronglyMeasurable_modelOp α β (Complex.measurable_ofReal.comp hre) hφm hρm a b
      h₁ h₂).aestronglyMeasurable
    (FiberCZ.stronglyMeasurable_modelOp α β (Complex.measurable_ofReal.comp him) hφm hρm a b
      h₁ h₂).aestronglyMeasurable hr).trans ?_
  calc _ ≤ Y + Y := add_le_add (H _ hre fun t => (Complex.abs_re_le_norm _).trans (hc1 t))
        (H _ him fun t => (Complex.abs_im_le_norm _).trans (hc1 t))
    _ = _ := by ring

/-! ### Truncation -/

theorem modelOp_indicator (α β : ℕ) (c : ℝ → ℂ) (φ ρ : ℝ → ℝ) {a b A B : ℝ} (hA : A ≤ a)
    (hB : b ≤ B) (f₁ f₂ : ℝ × ℝ → ℂ) (z : ℝ × ℝ) :
    modelOp α β c φ ρ a b f₁ f₂ z = modelOp α β ((Ioc a b).indicator c) φ ρ A B f₁ f₂ z := by
  rw [FiberCZ.modelOp_eq, FiberCZ.modelOp_eq]
  set F : ℝ → ℂ := fun t =>
    c t * (FiberCZ.inner1 α φ f₁ t z * FiberCZ.inner2 β ρ f₂ t z) / t with hF
  calc ∫ t in Ioc a b, F t = ∫ t in Ioc A B ∩ Ioc a b, F t := by
        rw [inter_eq_right.mpr (Ioc_subset_Ioc hA hB)]
    _ = ∫ t in Ioc A B, (Ioc a b).indicator F t := (setIntegral_indicator measurableSet_Ioc).symm
    _ = _ := by
        refine integral_congr_ae (Eventually.of_forall fun t => ?_)
        by_cases ht : t ∈ Ioc a b <;> simp [hF, ht]

theorem exists_dyadic {a b : ℝ} (ha : 0 < a) :
    ∃ K₁ K₂ : ℤ, (2 : ℝ) ^ K₁ / 2 ≤ a ∧ b ≤ 2 ^ K₂ := by
  obtain ⟨K₁, hK₁, -⟩ := exists_mem_Ico_zpow (x := 2 * a) (y := (2 : ℝ)) (by positivity)
    one_lt_two
  obtain ⟨K₂, -, hK₂⟩ := exists_mem_Ico_zpow (x := max b 1) (y := (2 : ℝ)) (by positivity)
    one_lt_two
  exact ⟨K₁, K₂ + 1, by linarith, (le_max_left _ _).trans hK₂.le⟩

/-! ### The initial range for complex data -/

theorem initial_exponents {p q r : ℝ} (hp : 2 < p) (hq : 2 < q) (hr2 : r < 2)
    (hpqr : 1 / p + 1 / q = 1 / r) :
    1 < r ∧ 2 < r / (r - 1) ∧ 1 / p + 1 / q + 1 / (r / (r - 1)) = 1 ∧
      r⁻¹ + (r / (r - 1))⁻¹ = 1 := by
  have h1p : 1 / p < 1 / 2 := (one_div_lt_one_div (by linarith) two_pos).mpr hp
  have h1q : 1 / q < 1 / 2 := (one_div_lt_one_div (by linarith) two_pos).mpr hq
  have hp0 : 0 < 1 / p := one_div_pos.mpr (by linarith)
  have hq0 : 0 < 1 / q := one_div_pos.mpr (by linarith)
  have hr0 : 0 < r := one_div_pos.mp (by rw [← hpqr]; linarith)
  have hr1 : 1 < r := by
    have h : 1 / r < 1 / 1 := by rw [← hpqr]; linarith
    exact (one_div_lt_one_div hr0 one_pos).mp h
  have hr1' : r - 1 ≠ 0 := by linarith
  refine ⟨hr1, ?_, ?_, ?_⟩
  · rw [lt_div_iff₀ (by linarith)]; linarith
  · rw [hpqr, one_div_div]; field_simp; ring
  · rw [inv_div]; field_simp; ring

/-- `pt2` for complex data, arbitrary truncations and the operator form: for `2 < p, q`,
`1 < r < 2`, the truncated model operator maps `L^p × L^q → L^r`. -/
theorem strong_initial {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) :
    ∃ N : ℕ, ∀ {p q r : ℝ}, 2 < p → 2 < q → r < 2 → 1 / p + 1 / q = 1 / r →
    ∃ C : ℝ, 0 ≤ C ∧ ∀ Φ Ψ : ℝ → ℝ, Continuous Φ → Continuous Ψ →
      (∀ x, |Φ x| ≤ (1 + |x|) ^ (-(N : ℝ))) → (∀ x, |Ψ x| ≤ (1 + |x|) ^ (-(N : ℝ))) →
      Measurable (corrK Twisted.gaussian Φ) → Integrable (corrK Twisted.gaussian Φ) →
      Measurable (corrK Twisted.gaussianDeriv (hconv Ψ)) →
      Integrable (corrK Twisted.gaussianDeriv (hconv Ψ)) →
      ∀ (a b : ℝ) (c : ℝ → ℂ), 0 < a → a < b → Measurable c → (∀ t, ‖c t‖ ≤ 1) →
      ∀ f₁ f₂ : ℝ × ℝ → ℂ, Measurable f₁ → Measurable f₂ → (∃ M, ∀ z, ‖f₁ z‖ ≤ M) →
        (∃ M, ∀ z, ‖f₂ z‖ ≤ M) →
        eLpNorm (modelOp α β c (corrK Twisted.gaussian Φ) (corrK Twisted.gaussianDeriv (hconv Ψ))
          a b f₁ f₂) (ENNReal.ofReal r) volume ≤
          ENNReal.ofReal C * eLpNorm f₁ (ENNReal.ofReal p) volume *
            eLpNorm f₂ (ENNReal.ofReal q) volume := by
  obtain ⟨N, HN⟩ := modelForm_initial hα hβ
  refine ⟨N, fun {p q r} hp hq hr2 hpqr => ?_⟩
  obtain ⟨hr1, hp₃, hsum, hconj⟩ := initial_exponents hp hq hr2 hpqr
  obtain ⟨C₀, hC₀, H⟩ := HN hp hq hp₃ hsum
  refine ⟨16 * C₀, by positivity, ?_⟩
  intro Φ Ψ hΦ hΨ hdΦ hdΨ hφm iφ hρm iρ a b c ha hab hc hc1 f₁ f₂ h₁ h₂ hb₁ hb₂
  obtain ⟨M₁, hM₁⟩ := hb₁
  obtain ⟨M₂, hM₂⟩ := hb₂
  obtain ⟨K₁, K₂, hK₁, hK₂⟩ := exists_dyadic (b := b) ha
  have hA : 0 < (2 : ℝ) ^ K₁ / 2 := by positivity
  rw [show modelOp α β c (corrK Twisted.gaussian Φ) (corrK Twisted.gaussianDeriv (hconv Ψ))
      a b f₁ f₂ = modelOp α β ((Ioc a b).indicator c) (corrK Twisted.gaussian Φ)
        (corrK Twisted.gaussianDeriv (hconv Ψ)) ((2 : ℝ) ^ K₁ / 2) (2 ^ K₂) f₁ f₂ from
      funext (modelOp_indicator α β c _ _ hK₁ hK₂ f₁ f₂)]
  have hcI : Measurable ((Ioc a b).indicator c) := hc.indicator measurableSet_Ioc
  have hcI1 : ∀ t, ‖(Ioc a b).indicator c t‖ ≤ 1 := fun t =>
    (norm_indicator_le_norm_self c t).trans (hc1 t)
  have Hreal : ∀ c' : ℝ → ℝ, Measurable c' → (∀ t, |c' t| ≤ 1) → ∀ u v : ℝ × ℝ → ℝ,
      Measurable u → Measurable v → (∃ M, ∀ z, |u z| ≤ M) → (∃ M, ∀ z, |v z| ≤ M) →
      eLpNorm (modelOp α β (fun t => (c' t : ℂ)) (corrK Twisted.gaussian Φ)
        (corrK Twisted.gaussianDeriv (hconv Ψ)) ((2 : ℝ) ^ K₁ / 2) (2 ^ K₂)
        (fun z => (u z : ℂ)) (fun z => (v z : ℂ))) (ENNReal.ofReal r) volume ≤
        2 * (ENNReal.ofReal C₀ * eLpNorm u (ENNReal.ofReal p) volume *
          eLpNorm v (ENNReal.ofReal q) volume) := by
    intro c' hc' hc'1 u v hu hv hub hvb
    obtain ⟨Mu, hMu⟩ := hub
    obtain ⟨Mv, hMv⟩ := hvb
    refine eLpNorm_realStage α β hφm hρm hr1 hconj hc' hu hv ?_
    intro f₃ h₃ hb₃ i₃
    obtain ⟨M₃, hM₃⟩ := hb₃
    have h := H Φ Ψ 1 1 hΦ hΨ (fun x => by rw [one_mul]; exact hdΦ x)
      (fun x => by rw [one_mul]; exact hdΨ x) K₁ K₂ c' hc' hc'1 u v f₃ hu hv h₃
      (max Mu (max Mv M₃)) (fun z => (hMu z).trans (le_max_left _ _))
      (fun z => (hMv z).trans ((le_max_left _ _).trans (le_max_right _ _)))
      (fun z => (hM₃ z).trans ((le_max_right _ _).trans (le_max_right _ _))) i₃
    rw [mul_one, mul_one] at h
    exact h
  refine (stage_c α β hφm hρm iφ iρ hA hr1.le h₁ h₂ hM₁ hM₂
    (Y := 8 * ENNReal.ofReal C₀ * eLpNorm f₁ (ENNReal.ofReal p) volume *
      eLpNorm f₂ (ENNReal.ofReal q) volume) ?_ hcI hcI1).trans (le_of_eq ?_)
  · intro c' hc' hc'1
    have hcm : Measurable fun t => (c' t : ℂ) := Complex.measurable_ofReal.comp hc'
    have hcn : ∀ t, ‖(c' t : ℂ)‖ ≤ 1 := fun t => by
      rw [Complex.norm_real, Real.norm_eq_abs]; exact hc'1 t
    refine (stage_left α β hφm hρm iφ iρ hA hr1.le hcm hcn h₂ hM₂
      (Y := 4 * ENNReal.ofReal C₀ * eLpNorm f₂ (ENNReal.ofReal q) volume) ?_ h₁ hM₁).trans
      (le_of_eq (by ring))
    intro u hu hub
    obtain ⟨Mu, hMu⟩ := hub
    refine (stage_right α β hφm hρm iφ iρ hA hr1.le hcm hcn
      (f₁ := fun z => (u z : ℂ)) (Complex.measurable_ofReal.comp hu) (M₁ := Mu)
      (fun z => by rw [Complex.norm_real, Real.norm_eq_abs]; exact hMu z)
      (Y := 2 * ENNReal.ofReal C₀ * eLpNorm u (ENNReal.ofReal p) volume) ?_ h₂ hM₂).trans
      (le_of_eq (by ring))
    intro v hv hvb
    exact (Hreal c' hc' hc'1 u v hu hv ⟨Mu, hMu⟩ hvb).trans (le_of_eq (by ring))
  · rw [ENNReal.ofReal_mul (by norm_num : (0 : ℝ) ≤ 16), ENNReal.ofReal_ofNat]
    ring

/-! ### Bilinear Marcinkiewicz interpolation with a uniform constant -/

section Uniform

open Auto.BilMarc

variable {X Y Z : Type*} [MeasurableSpace X] [MeasurableSpace Y] [MeasurableSpace Z]
  {μ : Measure X} {ν : Measure Y} {ρ : Measure Z}


/-- A distribution-function bound gives a weak quasinorm bound. -/
theorem weakLpNorm_le_of_distribution {v : Z → ℂ} {r C : ℝ} (hr : 0 < r) (hC : 0 ≤ C)
    {W : ℝ≥0∞} (h : ∀ lam : ℝ, 0 < lam →
      ρ {z | lam < ‖v z‖} ≤ ENNReal.ofReal (C * lam ^ (-r)) * W ^ r) :
    weakLpNorm ρ r v ≤ ENNReal.ofReal (C ^ (1 / r)) * W := by
  unfold weakLpNorm
  refine iSup₂_le fun τ hτ => ?_
  have hr' : 0 ≤ 1 / r := by positivity
  calc ENNReal.ofReal τ * ρ {z | τ < ‖v z‖} ^ (1 / r)
      ≤ ENNReal.ofReal τ * (ENNReal.ofReal (C * τ ^ (-r)) * W ^ r) ^ (1 / r) := by
        gcongr; exact h τ hτ
    _ = ENNReal.ofReal τ * (ENNReal.ofReal (C * τ ^ (-r)) ^ (1 / r) * W) := by
        rw [ENNReal.mul_rpow_of_nonneg _ _ hr', ← ENNReal.rpow_mul, mul_one_div_cancel hr.ne',
          ENNReal.rpow_one]
    _ = ENNReal.ofReal (C ^ (1 / r)) * W := by
        rw [ENNReal.ofReal_rpow_of_nonneg (by positivity) hr', ← mul_assoc,
          ← ENNReal.ofReal_mul hτ.le]
        congr 2
        rw [Real.mul_rpow hC (by positivity), ← Real.rpow_mul hτ.le,
          show -r * (1 / r) = -1 by field_simp, Real.rpow_neg_one]
        field_simp

end Uniform

/-! ### The model operator as a bilinear operator on simple functions -/

theorem exists_bound_simpleFunc (f : SimpleFunc (ℝ × ℝ) ℂ) : ∃ M, ∀ z, ‖f z‖ ≤ M :=
  f.exists_forall_norm_le

/-- The truncated model operator on pairs of simple functions. -/
def modelBil (α β : ℕ) {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1)
    {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ) (hφ : Integrable φ)
    (hρ : Integrable ρ) {a : ℝ} (b : ℝ) (ha : 0 < a) :
    SimpleFunc (ℝ × ℝ) ℂ →ₗ[ℂ] SimpleFunc (ℝ × ℝ) ℂ →ₗ[ℂ] (ℝ × ℝ → ℂ) :=
  LinearMap.mk₂ ℂ (fun f g => modelOp α β c φ ρ a b f g)
    (fun f₁ f₂ g => by
      obtain ⟨M₁, hM₁⟩ := f₁.exists_forall_norm_le
      obtain ⟨M₂, hM₂⟩ := f₂.exists_forall_norm_le
      obtain ⟨N, hN⟩ := g.exists_forall_norm_le
      funext z
      rw [SimpleFunc.coe_add, Pi.add_apply]
      exact FiberCZ.modelOp_add_left α β hc hc1 hφm hρm hφ hρ ha f₁.measurable f₂.measurable
        g.measurable hM₁ hM₂ hN z)
    (fun k f g => by
      funext z
      rw [SimpleFunc.coe_smul, Pi.smul_apply, smul_eq_mul]
      exact FiberCZ.modelOp_smul_left α β c φ ρ a b k f g z)
    (fun f g₁ g₂ => by
      obtain ⟨M, hM⟩ := f.exists_forall_norm_le
      obtain ⟨N₁, hN₁⟩ := g₁.exists_forall_norm_le
      obtain ⟨N₂, hN₂⟩ := g₂.exists_forall_norm_le
      funext z
      rw [SimpleFunc.coe_add, Pi.add_apply]
      exact modelOp_add_right α β hc hc1 hφm hρm hφ hρ ha f.measurable g₁.measurable
        g₂.measurable hM hN₁ hN₂ z)
    (fun k f g => by
      funext z
      rw [SimpleFunc.coe_smul, Pi.smul_apply, smul_eq_mul]
      exact FiberCZ.modelOp_smul_right α β c φ ρ a b k f g z)

theorem modelBil_apply (α β : ℕ) {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1)
    {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ) (hφ : Integrable φ)
    (hρ : Integrable ρ) {a : ℝ} (b : ℝ) (ha : 0 < a) (f g : SimpleFunc (ℝ × ℝ) ℂ) :
    modelBil α β hc hc1 hφm hρm hφ hρ b ha f g = modelOp α β c φ ρ a b f g := rfl

/-! ### From simple functions to bounded functions -/

theorem inner1_tendsto (α : ℕ) {φ : ℝ → ℝ} (hφ : Integrable φ) {F : ℕ → ℝ × ℝ → ℂ}
    (hFm : ∀ n, Measurable (F n)) {B : ℝ} (hB : ∀ n z, ‖F n z‖ ≤ B) {f : ℝ × ℝ → ℂ}
    (hf : ∀ z, Tendsto (fun n => F n z) atTop (𝓝 (f z))) {t : ℝ} (ht : 0 < t) (z : ℝ × ℝ) :
    Tendsto (fun n => FiberCZ.inner1 α φ (F n) t z) atTop (𝓝 (FiberCZ.inner1 α φ f t z)) := by
  unfold FiberCZ.inner1
  have hk := FiberCZ.integrable_kernelAt hφ (pow_pos ht α) z.1
  refine tendsto_integral_of_dominated_convergence (fun x' => B * |kernelAt φ (t ^ α) x' z.1|)
    (fun n => (((hFm n).comp (measurable_id.prodMk measurable_const)).aestronglyMeasurable).mul
      hk.ofReal.aestronglyMeasurable) (hk.abs.const_mul B) (fun n => ?_) ?_
  · refine Eventually.of_forall fun x' => ?_
    rw [norm_mul, Complex.norm_real, Real.norm_eq_abs]
    exact mul_le_mul_of_nonneg_right (hB n _) (abs_nonneg _)
  · exact Eventually.of_forall fun x' => (hf _).mul_const _

theorem inner2_tendsto (β : ℕ) {ρ : ℝ → ℝ} (hρ : Integrable ρ) {G : ℕ → ℝ × ℝ → ℂ}
    (hGm : ∀ n, Measurable (G n)) {B : ℝ} (hB : ∀ n z, ‖G n z‖ ≤ B) {g : ℝ × ℝ → ℂ}
    (hg : ∀ z, Tendsto (fun n => G n z) atTop (𝓝 (g z))) {t : ℝ} (ht : 0 < t) (z : ℝ × ℝ) :
    Tendsto (fun n => FiberCZ.inner2 β ρ (G n) t z) atTop (𝓝 (FiberCZ.inner2 β ρ g t z)) := by
  unfold FiberCZ.inner2
  have hk := FiberCZ.integrable_kernelAt hρ (pow_pos ht β) z.2
  refine tendsto_integral_of_dominated_convergence (fun y' => B * |kernelAt ρ (t ^ β) y' z.2|)
    (fun n => (((hGm n).comp (measurable_const.prodMk measurable_id)).aestronglyMeasurable).mul
      hk.ofReal.aestronglyMeasurable) (hk.abs.const_mul B) (fun n => ?_) ?_
  · refine Eventually.of_forall fun y' => ?_
    rw [norm_mul, Complex.norm_real, Real.norm_eq_abs]
    exact mul_le_mul_of_nonneg_right (hB n _) (abs_nonneg _)
  · exact Eventually.of_forall fun y' => (hg _).mul_const _

theorem modelOp_tendsto (α β : ℕ) {c : ℝ → ℂ} (hc : Measurable c) (hc1 : ∀ t, ‖c t‖ ≤ 1)
    {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ) (hφ : Integrable φ)
    (hρ : Integrable ρ) {a b : ℝ} (ha : 0 < a) {F G : ℕ → ℝ × ℝ → ℂ}
    (hFm : ∀ n, Measurable (F n)) (hGm : ∀ n, Measurable (G n)) {B₁ B₂ : ℝ}
    (hB₁ : ∀ n z, ‖F n z‖ ≤ B₁) (hB₂ : ∀ n z, ‖G n z‖ ≤ B₂) {f g : ℝ × ℝ → ℂ}
    (hf : ∀ z, Tendsto (fun n => F n z) atTop (𝓝 (f z)))
    (hg : ∀ z, Tendsto (fun n => G n z) atTop (𝓝 (g z))) (z : ℝ × ℝ) :
    Tendsto (fun n => modelOp α β c φ ρ a b (F n) (G n) z) atTop
      (𝓝 (modelOp α β c φ ρ a b f g z)) := by
  simp only [FiberCZ.modelOp_eq]
  have hB₁0 : 0 ≤ B₁ := (norm_nonneg _).trans (hB₁ 0 0)
  have hB₂0 : 0 ≤ B₂ := (norm_nonneg _).trans (hB₂ 0 0)
  have hL1 : 0 ≤ B₁ * ∫ u, |φ u| := mul_nonneg hB₁0 (integral_nonneg fun _ => abs_nonneg _)
  have hL2 : 0 ≤ B₂ * ∫ u, |ρ u| := mul_nonneg hB₂0 (integral_nonneg fun _ => abs_nonneg _)
  refine tendsto_integral_of_dominated_convergence
    (fun _ => (B₁ * ∫ u, |φ u|) * (B₂ * ∫ u, |ρ u|) / a) (fun n => ?_)
    (integrableOn_const measure_Ioc_lt_top.ne) (fun n => ?_) ?_
  · exact ((FiberCZ.measurable_integrand α β hc hφm hρm (hFm n) (hGm n)).comp
      (measurable_const.prodMk measurable_id)).aestronglyMeasurable
  · filter_upwards [ae_restrict_mem measurableSet_Ioc] with t ht
    have ht0 : 0 < t := ha.trans ht.1
    have i1 := FiberCZ.norm_inner1_le hφ (hB₁ n) α ht0 z
    have i2 := FiberCZ.norm_inner2_le hρ (hB₂ n) β ht0 z
    rw [norm_div, norm_mul, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_pos ht0]
    calc ‖c t‖ * (‖FiberCZ.inner1 α φ (F n) t z‖ * ‖FiberCZ.inner2 β ρ (G n) t z‖) / t
        ≤ 1 * ((B₁ * ∫ u, |φ u|) * (B₂ * ∫ u, |ρ u|)) / t := by
          gcongr
          · exact hc1 t
      _ ≤ (B₁ * ∫ u, |φ u|) * (B₂ * ∫ u, |ρ u|) / a := by
          rw [one_mul]; exact div_le_div_of_nonneg_left (mul_nonneg hL1 hL2) ha ht.1.le
  · filter_upwards [ae_restrict_mem measurableSet_Ioc] with t ht
    have ht0 : 0 < t := ha.trans ht.1
    exact (((inner1_tendsto α hφ hFm hB₁ hf ht0 z).mul
      (inner2_tendsto β hρ hGm hB₂ hg ht0 z)).const_mul (c t)).div_const _

/-- The approximating simple functions `approxOn f univ 0`. -/
def sApprox {f : ℝ × ℝ → ℂ} (hf : Measurable f) (n : ℕ) : SimpleFunc (ℝ × ℝ) ℂ :=
  SimpleFunc.approxOn f hf univ 0 (mem_univ 0) n

theorem norm_sApprox_le {f : ℝ × ℝ → ℂ} (hf : Measurable f) (n : ℕ) (z : ℝ × ℝ) :
    ‖sApprox hf n z‖ ≤ 2 * ‖f z‖ := by
  have := SimpleFunc.norm_approxOn_zero_le hf (mem_univ (0 : ℂ)) z n
  unfold sApprox; linarith

theorem tendsto_sApprox {f : ℝ × ℝ → ℂ} (hf : Measurable f) (z : ℝ × ℝ) :
    Tendsto (fun n => sApprox hf n z) atTop (𝓝 (f z)) :=
  SimpleFunc.tendsto_approxOn hf (mem_univ 0) (by simp)

theorem finMeasSupp_sApprox {f : ℝ × ℝ → ℂ} (hf : Measurable f) {p : ℝ} (hp : 0 < p)
    (hfp : MemLp f (ENNReal.ofReal p)) (n : ℕ) : (sApprox hf n).FinMeasSupp volume :=
  (SimpleFunc.memLp_iff_finMeasSupp (by simpa using hp) ENNReal.ofReal_ne_top).mp
    (SimpleFunc.memLp_approxOn hf hfp (mem_univ 0) MemLp.zero' n)

theorem eLpNorm_sApprox_le {f : ℝ × ℝ → ℂ} (hf : Measurable f) (p : ℝ≥0∞) (n : ℕ) :
    eLpNorm (sApprox hf n) p volume ≤ 2 * eLpNorm f p volume := by
  have h2 : ‖(2 : ℂ)‖ₑ = 2 := by
    rw [← ofReal_norm, Complex.norm_two, ENNReal.ofReal_ofNat]
  calc eLpNorm (sApprox hf n) p volume ≤ eLpNorm ((2 : ℂ) • f) p volume :=
        eLpNorm_mono fun z => by
          rw [Pi.smul_apply, smul_eq_mul, norm_mul, Complex.norm_two]
          exact norm_sApprox_le hf n z
    _ = 2 * eLpNorm f p volume := by rw [eLpNorm_const_smul, h2]

/-- A strong bound for simple functions with finite measure support extends to bounded
measurable functions (with constant `4 C`). -/
theorem strongBound_of_simple (α β : ℕ) {φ ρ : ℝ → ℝ} (hφm : Measurable φ) (hρm : Measurable ρ)
    (hφ : Integrable φ) (hρ : Integrable ρ) {p q r C : ℝ} (hp : 0 < p) (hq : 0 < q)
    (H : ∀ (a b : ℝ) (c : ℝ → ℂ), 0 < a → a < b → Measurable c → (∀ t, ‖c t‖ ≤ 1) →
      ∀ f g : SimpleFunc (ℝ × ℝ) ℂ, f.FinMeasSupp volume → g.FinMeasSupp volume →
      eLpNorm (modelOp α β c φ ρ a b f g) (ENNReal.ofReal r) volume ≤
        ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) volume *
          eLpNorm g (ENNReal.ofReal q) volume) :
    FiberCZ.StrongBound α β φ ρ p q r (4 * C) := by
  intro a b c ha hab hc hc1 f₁ f₂ h₁ h₂ hb₁ hb₂ m₁ m₂
  obtain ⟨M₁, hM₁⟩ := hb₁
  obtain ⟨M₂, hM₂⟩ := hb₂
  have hlim := Lp.eLpNorm_lim_le_liminf_eLpNorm (p := ENNReal.ofReal r) (μ := volume)
    (f := fun n => modelOp α β c φ ρ a b (sApprox h₁ n) (sApprox h₂ n))
    (fun n => (FiberCZ.stronglyMeasurable_modelOp α β hc hφm hρm a b (sApprox h₁ n).measurable
      (sApprox h₂ n).measurable).aestronglyMeasurable)
    (modelOp α β c φ ρ a b f₁ f₂) (Eventually.of_forall fun z =>
      modelOp_tendsto α β hc hc1 hφm hρm hφ hρ ha (fun n => (sApprox h₁ n).measurable)
        (fun n => (sApprox h₂ n).measurable)
        (B₁ := 2 * M₁) (B₂ := 2 * M₂)
        (fun n z => (norm_sApprox_le h₁ n z).trans (by linarith [hM₁ z]))
        (fun n z => (norm_sApprox_le h₂ n z).trans (by linarith [hM₂ z]))
        (tendsto_sApprox h₁) (tendsto_sApprox h₂) z)
  refine hlim.trans (liminf_le_of_frequently_le' (Frequently.of_forall fun n => ?_))
  refine (H a b c ha hab hc hc1 _ _ (finMeasSupp_sApprox h₁ hp m₁ n)
    (finMeasSupp_sApprox h₂ hq m₂ n)).trans ?_
  calc ENNReal.ofReal C * eLpNorm (sApprox h₁ n) (ENNReal.ofReal p) volume *
        eLpNorm (sApprox h₂ n) (ENNReal.ofReal q) volume
      ≤ ENNReal.ofReal C * (2 * eLpNorm f₁ (ENNReal.ofReal p) volume) *
        (2 * eLpNorm f₂ (ENNReal.ofReal q) volume) := by
        gcongr
        · exact eLpNorm_sApprox_le h₁ _ n
        · exact eLpNorm_sApprox_le h₂ _ n
    _ = _ := by
        rw [ENNReal.ofReal_mul (by norm_num : (0 : ℝ) ≤ 4), ENNReal.ofReal_ofNat]
        ring

/-! ### Uniform strong and weak bounds -/

/-- The admissible kernel pairs `φ = g ⋆ Φ`, `ρ = h ⋆ h ⋆ Ψ` (written as correlations), with
`Φ, Ψ` of normalized decay of order `N` and the regularity needed in §4.5. -/
def KerClass (N : ℕ) (A₀ : ℝ) (φ ρ : ℝ → ℝ) : Prop :=
  (∃ Φ Ψ : ℝ → ℝ, Continuous Φ ∧ Continuous Ψ ∧ (∀ x, |Φ x| ≤ (1 + |x|) ^ (-(N : ℝ))) ∧
    (∀ x, |Ψ x| ≤ (1 + |x|) ^ (-(N : ℝ))) ∧ φ = corrK Twisted.gaussian Φ ∧
    ρ = corrK Twisted.gaussianDeriv (hconv Ψ)) ∧
  Differentiable ℝ φ ∧ Differentiable ℝ ρ ∧ (∀ u, |φ u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) ∧
  (∀ u, |deriv φ u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) ∧
  (∀ u, |ρ u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) ∧ (∀ u, |deriv ρ u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ))

theorem KerClass.measurable_left {N : ℕ} {A₀ : ℝ} {φ ρ : ℝ → ℝ} (h : KerClass N A₀ φ ρ) :
    Measurable φ := h.2.1.continuous.measurable

theorem KerClass.measurable_right {N : ℕ} {A₀ : ℝ} {φ ρ : ℝ → ℝ} (h : KerClass N A₀ φ ρ) :
    Measurable ρ := h.2.2.1.continuous.measurable

theorem KerClass.integrable_left {N : ℕ} {A₀ : ℝ} {φ ρ : ℝ → ℝ} (h : KerClass N A₀ φ ρ) :
    Integrable φ := FiberCZ.integrable_of_decay h.measurable_left h.2.2.2.1

theorem KerClass.integrable_right {N : ℕ} {A₀ : ℝ} {φ ρ : ℝ → ℝ} (h : KerClass N A₀ φ ρ) :
    Integrable ρ := FiberCZ.integrable_of_decay h.measurable_right h.2.2.2.2.2.1

/-- Strong bound at reciprocal exponents `(s, t)`, uniform over the kernel class. -/
def UStrong (α β N : ℕ) (A₀ s t : ℝ) : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧ ∀ φ ρ, KerClass N A₀ φ ρ →
    FiberCZ.StrongBound α β φ ρ (1 / s) (1 / t) (1 / (s + t)) C

/-- Weak bound at reciprocal exponents `(s, t)` for simple functions, uniform over the kernel
class, the truncations and `c`. -/
def UWeak (α β N : ℕ) (A₀ s t : ℝ) : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧ ∀ φ ρ, KerClass N A₀ φ ρ →
    ∀ (a b : ℝ) (c : ℝ → ℂ), 0 < a → a < b → Measurable c → (∀ t, ‖c t‖ ≤ 1) →
    ∀ f g : SimpleFunc (ℝ × ℝ) ℂ, f.FinMeasSupp volume → g.FinMeasSupp volume →
      weakLpNorm volume (1 / (s + t)) (modelOp α β c φ ρ a b f g) ≤
        ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal (1 / s)) volume *
          eLpNorm g (ENNReal.ofReal (1 / t)) volume

/-- The initial range `0 < s, t < 1/2 < s + t` (`pt2`). -/
theorem ustrong_initial {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) :
    ∃ N : ℕ, ∀ {s t : ℝ}, 0 < s → s < 1 / 2 → 0 < t → t < 1 / 2 → 1 / 2 < s + t →
      ∀ A₀, UStrong α β N A₀ s t := by
  obtain ⟨N, HN⟩ := strong_initial hα hβ
  refine ⟨N, fun {s t} hs0 hs ht0 ht hst A₀ => ?_⟩
  have hp : 2 < 1 / s := (lt_one_div two_pos hs0).mpr (by simpa using hs)
  have hq : 2 < 1 / t := (lt_one_div two_pos ht0).mpr (by simpa using ht)
  have hr : 1 / (s + t) < 2 := (one_div_lt (by linarith) two_pos).mpr hst
  have hpqr : 1 / (1 / s) + 1 / (1 / t) = 1 / (1 / (s + t)) := by
    simp only [one_div_one_div]
  obtain ⟨C, hC0, HC⟩ := HN hp hq hr hpqr
  refine ⟨C, hC0, fun φ ρ hK => ?_⟩
  have m1 := hK.measurable_left
  have m2 := hK.measurable_right
  have i1 := hK.integrable_left
  have i2 := hK.integrable_right
  obtain ⟨⟨Φ, Ψ, hΦ, hΨ, hdΦ, hdΨ, rfl, rfl⟩, -⟩ := hK
  intro a b c ha hab hc hc1 f₁ f₂ h₁ h₂ hb₁ hb₂ _ _
  exact HC Φ Ψ hΦ hΨ hdΦ hdΨ m1 i1 m2 i2 a b c ha hab hc hc1 f₁ f₂ h₁ h₂ hb₁ hb₂

/-- Interpolation: uniform weak bounds at the four corners `(s ± δ, t ± δ)` give the uniform
strong bound at `(s, t)`. -/
theorem ustrong_of_uweak (α β N : ℕ) (A₀ : ℝ) {s t δ : ℝ} (hδ : 0 < δ) (hs : δ < s)
    (ht : δ < t) (hw : ∀ i j : Bool, UWeak α β N A₀ (s + cornerShift δ i) (t + cornerShift δ j)) :
    UStrong α β N A₀ s t := by
  choose C hC0 hC using hw
  set A : ℝ := C true true + C true false + C false true + C false false + 1 with hA
  have hCA : ∀ i j, C i j ≤ A := by
    have := hC0 true true; have := hC0 true false; have := hC0 false true
    have := hC0 false false
    intro i j; cases i <;> cases j <;> simp only [hA] <;> linarith
  have hA0 : 0 < A := by
    have := hC0 true true; have := hC0 true false; have := hC0 false true
    have := hC0 false false
    simp only [hA]; linarith
  obtain ⟨C', hC'0, HC'⟩ := bilinear_marcinkiewicz_uniform (μ := (volume : Measure (ℝ × ℝ)))
    (ν := (volume : Measure (ℝ × ℝ))) (ρ := (volume : Measure (ℝ × ℝ))) hδ hs ht hA0
  have hs0 : 0 < s := hδ.trans hs
  have ht0 : 0 < t := hδ.trans ht
  refine ⟨4 * C', by positivity, fun φ ρ hK => ?_⟩
  refine strongBound_of_simple α β hK.measurable_left hK.measurable_right hK.integrable_left
    hK.integrable_right (one_div_pos.mpr hs0) (one_div_pos.mpr ht0) ?_
  intro a b c ha hab hc hc1 f g hf hg
  refine HC' (modelBil α β hc hc1 hK.measurable_left hK.measurable_right hK.integrable_left
    hK.integrable_right b ha) (fun f g => (FiberCZ.stronglyMeasurable_modelOp α β hc
      hK.measurable_left hK.measurable_right a b f.measurable g.measurable).aestronglyMeasurable)
    (fun i j f g hf hg => ?_) f g hf hg
  refine (hC i j φ ρ hK a b c ha hab hc hc1 f g hf hg).trans ?_
  gcongr
  exact hCA i j

/-- The fiber-wise Calderón-Zygmund decomposition in the first fiber, uniform version:
from `(s₀, t₀)` to `(s, t₀)` with `s₀ ≤ s ≤ 1`. -/
theorem uweak_of_ustrong₁ {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) (N : ℕ) (A₀ : ℝ) {s₀ t₀ s : ℝ}
    (hs₀ : 0 < s₀) (hs₀1 : s₀ < 1) (ht₀ : 0 < t₀) (ht₀1 : t₀ < 1) (hss : s₀ ≤ s) (hs1 : s ≤ 1)
    (H : UStrong α β N A₀ s₀ t₀) : UWeak α β N A₀ s t₀ := by
  obtain ⟨A, -, HA⟩ := H
  have hs : 0 < s := hs₀.trans_le hss
  have hp₀ : 1 < 1 / s₀ := by rw [lt_one_div one_pos hs₀]; simpa using hs₀1
  have hq₀ : 1 < 1 / t₀ := by rw [lt_one_div one_pos ht₀]; simpa using ht₀1
  have hr₀ : 1 / (1 / (s₀ + t₀)) = 1 / (1 / s₀) + 1 / (1 / t₀) := by simp only [one_div_one_div]
  have hp : 1 ≤ 1 / s := by rw [le_one_div one_pos hs]; simpa using hs1
  have hpp : 1 / s ≤ 1 / s₀ := one_div_le_one_div_of_le hs₀ hss
  obtain ⟨C, hC0, HC⟩ := modelOp_weak_fiber1_uniform (A₀ := A₀) (A := A) hα hβ hp₀ hq₀ hr₀ hp hpp
  have hr : 0 < 1 / (s + t₀) := by positivity
  refine ⟨C ^ (s + t₀), by positivity, fun φ ρ hK a b c ha hab hc hc1 f g hf hg => ?_⟩
  obtain ⟨-, hφd, hρd, b1, b2, b3, b4⟩ := id hK
  have hW := HC φ ρ hφd hρd b1 b2 b3 b4 (HA φ ρ hK) a b c ha hab hc hc1 f g f.measurable
    g.measurable f.exists_forall_norm_le g.exists_forall_norm_le
    ((SimpleFunc.memLp_iff_finMeasSupp (by simpa using hs) ENNReal.ofReal_ne_top).mpr hf)
    ((SimpleFunc.memLp_iff_finMeasSupp (by simpa using ht₀) ENNReal.ofReal_ne_top).mpr hg)
  simp only [one_div_one_div] at hW
  have h := weakLpNorm_le_of_distribution (ρ := volume) (v := modelOp α β c φ ρ a b f g) hr hC0
    (W := eLpNorm f (ENNReal.ofReal (1 / s)) volume * eLpNorm g (ENNReal.ofReal (1 / t₀)) volume)
    hW
  rw [one_div_one_div, ← mul_assoc] at h
  exact h

/-- The fiber-wise Calderón-Zygmund decomposition in the second fiber, uniform version:
from `(s₀, t₀)` to `(s₀, t)` with `t₀ ≤ t ≤ 1`. -/
theorem uweak_of_ustrong₂ {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) (N : ℕ) (A₀ : ℝ) {s₀ t₀ t : ℝ}
    (hs₀ : 0 < s₀) (hs₀1 : s₀ < 1) (ht₀ : 0 < t₀) (ht₀1 : t₀ < 1) (htt : t₀ ≤ t) (ht1 : t ≤ 1)
    (H : UStrong α β N A₀ s₀ t₀) : UWeak α β N A₀ s₀ t := by
  obtain ⟨A, -, HA⟩ := H
  have ht : 0 < t := ht₀.trans_le htt
  have hp₀ : 1 < 1 / s₀ := by rw [lt_one_div one_pos hs₀]; simpa using hs₀1
  have hq₀ : 1 < 1 / t₀ := by rw [lt_one_div one_pos ht₀]; simpa using ht₀1
  have hr₀ : 1 / (1 / (s₀ + t₀)) = 1 / (1 / s₀) + 1 / (1 / t₀) := by simp only [one_div_one_div]
  have hq : 1 ≤ 1 / t := by rw [le_one_div one_pos ht]; simpa using ht1
  have hqq : 1 / t ≤ 1 / t₀ := one_div_le_one_div_of_le ht₀ htt
  obtain ⟨C, hC0, HC⟩ := modelOp_weak_fiber2_uniform (A₀ := A₀) (A := A) hα hβ hp₀ hq₀ hr₀ hq hqq
  have hr : 0 < 1 / (s₀ + t) := by positivity
  refine ⟨C ^ (s₀ + t), by positivity, fun φ ρ hK a b c ha hab hc hc1 f g hf hg => ?_⟩
  obtain ⟨-, hφd, hρd, b1, b2, b3, b4⟩ := id hK
  have hW := HC φ ρ hφd hρd b1 b2 b3 b4 (HA φ ρ hK) a b c ha hab hc hc1 f g f.measurable
    g.measurable f.exists_forall_norm_le g.exists_forall_norm_le
    ((SimpleFunc.memLp_iff_finMeasSupp (by simpa using hs₀) ENNReal.ofReal_ne_top).mpr hf)
    ((SimpleFunc.memLp_iff_finMeasSupp (by simpa using ht) ENNReal.ofReal_ne_top).mpr hg)
  simp only [one_div_one_div] at hW
  have h := weakLpNorm_le_of_distribution (ρ := volume) (v := modelOp α β c φ ρ a b f g) hr hC0
    (W := eLpNorm f (ENNReal.ofReal (1 / s₀)) volume * eLpNorm g (ENNReal.ofReal (1 / t)) volume)
    hW
  rw [one_div_one_div, ← mul_assoc] at h
  exact h

theorem cornerShift_bounds (δ : ℝ) (hδ : 0 < δ) (x : ℝ) (b : Bool) :
    x - δ ≤ x + cornerShift δ b ∧ x + cornerShift δ b ≤ x + δ := by
  cases b <;> simp only [cornerShift] <;> constructor <;> simp <;> linarith

/-- First interpolation step (`fwrange-1`): strong bounds for `0 < t < 1/2`,
`max(0, 1/2 - t) < s < 1`. -/
theorem ustrong_phase1 {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) {N : ℕ}
    (hN : ∀ {s t : ℝ}, 0 < s → s < 1 / 2 → 0 < t → t < 1 / 2 → 1 / 2 < s + t →
      ∀ A₀, UStrong α β N A₀ s t)
    {s t : ℝ} (hs0 : 0 < s) (hs1 : s < 1) (ht0 : 0 < t) (ht : t < 1 / 2) (hst : 1 / 2 < s + t)
    (A₀ : ℝ) : UStrong α β N A₀ s t := by
  set δ : ℝ := min (min (min t (1 / 2 - t)) (min (1 - s) s)) (s + t - 1 / 2) / 4 with hδdef
  have hm : 0 < min (min (min t (1 / 2 - t)) (min (1 - s) s)) (s + t - 1 / 2) := by
    simp only [lt_min_iff]; refine ⟨⟨⟨?_, ?_⟩, ?_, ?_⟩, ?_⟩ <;> linarith
  have hδ : 0 < δ := by positivity
  have h1 : δ ≤ t / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_left _ _).trans (min_le_left _ _))
  have h2 : δ ≤ (1 / 2 - t) / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_left _ _).trans (min_le_right _ _))
  have h3 : δ ≤ (1 - s) / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_right _ _).trans (min_le_left _ _))
  have h4 : δ ≤ s / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_right _ _).trans (min_le_right _ _))
  have h5 : δ ≤ (s + t - 1 / 2) / 4 := by
    simp only [hδdef]; gcongr
    exact min_le_right _ _
  set s₀ : ℝ := min (s - δ) (1 / 2 - δ) with hs₀
  have hs₀a : s₀ ≤ s - δ := min_le_left _ _
  have hs₀b : s₀ ≤ 1 / 2 - δ := min_le_right _ _
  have hs₀p : 0 < s₀ := lt_min (by linarith) (by linarith)
  have hs₀t : 1 / 2 - t + δ < s₀ := lt_min (by linarith) (by linarith)
  refine ustrong_of_uweak α β N A₀ hδ (by linarith) (by linarith) fun i j => ?_
  obtain ⟨hi1, hi2⟩ := cornerShift_bounds δ hδ s i
  obtain ⟨hj1, hj2⟩ := cornerShift_bounds δ hδ t j
  refine uweak_of_ustrong₁ hα hβ N A₀ hs₀p (by linarith) (by linarith) (by linarith)
    (by linarith) (by linarith) ?_
  exact hN hs₀p (by linarith) (by linarith) (by linarith) (by linarith) A₀

/-- Second interpolation step: strong bounds for all `0 < s, t < 1` with `1/2 < s + t`. -/
theorem ustrong_phase2 {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) {N : ℕ}
    (hN : ∀ {s t : ℝ}, 0 < s → s < 1 / 2 → 0 < t → t < 1 / 2 → 1 / 2 < s + t →
      ∀ A₀, UStrong α β N A₀ s t)
    {s t : ℝ} (hs0 : 0 < s) (hs1 : s < 1) (ht0 : 0 < t) (ht1 : t < 1) (hst : 1 / 2 < s + t)
    (A₀ : ℝ) : UStrong α β N A₀ s t := by
  set δ : ℝ := min (min (min s (1 - s)) (min t (1 - t))) (s + t - 1 / 2) / 4 with hδdef
  have hm : 0 < min (min (min s (1 - s)) (min t (1 - t))) (s + t - 1 / 2) := by
    simp only [lt_min_iff]; refine ⟨⟨⟨?_, ?_⟩, ?_, ?_⟩, ?_⟩ <;> linarith
  have hδ : 0 < δ := by positivity
  have h1 : δ ≤ s / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_left _ _).trans (min_le_left _ _))
  have h2 : δ ≤ (1 - s) / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_left _ _).trans (min_le_right _ _))
  have h3 : δ ≤ t / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_right _ _).trans (min_le_left _ _))
  have h4 : δ ≤ (1 - t) / 4 := by
    simp only [hδdef]; gcongr
    exact (min_le_left _ _).trans ((min_le_right _ _).trans (min_le_right _ _))
  have h5 : δ ≤ (s + t - 1 / 2) / 4 := by
    simp only [hδdef]; gcongr
    exact min_le_right _ _
  set t₀ : ℝ := min (t - δ) (1 / 2 - δ) with ht₀
  have ht₀a : t₀ ≤ t - δ := min_le_left _ _
  have ht₀b : t₀ ≤ 1 / 2 - δ := min_le_right _ _
  have ht₀p : 0 < t₀ := lt_min (by linarith) (by linarith)
  have ht₀s : 1 / 2 - s + δ < t₀ := lt_min (by linarith) (by linarith)
  refine ustrong_of_uweak α β N A₀ hδ (by linarith) (by linarith) fun i j => ?_
  obtain ⟨hi1, hi2⟩ := cornerShift_bounds δ hδ s i
  obtain ⟨hj1, hj2⟩ := cornerShift_bounds δ hδ t j
  refine uweak_of_ustrong₂ hα hβ N A₀ (by linarith) (by linarith) ht₀p (by linarith)
    (by linarith) (by linarith) ?_
  exact ustrong_phase1 hα hβ hN (by linarith) (by linarith) ht₀p (by linarith) (by linarith) A₀

end

end FullRange

open MeasureTheory

open FullRange in
/-- **The truncated model operator in the full range** (CDR §4.5): for `1 < p, q`,
`1/2 < r < 2`, `1/p + 1/q = 1/r`, the truncated model operator
`U_{a,b}(f₁, f₂) = ∫_{a<t≤b} c(t) (f₁ *₁ φ_{t^α})(f₂ *₂ ρ_{t^β}) dt/t` with
`φ = corrK g Φ`, `ρ = corrK h (h ⋆ Ψ)` maps `L^p × L^q → L^r`. The decay order `N` is chosen
before the exponents, and the constant depends only on `α, β, p, q, r` and the constant `A₀` in
the regularity bounds of `φ, ρ` (not on `Φ, Ψ, a, b, c`). -/
theorem modelOp_full_range {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) :
    ∃ N : ℕ, ∀ p q r : ℝ, 1 < p → 1 < q → 1 / 2 < r → r < 2 → 1 / p + 1 / q = 1 / r →
      ∀ A₀ : ℝ, ∃ C : ℝ, 0 ≤ C ∧ ∀ Φ Ψ : ℝ → ℝ, Continuous Φ → Continuous Ψ →
      (∀ x, |Φ x| ≤ (1 + |x|) ^ (-(N : ℝ))) → (∀ x, |Ψ x| ≤ (1 + |x|) ^ (-(N : ℝ))) →
      Differentiable ℝ (corrK Twisted.gaussian Φ) →
      Differentiable ℝ (corrK Twisted.gaussianDeriv (hconv Ψ)) →
      (∀ u, |corrK Twisted.gaussian Φ u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
      (∀ u, |deriv (corrK Twisted.gaussian Φ) u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
      (∀ u, |corrK Twisted.gaussianDeriv (hconv Ψ) u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
      (∀ u, |deriv (corrK Twisted.gaussianDeriv (hconv Ψ)) u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
      ∀ (a b : ℝ) (c : ℝ → ℂ), 0 < a → a < b → Measurable c → (∀ t, ‖c t‖ ≤ 1) →
      ∀ f₁ f₂ : ℝ × ℝ → ℂ, Measurable f₁ → Measurable f₂ → (∃ M, ∀ z, ‖f₁ z‖ ≤ M) →
        (∃ M, ∀ z, ‖f₂ z‖ ≤ M) → MemLp f₁ (ENNReal.ofReal p) → MemLp f₂ (ENNReal.ofReal q) →
        eLpNorm (modelOp α β c (corrK Twisted.gaussian Φ) (corrK Twisted.gaussianDeriv (hconv Ψ))
          a b f₁ f₂) (ENNReal.ofReal r) volume ≤
          ENNReal.ofReal C * eLpNorm f₁ (ENNReal.ofReal p) volume *
            eLpNorm f₂ (ENNReal.ofReal q) volume := by
  obtain ⟨N, hN⟩ := ustrong_initial hα hβ
  refine ⟨N, fun p q r hp hq _ hr2 hpqr A₀ => ?_⟩
  have hs0 : 0 < 1 / p := one_div_pos.mpr (by linarith)
  have ht0 : 0 < 1 / q := one_div_pos.mpr (by linarith)
  have hs1 : 1 / p < 1 := by rw [div_lt_one (by linarith)]; exact hp
  have ht1 : 1 / q < 1 := by rw [div_lt_one (by linarith)]; exact hq
  have hr0 : 0 < r := one_div_pos.mp (by rw [← hpqr]; positivity)
  have hst : 1 / 2 < 1 / p + 1 / q := by
    rw [hpqr]; exact (one_div_lt_one_div two_pos hr0).mpr hr2
  obtain ⟨C, hC0, HC⟩ := ustrong_phase2 hα hβ hN hs0 hs1 ht0 ht1 hst A₀
  refine ⟨C, hC0, fun Φ Ψ hΦ hΨ hdΦ hdΨ hφd hρd b1 b2 b3 b4 => ?_⟩
  have H := HC _ _ ⟨⟨Φ, Ψ, hΦ, hΨ, hdΦ, hdΨ, rfl, rfl⟩, hφd, hρd, b1, b2, b3, b4⟩
  unfold FiberCZ.StrongBound at H
  rw [hpqr, one_div_one_div, one_div_one_div, one_div_one_div] at H
  exact H


section TheoremTwo

open MeasureTheory Set Filter
open Auto.Twisted (gaussian gaussianDeriv kernelAt)
open scoped ENNReal Topology ContDiff

noncomputable section

/-! ### From the truncated bounds to `ModelBound`, and Theorem 2 -/

namespace Glue

theorem corrK_const_mul (k k' : ℝ → ℝ) (a : ℝ) :
    corrK k (fun x => a * k' x) = fun w => a * corrK k k' w := by
  funext w
  simp only [corrK]
  rw [← integral_const_mul]
  congr 1; funext u; ring

theorem hconv_const_mul (Ψ : ℝ → ℝ) (b : ℝ) :
    hconv (fun x => b * Ψ x) = fun y => b * hconv Ψ y := by
  funext y
  simp only [hconv]
  rw [← integral_const_mul]
  congr 1; funext u; ring

theorem kernelAt_const_mul (φ : ℝ → ℝ) (A s a x : ℝ) :
    kernelAt (fun w => A * φ w) s a x = A * kernelAt φ s a x := by
  simp only [kernelAt, Twisted.kernelDilate, smul_eq_mul]; ring

theorem modelOp_const_mul (α β : ℕ) (c : ℝ → ℂ) (φ ρ : ℝ → ℝ) (A B a b : ℝ)
    (f₁ f₂ : ℝ × ℝ → ℂ) :
    modelOp α β c (fun w => A * φ w) (fun w => B * ρ w) a b f₁ f₂ =
      fun z => ((A * B : ℝ) : ℂ) * modelOp α β c φ ρ a b f₁ f₂ z := by
  funext z
  simp only [modelOp, kernelAt_const_mul]
  rw [← integral_const_mul]
  congr 1; funext t
  have h1 : (∫ x', f₁ (x', z.2) * (((A * kernelAt φ (t ^ α) x' z.1 : ℝ)) : ℂ)) =
      (A : ℂ) * ∫ x', f₁ (x', z.2) * ((kernelAt φ (t ^ α) x' z.1 : ℝ) : ℂ) := by
    rw [← integral_const_mul]; congr 1; funext x'; push_cast; ring
  have h2 : (∫ y', f₂ (z.1, y') * (((B * kernelAt ρ (t ^ β) y' z.2 : ℝ)) : ℂ)) =
      (B : ℂ) * ∫ y', f₂ (z.1, y') * ((kernelAt ρ (t ^ β) y' z.2 : ℝ) : ℂ) := by
    rw [← integral_const_mul]; congr 1; funext y'; push_cast; ring
  rw [h1, h2]; push_cast; ring

/-- The truncated full-range bound with normalized kernels (the output of the interpolation). -/
def TruncFull (α β N : ℕ) (p q r : ℝ) : Prop :=
  ∀ A₀ : ℝ, ∃ C : ℝ, 0 ≤ C ∧ ∀ Φ Ψ : ℝ → ℝ, Continuous Φ → Continuous Ψ →
    (∀ x, |Φ x| ≤ (1 + |x|) ^ (-(N : ℝ))) → (∀ x, |Ψ x| ≤ (1 + |x|) ^ (-(N : ℝ))) →
    Differentiable ℝ (corrK gaussian Φ) → Differentiable ℝ (corrK gaussianDeriv (hconv Ψ)) →
    (∀ u, |corrK gaussian Φ u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
    (∀ u, |deriv (corrK gaussian Φ) u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
    (∀ u, |corrK gaussianDeriv (hconv Ψ) u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
    (∀ u, |deriv (corrK gaussianDeriv (hconv Ψ)) u| ≤ A₀ * (1 + |u|) ^ (-12 : ℝ)) →
    ∀ (a b : ℝ) (c : ℝ → ℂ), 0 < a → a < b → Measurable c → (∀ t, ‖c t‖ ≤ 1) →
    ∀ f₁ f₂ : ℝ × ℝ → ℂ, Measurable f₁ → Measurable f₂ → (∃ M, ∀ z, ‖f₁ z‖ ≤ M) →
      (∃ M, ∀ z, ‖f₂ z‖ ≤ M) → MemLp f₁ (ENNReal.ofReal p) → MemLp f₂ (ENNReal.ofReal q) →
      eLpNorm (modelOp α β c (corrK gaussian Φ) (corrK gaussianDeriv (hconv Ψ)) a b f₁ f₂)
        (ENNReal.ofReal r) volume ≤
        ENNReal.ofReal C * eLpNorm f₁ (ENNReal.ofReal p) volume *
          eLpNorm f₂ (ENNReal.ofReal q) volume

theorem nonneg_of_decay {Φ : ℝ → ℝ} {A N : ℝ} (h : ∀ x, |Φ x| ≤ A * (1 + |x|) ^ (-N)) :
    0 ≤ A := by
  have h0 := (abs_nonneg (Φ 0)).trans (h 0)
  have : 0 < (1 + |(0 : ℝ)|) ^ (-N) := by positivity
  exact nonneg_of_mul_nonneg_left h0 this

theorem eq_zero_of_decay_zero {Φ : ℝ → ℝ} {N : ℝ} (h : ∀ x, |Φ x| ≤ 0 * (1 + |x|) ^ (-N)) :
    Φ = 0 := by
  funext x; have := h x; rw [zero_mul] at this; exact abs_nonpos_iff.1 this

theorem modelOpFull_left_zero (α β : ℕ) (c : ℝ → ℂ) (ρ : ℝ → ℝ) (f₁ f₂ : ℝ × ℝ → ℂ) :
    modelOpFull α β c (gconv 0) ρ f₁ f₂ = 0 := by
  funext z; simp [modelOpFull, gconv, kernelAt, Twisted.kernelDilate]

theorem modelOpFull_right_zero (α β : ℕ) (c : ℝ → ℂ) (φ : ℝ → ℝ) (f₁ f₂ : ℝ × ℝ → ℂ) :
    modelOpFull α β c φ (hhconv 0) f₁ f₂ = 0 := by
  funext z; simp [modelOpFull, hhconv, kernelAt, Twisted.kernelDilate]

theorem rpow_neg_mono {N D : ℝ} (hND : N ≤ D) (x : ℝ) :
    (1 + |x|) ^ (-D) ≤ (1 + |x|) ^ (-N) :=
  Real.rpow_le_rpow_of_exponent_le (by linarith [abs_nonneg x]) (by linarith)

theorem mul_le_pow_add_one {x : ℝ} (hx : 0 ≤ x) {D : ℕ} (hD : 1 ≤ D) : x ≤ (x + 1) ^ D :=
  calc x ≤ x + 1 := by linarith
    _ = (x + 1) ^ 1 := (pow_one _).symm
    _ ≤ (x + 1) ^ D := pow_le_pow_right₀ (by linarith) hD

theorem test_bdd {f : ℝ × ℝ → ℂ} (h : ContDiff ℝ ∞ f) (hc : HasCompactSupport f) :
    ∃ M, ∀ z, ‖f z‖ ≤ M := by
  obtain ⟨M, hM⟩ := h.continuous.bounded_above_of_compact_support hc
  exact ⟨M, hM⟩

/-- From the truncated bounds to `ModelBound`: rescaling to normalized kernels, the limit
`2^{-n} → 0`, `2^n → ∞` (Fatou), and `A B ≤ (A B + 1)^D`. -/
theorem modelBound_of_truncFull {α β N D : ℕ} (hα : 0 < α) (hβ : 0 < β) (hND : N ≤ D)
    (h12 : 12 ≤ D) {p q r : ℝ} (hT : TruncFull α β N p q r) : ModelBound α β p q r D := by
  obtain ⟨A₀, -, hreg⟩ := ModelKernel.kernel_regularity (N := (D : ℝ)) (by exact_mod_cast h12)
  obtain ⟨C, hC, hTC⟩ := hT A₀
  refine ⟨C, hC, fun Φ Ψ A B hΦ hΨ hdΦ hdΨ c hc hc1 f₁ f₂ h₁ h₁c h₂ h₂c => ?_⟩
  have hA := nonneg_of_decay hdΦ
  have hB := nonneg_of_decay hdΨ
  rcases hA.eq_or_lt with hA0 | hA0
  · subst hA0
    rw [eq_zero_of_decay_zero hdΦ, modelOpFull_left_zero]; simp
  rcases hB.eq_or_lt with hB0 | hB0
  · subst hB0
    rw [eq_zero_of_decay_zero hdΨ, modelOpFull_right_zero]; simp
  have hD1 : (1 : ℝ) ≤ D := by exact_mod_cast (show 1 ≤ D by omega)
  have hND' : (N : ℝ) ≤ D := by exact_mod_cast hND
  have hD2 : (2 : ℝ) < D := by
    have : (12 : ℝ) ≤ D := by exact_mod_cast h12
    linarith
  set Φ' : ℝ → ℝ := fun x => A⁻¹ * Φ (-x) with hΦ'
  set Ψ' : ℝ → ℝ := fun x => B⁻¹ * -Ψ (-x) with hΨ'
  have hΦc : Continuous Φ' := continuous_const.mul (hΦ.continuous.comp continuous_neg)
  have hΨc : Continuous Ψ' := continuous_const.mul (hΨ.continuous.comp continuous_neg).neg
  have dΦ' : ∀ x, |Φ' x| ≤ (1 + |x|) ^ (-(D : ℝ)) := fun x => by
    have := hdΦ (-x); rw [abs_neg] at this
    rw [hΦ', abs_mul, abs_inv, abs_of_pos hA0]
    calc A⁻¹ * |Φ (-x)| ≤ A⁻¹ * (A * (1 + |x|) ^ (-(D : ℝ))) := by gcongr
      _ = _ := by field_simp
  have dΨ' : ∀ x, |Ψ' x| ≤ (1 + |x|) ^ (-(D : ℝ)) := fun x => by
    have := hdΨ (-x); rw [abs_neg] at this
    rw [hΨ', abs_mul, abs_inv, abs_of_pos hB0, abs_neg]
    calc B⁻¹ * |Ψ (-x)| ≤ B⁻¹ * (B * (1 + |x|) ^ (-(D : ℝ))) := by gcongr
      _ = _ := by field_simp
  obtain ⟨d1, d2, b1, b2, b3, b4⟩ := hreg Φ' Ψ' hΦc.measurable hΨc.measurable dΦ' dΨ'
  have hgc : gconv Φ = fun w => A * corrK gaussian Φ' w := by
    rw [ModelKernel.gconv_eq_corrK, ← corrK_const_mul]
    congr 1; funext x; simp only [hΦ']; field_simp
  have iΨ : Integrable Ψ := by
    have hD12 : (12 : ℝ) ≤ D := by exact_mod_cast h12
    exact integrable_of_poly_decay hΨ.continuous (by linarith) hdΨ
  have hhc : hhconv Ψ = fun w => B * corrK gaussianDeriv (hconv Ψ') w := by
    rw [ModelKernel.hhconv_eq_corrK iΨ, ← corrK_const_mul, ← hconv_const_mul]
    congr 2; funext x; simp only [hΨ']; field_simp
  have hbound : ∀ n : ℕ, 1 ≤ n → eLpNorm (modelOp α β c (gconv Φ) (hhconv Ψ) ((2 : ℝ) ^ (-(n : ℤ)))
      (2 ^ n) f₁ f₂) (ENNReal.ofReal r) volume ≤
      ENNReal.ofReal (C * (A * B + 1) ^ D) * eLpNorm f₁ (ENNReal.ofReal p) volume *
        eLpNorm f₂ (ENNReal.ofReal q) volume := by
    intro n hn
    have hs : modelOp α β c (gconv Φ) (hhconv Ψ) ((2 : ℝ) ^ (-(n : ℤ))) (2 ^ n) f₁ f₂ =
        ((A * B : ℝ) : ℂ) • modelOp α β c (corrK gaussian Φ') (corrK gaussianDeriv (hconv Ψ'))
          ((2 : ℝ) ^ (-(n : ℤ))) (2 ^ n) f₁ f₂ := by
      rw [hgc, hhc, modelOp_const_mul]; rfl
    have hab : (2 : ℝ) ^ (-(n : ℤ)) < 2 ^ n := by
      rw [zpow_neg, zpow_natCast]
      have h1 : (1 : ℝ) < 2 ^ n := one_lt_pow₀ (by norm_num) (by omega)
      exact (inv_lt_one_of_one_lt₀ h1).trans h1
    have hT1 := hTC Φ' Ψ' hΦc hΨc (fun x => (dΦ' x).trans (rpow_neg_mono hND' x))
      (fun x => (dΨ' x).trans (rpow_neg_mono hND' x)) d1 d2 b1 b2 b3 b4 _ _ c (by positivity)
      hab hc hc1 f₁ f₂ h₁.continuous.measurable h₂.continuous.measurable (test_bdd h₁ h₁c)
      (test_bdd h₂ h₂c) (h₁.continuous.memLp_of_hasCompactSupport h₁c)
      (h₂.continuous.memLp_of_hasCompactSupport h₂c)
    rw [hs, eLpNorm_const_smul]
    have hAB : ‖((A * B : ℝ) : ℂ)‖ₑ = ENNReal.ofReal (A * B) := by
      rw [← ofReal_norm, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos (by positivity)]
    rw [hAB]
    calc ENNReal.ofReal (A * B) * eLpNorm (modelOp α β c (corrK gaussian Φ')
          (corrK gaussianDeriv (hconv Ψ')) ((2 : ℝ) ^ (-(n : ℤ))) (2 ^ n) f₁ f₂)
          (ENNReal.ofReal r) volume
        ≤ ENNReal.ofReal (A * B) * (ENNReal.ofReal C * eLpNorm f₁ (ENNReal.ofReal p) volume *
            eLpNorm f₂ (ENNReal.ofReal q) volume) := by gcongr
      _ = ENNReal.ofReal (C * (A * B)) * eLpNorm f₁ (ENNReal.ofReal p) volume *
            eLpNorm f₂ (ENNReal.ofReal q) volume := by
          rw [ENNReal.ofReal_mul hC]; ring
      _ ≤ _ := by
          gcongr
          exact mul_le_pow_add_one (by positivity) (by omega)
  have hlim := Lp.eLpNorm_lim_le_liminf_eLpNorm (p := ENNReal.ofReal r) (μ := volume)
    (fun n => (FiberCZ.stronglyMeasurable_modelOp α β hc (ModelKernel.measurable_gconv
      hΦ.continuous.measurable) (ModelKernel.measurable_hhconv hΨ.continuous.measurable iΨ)
      _ _ h₁.continuous.measurable h₂.continuous.measurable).aestronglyMeasurable)
    (modelOpFull α β c (gconv Φ) (hhconv Ψ) f₁ f₂)
    (Eventually.of_forall fun z => ModelKernel.tendsto_modelOp_modelOpFull hα hβ hc hc1
      hΦ.continuous hΨ.continuous (N := D) hD2 hdΦ hdΨ h₁ h₁c h₂ h₂c z)
  refine hlim.trans ?_
  exact Filter.liminf_le_of_frequently_le'
    ((eventually_ge_atTop 1).mono fun n hn => hbound n hn).frequently

theorem truncFull_of_full {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) :
    ∃ N : ℕ, ∀ p q r : ℝ, 1 < p → 1 < q → 1 / 2 < r → r < 2 → 1 / p + 1 / q = 1 / r →
      TruncFull α β N p q r := by
  obtain ⟨N, hN⟩ := modelOp_full_range hα hβ
  exact ⟨N, fun p q r hp hq hr hr2 hpqr => hN p q r hp hq hr hr2 hpqr⟩

end Glue

open Glue in
/-- **Theorem 2** (`thm:anisotp`): for positive integers `α, β` and a symbol `m` satisfying the
anisotropic symbol estimates `symest` up to a finite order `N₁`, the bilinear operator `T_m`
is bounded `L^p × L^q → L^r` for `p, q ∈ (1, ∞)`, `r ∈ (1/2, 2)`, `1/p + 1/q = 1/r` (a priori
inequality on test functions; the constant depends on `m` only through the constant `C₀` in
the symbol estimates). -/
theorem thm_anisotp {α β : ℕ} (hα : 0 < α) (hβ : 0 < β) :
    ∃ N₁ : ℕ, ∀ (C₀ : ℝ) (p q r : ℝ), 1 < p → 1 < q → 1 / 2 < r → r < 2 →
      1 / p + 1 / q = 1 / r →
      ∃ C : ℝ, 0 ≤ C ∧ ∀ m : ℝ × ℝ → ℂ, IsAnisoSymbol α β N₁ C₀ m →
        ∀ f₁ f₂ : ℝ × ℝ → ℂ, ContDiff ℝ ∞ f₁ → HasCompactSupport f₁ →
          ContDiff ℝ ∞ f₂ → HasCompactSupport f₂ →
          eLpNorm (Tm m f₁ f₂) (ENNReal.ofReal r) volume ≤
            ENNReal.ofReal C * eLpNorm f₁ (ENNReal.ofReal p) volume *
              eLpNorm f₂ (ENNReal.ofReal q) volume := by
  obtain ⟨N, hN⟩ := truncFull_of_full hα hβ
  obtain ⟨N', hN'⟩ := truncFull_of_full hβ hα
  refine thm_anisotp_of_modelBound hα hβ (D := max (max N N') 12)
    fun p q r hp hq hr hr2 hpqr => ⟨?_, ?_⟩
  · exact modelBound_of_truncFull hα hβ ((le_max_left _ _).trans (le_max_left _ _))
      (le_max_right _ _) (hN p q r hp hq hr hr2 hpqr)
  · exact modelBound_of_truncFull hβ hα ((le_max_right _ _).trans (le_max_left _ _))
      (le_max_right _ _) (hN' q p r hq hp hr hr2 (by rw [add_comm]; exact hpqr))

end

end TheoremTwo

end CDR

end Auto
